README.md
Removing whitespace from readme to trigger travis and create a rc.
=> chore: remove space from readme

netlify.toml
=> chore: Travis test

.gitignore, package-lock.json, package.json
=> chore: try adding bump false to standard-version

ci-scripts/publish-rc.sh, package.json
Temporarily removing `> /dev/null 2>&1;` so that we can get some more robust error output.
=> chore: testing travis

docs/_includes/search-box.html, docs/pages/getting-started.md
Closes SAP/fundamental-styles#37
=> docs: fixed the seach box in the docsite

docs/pages/components/action-bar.md
Closes SAP/fundamental-styles#11
Added back button aria-label for Action Bar Mobile View as per issue #11.
=> fix: Added back button aria-label for Action Bar Mobile View

docs/_includes/side-nav.html, docs/_layouts/default.html, docs/_layouts/full-width-page.html, docs/_layouts/page.html, docs/_sass/_docs-footer.scss, docs/_sass/_docs-general.scss, docs/_sass/_docs-main-content.scss, docs/_sass/_docs-search-box.scss, docs/_sass/_docs-side-nav.scss, docs/_sass/_docs-top-nav.scss, docs/index.html, docs/js/customscripts.js
Closes SAP/fundamental-styles#52
=> docs: add 2 separate scrollbars for left nav and main

.github/mergeable.yml
add initial version of `mergeable.yml` file
=> chore: add mergeable.yml

.github/mergeable.yml
let @markpalfreeman  approve prs :)
=> chore: add palf to mergeable

.github/PULL_REQUEST_TEMPLATE.md
Let's simplify and provide better emphasis on different requirements for PRs.
=> chore: Simplify and emphasize elements for PR descriptions

src/input-group.scss
This PR fixes the same issue addressed by @JKMarkowski in his
[PR](https://github.com/SAP/fundamental-styles/pull/359)
For some reason in his branch a couple of tests are failing and I wasn't able to fix it. 
I created a new branch from the latest master, applied the changes and all tests now pass.
Before the fix:
After:
Locally running the tests:
=> fix: localization-editor, input-group

docs/_sass/_docs-display-component.scss, src/product-switch.scss
Closes SAP/fundamental-styles#391
=> fix: removed bullets for product-switch

src/mixins/_mixins.scss, src/tile.scss
Description
Refactored all of the tile css file to remove any fd-colors and apply the appropriate theming
No changes done to actual visuals
No classes removed
=> fix: tile theme parameter refactoring

docs/pages/components/side-navigation.md
Removed the 3rd level of navigation in the Nested list / Side Navigation
=> docs: remove third level in the nested list/sidenav

README.md
=> docs: document some differences between Fundamental Library Styles and Fundamental

docs/pages/components/form.md
Closes SAP/fundamental-styles#526
Disabled property was missing in _Disabled Input_
=> fix: Can write inside disabled input

docs/_sass/_landingPage.scss, docs/index.html
I added more specificity to the icons in the hamburger menu to avoid overwriting of the default `.sap-icon--menu2` and `.sap-icon--decline` classes
=> docs: add fix for hamburger menu icons in the landing page

src/tabs.scss
Closes https://github.com/SAP/fundamental-styles/issues/639
There is added support for RTL. I mirrored some of padding/margins.
>
=> fix: Add RTL support for tabs

src/bar.scss
Added z-index: 1 to the header
=> fix: add z-index:1 to the bar header

docs/pages/components/form.md
Part of [660](https://github.com/SAP/fundamental-styles/issues/660)
=> docs: refactor form messages in textarea examples

package-lock.json, package.json
bump @sap-theming/theming-base-content version
=> chore: bump @sap-theming/theming-base-content version

README.md, docs/_includes/footer.html
=> chore: update readme and footer to 2020

docs/pages/patterns/multi-input.md
Closes https://github.com/SAP/fundamental-styles/issues/648
There is mobile mode added to multi input component. 
>
=> fix: (multi input) Add MultiInput mobile mode

package-lock.json
chore: package.json security update
=> chore: package.json security update

src/product-switch.scss
Closes https://github.com/SAP/fundamental-styles/issues/698
There is simplified background color, for pseudo elements in product switch .
I also fixed truncation for single line title.
>
=> fix: add fix for HCB dark mode, simplify code, fix single line truncation for Product Switch

docs/pages/components/bar.md
docs: update bar documentation to use the latest button classes
https://github.com/SAP/fundamental-styles/issues/709
=> docs: update bar documentation to use the latest button classes

docs/pages/components/dialog.md
update button in the dialog documentation (replace primary button)
=> docs: update button in the dialog documentation

docs/pages/patterns/date-picker.md
reported #709 
documentation page for datepicker changed acording to new button spec
see #709
=> docs: datepicker button fix

docs/pages/components/dialog.md, src/dialog.scss
Closes SAP/fundamental-styles#727
Add scroll to Dialog body  and update button styling.
=> fix: Cannot scroll Dialog body

docs/pages/components/notification.md, docs/pages/components/popover.md, docs/pages/components/select.md, docs/pages/patterns/combobox-input.md, docs/pages/patterns/multi-input.md
Button classes updated in docs
=> docs: button update

docs/_sass/_landingPage.scss
reported #709 
Underline removed from side navigation
see #709
=> fix: underline issue on side navigation

README.md, src/mixins/_forms.scss, src/radio.scss
@droshev and I accidentally pushed to master this morning. This pr reverses those commits:
https://github.com/SAP/fundamental-styles/commit/115ff3269b7d3ea8f3d93a859620481a2fa99e37
https://github.com/SAP/fundamental-styles/commit/98245f1fd0c46e3fc828dd38c46b07667bf806e4
=> fix: revert accidental pushes to master

docs/index.html
=> docs: minor text update

package-lock.json, package.json
bump theming library package version
=> chore: bump theming library package version

ci-scripts/publish.sh
PR adds a workaround for creating release notes
=> fix: added workaround for creating release notes

README.md
Added comma in place of apostrophe.
Corrected words to increase readability.
>
=> chore: Update typos in README.md

package-lock.json
update package-lock for security fixes
=> chore: update package-lock for security fixes

ci-scripts/publish.sh
Pr checks if release_tag starts with 'v' character (previous code checked if text contains 'v')
=> chore: check if tag starts with 'v' not if contains v

package-lock.json, package.json
=> chore: bump theming version

src/tokenizer.scss
Closes SAP/fundamental-styles# #860 
Add rtl support for tokenizer
=> fix: add RTL support for Tokenizer

docs/pages/components/button.md
=> docs: reduce some button examples(icon and text)

src/_drag-and-drop.scss, src/product-switch.scss
related to #625
remove fading from drag and drop
=> fix: remove fading from drag and drop

src/button.scss, src/switch.scss
add opacity parameter to disabled switch
=> fix: add opacity parameter to disabled switch

src/button.scss
button disabled opacity to use theming parameter
=> fix: button disabled opacity to use theming parameter

.stylelintignore, docs/_sass/_docs-colors.scss, docs/_sass/_docs-component-list.scss, docs/_sass/_docs-display-component.scss, docs/_sass/_docs-display-responsive-component.scss, docs/_sass/_docs-footer.scss, docs/_sass/_docs-functions.scss, docs/_sass/_docs-general.scss, docs/_sass/_docs-headers.scss, docs/_sass/_docs-home.scss, docs/_sass/_docs-icons.scss, docs/_sass/_docs-main-content.scss, docs/_sass/_docs-right-nav.scss, docs/_sass/_docs-search-box.scss, docs/_sass/_docs-settings.scss, docs/_sass/_docs-side-nav.scss, docs/_sass/_docs-spacing.scss, docs/_sass/_docs-top-nav.scss, docs/_sass/_docs-type.scss, docs/_sass/_docs-utils.scss, docs/_sass/_include-media.scss, docs/_sass/_landingPage.scss, docs/css/printstyles.css, docs/css/syntax.css, package.json
Stylelint was only being run on the `src` directory, this now covers all of our files.
=> chore: expand stylelint to all files

ci-scripts/publish-rc.sh, package-lock.json, package.json
=> fix: standard-version v6

package-lock.json, package.json
=> fix: try locking standard-version to 4.2.0

docs/pages/components/avatar.md, docs/pages/components/image.md, package-lock.json
deprecate Image > Avatar is the successor
=> fix: deprecate Image

docs/pages/patterns/date-picker.md
Defect Hunting
fixes #842 
related #938 
Datepicker example didn't reflect the lastest calendar markup
>
=> docs: Change markup for datepicker

docs/pages/components/form.md
Info about RTL mode added for radio button documentation.
=> docs: info about RTL mode added

docs/pages/components/input-group.md
=> docs: deprecate number input

docs/pages/components/list.md
update list example using old fd-colors
=> docs: update list example using old fd-colors

docs/pages/components/popover.md
remove some popover examples which don't seem appropriate
=> docs: remove some popover examples

docs/pages/resources/design-system-utilities.md
=> docs: remove old doc utilities

docs/_config.yml, docs/_includes/head.html
=> docs: update google analytics

docs/pages/components/table.md, src/table.scss
Part of #914 
Add table navigation indicator class and examples. Note this is a PR to the larger table PR and not to master.
=> feat: table fiori3 navigation indication

docs/_sass/_docs-general.scss, docs/_sass/_docs-tile.scss, docs/css/docs-all.scss, src/mixins/_layouts.scss
Mentioned #1060 
PR brings style fix for layout
=> docs: layout styles fixed

README.md
clarifies what Fundamental Styles provides, and provides a handy url for distribution (ie `https://github.com/SAP/fundamental-styles/blob/master/README.md#sla`)
=> chore: update readme clarify sla

docs/pages/getting-started.md
Update getting started guide to point to font downloads
=> chore: update getting started guide to point to font downloads

docs/pages/components/list.md
a minor doc issue list components
=> docs: a minor doc issue list components

ci-scripts/publish.sh
add workaround for release notes generation
=> chore: add workaround for release notes generation

src/_nested-list.scss, src/_product-switcher.scss, src/layout-panel.scss, src/menu.scss, src/object-status.scss, src/product-tile.scss, src/time.scss
remove dependancies for the migrated components to the old settings file
=> chore: remove dependancies to the old settings file

src/mixins/_mixins.scss
update inverted link hover color
=> fix: update inverted link hover color

docs/pages/components/toolbar.md
=> docs: removed unnecessary class from docs

src/action-bar.scss, src/mixins/button/_attention.scss, src/mixins/button/_ghost.scss, src/mixins/button/_negative.scss, src/mixins/button/_positive.scss, src/mixins/button/_standard.scss, src/shellbar.scss, src/variables.scss
fixes: #1049
PR brings fix for HCB colors in components mentioned in the issue.
See the issue
=> fix: fixing HCB bugs

docs/_data/icons.yml, src/icons/_settings.scss, stories/icon/__snapshots__/icon.stories.storyshot, stories/icon/data.json
=> fix: add new icons

docs/pages/components/file-uploader.md, src/file-uploader.scss, stories/file-uploader/__snapshots__/file-uploader.stories.storyshot, stories/file-uploader/file-uploader.stories.js
Remove the include of the `button.scss` into file-uploader.scss`
This was including the whole button file as part of the file uploader.
=> fix: remove button.scss from file uploader components

docs/pages/components/avatar.md, stories/avatar/avatar.stories.js
This PR adds minor fixes for the Avatar documentation.
=> docs: add minor fixes for Avatar documentation

.storybook/preview-head.html
PR brings fix when popover is clicked. Before it throws console error because function was missing
=> chore: popover click fix

src/popover.scss
This PR removes some unused variables from Popover component
=> chore: Popover variables clean-up

.storybook/custom/custom.scss, src/form-layout-grid.scss, src/layout.scss
Closes SAP/fundamental-styles#493
Closes #970 
Closes #297
Rebase and add storybook into feat-grid-layout-with-new-docs branch
=> feat: rebase and add storybook

stories/localization-editor/localization-editor.stories.js
=> docs: deprecate localization editor

src/form-item.scss
Part of SAP/fundamental-styles#1263
=> fix: align form label and input in horizontal mode

src/product-switch.scss, src/shellbar.scss
related to https://github.com/SAP/fundamental-styles/issues/1263
There was a need to make stronger selector for product switch control.
Also  badge on shellbar was cut by overflow.
>
=> fix: Make stronger selector for product switch, fix badge on shellbar

stories/table/__snapshots__/table.stories.storyshot, stories/table/table.stories.js
Part of SAP/fundamental-styles#1263
=> docs: add fix for Toolbar and Table overlapping

ci-scripts/publish-rc.sh, ci-scripts/publish.sh
=> chore: update the deploy script

ci-scripts/publish-rc.sh, ci-scripts/publish.sh
=> chore: fix release script

src/_functions.scss, src/functions/_deep-get.scss, src/object-status.scss
Closes: #956
This PR updates inverted Object status colors.
=> fix: Update ObjectStatus colors

stories/checkbox/checkbox.stories.js
=> docs: minor update on checkbox

stories/avatar/__snapshots__/avatar.stories.storyshot, stories/avatar/avatar.stories.js
Updating the avatar documentation with more context to the component types, usage and sizes.
=> docs: updating the avatar documentation

src/product-switch.scss
fixes #1285
add mouse pointer for hovered product switch item
=> fix: product switch item on hover fix 

stories/busy-indicator/__snapshots__/busy-indicator.stories.storyshot, stories/busy-indicator/busy-indicator.stories.js
Updating **Busy Indicator** component documentation.
=> docs: updated busy indicator documentation

.gitignore, .storybook/main.js, .storybook/preview-head.html, .storybook/preview.js, package-lock.json, package.json, scripts/storybook-prep.js
see: https://github.com/SAP/fundamental-react/pull/1151
This improves performance a bit and cleans up storybook scripts. I left webpack warnings turned on because there's still a lot of room for improvement, but this is a good jumping off point.
=> docs: storybook improvements

src/product-switch.scss, src/shellbar.scss
fixes: #1288 
**The visual tests for shellbar and product switch should fail**
=> fix: update shellbar icon color

stories/bar/__snapshots__/bar.stories.storyshot, stories/bar/bar.stories.js
=> docs: update Bar documentation

src/feed-input.scss, stories/feed-input/feed-input.stories.js
- added `In Development` tag
- added disabled state for the entire component to show the not-allowed cursor
=> fix: minor fixes for Feed Input component

stories/button/button.stories.js
Updated the documentation for the **button** component.
=> docs: updated button documentation

scripts/storybook-prep.js
This is a minor improvement of `sorybook-prep.js` code readability. If you are wondering about performance of calling `readFileSync` as a template literal, it doesn't have any significant negative impact (after rework code is the same/a bit faster than previous version).
=> chore: Improve storybook-prep.js code

src/avatar.scss, src/shellbar.scss, stories/shellbar/shellbar.stories.js
The Avatar got few design updates:
- border color theming parameter
- badge color and background theming parameters
Before:
After:
=> fix: avatar design updates

src/form-layout-grid.scss, stories/form-grid/form-grid.stories.js
Closes SAP/fundamental-styles#1312
Add recommended columns for form groups using grids to documentation
=> fix: add recommended columns to form grids

stories/button/button.stories.js, stories/calendar/calendar.stories.js
Updating documentation for **calendar component**.
=> docs: updated calendar documentation

stories/icon/icon.stories.js
=> docs: updated icon documentation

.reuse/dep5, LICENSE, NOTICE
Migrate Fundamental Styles from CLA to DCO
fixes: #1348
=> chore: migrate from CLA to DCO

src/shellbar.scss, stories/shellbar/__snapshots__/shellbar.stories.storyshot, stories/shellbar/shellbar.stories.js
Closes https://github.com/SAP/fundamental-styles/issues/1542
In this PR I Changed way how shellbar deals with responsive behaviour. I added 4 modifiers:
- `fd-shellbar-- (s/m/l/xl)`
and removed hardcoded breakpoints.
Also there are new examples of usage and fixed indent of examples, previous one was hard to read.
=> fix: Fiori 3 shellbar margin

.storybook/custom/components/tags.json, .storybook/preview-head.html, src/action-sheet.scss, src/button.scss, src/dialog.scss, src/mixins/_layouts.scss, src/mixins/_popover.scss, src/popover.scss, src/theming/sap_fiori_3.scss, src/theming/sap_fiori_3_dark.scss, src/theming/sap_fiori_3_hcb.scss, src/theming/sap_fiori_3_hcw.scss, src/theming/sap_fiori_3_light_dark.scss, stories/action-sheet/__snapshots__/action-sheet.stories.storyshot, stories/action-sheet/action-sheet.stories.js, stories/action-sheet/action-sheet.visual.js
Closes https://github.com/SAP/fundamental-styles/issues/1577
There is new component called Action Sheet. 
Also to achieve the look I had to add
- new modifier to button, called `--full-width`, to keep width of container.
>
Desktop:
Tablet:
Mobile:
=> feat: new component Action Sheet

src/rating-indicator.scss, src/theming/sap_fiori_3.scss, src/theming/sap_fiori_3_dark.scss, src/theming/sap_fiori_3_hcb.scss, src/theming/sap_fiori_3_hcw.scss, src/theming/sap_fiori_3_light_dark.scss
remove unused rating indicator delta theming variables
=> fix: remove unused rating indicator delta theming variables

src/object-identifier.scss, src/table.scss, stories/object-identifier/__snapshots__/object-identifier.stories.storyshot, stories/object-identifier/object-identifier.stories.js, stories/object-identifier/object-identifier.visual.js
Closes #1444
Introducing the new Object Identifier component
=> feat: new Object Identifier component

src/icon.scss
=> fix: Reset font-style on icons

src/action-sheet.scss, src/object-status.scss, src/rating-indicator.scss, src/theming/sap_fiori_3.scss, src/theming/sap_fiori_3_dark.scss, src/theming/sap_fiori_3_hcb.scss, src/theming/sap_fiori_3_hcw.scss, src/theming/sap_fiori_3_light_dark.scss
rename the delta theming parameters with fd prefix
=> chore: rename the delta theming parameters with fd prefix

src/product-switch.scss, stories/product-switch/product-switch.stories.js
Closes https://github.com/SAP/fundamental-styles/issues/1603
Breaking Changes - Markup/A11Y changes
Before:
```
<div class="fd-product-switch__icon sap-icon--home"></div>
```
After:
```
<i role="presentation" class="fd-product-switch__icon sap-icon--home"></i>
```
=> fix: change icons on product switch

src/message-page.scss, stories/message-page/message-page.stories.js
Successor of: #1654
Part of: #1603, #1639
This PR: 
- Updates icon styling with icon mixins
- Updates icons markup
- Adds aria attributes
```
<span class="sap-icon sap-icon--filter fd-message-page__icon"></span>
```
```
<i role="presentation" class="sap-icon--filter fd-message-page__icon"></i>
```
=> fix: Message Page - Refactor icons usage - #2

stories/file-uploader/__snapshots__/file-uploader.stories.storyshot, stories/file-uploader/file-uploader.stories.js
Update File Uploader accessibility:
- Add aria-live region with file name
- Make readonly input tabbable
- Fix incorrect aria attributes on input
- Add example of post file selection
No visual changes
=> fix: update file uploader accessibility

.storybook/preview-head.html, stories/action-bar/__snapshots__/action-bar.stories.storyshot, stories/action-bar/action-bar.stories.js, stories/breadcrumb/__snapshots__/breadcrumb.stories.storyshot, stories/breadcrumb/breadcrumb.stories.js, stories/feed-input/feed-input.stories.js, stories/form-message/form-message.stories.js
Closes: https://github.com/SAP/fundamental-styles/issues/1682
closes: #1683 
This PR fixes:
- file uploader click bug - added missing method
- RTL example on action bar
- Breadcrump overflow popover + increase size of iFrame
- Feed input - removed redundant class
- Form Message - Display message on focus/focusout
>
=> docs: 0.12.0 minor docs issues

stories/form-grid/__snapshots__/form-grid.stories.storyshot, stories/form-grid/form-grid.stories.js
In this PR there are added fixes related to A11y:
- Added missing labels
- Removed invalid roles
- Removed duplicated ID/For attributes.
>
=> docs: A11y on form grid examples

stories/list/byline/byline-list.stories.js, stories/list/standard/standard-list.stories.js
Part of: #1433
This PR:
- makes sure all of the id attribute values used in list documentation are unique
=> fix: Unique id values in list examples

stories/input/__snapshots__/input.stories.storyshot, stories/input/input.stories.js
Part of: #1433
This PR is fixing documentation code (invalid markup).
=> fix: Input States documentation

stories/select/select.stories.js
fixes #1686
update select button 
=> docs: update 2 column select button example

stories/card/card.stories.js
Part of: #1433
This PR:
- Updates Avatar component markup in Object Card example
```
<span class="fd-avatar fd-avatar--xs fd-avatar--circle sap-icon--person-placeholder" role="presentation"></span>
```
```
<span class="fd-avatar fd-avatar--xs fd-avatar--circle" aria-label="Avatar">
<i class="fd-avatar__icon sap-icon--person-placeholder" role="presentation"></i>
</span>
```
=> fix: update Avatar in Object Card example

stories/checkbox/__snapshots__/checkbox.stories.storyshot, stories/checkbox/checkbox.stories.js
=> docs: updated checkbox documentation

.reuse/dep5, LICENSE, LICENSES/Apache-2.0.txt, README.md
=> chore: add REUSE badge

src/toolbar.scss
fixes: #1044 
Update toolbar separator background variable with the new theming parameter
3. Testing
=> chore: replace toolbar temporary variable

stories/action-bar/__snapshots__/action-bar.stories.storyshot, stories/action-bar/action-bar.stories.js
=> docs: updated action bar documentation

src/layout-grid.scss, stories/layout-grid/__snapshots__/layout-grid.stories.storyshot, stories/layout-grid/layout-grid.stories.js
Closes SAP/fundamental-styles#1734
New modifier class called `--full` to make layout grid column take the remaining space left
Due to the grid being min 1/12 it still does have a min-width of 1/12 columns
none
3. Testing
=> feat: add full class modifier

stories/feed-input/__snapshots__/feed-input.stories.storyshot, stories/feed-input/feed-input.stories.js
=> docs: updated feed input documentation

stories/card/__snapshots__/card.stories.storyshot, stories/card/card.stories.js
=> docs: updated card documentation

README.md
* Update README link to point to updated documentation, after this change: https://github.com/SAP/fundamental-styles/pull/1584
* Added a Storybook badge pointing to the storybook built by Chromatic for the master branch
- [NA] Responsiveness rules - the component has modifier classes for all breakpoints …
=> chore: update README visual testing link.

stories/list/byline/__snapshots__/byline-list.stories.storyshot, stories/list/byline/byline-list.stories.js
=> docs: updated byline list documentation

stories/list/standard/__snapshots__/standard-list.stories.storyshot, stories/list/standard/standard-list.stories.js
Updated **Standard List** docs.
=> docs: updated standard list documentation

stories/avatar/__snapshots__/avatar.stories.storyshot, stories/avatar/avatar.stories.js, stories/card/__snapshots__/card.stories.storyshot, stories/card/card.stories.js, stories/carousel/__snapshots__/carousel.stories.storyshot, stories/carousel/carousel.stories.js, stories/combobox-input/combobox-input.stories.js, stories/datepicker/datepicker.stories.js, stories/feed-input/feed-input.stories.js, stories/info-label/info-label.stories.js, stories/input-group/input-group.stories.js, stories/input/input.stories.js, stories/multi-input/multi-input.stories.js, stories/notification/__snapshots__/notification.stories.storyshot, stories/notification/notification.stories.js, stories/object-list/__snapshots__/object-list.stories.storyshot, stories/object-list/object-list.stories.js, stories/popover/__snapshots__/popover.stories.storyshot, stories/popover/popover.stories.js, stories/product-switch/product-switch.stories.js, stories/select/select.stories.js, stories/shellbar/shellbar.stories.js, stories/specific-tile/__snapshots__/specific-tile.stories.storyshot, stories/specific-tile/specific-tile.stories.js, stories/table/table.stories.js, stories/tabs/tabs.stories.js, stories/time/time.stories.js
update component dependencies for the storybook and replace the images URL as the previous weren't working
>
- [N/A] All values are in `rem`
- [N/A] Text elements follow the truncation rules
- …
=> docs: add story dependencies

stories/message-toast/__snapshots__/message-toast.stories.storyshot, stories/message-toast/message-toast.stories.js
Updated **Message Toast** docs.
=> docs: updated message toast documentation

stories/message-strip/__snapshots__/message-strip.stories.storyshot, stories/message-strip/message-strip.stories.js
Updated **Message Strip** docs.
=> docs: updated message strip documentation

stories/message-page/__snapshots__/message-page.stories.storyshot, stories/message-page/message-page.stories.js
Same as https://github.com/SAP/fundamental-styles/pull/1798 but without Message Strip
=> docs: updated message page documentation

stories/menu/__snapshots__/menu.stories.storyshot, stories/menu/menu.stories.js
part of https://github.com/SAP/fundamental-styles/issues/1760
=> fix: menu styles and improved accessibility

src/calendar.scss, stories/calendar/calendar.stories.js
Closes https://github.com/SAP/fundamental-styles/issues/1760
>
=> fix: Calendar navigation button, add missing imports

stories/action-bar/__snapshots__/action-bar.stories.storyshot, stories/action-bar/action-bar.stories.js
part of https://github.com/SAP/fundamental-styles/issues/1760
Ther is added missing popover functionality.
=> docs: bring popover to action bar

stories/context-menu/__snapshots__/context-menu.stories.storyshot, stories/context-menu/context-menu.stories.js, stories/multi-input/__snapshots__/multi-input.stories.storyshot, stories/multi-input/multi-input.stories.js, stories/time-picker/__snapshots__/time-picker.stories.storyshot, stories/time-picker/time-picker.stories.js
Part of SAP/fundamental-styles#1760
Affected components: Contextual menu, Multi Input (filtering), Time Picker (Tablet mode)
In some examples the way we specify the height of the iframe didn't work. Had to provide a wrapping div with a fixed height.
Also fixed a typo for Contextual menu
=> fix: multi-input accessibility + add iframe height to some examples

stories/message-box/__snapshots__/message-box.stories.storyshot, stories/message-box/message-box.stories.js
=> docs: updated message box documentation

src/icons/_settings.scss, stories/icon/__snapshots__/icon.stories.storyshot, stories/icon/data.json
fix the code for `keyboard-and-mouse`
add icons `s4hana` and `translate`
#
=> fix: add 2 new icons

src/form-header.scss, src/theming/sap_fiori_3.scss, src/theming/sap_fiori_3_dark.scss, src/theming/sap_fiori_3_hcb.scss, src/theming/sap_fiori_3_hcw.scss, src/theming/sap_fiori_3_light_dark.scss, stories/form-header/__snapshots__/form-header.stories.storyshot, stories/form-header/form-header.stories.js
Introduce Form Header which is needed for Wizard Summary page
Note:
--sapFontHeaderWeight is not present in sap-theming, the designers have been contacted about this.
- [N/A] Responsiveness rules - the component has modifier classes for all breakpoints
- [N/A] Includes Compact/Cosy/Tablet design
3. Testing
- [N/A] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-C …
=> feat: add Form Header

src/product-switch.scss, stories/product-switch/__snapshots__/product-switch.stories.storyshot, stories/product-switch/product-switch.stories.js
Part of SAP/fundamental-styles#1818
Replaced `multiline-truncate` with `line-clamp` as `multiline-truncate` was causing a lot of issues
>
3. Testing
=> fix: add fix for Product Switch truncation issue

package-lock.json, package.json
bump theming-base-content version
=> chore: bump theming-base-content version

src/button.scss, src/mixins/button/_badge.scss, src/theming/sap_fiori_3.scss, src/theming/sap_fiori_3_dark.scss, src/theming/sap_fiori_3_hcb.scss, src/theming/sap_fiori_3_hcw.scss, src/theming/sap_fiori_3_light_dark.scss, stories/button/__snapshots__/button.stories.storyshot, stories/button/button.stories.js
Closes SAP/fundamental-styles#1251
There is added badge in button, with example. Besides that in this PR I decided to add `inline-flex` for button, to keep vertically center alignment. There is not big visual change, but probably many icons previously not centered correctly will be moved by 1px,.
Also way how margins are applied between icons/text is changed. now the margin is added between every elements.
> …
=> feat: add Button with badge

stories/action-sheet/__snapshots__/action-sheet.stories.storyshot, stories/action-sheet/action-sheet.stories.js, stories/select/__snapshots__/select.stories.storyshot, stories/select/select.stories.js, stories/table/table.stories.js
Part of SAP/fundamental-styles#1818
For Action Sheet and Select - show the popover body so tests can detect changes there
Grid Table - add missing import of Select which caused issues in one of the Table columns
=> docs: documentation improvements for Grid Table, Action Sheet and Select

stories/pagination/__snapshots__/pagination.stories.storyshot, stories/pagination/pagination.stories.js
=> docs: updated pagination documentation

src/token.scss, src/tokenizer.scss
Part of: #1760
This PR:
- removes growing behavior from Token
- add proper max-width for tokens inside the tokenizer
=> fix: Prevent token from growing

stories/panel/__snapshots__/panel.stories.storyshot, stories/panel/panel.stories.js
=> docs: updated panel documentation

stories/product-switch/__snapshots__/product-switch.stories.storyshot, stories/product-switch/product-switch.stories.js
Updated **Product Switch** docs.
=> docs: updated product switch documentation

.storybook/custom/custom.scss, src/flexible-column-layout.scss, src/mixins/_mixins.scss, src/theming/sap_fiori_3.scss, src/theming/sap_fiori_3_dark.scss, src/theming/sap_fiori_3_hcb.scss, src/theming/sap_fiori_3_hcw.scss, src/theming/sap_fiori_3_light_dark.scss, stories/flexible-column-layout/__snapshots__/flexible-column-layout.stories.storyshot, stories/flexible-column-layout/flexible-column-layout.stories.js
Closes SAP/fundamental-styles#1878
There is added `flexible column layout` component with delta theming and examples of usage.
- [NA] RTL support
3. Testing
=> feat: flexible column layout

.storybook/custom/custom.scss, src/fundamental-styles.scss, src/text.scss, stories/text/__snapshots__/text.stories.storyshot, stories/text/text.stories.js
No related issue
Introduce text component styles
3. Testing
=> feat: introduce Text component

CODE_OF_CONDUCT.md
add code of conduct file
- [N/A] All values are in `rem`
- [N/A] Text elements follow the truncation rules
- [N/A] pressed state of the element follow design spec
- [N/A] Responsiveness rules - the component has modifier classes for all breakpoints
- [N/A] Includes Compact/Cosy/Tablet design
- [N/A] RTL support
- [N/A] only one top level `fd-*` class is used in the file
- [N/A] BEM naming convention is used
- …
=> chore: add code of conduct file

src/_listDefinitions.scss, src/_listItemCounter.scss, src/list.scss, stories/list/standard/__snapshots__/standard-list.stories.storyshot, stories/list/standard/standard-list.stories.js
Closes SAP/fundamental-styles#1400
introduce an enhancement to List component - Item Counter
- [na] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
3. Testing
- [na] Breaking Changes …
=> feat: add Item Counter to List component

src/_listBase.scss, src/_listDropdown.scss, stories/multi-combo-box/__snapshots__/multi-combo-box.stories.storyshot, stories/multi-combo-box/multi-combo-box.stories.js
introducing new multi combobox style changes
https://github.com/SAP/fundamental-styles/issues/1469
Introducing the Multi Combobox. Since Multi combobox is a pattern component it is dependent on few other components like
Input Group, button, token, tokenizer, bar, popover.
3. Testing
=> feat: introducing new multi combobox style changes

.storybook/custom/custom.scss, src/fundamental-styles.scss, src/list-grid.scss, src/theming/sap_fiori_3.scss, src/theming/sap_fiori_3_dark.scss, src/theming/sap_fiori_3_hcb.scss, src/theming/sap_fiori_3_hcw.scss, src/theming/sap_fiori_3_light_dark.scss, stories/list-grid/__snapshots__/list-grid.stories.storyshot, stories/list-grid/list-grid.stories.js
Closes https://github.com/SAP/fundamental-styles/issues/867
Introducing the new Grid List component
3. Testing
=> feat: introduce Grid List component

stories/shellbar/__snapshots__/shellbar.stories.storyshot, stories/shellbar/shellbar.stories.js
=> docs: updated shellbar documentation

src/form-group.scss, src/form-layout-grid.scss, stories/form-group/__snapshots__/form-group.stories.storyshot, stories/form-group/form-group.stories.js
Closes SAP/fundamental-styles#1880
PR introduces Form Group Header to Form Group
N/A
3. Testing
=> feat: introduce Form Group Header to Form Group

src/flexible-column-layout.scss
This PR adds animation for the change of the column width when switching layouts.
=> fix: add animation for column in Flexible Column Layout

stories/slider/__snapshots__/slider.stories.storyshot, stories/slider/slider.stories.js
{{ _Updated **Slider** docs._ }}
=> docs: update Slider documentation

stories/side-navigation/__snapshots__/side-navigation.stories.storyshot, stories/side-navigation/side-navigation.stories.js
{{ Updating **Side Navigation** docs. }}
=> docs: update Side Navigation documentation

stories/list-grid/__snapshots__/list-grid.stories.storyshot, stories/list-grid/list-grid.stories.js
Part of SAP/fundamental-styles#1907
In IE11 the examples are not visible as the iframe has no height.
=> docs: add height for the iframe in Grid List examples

stories/shellbar/shellbar.stories.js
Updates the documentation for Shellbar. This PR is a copy of https://github.com/SAP/fundamental-styles/pull/1914 which for some reason cannot be rebased with latest master and shows conflicting files.
=> docs: update ShellBar documentation

stories/step-input/__snapshots__/step-input.stories.storyshot, stories/step-input/step-input.stories.js
=> docs: update Step Input documentation

src/dynamic-page.scss, stories/dynamic-page/__snapshots__/dynamic-page.stories.storyshot, stories/dynamic-page/dynamic-page.stories.js
Closes SAP/fundamental-styles#1800
This PR does the following:
- aligns title and title content in Dynamic Page 
- modifies z-index usage to fix look in mobile popover case
- keeps title content ellipsible and restricts to single line to maintain alignment
- uses variable for common value
Breaking change:
- removed modifier class `fd-dynamic-page__collapsible-header-container--collapsed`
>
alignment: ![image](https://user-images.githubusercontent.com/53509521/100732336-992e9080-33f2-11eb-8f43-ae22ab29fb57.png) …
=> fix: align title and title content in Dynamic Page

src/feed-input.scss
Closes
https://github.com/SAP/fundamental-ngx/issues/4020
The issue raised in the ngx but actually related to styles
- [na] only one top level `fd-*` class is used in …
=> fix: change min width when a user image will disappear Feed Input

package-lock.json, package.json
no need to update anything on our end for now
- [N/A] All values are in `rem`
- [N/A] Text elements follow the truncation rules
- [N/A] pressed state of the element follow design spec
- [N/A] Responsiveness rules - the component has modifier classes for all breakpoints
- [N/A] Includes Compact/Cosy/Tablet design
- [N/A] RTL support
- [N/A] only one top level `fd-*` class is used in the file
- [N/A] BEM naming …
=> chore: bump theming-base-content to version 11.1.24

src/checkbox.scss
Closes SAP/fundamental-styles#1343
Changes the margin to the text element of the checkbox. 
This will remove the unwanted spacing for focus when there is no label
3. Testing
=> fix: checkbox focus with margin

README.md
=> docs: update dead link on README.md

stories/tabs/__snapshots__/tabs.stories.storyshot, stories/tabs/tabs.stories.js
=> docs: update Tabs component documentation

stories/toolbar/__snapshots__/toolbar.stories.storyshot, stories/toolbar/toolbar.stories.js
=> docs: update Toolbar component documentation

.travis.yml, CHANGELOG.md, README.md, ci-scripts/publish.sh, config/postcss.config.js, scripts/publish-release.sh
Part of  SAP/fundamental-styles#1751
Changes all inner files that use "master" for github to main
=> chore: change master to main and update travis.yml

.storybook/custom/custom.scss
This is testing PR, to check chromatic and CI
=> test: Check CI/Chromatic

stories/form-item/form-item.stories.js
{{ _Updated **Form Item** docs._ }}
=> docs: update form item documentation

stories/form-label/form-label.stories.js
{{ _Updated **Form Label** docs._ }}
=> docs: update form label documentation

stories/form-header/__snapshots__/form-header.stories.storyshot, stories/form-header/form-header.stories.js
=> docs: update form header documentation

stories/form-group/__snapshots__/form-group.stories.storyshot, stories/form-group/form-group.stories.js
{{ _Updated **Form Group** docs._ }}
=> docs: update form group documentation

stories/token/__snapshots__/token.stories.storyshot, stories/token/token.stories.js
=> docs: update token component documentation

src/fundamental-styles.scss, src/layout-grid.scss, stories/layout-grid/__snapshots__/layout-grid.stories.storyshot, stories/layout-grid/layout-grid.stories.js
BREAKING CHANGES: `.fd-layout-grid--no-gap` removed
`.fd-layout-grid--no-vertical-gap` added
`.fd-layout-grid--no-horizontal-gap` added
Closes SAP/fundamental-styles#1803
This PR adds more control to having no gap for layout grids.
The user can now choose between having no vertical gap which removes space in between rows, no horizontal gap which removes spacing between rows or can have no gap at all.
After consists of before and more
3. Testing
=> feat: more control over no gap for grid layout

stories/calendar/calendar.stories.js
Closes SAP/fundamental-styles#1277
Add segmented button class in list of components
3. Testing
=> fix: segmented button on calendar

src/table.scss
Closes SAP/fundamental-styles#1329
Add background color for the table's footer
If it is hard to see it's because of your monitor
3. Testing
=> fix: table footer background color

stories/form-grid/__snapshots__/form-grid.stories.storyshot, stories/form-grid/form-grid.stories.js
{{ _Updated **Form Grid** docs._ }}
Comment: I think it's best to remove the last example, since we shouldn't be providing an example of layouts that are unrecommended. Instead, I would like to add a note that advises against them in the "Recommended layouts" example.
=> docs: update form grid documentation

stories/form-message/form-message.stories.js
{{ _Updated **Form Message** docs._ }}
=> docs: update form message documentation

stories/switch/__snapshots__/switch.stories.storyshot, stories/switch/switch.stories.js
{{ _Updated **Switch** docs._ }}
Code needs to be reorganized before this documentation is done (for the withText example)
NS = need support.
=> docs: updated switch documentation

stories/table/__snapshots__/table.stories.storyshot, stories/table/table.stories.js
{{ Updated **Table** component docs. }}
NS = need support
The Responsive Table example needs to be reviewed to better understand its use case, and if it's really different from the default table examples.
=> docs: updated table documentation

src/_listBase.scss, src/theming/sap_fiori_3.scss, src/theming/sap_fiori_3_dark.scss, src/theming/sap_fiori_3_hcb.scss, src/theming/sap_fiori_3_hcw.scss, src/theming/sap_fiori_3_light_dark.scss
add delta theming for Action List Item
NA
3. Testing
NA
NA
=> fix: add delta theming for List

src/link.scss, src/mixins/_mixins.scss, src/theming/sap_fiori_3.scss, src/theming/sap_fiori_3_dark.scss, src/theming/sap_fiori_3_hcb.scss, src/theming/sap_fiori_3_hcw.scss, src/theming/sap_fiori_3_light_dark.scss
Adds delta theming for Link. 
NA
3. Testing
NA
NA
=> fix: add delta theming for Link

src/page.scss, src/theming/sap_fiori_3.scss, src/theming/sap_fiori_3_dark.scss, src/theming/sap_fiori_3_hcb.scss, src/theming/sap_fiori_3_hcw.scss, src/theming/sap_fiori_3_light_dark.scss
part of #1357 
These code changes don't result in visual changes but match the specifications
=> fix: add delta theming for Page

src/table.scss, src/theming/sap_fiori_3.scss, src/theming/sap_fiori_3_dark.scss, src/theming/sap_fiori_3_hcb.scss, src/theming/sap_fiori_3_hcw.scss, src/theming/sap_fiori_3_light_dark.scss
part of #1357 
No screenshots as this does not result in visual changes
=> fix: add delta theming for Table

src/feed-input.scss, src/theming/sap_fiori_3.scss, src/theming/sap_fiori_3_dark.scss, src/theming/sap_fiori_3_hcb.scss, src/theming/sap_fiori_3_hcw.scss, src/theming/sap_fiori_3_light_dark.scss
Add delta theming for Feed Input placeholder font-style
NA
NA
3. Testing
NA
NA
=> fix: add delta theming for Feed Input

stories/form-fieldset/__snapshots__/form-fieldset.stories.storyshot, stories/form-fieldset/form-fieldset.stories.js
part of https://github.com/SAP/fundamental-styles/issues/2045
There is updated markup for checkbox in field set
3. Testing
=> docs: Change example in checkbox field set

src/feed-list.scss
Part of SAP/fundamental-styles#2045
NA
NA
3. Testing
NA
NA
=> fix: change the cursor to pointer for MORE/LESS links in Feed List Item

scripts/build-visual-stories.js
reduce chromatic theming tests
=> chore: reduce chromatic theming tests

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/chromatic.yml
The PR brings changes how the visual regression testing is done as part of the PRs.
By default the visual regression won't be triggered. In order to trigger it a commit has to have the following string `[ci visual]`
If we agree to go this way then we need to update the documentation and how a PR should be opened and maintained.
The [wiki](https://github.com/SAP/fundamental-styles/wiki/Visual-testing-with-Chromatic) has been updated.
=> chore: update the rules for running chromatic in PRs

src/_listBase.scss, src/_listByline.scss, src/theming/sap_fiori_3.scss, src/theming/sap_fiori_3_dark.scss, src/theming/sap_fiori_3_hcb.scss, src/theming/sap_fiori_3_hcw.scss, src/theming/sap_fiori_3_light_dark.scss, stories/list/byline/__snapshots__/byline-list.stories.storyshot, stories/list/byline/byline-list.stories.js, stories/list/standard/__snapshots__/standard-list.stories.storyshot, stories/list/standard/standard-list.stories.js
Part of https://github.com/SAP/fundamental-styles/issues/2063
>
3. Testing
=> feat: button inside list

src/object-identifier.scss, stories/object-identifier/__snapshots__/object-identifier.stories.storyshot, stories/object-identifier/object-identifier.stories.js
Closes SAP/fundamental-styles#1742
There is simplification of object identifier.
Now link has to be used with `fd-link`. Previously there was 2 ways to make `link` object identifier. which didn't make any sense.
Also `medium` size is not restricted to table anymore
Removed Classes:
- `fd-object-identifier__title--link`
- `fd-object-identifier__table`
Added:
- `fd-object-identifier--medum`
>
No visual changes.
- [NA] RTL support
2. The code follows fundamental-styles code …
=> fix: Simplify object identifier

package-lock.json
update browserlist package version
=> chore: update browserlist package version

src/_listDefinitions.scss
Part of SAP/fundamental-styles#2063
updated the color of the Navigated Item Indicator in List component
=> fix: update the color of nav indicator in List

package-lock.json, package.json
bump theme-base-content to 11.1.26
=> chore: bump theme-base-content to 11.1.26 [ci visual]

.github/workflows/chromatic.yml
improve chromatic to run dependabot PRs
=> chore: improve chromatic to run dependabot PRs

src/list-grid.scss
Closes https://github.com/SAP/fundamental-ngx/issues/4560
Fixed label focus style and added overflow for item
3. Testing
=> fix: grid list styles

stories/quick-view/__snapshots__/quick-view.stories.storyshot, stories/quick-view/quick-view.stories.js
Closes https://github.com/SAP/fundamental-styles/issues/2126
- [n/a] only one top level `fd-*` class is used in the file
- …
=> docs: centered Quick View title

stories/action-bar/__snapshots__/action-bar.stories.storyshot, stories/action-bar/action-bar.stories.js
=> docs: action bar popover needs to be right aligned

stories/token/token.stories.js
part of https://github.com/SAP/fundamental-styles/issues/2090
3. Testing
=> docs: Add input import to tokenizer docs

stories/bar/__snapshots__/bar.stories.storyshot, stories/bar/bar.stories.js
=> docs: cozy bar footer needs cozy buttons

stories/notification/__snapshots__/notification.stories.storyshot, stories/notification/notification.stories.js
=> docs: updates to notification group docs

stories/message-page/message-page.stories.js
=> docs: import link on message page

.storybook/static/preview-head.js, stories/checkbox/checkbox.stories.js
part of #2090 
Set tristate checkbox to indeterminate on load
=> docs: tristate checkboxes indeterminate on load

stories/object-list/__snapshots__/object-list.stories.storyshot, stories/object-list/object-list.stories.js
part of #2090 
Previously object list was using critical semantics for everything.  This just adds some variation
=> docs: add some variation to object list docs

package-lock.json, package.json
=> chore: bump standard-version 9.1.0

.storybook/static/preview-head.js, stories/multi-combo-box/__snapshots__/multi-combo-box.stories.storyshot, stories/multi-combo-box/multi-combo-box.stories.js
update the checkbox ids in the multi combo box page.
=> docs: update checkbox ids in multi combo docs

stories/notification/__snapshots__/notification.stories.storyshot, stories/notification/notification.stories.js
revert notification group docs update
=> docs: revert notification group docs update

src/_listDropdown.scss
=> fix: remove border-bottom radius from mult-input list items

src/dynamic-page.scss, stories/dynamic-page/__snapshots__/dynamic-page.stories.storyshot, stories/dynamic-page/dynamic-page.stories.js
Closes https://github.com/SAP/fundamental-styles/issues/2128
There is refactor  of dynamic page - A lot of classes have been removed / updated. 
Examples have been changed to keep cozy buttons / cozy footers.
Placement for toolbars with buttons has been changed. For
- Desktop - it's aligned with title in single line
- Tablet / Mobile - first row is aligned with breadcrumb, second is aligned with a the tite
- Removed all of size modifier classes with `--sm/--md/--lg/--xl`
- Removed `fd-dynamic-page__actions-container` - Additional container is not needed anymore
- `fd-dynamic-page__toolbar-actions` changed to `fd-dynamic-page__toolbar--actions`
- `fd-dynamic-page__content-toolbar` changed to `fd-dynamic-page__toolbar--content`
- `fd-tab` size modifier are not needed anymore 
- Placement of …
=> fix: simplify dynamic page

src/dynamic-page.scss, src/facet.scss, src/fundamental-styles.scss, src/object-number.scss, src/object-status.scss, stories/dynamic-page/__snapshots__/dynamic-page.stories.storyshot, stories/dynamic-page/dynamic-page.stories.js, stories/facets/__snapshots__/facets.stories.storyshot, stories/facets/facets.stories.js
Closes SAP/fundamental-styles#2020
This PR introduces Facets. Facets are used with Object Page and Dynamic Page usually, but the facet types can also be used independently. Therefore, we are introducing Facets as a component by itself, which consists of different facet types- form facet, key-value facet, image facet, and rating indicator facet.
It also introduce a couple of new classes in Dynamic Page to work with the image facet when used in the header.
3. Testing
=> feat: introduce Facets- Form, Key-value, Image, and Rating Indicator

src/message-toast.scss
=> fix: center message toast text [ci visual]

src/icon.scss, src/mixins/_icons.scss
Deleted some code that was not really used.
=> chore: cleanup redundant code for icons [ci visual]

.travis.yml
update node version to 15.11.0 for travis
=> chore: update node version to 15.11.0 for travis

src/fundamental-styles.scss, src/page-footer.scss, stories/page-footer/__snapshots__/page-footer.stories.storyshot, stories/page-footer/page-footer.stories.js
Closes SAP/fundamental-styles#2232
introduce non fiori3 page footer component, as part of the platform ngx component development
3. Testing
=> feat: Introduce non fiori3 page footer component

src/badge.scss, src/user-menu.scss, stories/user-menu/__snapshots__/user-menu.stories.storyshot, stories/user-menu/user-menu.stories.js
Closes https://github.com/SAP/fundamental-styles/issues/2241
Introduce User Actions Menu component
>
3. Testing
- Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.
=> feat: introduce User Menu component

.github/dependabot.yml
=> chore: cleanup dependabot config

package-lock.json, package.json
=> chore: revert the react version

src/rating-indicator.scss, src/resizable-card-layout.scss, src/status-indicator.scss
Closes https://github.com/SAP/fundamental-styles/issues/1753
Remove unneeded import of 'icon' file
3. Testing
=> chore: remove unneeded icon import

src/wizard.scss, stories/wizard/__snapshots__/wizard.stories.storyshot, stories/wizard/wizard.stories.js
fixes https://github.com/SAP/fundamental-styles/issues/2200
change styling priorities in order to apply correct styles for stacked steps
>
3. Testing
=> fix: Wizard - change styling priorities in order to apply correct styles for stacked steps

src/fixed-card-layout.scss, src/fundamental-styles.scss, stories/fixed-card-layout/__snapshots__/fixed-card-layout.stories.storyshot, stories/fixed-card-layout/fixed-card-layout.stories.js
part of https://github.com/SAP/fundamental-ngx/issues/5025
Fixed card layout component styles was not created in styles and was present in Ngx.
This can be moved to styles now. when this is merged and available, styles from Ngx can be removed and can be imported from styles.
3. Testing
- na Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.
=> feat: introduce Fixed Card Layout component

.github/workflows/codeql-analysis.yml
=> chore: security scans

package-lock.json
=> chore: fix security issue

.storybook/static/preview-head.js, config/bundlesize.json, package-lock.json, src/_listDefinitions.scss, src/_listNavigationItem.scss, src/_listNavigationItemIndication.scss, src/_nested-list.scss, src/fundamental-styles.scss, src/list.scss, src/mixins/_mixins.scss, src/theming/sap_fiori_3.scss, src/theming/sap_fiori_3_dark.scss, src/theming/sap_fiori_3_hcb.scss, src/theming/sap_fiori_3_hcw.scss, src/theming/sap_fiori_3_light_dark.scss, src/vertical-nav.scss, stories/side-navigation/side-navigation.stories.js, stories/vertical-navigation/__snapshots__/vertical-navigation.stories.storyshot, stories/vertical-navigation/vertical-navigation.stories.js
closes #2211 
This is the same PR as https://github.com/SAP/fundamental-styles/pull/2278 opened by @mikerodonnell89  but because Travis was failing and nothing really helped I moved the code to this PR. Please check #2278 for the review comments.
Implements the vertical navigation and deprecates side navigation
3. Testing
=> feat: introduce Vertical Navigation component

commitlint.config.js
Updated commitlint rules: 
- body-max-line-length: 200
- footer-max-line-length: 200
=> chore: update commitlint rules

src/input-group.scss
Closes SAP/fundamental-styles#2235
Highlight focused state for button in input-group by design (see screenshots from design how it has to look)
>
There were no state
Added state
3. Testing
=> fix: add focused state for buttons in input-groups

ci-scripts/publish.sh, package.json
=> chore: fix version release

src/avatar-group.scss
Part of https://github.com/SAP/fundamental-ngx/issues/5285
Added classes for: 
- hide scrollbar in overflow body (`.fd-avatar-group__overflow-body--no-horizontal-scroll` and `.fd-avatar-group__overflow-body--no-vertical-scroll`)
- remove the padding in overflow body (`.fd-avatar-group__overflow-body--no-padding`)
- [ N/A] All values are in `rem`
- [ N/A] Text elements follow the truncation rules
- [ N/A] hover state of the element follow design spec
- [ N/A] focus state of the element follow design spec
- [ N/A] active state of the element follow design spec
- [ N/A] selected state of the element follow design spec
- [ N/A] selected hover state of the element follow design spec
- [ N/A] pressed state of the element follow design spec
- [ N/A] …
=> feat: added ability to hide scroll and padding from Avatar Group overflow body

config/postcss.config.js, package-lock.json, package.json
fixes #2366 
move `@charset` at the beginning of each css files
=> fix: bring charset at the beginning of the css files

.github/workflows/stale.yml
=> chore: introduce stale workflow

ci-scripts/publish-rc.sh, ci-scripts/publish.sh
=> chore: fix publish script

package.json
=> chore: fix the build command

src/icons/_settings.scss, stories/icon/SAPIcons/__snapshots__/icon.stories.storyshot, stories/icon/SAPIcons/data.json
=> feat: introduce qr-code icon

stories/form-fieldset/form-fieldset.stories.js
Closes SAP/fundamental-styles#2453
Updated fieldset.css file path for docs.
- n/a All values are in `rem`
- n/a Text elements follow the truncation rules
- n/a hover state of the element follow design spec
- n/a focus state of the element follow design spec
- n/a active state of the element follow design spec
- n/a selected state of the element follow design spec
- n/a selected hover state of the element follow design spec
- n/a pressed state of the element follow design spec
- n/a Responsiveness rules - the component has modifier classes for all breakpoints
- n/a Includes Compact/Cosy/Tablet design
- n/a RTL support
- n/a only one top level `fd-*` class is used in the file
- n/a BEM …
=> docs: correct fieldset css file name

src/table.scss, stories/table/__snapshots__/table.stories.storyshot, stories/table/table.stories.js
Closes [Fundamental NGX #5097](https://github.com/SAP/fundamental-ngx/issues/5097).
Table:
* Fixed columns border styles fix.
* Condensed mode selection checkbox styles fix.
* Documentation title fix.
1.
2.
3.
1.
2.
3.
3. Testing
=> fix: table fixed column borders fix, table improvements

.storybook/custom/components/tags.json, src/fundamental-styles.scss, src/icon-tab-bar.scss, src/mixins/_mixins.scss, src/theming/sap_fiori_3.scss, src/theming/sap_fiori_3_dark.scss, src/theming/sap_fiori_3_hcb.scss, src/theming/sap_fiori_3_hcw.scss, src/theming/sap_fiori_3_light_dark.scss, src/tool-header.scss, stories/tool-header/__snapshots__/tool-header.stories.storyshot, stories/tool-header/tool-header.stories.js, stories/vertical-navigation/vertical-navigation.stories.js
Closes SAP/fundamental-styles#2209
This PR introduces Tool Header component  from BTP design
3. Testing
=> feat: introduce Tool Header component from BTP design

stories/textarea/__snapshots__/textarea.stories.storyshot, stories/textarea/textarea.stories.js
=> docs: update textarea validation messages

stories/list/standard/__snapshots__/standard-list.stories.storyshot, stories/list/standard/standard-list.stories.js
=> docs: add missing class to inactive list item example [ci visual]

src/_listNavigationItem.scss, src/vertical-nav.scss, stories/vertical-navigation/__snapshots__/vertical-navigation.stories.storyshot, stories/vertical-navigation/vertical-navigation.stories.js
Closes SAP/fundamental-styles#2442
- changed the cursor to pointer for navigable items
- added modifier class `fd-vertical-nav__group-header` for the `fd-list__group-header` class 
- added example with Grouping
- applied `!important` to the rules changing the color of the navigated/indicated items. Couldn't rely on specificity as it was already used once. 
- In the example added another item with text and icon that is navigated to illustrate the changing of the color.
=> fix: add missing features for Vertical Navigation 

.storybook/static/preview-head.js
Removed recently added JS code for our documentation that was breaking other components documentation.
=> fix: remove code breaking documentation functionality and tristate for checkboxes

src/icon-tab-bar.scss, src/tool-header.scss, stories/horizontal-navigation/__snapshots__/horizontal-navigation.stories.storyshot, stories/horizontal-navigation/horizontal-navigation.stories.js, stories/icon-tab-bar/__snapshots__/icon-tab-bar.stories.storyshot, stories/icon-tab-bar/icon-tab-bar.stories.js
Closes SAP/fundamental-styles#2210
BREAKING CHANGE: 
- Added an additional modifier class `fd-icon-tab-bar__item--overflow` to `fd-icon-tab-bar__item` for the `li` element wrapping the overflow button
- Added an additional modifier class `fd-icon-tab-bar__popover-body` to `fd-popover__body` for the overflow
Horizontal Navigation is a composite component built on extended functionality of Universal IconTabBar and Tool Header.
3. Testing
=> feat: introduce Horizontal Navigation pattern

.github/workflows/chromatic.yml
Closes #2619.
Trigger Chromatic run on commit to `main`.
Not applicable.
- [n/a] only one top level `fd-*` class is used in …
=> chore: trigger chromatic when pushing to main

theming-preview/button.html, theming-preview/calendar.html, theming-preview/form.html, theming-preview/header-footer.html, theming-preview/icon.html, theming-preview/indication-colors.html, theming-preview/input.html, theming-preview/object-header.html, theming-preview/panel.html, theming-preview/semantic-colors.html, theming-preview/shell-tile-card.html, theming-preview/table.html, theming-preview/text.html, theming-preview/toolbar.html
Part of SAP/fundamental-styles#2305
- update the test pages to contain the whole html page(including the styling sheets)
- bring fundamental-styles
3. Testing
=> chore: add style to theming preview files

README.md, package.json, theming-preview/button.html, theming-preview/calendar.html, theming-preview/form.html, theming-preview/header-footer.html, theming-preview/icon.html, theming-preview/indication-colors.html, theming-preview/input.html, theming-preview/object-header.html, theming-preview/panel.html, theming-preview/semantic-colors.html, theming-preview/shell-tile-card.html, theming-preview/table.html, theming-preview/text.html, theming-preview/toolbar.html
update theming-preview package styling imports
=> fix: update theming-preview package styling imports

.storybook/custom/custom.scss, src/icon-tab-bar.scss, stories/dnd-icon-tab-bar/__snapshots__/dnd-icon-tab-bar.stories.storyshot, stories/dnd-icon-tab-bar/dnd-icon-tab-bar.stories.js, stories/icon-tab-bar/__snapshots__/icon-tab-bar.stories.storyshot, stories/icon-tab-bar/icon-tab-bar.stories.js
- Added new modifier `.fd-icon-tab-bar__header--left-offset` when left overflow button are shown
- Added new modifieres with semantic colors for list items inside popover `.fd-icon-tab-bar__list-item--informative`, `.fd-icon-tab-bar__list-item--positive`, `.fd-icon-tab-bar__list-item--negative`, `.fd-icon-tab-bar__list-item--critical`
- Added new html structure for list of icon type items
These changes were made during the implementation of the icon-tab-bar component of ngx repo. Related [PR](https://github.com/SAP/fundamental-ngx/pull/6193) 
- Added missing styles for sub-tabs with icon type
- Added styles for drag and drop manipulation
- Added some styles for dynamic overflow behavior.
- Added an example for icon sub-tabs
These …
=> feat: added missing styles for icon-tab-bar

src/mixins/_mixins.scss, src/table.scss, stories/table/__snapshots__/table.stories.storyshot, stories/table/table.stories.js
Relates to https://github.com/SAP/fundamental-ngx/issues/5025
Tree Rows & Group Rows features implemented in Styles.
3. Testing
=> feat: table group rows, tree rows

config/bundlesize.json, src/mixins/_forms.scss, src/mixins/_mixins.scss
Closes SAP/fundamental-styles#2684
Update input theming parameters.
3. Testing
=> fix: update input theming

src/popover.scss
Closes SAP/fundamental-styles#2724
According to Fiori 3 spec, dropdowns should have top round corners
>
- [N/A] All values are in `rem`
- [N/A] Text elements follow the truncation rules
- [N/A] …
=> fix: dropdown top round corners

src/fundamental-styles.scss, src/micro-process-flow.scss, src/mixins/_mixins.scss, src/theming/sap_fiori_3.scss, src/theming/sap_fiori_3_dark.scss, src/theming/sap_fiori_3_hcb.scss, src/theming/sap_fiori_3_hcw.scss, src/theming/sap_fiori_3_light_dark.scss, stories/micro-process-flow/__snapshots__/micro-process-flow.stories.storyshot, stories/micro-process-flow/micro-process-flow.stories.js
The component was first implemented in Fund-ngx and the current PR brings the css code from there and creates the documentation for the component.
3. Testing
=> feat: introduce Micro Process Flow component

src/_listNavigationItem.scss, stories/vertical-navigation/__snapshots__/vertical-navigation.stories.storyshot, stories/vertical-navigation/vertical-navigation.stories.js
small fix for vertical navigation
=> fix: fixes a bug where the nav item height could be incorrect

src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/title.scss, src/styles/wizard.scss
title and wizard delta for horizon
=> feat(styles): title and wizard delta for horizon

src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/toolbar.scss, stories/toolbar/toolbar.stories.js
=> feat(styles): add toolbar horizon delta

src/styles/code.scss, src/styles/fundamental-styles.scss, stories/code/__snapshots__/code.stories.storyshot, stories/code/code.stories.js
feat(styles): introduce code component
=> feat(styles): introduce code component [ci visual]

src/styles/code.scss, stories/code/__snapshots__/code.stories.storyshot, stories/code/code.stories.js
=> fix(styles): add code inline case

src/styles/switch.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss
Adding the deltas for Switch component + focus update for the component
>
=> feat(styles): add horizon delta for Switch component

scripts/build-visual-stories.js
Stop running visual regression tests against horizon for the moment in chromatic
=> test(styles): stop horizon visual regression

src/fn/_fn-new-variables.scss, src/fn/fn-switch.scss
Update Switch to latest Fiori Next design
=> fix(fn): update Switch to latest design [ci visual]

.storybook/preview-head.html, README.md, src/fn/_dialog-placeholders.scss, src/fn/_fn-mixins.scss, src/fn/_fn-new-variables.scss, src/fn/fn-dialog.scss, src/fn/fn-link.scss, src/fn/fn-message-box.scss, src/fn/fn-title.scss, stories/fn-dialog/__snapshots__/fn-dialog.stories.storyshot, stories/fn-dialog/fn-dialog.stories.js, stories/fn-link/__snapshots__/fn-link.stories.storyshot, stories/fn-link/fn-link.stories.js, stories/fn-message-box/__snapshots__/fn-message-box.stories.storyshot, stories/fn-message-box/fn-message-box.stories.js, stories/fn-title/__snapshots__/title.stories.storyshot, stories/fn-title/title.stories.js, theming-preview/theme-manager.js
part of https://github.com/SAP/fundamental-styles/issues/2928
Introduce FN dialog, message box, title and link
=> feat(fn): introduce dialog, message-box, link, title [ci visual]

.ci-env/flags.sh, .ci-env/flags.sh-e, .travis.yml, ci-scripts/hotfix-publish.sh, package.json, scripts/hotfix-publish-release.sh
=> chore(styles): bring hotfix script

src/fn/fn-avatar.scss, src/fn/fundamental-next.scss, stories/fn-avatar/__snapshots__/fn-avatar.stories.storyshot, stories/fn-avatar/fn-avatar.stories.js
introduce new Avatar component
=> feat(fn): introduce Avatar component

src/fn/fundamental-next.scss
include missing components from fundamental-next.css
=> fix(fn): include missing components from fundamental-next.css

README.md
correct Icon and slack links in README.md
fixes #2997
=> docs(styles,fn): update Icon link and slack link

README.md
docs(styles,fn): minor README.md update
=> docs(styles,fn): minor README.md update

.github/workflows/chromatic.yml, package-lock.json
Closes #3023.
Chromatic GA fix.
=> fix: chromatic [ci visual]

package-lock.json
=> docs(styles,fn): fix storybook site

stories/avatar-group/__snapshots__/avatar-group.stories.storyshot, stories/avatar-group/avatar-group.stories.js, stories/avatar/__snapshots__/avatar.stories.storyshot, stories/avatar/avatar.stories.js, stories/feed-list/__snapshots__/feed-list.stories.storyshot, stories/feed-list/feed-list.stories.js, stories/page-footer/page-footer.stories.js
replace image URLs with local assets
=> docs(styles): replace external URLs with local assets

src/fn/fn-textarea.scss, src/fn/fn-token.scss, src/fn/fundamental-next.scss, stories/fn-textarea/__snapshots__/fn-textarea.stories.storyshot, stories/fn-textarea/fn-textarea.stories.js, stories/fn-token/__snapshots__/fn-token.stories.storyshot, stories/fn-token/fn-token.stories.js
Introduce Token and Textarea components from Fiori Next
=> feat(fn): introduce Textarea nad Token

src/fn/fn-nested-button.scss, src/fn/fn-step-input.scss, src/fn/fundamental-next.scss, stories/fn-step-input/__snapshots__/fn-step-input.stories.storyshot, stories/fn-step-input/fn-step-input.stories.js
=> feat(fn): introduce Step Input [ci visual]

README.md, package.json
=> docs(styles): update the usage of fiori

.github/workflows/on-push-or-pull.yml, .travis.yml
=> chore(deps): fix ghactions keys

.github/workflows/on-push-or-pull.yml
=> chore(deps): fix ghaction again

stories/fn-combobox/fn-combobox.stories.js, stories/fn-step-input/fn-step-input.stories.js, stories/fn-textarea/fn-textarea.stories.js, stories/fn-token/fn-token.stories.js
=> test(docs): fix storybook lint problems in #3061

src/fn/fn-object-status.scss, src/fn/fundamental-next.scss, stories/fn-object-status/__snapshots__/fn-object-status.stories.storyshot, stories/fn-object-status/fn-object-status.stories.js
introduce new Fiori Next component Object Status
=> feat(fn): introduce Object Status [ci visual]

ci-scripts/publish-rc.sh, ci-scripts/publish.sh, scripts/sync-version.js
Closes #3103
Theming directory would be rebuild but not version updated. Without this `@fundamental-styles/theming-preview` will not be deployed to the npm
=> chore(ci): added missing scripts and more detailed logging on version sync

src/fn/fn-button.scss, stories/fn-button/__snapshots__/fn-button.stories.storyshot, stories/fn-button/fn-button.stories.js
=> feat(fn): add Menu button to Fiori Next buttons [ci visual]

src/fn/fn-form.scss, src/fn/fn-label.scss, stories/fn-form/__snapshots__/fn-form.stories.storyshot, stories/fn-form/fn-form.stories.js
part of #2928 
implements fn-form, fn-form__item, fn-form__group, fn-form__label etc
=> feat(fn): implement fn-form

src/fn/_fn-mixins.scss, src/fn/fn-message-strip.scss, stories/fn-message-strip/__snapshots__/fn-message-strip.stories.storyshot, stories/fn-message-strip/fn-message-strip.stories.js
part of #2928 
Implements the fn-message-strip
=> feat(fn): implement message strip

README.md
Part of SAP/fundamental-styles#3095
Added instructions of how to use [unpkg](https://unpkg.com/) for including fundamental-styles via CDN
=> chore(docs): added CDN usage instruction

.storybook/static/preview-head.js
remove console.log from preview-head.js
=> chore(docs): clean up preview head

.github/workflows/rebase.yml
=> chore(ci): introduce rebase gh actions

stories/datepicker/__snapshots__/datepicker.stories.storyshot, stories/datepicker/datepicker.stories.js
=> docs(styles): datepicker documentation update new

src/fn/_fn-new-variables.scss
update the values for the colors, including the box-shadows
=> fix(fn): update Fiori Next colors [ci visual]

src/fn/_fn-mixins.scss, src/fn/_fn-new-variables.scss, src/fn/fn-button.scss, src/fn/fn-nested-button.scss, src/fn/fn-segmented-button.scss, src/fn/fn-split-button.scss, src/fn/fundamental-next.scss, stories/fn-button/__snapshots__/fn-button.stories.storyshot, stories/fn-button/fn-button.stories.js, stories/fn-card/__snapshots__/fn-card.stories.storyshot, stories/fn-card/fn-card.stories.js, stories/fn-dialog/__snapshots__/fn-dialog.stories.storyshot, stories/fn-dialog/fn-dialog.stories.js, stories/fn-message-box/__snapshots__/fn-message-box.stories.storyshot, stories/fn-message-box/fn-message-box.stories.js, stories/fn-message-strip/__snapshots__/fn-message-strip.stories.storyshot, stories/fn-message-strip/fn-message-strip.stories.js, stories/fn-shell/__snapshots__/fn-shell.stories.storyshot, stories/fn-shell/fn-shell.stories.js, stories/fn-tabs/__snapshots__/fn-tabs.stories.storyshot, stories/fn-tabs/fn-tabs.stories.js
- updated the API for buttons (unified the button types with the ones from the design)
- updated Nested Button
- introduced Split Button
- classes clean-up
Removed classes:
fn-button--ghost
fn-button--neutral
fn-button--transparent
fn-button--accept
fn-button--success
fn-button--attention
fn-button--reject
fn-button--icon-left
fn-button--icon-right
=> fix(fn): update Fiori Next buttons [ci visual]

stories/form-fieldset/form-fieldset.stories.js
- Updated the documentation for fields.
=> docs(styles): updated the documentation of fieldset component 

stories/dialog/dialog.stories.js, stories/form-fieldset/form-fieldset.stories.js
=> docs(styles): updated the documentation of dialog component

stories/file-uploader/file-uploader.stories.js, stories/fn-input/fn-input.stories.js, stories/input/input.stories.js
=> docs(styles): updated the documentation of input component

stories/file-uploader/file-uploader.stories.js, stories/fn-input/fn-input.stories.js, stories/input/input.stories.js
=> docs(styles): file uploader update

src/fn/fn-message-toast.scss, src/fn/fundamental-next.scss, stories/fn-message-toast/__snapshots__/fn-message-toast.stories.storyshot, stories/fn-message-toast/fn-message-toast.stories.js, stories/menu/__snapshots__/menu.stories.storyshot, stories/vertical-navigation/__snapshots__/vertical-navigation.stories.storyshot
Introduce new Message Toast component in Fiori Next
=> feat(fn): introduce Message Toast in Fiori Next

src/fn/_fn-mixins.scss, src/fn/fn-rating-indicator.scss, src/fn/fundamental-next.scss, stories/docs/introduction.stories.mdx, stories/fn-rating-indicator/__snapshots__/fn-rating-indicator.stories.storyshot, stories/fn-rating-indicator/fn-rating-indicator.stories.js, stories/menu/__snapshots__/menu.stories.storyshot, stories/vertical-navigation/__snapshots__/vertical-navigation.stories.storyshot
Introduce new Rating Indicator component in Fiori Next
=> feat(fn): introduce Rating Indicator in Fiori Next [ci visual]

src/fn/fn-dropdown.scss, src/fn/fundamental-next.scss, stories/fn-dropdown/__snapshots__/fn-dropdown.stories.storyshot, stories/fn-dropdown/fn-dropdown.stories.js, stories/fn-select/fn-select.stories.js
Introduce new Dropdown component in Fiori Next
=> feat(fn): introduce Dropdown in Fiori Next

src/fn/fn-notification.scss, stories/fn-dropdown/__snapshots__/fn-dropdown.stories.storyshot, stories/fn-dropdown/fn-dropdown.stories.js, stories/fn-notification/__snapshots__/fn-notification.stories.storyshot, stories/fn-notification/fn-notification.stories.js
part of #2928 
Implements the fn-notification component
=> feat(fn): implement notification component [ci visual]

README.md
=> docs(styles,fn): update wrong link to icons

stories/code/code.stories.js, stories/docs/introduction.stories.mdx
=> docs(styles): updated the documentation of code

src/fn/_fn-new-variables.scss, src/fn/fn-page.scss, src/fn/fundamental-next.scss, stories/fn-page/__snapshots__/fn-page.stories.storyshot, stories/fn-page/fn-page.stories.js
Adds Page title, footer, group title
=> feat(fn): introduce Page components [ci visual]

README.md
replace travis badge with gh actions one
=> docs(ci): replace travis badge with gh actions one

README.md
=> docs(ci): fix badge

src/fn/fn-label.scss, src/fn/fn-shell.scss, src/fn/fundamental-next.scss, stories/fn-form/fn-form.stories.js
- update the Label color
- update the box-shadow for Shell
=> fix(fn): update Label and Shell to match the design [ci visual]

README.md
add monthly npm download badge
=> docs(styles): add monthly npm download badge

stories/multi-input/multi-input.stories.js
=> docs(styles): update the documentation for multi input [ci visual]

stories/multi-combo-box/multi-combo-box.stories.js, stories/multi-input/multi-input.stories.js
=> docs(styles): update the documentation for multi combobox

src/fn/fn-slider.scss
- update Slider to lates design
=> fix(fn): update Slider to lates design [ci visual]

src/fn/fn-popover.scss, stories/fn-popover/__snapshots__/fn-popover.stories.storyshot, stories/fn-popover/fn-popover.stories.js
=> feat(fn): introduce fn-popover [ci visual]

src/fn/fn-tabs.scss, stories/fn-tabs/__snapshots__/fn-tabs.stories.storyshot, stories/fn-tabs/fn-tabs.stories.js
=> fix(fn): add split Tabs type [ci visual]

src/fn/fn-busy-indicator.scss, src/fn/fundamental-next.scss, stories/fn-busy-indicator/__snapshots__/fn-busy-indicator.stories.storyshot, stories/fn-busy-indicator/fn-busy-indicator.stories.js
=> feat(fn): introduce FN Busy Indicator [ci visual]

src/styles/avatar.scss, stories/avatar/__snapshots__/avatar.stories.storyshot, stories/avatar/avatar.stories.js
a defect hunting issue in Fundamental-ngx
the "zoom icon", which can be a badge or icon is used with clickable avatars to indicate that the avatar is interactive or to indicate the action triggered by clicking the avatar. Updated the markup so that Avatars get focus and added css to make the cursor pointer to show the user this type of Avatar is interactive.
=> fix(styles): add cursor pointer to Avatar with zoom icon [ci visual]

src/styles/fixed-card-layout.scss, stories/fixed-card-layout/__snapshots__/fixed-card-layout.stories.storyshot, stories/fixed-card-layout/fixed-card-layout.stories.js
Related issue https://github.com/SAP/fundamental-ngx/pull/7701
Fixed card layout component refactoring because of changes on the ngx side.
No visual changes.
* No more fixed card layout columns
* Container element should have column class
* Container element should have height\max-height
* Wrapper element for card introduced
=> fix: fixed card layout refactoring

src/styles/message-strip.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
part of #3213
- add delta horizon theming for message strip(hardcoded colors for some parameters in horizon themes)
- changed the icon colors for message strip
=> feat(styles): add delta horizon theming for message strip

stories/counter/counter.stories.js
=> docs(styles): update the documentation for counter [ci visual]

src/styles/avatar.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
part of #3213
- add delta horizon theming for Avatar(hardcoded colors for some parameters in horizon themes)
=> feat(styles): add delta horizon theming for Avatar

src/styles/busy-indicator.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
part of #3213
- add delta horizon theming for Busy Indicator
=> feat(styles): add delta horizon theming for Busy Indicator

src/styles/popover.scss
Closes ngx https://github.com/SAP/fundamental-ngx/issues/7706
Follow up pr in ngx https://github.com/SAP/fundamental-ngx/pull/7832
Core popover styles refactoring.
>
=> fix: popover styles refactoring

src/styles/mixins/button/_badge.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
part of #3213
- add delta horizon theming for Badge on Button
=> feat(styles): add delta horizon theming for Badge on Button

package.json
bump theming-base-content version 11.1.36
=> fix(styles): bump theming-base-content version 11.1.36 [ci visual]

src/styles/upload-collection.scss, stories/upload-collection/__snapshots__/upload-collection.stories.storyshot, stories/upload-collection/upload-collection.stories.js
Part of https://github.com/SAP/fundamental-ngx/issues/7815
Follow-up pr in ngx https://github.com/SAP/fundamental-ngx/pull/7857
Overflow handling improvements.
Modifier classes added to the upload collection item object status to handle overflow approriate.
* Upload collection item object status layout changed & now needs additional classes to be applied
Wiki https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes#upload-collection-3227
=> fix: upload collection overflow [ci visual]

src/styles/mixins/_popover.scss, src/styles/popover.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
Part of https://github.com/SAP/fundamental-styles/issues/3213
add delta horizon theming support for Popover
=> feat(styles): add delta horizon theming support for Popover [ci visual]

src/styles/message-strip.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
uncomment the new message strip horizon parameters
=> chore(styles): message strip horizon parameters [ci visual]

src/styles/checkbox.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
Part of #3213.
Variables fixes for Checkbox component to support Horizon themes.
=> feat(styles): checkbox horizon support

src/styles/radio.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
part of #3213 
Update variables to support Horizon theming for RadioButton
=> feat(styles): add delta horizon theming for Radio Button

src/styles/text.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
Horizon theming for Text Component
=> feat(styles): horizon theming for Text

src/styles/shellbar.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss, stories/shellbar/shellbar.stories.js
Part of #3213.
* Shellbar Horizon themes support.
* Shellbar component refactoring.
* Unused classes removed.
* Classes renamed to conform to BEM metodology.
Wiki https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes#shellbar-3254
=> feat(styles): shellbar horizon support

package.json
=> chore(deps): theming-base-content 11.1.37

src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss, src/styles/token.scss
Part of https://github.com/SAP/fundamental-styles/issues/3213
add delta horizon theming support for Token 
Tokenizer will be implemented separately with the Inputs
=> feat(styles): add delta horizon theming support for Token [ci visual]

config/common-css/package.json, scripts/sync-version.js
fix the package name and versions
=> chore(common-css): fix the package name and versions

package.json
update theming-base-content version 11.1.38
=> chore(deps): update theming-base-content version 11.1.38

src/common-css/_common-mixins.scss, src/common-css/common-css.scss
publish padding and margin classes
=> feat(common-css): publish padding and margin classes

.storybook/custom/decorators/componentStylesProvider.js, .storybook/custom/decorators/themeProvider.js, .storybook/custom/styleChangers/dev/componentStylesManager.js, .storybook/custom/styleChangers/dev/themeVariablesManager.js, .storybook/custom/styleChangers/prod/componentStylesManager.js, .storybook/custom/styleChangers/prod/themeVariablesManager.js
Closes SAP/fundamental-styles#3307
=> fix(styles): fixed flickering when theme switches

src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
=> feat(styles): add Horizon theming for Page[ci visual]

src/styles/layout-grid.scss
Closes none.
Layout grid nested rows fix.
=> fix(styles): layout grid nested rows

ci-scripts/publish-rc.sh
=> chore(ci): fix rc script

ci-scripts/publish-rc.sh
=> chore(ci): fix rc publishing script

ci-scripts/hotfix-publish.sh, ci-scripts/publish.sh
optimize release and hotfix scripts
=> chore(ci): optimize release and hotfix scripts

src/styles/scrollbar.scss, src/styles/theming/common/scrollbar/_sap_fiori.scss, src/styles/theming/common/scrollbar/_sap_horizon.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
Relates  SAP/fundamental-styles#3354
Added Horizon scrollbar theme support
3. Testing
=> feat: horizon theme scrollbar

src/styles/link.scss, src/styles/mixins/_mixins.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
=> feat(styles): horizon family delta for link

src/styles/tabs.scss, src/styles/tool-header.scss
Closes none.
Button todos fixed.
No visual changes.
=> fix(styles): button todos

src/styles/panel.scss, src/styles/theming/common/panel/_sap_fiori.scss, src/styles/theming/common/panel/_sap_horizon.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
part of #3354 
no breaking changes
=> feat(styles): panel horizon updates [ci-visual]

.storybook/static/preview-head.js, src/styles/mixins/list/_list-definitions.scss, src/styles/mixins/tree/_mixins.scss, src/styles/mixins/tree/_modifiers.scss, src/styles/tree.scss, stories/tree/tree.stories.js
Part of SAP/fundamental-styles#3213
Added selectable tree independent selections, which was missing previously. extracted some mixins from list styles to be reusable in tree. Replaced SASS variables with CSS variables to reduce size and overrides on selectors. output went down from 100ish kb to 30ish kb.
=> feat(styles): tree refactor and horizon adaptation

src/styles/slider.scss, src/styles/theming/common/slider/_sap_fiori.scss, src/styles/theming/common/slider/_sap_fiori_hc.scss, src/styles/theming/common/slider/_sap_horizon.scss, src/styles/theming/common/slider/_sap_horizon_hc.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss, stories/slider/slider.stories.js
Relates SAP/fundamental-styles#3354
Added delta theming for Horizon theme for the Slider component
Slider handle is now moved outside `.fd-slider__track` element.
_Before:_
```
<div class="fd-slider__inner">
<div class="fd-slider__track">
<div class="fd-slider__track-range" style="width: 50%;"></div>
<div class="fd-slider__handle" tabindex="0" role="slider" aria-label="slider" aria-valuemin="1" aria-valuemax="100" aria-valuenow="50" style="left: 50%;"></div>
</div>
</div>
```
_After:_
```
<div class="fd-slider__inner">
<div class="fd-slider__handle" tabindex="0" role="slider" aria-label="slider" aria-valuemin="1" aria-valuemax="100" aria-valuenow="50" style="left: 50%;">
</div>
<div class="fd-slider__track">
<div class="fd-slider__track-range" style="width: …
```
=> feat(styles): slider horizon theme

src/styles/calendar.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss, stories/calendar/calendar.stories.js
Various calendar issues fixes.
=> fix(styles): calendar horizon issues

.storybook/custom/custom.scss, src/styles/avatar-group.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
Various avatar, avatar group issues fixes.
=> fix(styles): avatar and group issues fixes

src/styles/shellbar.scss
Shellbar css specificity & styles from ngx
=> fix(styles): shellbar css specificity & styles from ngx

src/styles/mixins/_forms.scss, src/styles/mixins/_mixins.scss, src/styles/theming/common/input-group/_sap_horizon_hc.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
part of https://github.com/SAP/fundamental-styles/issues/3327
Fixed the hover&active states for the control button in Input Group in HC themes.
=> fix(styles): add fix for control button states in Input Groups

src/styles/tabs.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss, stories/tabs/tabs.stories.js
Part of https://github.com/SAP/fundamental-styles/issues/3327#issuecomment-1122106350
Tabs component fixes for hc themes.
=> fix(styles): tabs hc themes various fixes

src/styles/rating-indicator.scss, src/styles/theming/common/rating-indicator/_sap_fiori.scss, src/styles/theming/common/rating-indicator/_sap_fiori_hc.scss, src/styles/theming/common/rating-indicator/_sap_horizon.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
Part of SAP/fundamental-styles#3354
Adapted to horizon and reduced size twice
=> fix(styles): rating indicator horizon

src/styles/switch.scss, src/styles/theming/common/switch/_sap_fiori.scss, src/styles/theming/common/switch/_sap_fiori_hc.scss, src/styles/theming/common/switch/_sap_horizon.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss
Closes SAP/fundamental-styles#3453
* Added missing variables and styles
* Optimized css structure
* Added sync script to reformat theming content files to same structure and detect missing variables across theming files
3. Testing
=> fix: add missing switch variables

src/styles/theming/common/tile/_sap_fiori.scss, src/styles/theming/common/tile/_sap_fiori_hc.scss, src/styles/theming/common/tile/_sap_horizon.scss, src/styles/theming/common/tile/_sap_horizon_hc.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss, src/styles/tile.scss, stories/generic-tile/generic-tile.stories.js
Part of #3327 
fixed tile interaction state diffs
=> fix(styles): tile horizon adaptation fixes

src/styles/quick-view.scss
no accompanying issue #
fixes minor issue with quick view border radius
=> fix(styles): border radius should not come from quick view first child

scripts/sync-components.js
Script was not compatible with Windows env, line endings... as usual... Also added path.resolve
=> fix(ci): fixed sync-components script compatibility with windows

stories/button/button.stories.js
=> docs(styles): fix icon button docs

stories/action-bar/__snapshots__/action-bar.stories.storyshot, stories/action-sheet/__snapshots__/action-sheet.stories.storyshot, stories/busy-indicator/__snapshots__/busy-indicator.stories.storyshot, stories/calendar/__snapshots__/calendar.stories.storyshot, stories/card/__snapshots__/card.stories.storyshot, stories/carousel/__snapshots__/carousel.stories.storyshot, stories/feed-list/__snapshots__/feed-list.stories.storyshot, stories/list-grid-select/__snapshots__/grid-list-select.stories.storyshot, stories/list-grid/__snapshots__/grid-list.stories.storyshot, stories/list/standard/__snapshots__/standard-list.stories.storyshot, stories/menu/__snapshots__/menu.stories.storyshot, stories/popover/__snapshots__/popover.stories.storyshot, stories/progress-indicator/__snapshots__/progress-indicator.stories.storyshot, stories/shellbar/__snapshots__/shellbar.stories.storyshot, stories/slider/__snapshots__/slider.stories.storyshot, stories/splitter/__snapshots__/splitter.stories.storyshot, stories/tree/__snapshots__/tree.stories.storyshot
update forgotten storyshots after running `npm run test:update`
=> test(styles): update forgotten storyshots

src/styles/mixins/_mixins.scss, stories/avatar-group/avatar-group.stories.js, stories/card/card.stories.js, stories/facets/facets.stories.js, stories/feed-list/feed-list.stories.js, stories/link/link.stories.js, stories/list-grid-select/grid-list-select.stories.js, stories/list-grid/grid-list.stories.js, stories/list/byline/byline-list.stories.js, stories/message-box/message-box.stories.js, stories/message-page/message-page.stories.js, stories/multi-input/multi-input.stories.js, stories/object-identifier/object-identifier.stories.js, stories/page-footer/page-footer.stories.js, stories/quick-view/quick-view.stories.js, stories/table/table.stories.js, stories/text/text.stories.js
Previously added unnamed span to contain text, but it's not that helpful and semantic, we need something to differentiate content from other elements
[Breaking changes wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes#link-3501-and-3504)
=> feat(styles): added link content class

src/styles/progress-indicator.scss, stories/progress-indicator/progress-indicator.stories.js
https://github.com/SAP/fundamental-styles/issues/3495#issuecomment-1144902248
https://github.com/SAP/fundamental-styles/issues/3495#issuecomment-1144782142
Fixed issues. Suggested by @N1XUS
=> fix(styles): progress indicator progress element positions

src/styles/rating-indicator.scss, src/styles/theming/common/rating-indicator/_sap_horizon.scss, src/styles/theming/common/rating-indicator/_sap_horizon_hc.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
https://github.com/SAP/fundamental-styles/issues/3495#issuecomment-1144126259
Fixed focus
=> fix(styles): focus outline of rating indicator

src/styles/micro-process-flow.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss, src/styles/theming/sap_horizon.scss, src/styles/theming/sap_horizon_dark.scss, src/styles/theming/sap_horizon_hcb.scss, src/styles/theming/sap_horizon_hcw.scss
part of [#https://github.com/SAP/fundamental-styles/issues/3495#issuecomment-1144121103](https://github.com/SAP/fundamental-styles/issues/3495#issuecomment-1144121103)
* Added correct offset calculation and margin
* Optimized css structure
=> fix: micro process flow outline overflow and optimizations

package.json
Closes None
Setting SASS version temporarily locked to 1.52.1 to fight back issue. We need to either find the source of issue or stay at this version
=> fix(deps): last known good configuration of sass version

stories/carousel/carousel.stories.js
=> docs(styles): change carousel max-width

src/styles/mixins/list/_list-base.scss
Part of https://github.com/SAP/fundamental-ngx/issues/7984#issuecomment-1145325107
List icon position fix.
=> fix(styles): list icon position

src/styles/breadcrumb.scss, stories/breadcrumb/breadcrumb.stories.js, stories/dynamic-page/dynamic-page.stories.js, stories/facets/facets.stories.js
https://github.com/SAP/fundamental-styles/issues/3495#issuecomment-1145934567
Removed redundant element and replaced it with widely adopted element
[Breaking Changes WIKI](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes#breadcrumbs-3512)
=> fix(styles): removed fd-breadcrumb__link element

stories/flexible-column-layout/flexible-column-layout.stories.js
Part of https://github.com/SAP/fundamental-ngx/issues/7984#issuecomment-1128609647
Flexible Column Layout background to support various themes.
=> docs(styles): flexible column layout background

package.json
upgrade to theming-base-content version 11.1.40
=> chore(deps): upgrade to theming-base-content version 11.1.40 [ci visual]

.storybook/custom/components/DocsPage.js, .storybook/custom/components/Versions.js, .storybook/custom/custom.scss, stories/docs/introduction.page.js
add links to older version to introduction page. It is manual and I am open for automated way.
=> docs(styles): add links to older version to introduction page

src/styles/shellbar.scss, stories/shellbar/shellbar.stories.js
introduce shellbar responsible padding modifier
we had that in tool-header already
=> feat(styles): introduce shellbar responsible padding modifier

metadata.yaml
=> chore(docs): link it with the portal

src/styles/bar.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_horizon.scss, stories/bar/bar.stories.js
part of https://github.com/SAP/fundamental-styles/issues/3600
Some minor fixes for bar based on spec review
=> fix(styles): some fixes for fd-bar [ci visual]

src/styles/message-strip.scss, src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_fiori_3_dark.scss, src/styles/theming/sap_fiori_3_hcb.scss, src/styles/theming/sap_fiori_3_hcw.scss, src/styles/theming/sap_fiori_3_light_dark.scss
update message strip info border color and icons for fiori 3
fixes https://github.com/SAP/fundamental-styles/issues/3719
fixes https://github.com/SAP/fundamental-styles/issues/3701
=> fix(styles): message strip info border color and icons for fiori 3

src/styles/info-label.scss
part of https://github.com/SAP/fundamental-ngx/issues/8342
=> fix(styles): vertical align info label icon

.github/workflows/chromatic.yml, package.json
- fixed chromatic workflow. Now it uses yarn instead of npm, which was issue
- updated actions:
- checkout
=> fix(ci): fixed chromatic workflow

stories/bar/__snapshots__/bar.stories.storyshot, stories/breadcrumb/__snapshots__/breadcrumb.stories.storyshot, stories/calendar/__snapshots__/calendar.stories.storyshot, stories/card/__snapshots__/card.stories.storyshot, stories/carousel/__snapshots__/carousel.stories.storyshot, stories/combobox-input/__snapshots__/combobox-input.stories.storyshot, stories/dynamic-page/__snapshots__/dynamic-page.stories.storyshot, stories/facets/__snapshots__/facets.stories.storyshot, stories/feed-list/__snapshots__/feed-list.stories.storyshot, stories/flexible-column-layout/__snapshots__/flexible-column-layout.stories.storyshot, stories/link/__snapshots__/link.stories.storyshot, stories/list-grid-select/__snapshots__/grid-list-select.stories.storyshot, stories/list-grid/__snapshots__/grid-list.stories.storyshot, stories/list/byline/__snapshots__/byline-list.stories.storyshot, stories/menu/__snapshots__/menu.stories.storyshot, stories/message-box/__snapshots__/message-box.stories.storyshot, stories/message-page/__snapshots__/message-page.stories.storyshot, stories/multi-combo-box/__snapshots__/multi-combo-box.stories.storyshot, stories/multi-input/__snapshots__/multi-input.stories.storyshot, stories/object-identifier/__snapshots__/object-identifier.stories.storyshot, stories/page-footer/__snapshots__/page-footer.stories.storyshot, stories/product-switch/__snapshots__/product-switch.stories.storyshot, stories/quick-view/__snapshots__/quick-view.stories.storyshot, stories/select/__snapshots__/select.stories.storyshot, stories/shellbar/__snapshots__/shellbar.stories.storyshot, stories/side-navigation/__snapshots__/side-navigation.stories.storyshot, stories/table/__snapshots__/table.stories.storyshot, stories/tabs/__snapshots__/tabs.stories.storyshot, stories/text/__snapshots__/text.stories.storyshot, stories/vertical-navigation/__snapshots__/vertical-navigation.stories.storyshot
=> test(styles): update snapshots

package.json
Closes SAP/fundamental-styles#3748
=> fix: removed preinstall from package.json

src/styles/mixins/_mixins.scss
=> fix(styles): add cursor pointer to links

src/styles/info-label.scss
=> fix(styles): update InfoLabel design [ci visual]

package.json, src/styles/icons/_settings.scss, stories/icon/SAPIcons/__snapshots__/icon.stories.storyshot, stories/icon/SAPIcons/data.json, yarn.lock
=> feat(styles): bring SAP-icons version 4.14 [ci visual]

src/styles/table.scss
none, reported by Dominika from CX
update the background of the Table footer
=> fix(styles): add fix for Table footer background [ci visual]

src/common-css/common-css.scss, src/common-css/sap-margin.scss, src/common-css/sap-padding.scss, stories/Helpers/flex/__snapshots__/flex.stories.storyshot, stories/Helpers/margin/margin.stories.js, stories/Helpers/padding/__snapshots__/display.stories.storyshot, stories/Helpers/padding/__snapshots__/margin.stories.storyshot, stories/Helpers/padding/__snapshots__/padding.stories.storyshot, stories/Helpers/padding/padding.stories.js
part of https://github.com/SAP/fundamental-styles/issues/3720
adds Padding to the common CSS
=> feat(styles): add Padding to the common-css

src/common-css/common-css.scss, src/common-css/sap-border-radius.scss, stories/Helpers/border-radius/__snapshots__/border-radius.stories.storyshot, stories/Helpers/border-radius/border-radius.stories.js
part of https://github.com/SAP/fundamental-styles/issues/3720
=> feat(styles): add Border-radius to common css

src/styles/form-layout-grid.scss, stories/form-grid/__snapshots__/form-grid.stories.storyshot, stories/form-grid/form-grid.stories.js
Refers to https://github.com/SAP/fundamental-ngx/issues/7854
Minor Form Grid fixes.
=> fix(styles): form layout grid

babel.config.js, package.json, yarn.lock
`[BLOCKED]` till storybook changes are not reviewed on main.
Closes #3287
Stories order set to order in a file instead of alphabetical sorting.
=> fix(docs): stories order

scripts/build-visual-stories.js
Closes none.
Follows up https://github.com/SAP/fundamental-styles/pull/3839
Fix for the failing chromatic build on main.
=> fix(docs): chromatic build issue

src/common-css/_common-mixins.scss
add flex direction as input to all flex mixins
=> fix(common-css): add flex direction as input to all flex mixins

src/styles/notification.scss, stories/notification/__snapshots__/notification.stories.storyshot, stories/notification/notification.stories.js
Refers to https://github.com/SAP/fundamental-ngx/pull/8525
Notifications in dialog update.
=> feat(styles): notification in dialog

src/styles/shellbar.scss
fixes shellbar title focus, similar to https://github.com/SAP/fundamental-styles/pull/3730
=> fix(styles): add shellbar title focus

package.json
=> fix(styles): force rc increase

src/styles/card.scss, src/styles/carousel.scss, src/styles/checkbox.scss, src/styles/flexible-column-layout.scss, src/styles/menu.scss, src/styles/mixins/_breakpoints.scss, src/styles/mixins/_forms.scss, src/styles/mixins/_mixins.scss, src/styles/nested-list.scss, src/styles/notification.scss, src/styles/numeric-content.scss, src/styles/object-attribute.scss, src/styles/object-list.scss, src/styles/popover.scss, src/styles/product-switch.scss, src/styles/radio.scss, src/styles/rating-indicator.scss, src/styles/tabs.scss, src/styles/tile.scss, src/styles/tokenizer.scss, src/styles/wizard.scss
none
some of the mixins we use are missing the `fd-` prefix. This PR is adding the prefix to the mixins that don't have it.
=> chore(styles): unify mixing names by adding fd prefix to all of them

stories/form-grid/__snapshots__/form-grid.stories.storyshot, stories/notification/__snapshots__/notification.stories.storyshot
update storyshots for form grid and notification
=> test(styles): update storyshots for form grid and notification

src/styles/theming/sap_fiori_3.scss, src/styles/theming/sap_horizon.scss, src/styles/title.scss
Closes #3923 
Update font family for Dialog Header in Horizon
=> fix(styles): update font-family for Dialog Header for Horizon

src/common-css/_common-mixins.scss, stories/Helpers/border/border.stories.js
part of https://github.com/SAP/fundamental-styles/issues/3720
add border helper mixin to common-css
=> feat(styles): add border mixin to common-css

src/styles/_message-view.scss, src/styles/bar.scss, src/styles/list.scss, src/styles/message-popover.scss, src/styles/mixins/button/_button-types.scss, src/styles/mixins/list/_list-message-view.scss, src/styles/object-status.scss, stories/form-grid/__snapshots__/form-grid.stories.storyshot, stories/message-popover/__snapshots__/message-popover.stories.storyshot, stories/message-popover/message-popover.stories.js, stories/notification/__snapshots__/notification.stories.storyshot
Relates https://github.com/SAP/fundamental-ngx/issues/8329
Added new components:
- Message List
- Message View
- Message Popover
>
3. Testing
=> feat(styles): introduce message popover component [ci visual]

src/styles/object-status.scss
=> fix(styles): update Object Status radius

src/styles/mixins/vertical-nav/_vertical-nav-navigation.scss
part of SAP/fundamental-ngx#8557
=> fix(styles): add vertical nav on hover icon color

src/common-css/_common-mixins.scss, stories/Helpers/focus/focus.stories.js
part of https://github.com/SAP/fundamental-styles/issues/3720
add Visual Focus Concept to common css
=> feat(styles): add focus to common css

.github/workflows/chromatic.yml, .github/workflows/create-hotfix.yml, .github/workflows/create-release.yml, .github/workflows/on-pull.yml, nx.json
Added both local and ci cloud tokens
=> chore: added nx cloud token

.storybook/preview.ts
Moved CX package to be after BTP in sidenav
=> chore: fixed order of the packages

.storybook/preview.ts, packages/common-css/package-config.ts, packages/storybook/src/lib/decorators/themeProvider.ts, projects.js
- Added list of themes to the common-css package
- Optimized theme switching and added logic for removing previously selected theming variables, so that they do not overlap each other
=> docs(common-css): added theming support to the common-css package

packages/doc-ui/src/components/Community.tsx, packages/styles/tests/__snapshots__/styles.test.ts.snap, packages/styles/tests/styles.test.ts
Closes none.
After migration to NX and Vite updating storyshots was broken.
=> fix(e2e): storybook tests issue fix

packages/styles/src/radio.scss
Closes SAP/fundamental-styles#3990
update radio label color for Horizon(new design update)
=> fix(styles): update radio label color [ci visual]

package.json, packages/styles/src/icons/_settingsBusiness.scss, packages/styles/stories/Components/Icons/icon/BusinessSuiteInAppSymbols/dataBusinessSuite.json, yarn.lock
Closes SAP/fundamental-styles#3961
updated SAP theming package and adopted changes
=> chore(deps): updated SAP theming package and adopted changes

packages/cx/project.json, packages/styles/project.json
set chromatic to test against Horizon and Horizon HCB
=> test(styles,cx): switch to 2 horizon themes in chromatic [ci visual]

packages/common-css/stories/elevation/elevation.stories.js, packages/common-css/stories/overflow/overflow.stories.js, packages/cx/src/_nested-list.scss, packages/cx/src/_settings.scss, packages/cx/src/side-nav.scss, packages/cx/stories/Components/cx-side-navigation/cx-side-navigation.stories.js
add cx namespace(`fdx`) for side nav
=> fix(cx): add cx namespace for side nav

packages/styles/stories/Components/Forms/input/input.stories.js, packages/styles/stories/Components/Icons/icon/BusinessSuiteInAppSymbols/iconBusinessSuite.stories.js, packages/styles/stories/Components/Icons/icon/SAPIcons/icon.stories.js, packages/styles/stories/Components/Icons/icon/TNTIcons/iconTnt.stories.js, packages/styles/stories/Components/info-label/info-label.stories.js, packages/styles/stories/Components/object-marker/object-marker.stories.js, packages/styles/stories/Components/object-number/object-number.stories.js, packages/styles/stories/Components/object-status/object-status.stories.js
Closes SAP/fundamental-styles#4019
=> fix(docs): moved jsdoc story descriptions to parameters

packages/styles/src/button.scss, packages/styles/src/fundamental-styles.scss, packages/styles/src/timepicker.scss, packages/styles/stories/Components/timepicker/timepicker.stories.js, packages/styles/stories/Deprecated/Components/time-picker/time-picker.stories.js, packages/styles/stories/Patterns/time-picker/time-picker.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/3868
- deprecated the Pattern Time Picker
- added a new component Time Picker
- added a modifier class for buttons when used in Dialog footer `fd-button--decisive`
=> feat(styles): add new Time Picker component

packages/styles/src/timepicker.scss, packages/styles/stories/Components/timepicker/timepicker.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
none
- changed the color of the selected tick
- added in the documentation is-active (button) and is-focus (input) classes
=> fix(styles): add minor changes after design review [ci visual]

packages/styles/src/file-uploader.scss, packages/styles/src/object-list.scss, packages/styles/src/object-status.scss, packages/styles/src/theming/common/file-uploader/_sap_fiori.scss, packages/styles/src/theming/common/file-uploader/_sap_fiori_hc.scss, packages/styles/src/theming/common/file-uploader/_sap_horizon.scss, packages/styles/src/theming/common/file-uploader/_sap_horizon_hc.scss, packages/styles/src/theming/sap_fiori_3.scss, packages/styles/src/theming/sap_fiori_3_dark.scss, packages/styles/src/theming/sap_fiori_3_hcb.scss, packages/styles/src/theming/sap_fiori_3_hcw.scss, packages/styles/src/theming/sap_fiori_3_light_dark.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcw.scss, packages/styles/src/upload-collection.scss, packages/styles/stories/Components/file-uploader/file-uploader.stories.js, packages/styles/stories/Components/object-list/object-list.stories.js, packages/styles/stories/Components/object-status/object-status.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
closes https://github.com/SAP/fundamental-styles/issues/4022
The current PR includes the following changes:
- Refactor the markup for File Uploader to follow BEM (check Breaking Changes section)
- Add a section for showing and modifying the uploaded files (feature for CX)
- Refactor Object Status to show the status icon always aligned with the first row (case where long text takes multiple lines)
**Before**
**After**
**Markup before**
```
<div class="fd-form-item">
<label class="fd-form-label">Upload Document</label>
<div class="fd-file-uploader">
<input  class="fd-input fd-file-uploader__input">
<button class="fd-button">Browse...</button>
</div>
<div class="fd-file-uploader__hidden" aria-live="polite" aria-atomic="true"></div>
<input …
```
=> feat(styles): add Uploaded Files section to File Uploader [ci visual]

packages/styles/src/mixins/list/_list-byline.scss, packages/styles/stories/Components/List/list/byline/byline-list.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
part of https://github.com/SAP/fundamental-ngx/issues/8874
add notification to byline list
=> feat(styles): add notification to byline list [ci visual]

package.json, yarn.lock
update theming-base-content v 11.1.47
=> chore(deps): update theming-base-content v 11.1.47 [ci visual]

packages/styles/src/theming/sap_fiori_3.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/title.scss
Closes https://github.com/SAP/fundamental-styles/issues/3757
=> fix(styles): add fix for Title font-family [ci visual]

packages/styles/src/mixins/list/_list-byline.scss
Closes none
added minor changes to the unread notification after receiving more details about the "dot"
=> fix(styles): minor changes to the notification in Byline list 

packages/styles/src/fundamental-styles.scss, packages/styles/src/theming/common/variant-management/_sap_fiori.scss, packages/styles/src/theming/common/variant-management/_sap_horizon.scss, packages/styles/src/theming/sap_fiori_3.scss, packages/styles/src/theming/sap_fiori_3_dark.scss, packages/styles/src/theming/sap_fiori_3_hcb.scss, packages/styles/src/theming/sap_fiori_3_hcw.scss, packages/styles/src/theming/sap_fiori_3_light_dark.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcw.scss, packages/styles/src/variant-management.scss, packages/styles/stories/Components/variant-management/variant-management.stories.js
relates https://github.com/SAP/fundamental-ngx/issues/5639
Added missing styling for variant management component
=> feat(styles): introduce variant management styling [ci visual]

packages/styles/src/select.scss
Closes https://github.com/SAP/fundamental-styles/issues/4083
=> fix(styles): change the cursor from text to pointer in Select componеnt

packages/styles/stories/Components/Forms/input-group/input-group.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/3732
=> docs(styles): add readonly state example in Input Group [ci visual]

packages/styles/src/mixins/_mixins.scss
fix for high-contrast under windows
=> fix(styles): fix for high-contrast under windows

.github/workflows/create-release.yml, .storybook/main.ts, package.json, packages/common-css/stories/colors/colors.stories.js, vite.config.ts, yarn.lock
The base href was missing for the build of the GH pages
This patch should fix gh pages
=> fix(docs): fixed gh deployment base url

iframe.html
Leading slash is not needed for these assets
=> fix: fixing asset urls

packages/styles/src/mixins/_mixins.scss, packages/styles/src/object-marker.scss
Relates to https://github.com/SAP/fundamental-styles/issues/3955#issuecomment-1355371525
Object Marker link mode style fixes & component refactoring.
=> fix(styles): object marker link & refactoring

packages/styles/stories/Components/object-status/object-status.stories.js, packages/styles/stories/Components/table/table.stories.js, packages/styles/stories/Layouts/dynamic-page/dynamic-page.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Relates to https://github.com/SAP/fundamental-styles/issues/3955#issuecomment-1355405788
Relates to https://github.com/SAP/fundamental-styles/issues/3955#issuecomment-1355386561
Relates to https://github.com/SAP/fundamental-styles/issues/3955#issuecomment-1355372529
Various broken examples fixes.
Dynamic Page
Table
Object Status
Dynamic Page
Table
Object Status
=> fix(docs): broken examples, defect hunting 103

.github/actions/npm-publish/index.js
This fixes implicit type publics
=> fix: fixed access type on releases

.github/actions/npm-publish/index.js
Package json path given to the publish script was wrong
=> fix(ci): fixed package.json paths in publish script

packages/styles/src/illustrated-message.scss, packages/styles/stories/Components/illustrated-message/illustrated-message.stories.js
Part of SAP/fundamental-ngx#9114
Styles implementation of "dot" type illustrated message
=> feat(styles): introduced Dot type in illustrated-message

packages/styles/src/theming/common/user-menu/_sap_fiori.scss, packages/styles/src/theming/common/user-menu/_sap_horizon.scss, packages/styles/src/theming/sap_fiori_3.scss, packages/styles/src/theming/sap_fiori_3_dark.scss, packages/styles/src/theming/sap_fiori_3_hcb.scss, packages/styles/src/theming/sap_fiori_3_hcw.scss, packages/styles/src/theming/sap_fiori_3_light_dark.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcw.scss, packages/styles/src/user-menu.scss, packages/styles/stories/Components/shellbar/shellbar.stories.js, packages/styles/stories/Components/user-menu/user-menu.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/4091
=> fix(styles): add Horizon delta for User Menu [ci visual]

packages/styles/src/action-bar.scss, packages/styles/src/mixins/_states.scss
part of https://github.com/SAP/fundamental-styles/issues/3962
v1 code refactor for Action Bar
=> fix(styles): action bar version 1 update [ci visual]

packages/cx/stories/Components/cx-side-navigation/cx-side-navigation.stories.js
fixes none
documentation was using the incorrect button type for cx side nav
=> fix(styles): update cx side nav button type

packages/styles/stories/Components/shellbar/shellbar.stories.js
=> chore(styles): fix shellbar storyname

package.json, packages/styles/src/icons/_settings.scss, packages/styles/stories/Components/Icons/icon/SAPIcons/data.json, yarn.lock
bump to theming-base-content version 11.1.49
=> chore(deps): bump to theming-base-content version 11.1.49 [ci visual]

packages/styles/src/form-message.scss, packages/styles/src/input.scss, packages/styles/src/popover.scss, packages/styles/stories/Components/Forms/form-message/form-message.stories.js, packages/styles/stories/Components/Forms/input/input.stories.js, packages/styles/stories/Components/Forms/textarea/textarea.stories.js, packages/styles/stories/Components/select/select.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/4202.
Fixes issue when icon placed on the separate line in Form Message.
https://user-images.githubusercontent.com/20265336/217062688-ec41c0c9-f256-46ce-bd76-7e8da0d9a78e.mov
https://user-images.githubusercontent.com/20265336/217062546-ea706ed3-0869-4a94-bf3c-cf95362a91c0.mov
=> fix(styles): form message with icon layout, styles & docs refactoring

packages/styles/src/layout-panel.scss, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes none
changed the font-size of the description per designers request
=> fix(styles): fix for the font-size of Layout Panel [ci visual]

.github/workflows/create-hotfix.yml, .github/workflows/create-release.yml, .storybook/main.ts, package.json, packages/configuration/src/lib/packages.ts, packages/fn/project.json, projects.js, scripts/sync-components.js
Removed fn package from docs and publishes
=> chore: removed fn from documentation and publish

packages/common-css/src/_common-mixins.scss, packages/common-css/src/common-css.scss, packages/common-css/src/sap-position.scss, packages/common-css/stories/position/position.stories.js, packages/common-css/stories/position/position.story.description.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes none
add classes and mixins for position in common CSS
=> feat(styles): add position to common CSS 

.storybook/preview-head.html, README.md, package.json, packages/styles/README.md, packages/styles/src/fonts/sap_horizon_fonts.scss, packages/styles/src/icons/_settingsBusiness.scss, packages/styles/stories/Components/Icons/icon/BusinessSuiteInAppSymbols/dataBusinessSuite.json, packages/styles/tests/__snapshots__/styles.test.ts.snap, yarn.lock
upgrade to theming-base-content version 11.2.1
=> chore(deps): upgrade to theming-base-content version 11.2.1

packages/cx/src/side-nav.scss
fixes none
Part of https://github.com/SAP/fundamental-ngx/issues/9405
Adds a --mobile class to the cx side nav
=> fix(styles): add --mobile class to CX side nav [ci visual]

packages/styles/src/mixins/_mixins.scss, packages/styles/src/pagination.scss
=> fix(styles): simplify compact selector [ci visual]

packages/common-css/src/sap-flex.scss
remove explicit flex-direction from flex-gap
=> fix(common-css): remove explicit flex-direction from flex-gap

packages/styles/src/mixins/_mixins.scss, packages/styles/src/mixins/table/_table-no-borders.scss, packages/styles/src/mixins/table/_table-pop-in.scss, packages/styles/src/shellbar.scss, packages/styles/src/table.scss, packages/styles/src/theming/common/shellbar/_sap_horizon.scss, packages/styles/src/theming/common/shellbar/_sap_horizon_hc.scss
Closes https://github.com/SAP/fundamental-styles/issues/4422
- Fixed button outline for shellbar search dropdown;
- Fixed minor issues with table styles for ngx platform implementation;
3. Testing
=> fix(styles): adjust table and shellbar styling

packages/fn/package.json, packages/icons/package.json, packages/workspace-plugins/src/executors/build/executor.ts
Part of https://github.com/SAP/fundamental-ngx/issues/9629
Made peer dependencies non-strict
=> fix: changed peer dependency versions

packages/styles/tests/__snapshots__/styles.test.ts.snap
=> test(styles): update testing storyshots

packages/styles/src/popover.scss, packages/styles/stories/Components/popover/popover.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/4408
New feature
=> feat(styles): add resizable functionality to Popover

packages/styles/src/form-label.scss, packages/styles/stories/Components/Forms/form-label/form-label.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
update label for horizon
fixes #4378
=> feat(styles): update label for horizon [ci visual]

packages/styles/src/busy-indicator.scss, packages/styles/stories/Components/busy-indicator/busy-indicator.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/4399
adds Busy Dialog
=> feat(styles): add Busy Dialog variation to Busy Indicator [ci visual]

packages/styles/tests/__snapshots__/styles.test.ts.snap
=> chore(e2e): update snapshots

package.json, yarn.lock
bump theming-base-content to version 11.3.2
=> chore(deps): bump theming-base-content to version 11.3.2 [ci visual]

packages/styles/src/slider.scss, packages/styles/src/theming/common/slider/_sap_fiori.scss, packages/styles/src/theming/common/slider/_sap_horizon.scss, packages/styles/src/theming/sap_fiori_3/_css_variables.scss, packages/styles/src/theming/sap_fiori_3_dark/_css_variables.scss, packages/styles/src/theming/sap_fiori_3_hcb/_css_variables.scss, packages/styles/src/theming/sap_fiori_3_hcw/_css_variables.scss, packages/styles/src/theming/sap_fiori_3_light_dark/_css_variables.scss, packages/styles/src/theming/sap_horizon/_css_variables.scss, packages/styles/src/theming/sap_horizon_dark/_css_variables.scss, packages/styles/src/theming/sap_horizon_hcb/_css_variables.scss, packages/styles/src/theming/sap_horizon_hcw/_css_variables.scss, packages/styles/stories/Components/slider/slider.stories.js
Closes SAP/fundamental-styles#4392
- Added vertical slider styles;
- Added range focus block per guidelines; - BREAKING CHANGE;
- Removed `fd-slider__handle--lg`. Now this style is combined with `fd-slider--lg`; - BREAKING CHANGE;
=> feat(styles): slider horizon delta

packages/styles/src/mixins/_mixins.scss, packages/styles/src/toolbar.scss, packages/styles/stories/Components/toolbar/toolbar.stories.js
Closes #4397
- Simplified scss logic.
- Added cozy mixin.
- Simplified html example markup
=> fix(styles): adjust toolbar styling

packages/styles/src/panel.scss, packages/styles/stories/Components/panel/panel.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/4387
- updated the paddings for the content area
- added modifier class for borderless header option  `.fd-panel--borderless`
- added modifier class for transparent Panel content option `.fd-panel--transparent`
=> fix(styles): add latest Horizon updates to Panel [ci visual]

packages/styles/src/fundamental-styles.scss, packages/styles/src/generic-tag.scss, packages/styles/src/theming/common/generic-tag/_sap_horizon.scss, packages/styles/src/theming/common/generic-tag/_sap_horizon_hc.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcw.scss, packages/styles/stories/Components/generic-tag/generic-tag.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/4396
new component added
=> feat(styles): introduce Generic Tag [ci visual]

packages/styles/src/mixins/table/_table-group-and-tree.scss, packages/styles/stories/Components/table/table.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Applied correct table indentation according to the design guidelines
=> fix(styles): correct table indentation [ci visual]

packages/styles/src/checkbox.scss, packages/styles/src/theming/common/checkbox/_common.scss, packages/styles/src/theming/common/checkbox/_sap_fiori_hc.scss, packages/styles/src/theming/common/checkbox/_sap_foiri.scss, packages/styles/src/theming/common/checkbox/_sap_horizon.scss, packages/styles/src/theming/common/checkbox/_sap_horizon_hc.scss, packages/styles/src/theming/sap_fiori_3.scss, packages/styles/src/theming/sap_fiori_3_dark.scss, packages/styles/src/theming/sap_fiori_3_hcb.scss, packages/styles/src/theming/sap_fiori_3_hcw.scss, packages/styles/src/theming/sap_fiori_3_light_dark.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcw.scss
Closes https://github.com/SAP/fundamental-styles/issues/4372
=> fix(styles): update Checkbox to latest Horizon 2023 [ci visual]

packages/styles/src/theming/common/flexible-column-layout/_sap_fiori.scss, packages/styles/src/theming/common/flexible-column-layout/_sap_fiori_hc.scss, packages/styles/src/theming/common/flexible-column-layout/_sap_horizon.scss, packages/styles/src/theming/common/flexible-column-layout/_sap_horizon_hc.scss, packages/styles/src/theming/sap_fiori_3.scss, packages/styles/src/theming/sap_fiori_3_dark.scss, packages/styles/src/theming/sap_fiori_3_hcb.scss, packages/styles/src/theming/sap_fiori_3_hcw.scss, packages/styles/src/theming/sap_fiori_3_light_dark.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcw.scss, packages/styles/stories/Layouts/flexible-column-layout/flexible-column-layout.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
update Flexible Column Layout Horizon
=> feat(styles): update Flexible Column Layout Horizon [ci visual]

packages/configuration/src/lib/tags.ts, packages/cx/stories/Components/cx-side-navigation/cx-side-navigation.stories.js, packages/styles/stories/Components/splitter/splitter.stories.js, packages/styles/stories/Components/tool-header/tool-header.stories.js, packages/styles/stories/Components/variant-management/variant-management.stories.js, packages/styles/stories/Components/vertical-navigation/vertical-navigation.stories.js, packages/styles/stories/Patterns/horizontal-navigation/horizontal-navigation.stories.js
update tags on the documentation (btp, sap design, cx)
=> docs(styles,cx): update tags on the documentation

packages/styles/src/splitter.scss, packages/styles/src/theming/common/splitter/_sap_horizon.scss, packages/styles/src/theming/common/splitter/_sap_horizon_hc.scss
Closes SAP/fundamental-styles #4484 
splitter with horizon 2023
=> feat(styles): splitter with horizon 2023 [ci visual]

packages/styles/src/_avatar-variables.scss, packages/styles/src/avatar-group.scss, packages/styles/src/avatar.scss, packages/styles/src/mixins/_states.scss, packages/styles/src/theming/common/avatar-group/_common.scss, packages/styles/src/theming/common/avatar-group/_sap_fiori.scss, packages/styles/src/theming/common/avatar-group/_sap_horizon.scss, packages/styles/src/theming/common/avatar/_common.scss, packages/styles/src/theming/common/avatar/_sap_fiori.scss, packages/styles/src/theming/common/avatar/_sap_fiori_hc.scss, packages/styles/src/theming/common/avatar/_sap_horizon.scss, packages/styles/src/theming/common/avatar/_sap_horizon_hc.scss, packages/styles/src/theming/sap_fiori_3.scss, packages/styles/src/theming/sap_fiori_3_dark.scss, packages/styles/src/theming/sap_fiori_3_hcb.scss, packages/styles/src/theming/sap_fiori_3_hcw.scss, packages/styles/src/theming/sap_fiori_3_light_dark.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcw.scss, packages/styles/stories/Components/avatar-group/avatar-group.stories.js, packages/styles/stories/Components/avatar/avatar.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/4366
Closes https://github.com/SAP/fundamental-styles/issues/4367
**Avatar**
- bring the latest Horizon 2023 changes to Avatar
- new feature: value states
- new feature: interactive states
- code refactor to use css variables for the modifier classes
- documentation improvements: a11y. Added aria-roles, aria-hidden, aria-labels, etc.
**Avatar Group**
- Interaction States
- Vertical Orientation
- Updates for the Overflow Button
- code refactor to use css variables for the modifier classes
- documentation improvements: a11y. Added aria-roles, aria-hidden, aria-labels, etc.
**BREAKING CHANGES:**
- removed element with class `fd-avatar-group__item` 
- minimizes the code repetition for the interaction states
**Before:**
```
<div …
```
=> feat(styles): add Horizon 2023 update for Avatar and Avatar Group[ci visual]

packages/styles/src/theming/common/tile/_sap_fiori.scss, packages/styles/src/theming/common/tile/_sap_horizon.scss, packages/styles/src/tile.scss, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes SAP/fundamental-styles#4502
update tile title font size
=> fix(styles): update tile title font size [ci visual]

packages/styles/src/message-popover.scss, packages/styles/src/theming/common/message-popover/_sap_fiori.scss, packages/styles/src/theming/common/message-popover/_sap_horizon.scss, packages/styles/src/theming/common/message-popover/_sap_horizon_hc.scss, packages/styles/src/theming/sap_fiori_3.scss, packages/styles/src/theming/sap_fiori_3_dark.scss, packages/styles/src/theming/sap_fiori_3_hcb.scss, packages/styles/src/theming/sap_fiori_3_hcw.scss, packages/styles/src/theming/sap_fiori_3_light_dark.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcw.scss, packages/styles/stories/Components/message-popover/details-view.example.html, packages/styles/stories/Components/message-popover/message-popover.stories.js, packages/styles/stories/Components/message-popover/message-trigger.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes [SAP/fundamental-styles#](https://github.com/SAP/fundamental-styles/issues/4540)
=> fix(styles): update Message Value State Button of Message Popover to latest Horizon 2023

package.json, yarn.lock
theming-base-content version 11.4.2
=> chore(deps): theming-base-content version 11.4.2 [ci visual]

packages/styles/src/grid-list.scss, packages/styles/src/theming/sap_fiori_3.scss, packages/styles/src/theming/sap_fiori_3_dark.scss, packages/styles/src/theming/sap_fiori_3_hcb.scss, packages/styles/src/theming/sap_fiori_3_hcw.scss, packages/styles/src/theming/sap_fiori_3_light_dark.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcw.scss, packages/styles/src/toolbar.scss, packages/styles/stories/Components/toolbar/alignment.example.html, packages/styles/stories/Components/toolbar/overflow.example.html, packages/styles/stories/Components/toolbar/primary.example.html, packages/styles/stories/Components/toolbar/separator.example.html, packages/styles/stories/Components/toolbar/toolbar.stories.js, packages/styles/stories/Components/toolbar/types.example.html
Closes https://github.com/SAP/fundamental-styles/issues/4398
- refactor the code to use CSS variables for changing parameters
- adopted the latest Horizon changes
- removed the `is-cozy` modifier class
- `is-cozy` modifier class is removed, now cozy is the default state
- added `is-compact` modifier class for compact state
=> fix(styles): update and refactor Toolbar [ci visual]

packages/styles/src/page.scss, packages/styles/stories/Layouts/page/page.stories.js
Closes #4386
Update Page stories and use css-var for background
=> docs(styles): update page docs

packages/styles/tests/__snapshots__/styles.test.ts.snap
=> test(styles): update test snapshots

packages/styles/src/icon-tab-bar.scss, packages/styles/src/theming/common/icon-tab-bar/_common.scss, packages/styles/src/theming/common/icon-tab-bar/_sap_fiori.scss, packages/styles/src/theming/common/icon-tab-bar/_sap_fiori_hc.scss, packages/styles/src/theming/common/icon-tab-bar/_sap_horizon.scss, packages/styles/src/theming/common/icon-tab-bar/_sap_horizon_hc.scss, packages/styles/stories/Components/icon-tab-bar/badge.example.html, packages/styles/stories/Components/icon-tab-bar/icon-tab-bar.stories.js, packages/styles/stories/Components/icon-tab-bar/multi-click.example.html, packages/styles/stories/Components/icon-tab-bar/navigation.example.html, packages/styles/stories/Components/icon-tab-bar/overflow.example.html, packages/styles/stories/Components/icon-tab-bar/single-click.example.html, packages/styles/stories/Components/icon-tab-bar/text-only-closable.example.html
Closes https://github.com/SAP/fundamental-styles/issues/4394
- new feature: Closable Tabs
- updates in multi click area
- updates for overflow button
- new params for Shell Navigation button
- code cleanup 
- use of CSS variables for modifiers
=> feat(styles): add Horizon 2023 updates for Icon tab Bar [ci visual]

.storybook/main.ts
opt out from storybook telemetry
=> chore(deps): opt out from storybook telemetry

packages/styles/src/object-list.scss, packages/styles/stories/Components/object-list/standart.example.html
Closes https://github.com/SAP/fundamental-styles/issues/4627
- fix the height not being 100%
- code clean-up
- check props for Horizon updates
=> fix(styles): add fix for Object List height [ci visual]

packages/styles/src/progress-indicator.scss, packages/styles/stories/Components/progress-indicator/truncation.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/4624
Closes https://github.com/SAP/fundamental-styles/issues/4388
- checked the specs and the props for design changes (none)
- fixed the issue with Label truncation
The container element should be the Popover control. `fd-popover__control` is used together with `fd-progress-indicator__container`, not with `fd-progress-indicator__progress-bar` and `fd-progress-indicator__remaining`.
The Popover body should have an arrow in the center
Before:
```
<div class="fd-progress-indicator fd-popover">
<div class="fd-progress-indicator__container">
<div class="fd-progress-indicator__progress-bar fd-popover__control" onclick="onPopoverClick('popoverF0')">
<span class="fd-progress-indicator__label">...</span>
</div>
<div …
```
=> fix(styles): add fix for Label truncation in Progress Indicator 

packages/theming-preview/src/button.html, packages/theming-preview/src/calendar.html, packages/theming-preview/src/form.html, packages/theming-preview/src/header-footer.html, packages/theming-preview/src/icon.html, packages/theming-preview/src/input.html, packages/theming-preview/src/object-header.html, packages/theming-preview/src/panel.html, packages/theming-preview/src/semantic-colors.html, packages/theming-preview/src/shell-tile-card.html, packages/theming-preview/src/table.html, packages/theming-preview/src/text.html, packages/theming-preview/src/toolbar.html
updated the markup for the theming-preview
=> fix(styles): update theming-preview examples' markup

packages/styles/src/theming/common/tokenizer/_sap_fiori.scss, packages/styles/src/theming/common/tokenizer/_sap_horizon.scss, packages/styles/src/theming/sap_fiori_3.scss, packages/styles/src/theming/sap_fiori_3_dark.scss, packages/styles/src/theming/sap_fiori_3_hcb.scss, packages/styles/src/theming/sap_fiori_3_hcw.scss, packages/styles/src/theming/sap_fiori_3_light_dark.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcw.scss, packages/styles/src/tokenizer.scss
Closes  SAP/fundamental-styles#](https://github.com/SAP/fundamental-styles/issues/4384)
Multi Combobox is a composite component. Updated the Tokenizer indicator (5 more, ...) to proper color in Horizon
=> fix(styles): bring Horizon updates for Tokenizer [ci visual]

packages/styles/tests/__snapshots__/styles.test.ts.snap
=> test(styles): update storyshots

packages/styles/src/button.scss, packages/styles/src/theming/common/button/_sap_fiori.scss, packages/styles/src/theming/common/button/_sap_fiori_hc.scss, packages/styles/src/theming/common/button/_sap_horizon.scss, packages/styles/src/theming/common/button/_sap_horizon_hc.scss, packages/styles/stories/Components/button/button.stories.js, packages/styles/stories/Components/button/nested.example.html, packages/styles/stories/Components/button/tool-header.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/4314
- add Tool Header button
- add Nested Button
NOTE: 
The code for these 2 new buttons don't overwrite the CSS variables for Button component intentionally so that in future, if needed, we can easily make them separate from Button. That's in case we decide to go with a separate package for BTP.
=> feat(styles): add BTP Tool Header and Nested Buttons to Button component

packages/styles/src/button.scss, packages/styles/src/fundamental-styles.scss, packages/styles/src/search-field.scss, packages/styles/src/theming/common/button/_sap_fiori.scss, packages/styles/src/theming/common/button/_sap_horizon.scss, packages/styles/src/theming/common/search-field/_sap_fiori.scss, packages/styles/src/theming/common/search-field/_sap_fiori_hc.scss, packages/styles/src/theming/common/search-field/_sap_horizon.scss, packages/styles/src/theming/common/search-field/_sap_horizon_hc.scss, packages/styles/src/theming/sap_fiori_3.scss, packages/styles/src/theming/sap_fiori_3/_css_variables.scss, packages/styles/src/theming/sap_fiori_3_dark.scss, packages/styles/src/theming/sap_fiori_3_dark/_css_variables.scss, packages/styles/src/theming/sap_fiori_3_hcb.scss, packages/styles/src/theming/sap_fiori_3_hcb/_css_variables.scss, packages/styles/src/theming/sap_fiori_3_hcw.scss, packages/styles/src/theming/sap_fiori_3_hcw/_css_variables.scss, packages/styles/src/theming/sap_fiori_3_light_dark.scss, packages/styles/src/theming/sap_fiori_3_light_dark/_css_variables.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon/_css_variables.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_dark/_css_variables.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcb/_css_variables.scss, packages/styles/src/theming/sap_horizon_hcw.scss, packages/styles/src/theming/sap_horizon_hcw/_css_variables.scss, packages/styles/stories/Components/search-field/default.example.html, packages/styles/stories/Components/search-field/search-field.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/4321
- new component Search field
- minor update for nested and tool header buttons
=> feat(styles): introduce BTP Search field component [ci visual]

package.json, yarn.lock
=> chore(deps): update theming-base-content v. 11.6.4

packages/styles/src/fundamental-styles.scss, packages/styles/src/navigation-menu.scss, packages/styles/src/theming/common/navigation-menu/_sap_fiori.scss, packages/styles/src/theming/common/navigation-menu/_sap_fiori_hc.scss, packages/styles/src/theming/common/navigation-menu/_sap_horizon.scss, packages/styles/src/theming/common/navigation-menu/_sap_horizon_hc.scss, packages/styles/src/theming/sap_fiori_3.scss, packages/styles/src/theming/sap_fiori_3/_css_variables.scss, packages/styles/src/theming/sap_fiori_3_dark.scss, packages/styles/src/theming/sap_fiori_3_dark/_css_variables.scss, packages/styles/src/theming/sap_fiori_3_hcb.scss, packages/styles/src/theming/sap_fiori_3_hcb/_css_variables.scss, packages/styles/src/theming/sap_fiori_3_hcw.scss, packages/styles/src/theming/sap_fiori_3_hcw/_css_variables.scss, packages/styles/src/theming/sap_fiori_3_light_dark.scss, packages/styles/src/theming/sap_fiori_3_light_dark/_css_variables.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon/_css_variables.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_dark/_css_variables.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcb/_css_variables.scss, packages/styles/src/theming/sap_horizon_hcw.scss, packages/styles/src/theming/sap_horizon_hcw/_css_variables.scss, packages/styles/stories/BTP/navigation-menu/navigation-menu-item-child.example.html, packages/styles/stories/BTP/navigation-menu/navigation-menu-item-group.example.html, packages/styles/stories/BTP/navigation-menu/navigation-menu-item.example.html, packages/styles/stories/BTP/navigation-menu/navigation-menu.stories.js
Closes none
Adding the building blocks for BTP Menu and Navigation component
- navigation parent item
- navigation child item
- navigation group item
NOTE: for now the documentation is under `Dev` folder until we implement the Menu, Vertical Navigation and Horizontal navigation.
=> feat(styles): add BTP nav items

packages/styles/src/popover.scss
closes none
- Simplified selectors for the resize handle of the Popover body
=> fix(styles): popover resize handle simplification

.github/workflows/chromatic.yml
add names to the jobs in chromatic.yml
=> chore(ci): add names to the jobs in chromatic.yml [ci visual]

packages/styles/src/calendar.scss
closes none
- Fixed issue with inner outline if cell is wider than standard width;
- Fixed issue with focus-visible state
=> fix(styles): fix calendar visual issues

.storybook/main.ts
Storybook updated specs, which needed our amendments as well
=> chore: fixed documentation sidebar grouping

package.json
=> chore(ci): bump versions

nx.json, package.json
Fixed nx caches and reverted commit which increased version before
=> chore(ci): fix nx caches

packages/styles/src/fundamental-styles.scss, packages/styles/src/theming/sap_fiori_3.scss, packages/styles/src/theming/sap_fiori_3_dark.scss, packages/styles/src/theming/sap_fiori_3_hcb.scss, packages/styles/src/theming/sap_fiori_3_hcw.scss, packages/styles/src/theming/sap_fiori_3_light_dark.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcw.scss, packages/styles/src/tool-layout.scss, packages/styles/stories/BTP/tool-layout/desktop.example.html, packages/styles/stories/BTP/tool-layout/mobile.example.html, packages/styles/stories/BTP/tool-layout/tablet.example.html, packages/styles/stories/BTP/tool-layout/tool-layout.stories.js
Closes https://github.com/SAP/fundamental-styles/issues/4319
- introduce new component Tool Layout
- I will have to update the examples to include the actual horizontal and vertical nav once their PRs are merged. For now I used inline styling to make the containers distinguishable.
=> feat(styles): add BTP Tool Layout component [ci visual]

packages/styles/src/tool-layout.scss, packages/styles/stories/BTP/tool-layout/desktop.example.html, packages/styles/stories/BTP/tool-layout/mobile.example.html, packages/styles/stories/BTP/tool-layout/tablet.example.html, packages/styles/stories/BTP/tool-layout/tool-layout.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes none
- fix a few bugs discovered during ngx implementation
- fix wrong classnames in the component description
=> fix(styles): add some CSS changes and fix docs bugs [ci visual]

packages/styles/src/fundamental-styles.scss, packages/styles/src/title-bar.scss, packages/styles/src/toolbar.scss, packages/styles/stories/BTP/Navigation/horizontal/navigation-horizontal.stories.js, packages/styles/stories/BTP/Navigation/vertical/navigation.stories.js, packages/styles/stories/BTP/title-bar/desktop.example.html, packages/styles/stories/BTP/title-bar/mobile.example.html, packages/styles/stories/BTP/title-bar/tablet.example.html, packages/styles/stories/BTP/title-bar/title-bar.stories.js, packages/styles/stories/BTP/tool-header/tool-header.stories.js, packages/styles/stories/BTP/tool-layout/tool-layout.stories.js
=> feat(styles): introduce new Title Bar BTP component [ci visual]

packages/styles/stories/Components/Forms/checkbox/inline.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
=> test: swap checkboxes examples [ci visual]

packages/styles/src/table.scss
fixes SAP/fundamental-ngx#10799
=> fix(styles): selected table cell border issue

packages/styles/src/calendar.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcw.scss, packages/styles/stories/Components/calendar/cal.html, packages/styles/stories/Components/calendar/days.example.html, packages/styles/stories/Patterns/datepicker/mobile-landscape.example.html, packages/styles/stories/Patterns/datepicker/mobile-portrait.example.html, packages/styles/stories/Patterns/datepicker/today-navigation-button.example.html, packages/styles/stories/Patterns/datepicker/today-selection-button.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap, packages/theming-preview/src/calendar.html
=> fix(styles): calendar updates [ci visual]

packages/styles/src/fonts/sap_fiori_3_fonts.scss
include the tnt font icons for fiori 3
=> fix(styles): include the tnt font icons for fiori 3

package.json, packages/styles/src/icons/_settings.scss, packages/styles/stories/Components/Icons/icon/SAPIcons/data.json, yarn.lock
update theming-base-content version 11.8.0
=> chore(deps): update theming-base-content version 11.8.0 [ci visual]

packages/styles/stories/Components/dialog/default-dialog.example.html, packages/styles/stories/Components/dialog/dialog.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
=> docs(styles): dialog updates

package.json, packages/styles/src/icons/_settingsTNT.scss, packages/styles/stories/Components/Icons/icon/TNTIcons/dataTNT.json, yarn.lock
update to theming-base-content 11.9.0
=> chore(deps): update to theming-base-content 11.9.0

packages/styles/src/mixins/_mixins.scss, packages/styles/src/progress-indicator.scss, packages/styles/src/quick-view.scss, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes none
The default line-height of the elements, coming from the reset mixin was **1.5**. Changing it to **normal** per specs.
=> fix(styles): change the default line height to normal [ci visual]

.github/actions/bump-version/action.yml, .github/actions/generate-conventional-release-notes/action.yml, .github/actions/npm-publish/action.yml
=> chore: fix node18 with node20

packages/common-css/stories/content-paddings/content-paddings.stories.js
fix typo in content-paddings storybook
=> chore(common-css): fix typo in content-paddings storybook

packages/common-css/project.json
Closes SAP/fundamental-styles#5048
Added missing files
=> fix(common-css): missing scss files in distribution

packages/styles/src/toolbar.scss, packages/styles/stories/Components/table/table.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Relates [SAP/fundamental-styles#10132](https://github.com/SAP/fundamental-ngx/issues/10132)
- Added one level of specificity to override default fd-title modifier styles.
=> fix(styles): toolbar title font size [ci visual]

packages/styles/src/fonts/sap_fonts.scss
Relates https://github.com/SAP/fundamental-ngx/issues/11171
=> fix(styles): add black font family [ci visual]

package.json, yarn.lock
update theming-base-content v. 11.10.0
=> chore(deps): update theming-base-content v. 11.10.0

packages/styles/src/_avatar-variables.scss, packages/styles/src/avatar-group.scss, packages/styles/stories/Components/avatar-group/avatar-group.stories.js, packages/styles/stories/Components/avatar-group/group-type-interaction-states.example.html, packages/styles/stories/Components/avatar-group/group-type-vertical.example.html, packages/styles/stories/Components/avatar-group/group-type.example.html, packages/styles/stories/Components/avatar-group/individual-type-vertical.example.html, packages/styles/stories/Components/avatar-group/individual-type.example.html, packages/styles/stories/Components/avatar-group/overflow.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
v1.0.0
- added new modifier classes for the sizes of the Avatar Groups so they are consistent with the other modifiers. The old are kept to avoid Breaking Changes
- updated the active/toggled state of the Group type
- updated the documentation examples
=> fix(styles): updates related to v1 for Avatar Group [ci visual]

package.json, yarn.lock
update theming-base-content v11.11.0
=> chore(deps): update theming-base-content v11.11.0

yarn.lock
revert #5153 as it breaks chromatic
=> chore: revert #5153

packages/configuration/src/lib/tags.ts, packages/styles/src/bar.scss, packages/styles/stories/Components/avatar-group/avatar-group.stories.js, packages/styles/stories/Components/avatar/avatar.stories.js, packages/styles/stories/Components/bar/bar.stories.js, packages/styles/stories/Components/bar/floating-footer.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
version 1
- checked the design specs for updates
- did code refactoring
- updated the docs text
- added new modifier classes for the sizes
- added version 1 tag
=> fix(styles): bar component v1 update [ci visual]

package.json
empty commit push to fix versioning
=> chore: empty commit push

.github/workflows/chromatic.yml, .github/workflows/on-pull.yml
@g-cheishvili  as you suggested simplify on_pull workflow (it saved some time :D )
=> chore(ci): simplify on_pull workflow

package.json, yarn.lock
update theming-base-content 11.12.0
=> chore(deps): update theming-base-content 11.12.0 [ci visual]

.github/workflows/on-pull.yml
=> chore(ci): bump ghaction cache version

packages/configuration/src/lib/previous-versions.ts
=> docs: add link to 0.33 to the docs

package.json, packages/styles/src/icons/_settings.scss, packages/styles/stories/Components/Icons/icon/SAPIcons/data.json, yarn.lock
=> chore(deps): theming-base-content v11.13.0 [ci visual]

packages/configuration/src/lib/previous-versions.ts
=> docs: add doc 0.34

packages/styles/src/card.scss, packages/styles/src/theming/common/card/_sap_fiori.scss, packages/styles/src/theming/common/card/_sap_horizon.scss, packages/styles/stories/Components/card/analytical-card.example.html, packages/styles/stories/Components/card/card-anatomy.example.html, packages/styles/stories/Components/card/card.stories.js, packages/styles/stories/Components/card/extended-header.example.html, packages/styles/stories/Components/card/list-card.example.html, packages/styles/stories/Components/card/numeric-header.example.html, packages/styles/stories/Components/card/object-card.example.html, packages/styles/stories/Components/card/table-card.example.html, packages/styles/stories/Layouts/fixed-card-layout/fixed-card-layout.example.html, packages/styles/stories/Layouts/resizable-card-layout/resize-card-horizontal-direction.example.html, packages/styles/stories/Layouts/resizable-card-layout/resize-card-horizontal-vertical-direction.example.html, packages/styles/stories/Layouts/resizable-card-layout/resize-card-layout.example.html, packages/styles/stories/Layouts/resizable-card-layout/resize-card-vertical-direction.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/5247
- Card header changes to reflect the latest design 
- a11y improvements
- example updates
- new modifier classes: `fd-card__content--with-spacing` for the `fd-card__content`
- added main, extended and numeric headers
- updated aria roles
- the card title with class `fd-card__title` now has aria-role="heading" and aria-level as well as id to label the card header
- the card header has a role="group", aria-roledescription="Card Header" and aria-labelledby
- removed `fd-card__header-non-interactive` class. It's now applied to the main header as only it can be interactive. 
- new markup for the header with new elements and classes
- the div element with class `fd-card__header` is now a container for the main, …
=> feat(styles): update Card header per latest design

package.json, yarn.lock
=> chore(deps): revert vite-tsconfig-path

packages/styles/src/shellbar.scss, packages/styles/src/theming/common/shellbar/_sap_horizon.scss, packages/styles/stories/Components/shellbar/responsive-paddings.example.html
Closes https://github.com/SAP/fundamental-styles/issues/5307
- fixed the issue with the missing border on hover
- updated the button icon color per the new specs
- updated the responsive paddings search markup and also made the input active so we have the active state of search button for testing purposes
=> fix(styles): add fix for buttons hover state in Shell Bar [ci visual]

packages/styles/src/object-status.scss, packages/styles/stories/Components/object-status/inverted.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/5284
The Inverted object status (Tag) has some updates so the current changes reflect them
=> fix(styles): update Inverted object status to latest design [ci visual]

package.json, packages/styles/src/icons/_settingsTNT.scss, packages/styles/stories/Components/Icons/icon/TNTIcons/dataTNT.json, yarn.lock
theming-base-content v.11.14.0
=> chore(deps): theming-base-content v.11.14.0 [ci visual]

packages/styles/src/textarea.scss
fix readonly textarea part of https://github.com/SAP/fundamental-ngx/issues/11809
=> fix(styles): fix readonly textarea [ci visual]

packages/styles/src/textarea.scss, packages/styles/src/theming/common/textarea/_sap_fiori.scss, packages/styles/src/theming/common/textarea/_sap_horizon.scss, packages/styles/src/theming/sap_fiori_3.scss, packages/styles/src/theming/sap_fiori_3_dark.scss, packages/styles/src/theming/sap_fiori_3_hcb.scss, packages/styles/src/theming/sap_fiori_3_hcw.scss, packages/styles/src/theming/sap_fiori_3_light_dark.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcw.scss
=> fix(styles): update textarea line-height [ci visual]

package.json, yarn.lock
theming-base-content v.11.15.0 ([PR](https://github.com/SAP/theming-base-content/commit/30a843e20910f6b6ed64fd116ac4b82dc612181b))
=> chore(deps): theming-base-content v.11.15.0 [ci visual]

packages/styles/src/shellbar.scss
Closes https://github.com/SAP/fundamental-styles/issues/5404
add the correct color for Mega Manu button
=> fix(styles): add fix for the Mega Manu button color [ci visual]

packages/configuration/src/lib/previous-versions.ts
update old version doc links (`0.35` and `0.36`)
=> docs: update old version doc links

.github/actions/bump-version/index.js, .github/actions/helpers/get-release-tag.js
=> fix(docs): publish github pages

.github/actions/bump-version/index.js
=> fix(ci): fix ci

.github/actions/bump-version/index.js
=> fix(ci): fix ci - try 2

package.json, yarn.lock
theming-base-content version 11.16.1
=> chore(deps): theming-base-content version 11.16.1

packages/common-css/stories/colors/background-color.example.html, packages/common-css/stories/colors/text-color.example.html
Closes none (part of common CSS task)
add more color examples to the documentation
=> docs(common-css): add more colors to the docs [ci visual]

packages/common-css/src/common-css.scss, packages/common-css/src/sap-title.scss, packages/common-css/stories/page-title/no-inline-padding.example.html, packages/common-css/stories/page-title/no-page-title.example.html, packages/common-css/stories/page-title/title.stories.js, packages/common-css/stories/page-title/with-page-title.example.html
Closes none (part of common css)
adds Title as building block of Pages
=> feat(common-css): add Titles to Common CSS package [ci visual]

packages/styles/src/theming/sap_belize.scss
=> fix: add belize preview

packages/common-css/src/_common-mixins.scss, packages/common-css/src/common-css.scss, packages/common-css/src/sap-busy-indicator.scss, packages/common-css/src/sap-margin.scss
Closes none
optimize the code for paddings and margins so that we don't need to handle RTL
=> fix(common-css): optimize paddings and margins usage [ci visual]

package.json, yarn.lock
=> chore(deps): theming-base-content 11.17.1 [ci visual]

.github/actions/bump-version/action.yml, .github/workflows/create-release.yml
fix the workflow for publishing the docs
=> chore(ci): fix the workflow for publishing the docs

packages/configuration/src/lib/previous-versions.ts
add link to version 0.37 documentation
=> docs: add link to version 0.37 documentation

packages/doc-ui/src/components/DocsPage/custom.scss, packages/styles/stories/Components/button/ai-button.example.html, packages/styles/stories/Components/button/button.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes none
add AI button to Button docs
=> docs(styles): add AI button [ci visual]

packages/configuration/src/lib/tags.ts, packages/styles/src/fundamental-styles.scss, packages/styles/src/prompt-input.scss, packages/styles/stories/Components/Forms/prompt-input/basic.example.html, packages/styles/stories/Components/Forms/prompt-input/prompt-input.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Add new AI Prompt Input component
=> feat(styles): introduce Prompt Input [ci visual]

packages/styles/src/form-item.scss, packages/styles/src/mixins/_mixins.scss, packages/styles/src/text.scss, packages/styles/src/textarea.scss, packages/styles/stories/Components/Forms/textarea/ai.example.html, packages/styles/stories/Components/Forms/textarea/textarea.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes none
Note: the row indicator requires JavaScript logic and that's why is not present in the example
=> feat(styles): add ai text highlight [ci visual]

package.json, yarn.lock
theming-base-content version 11.18.0
=> chore(deps): theming-base-content version 11.18.0 [ci visual]

packages/styles/src/form-item.scss, packages/styles/src/segmented-button.scss, packages/styles/stories/AI/Patterns/ai-guided-prompt/ai-guided-prompt.example.html, packages/styles/stories/AI/Patterns/ai-guided-prompt/ai-guided-prompt.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes none
- added Guided Prompt  pattern to the docs (no CSS needed that's why it's a fix)
- added vertical spacing between form items (that's why the PR is a fix)
=> fix(styles): add Guided Prompt pattern [ci visual]

.github/actions/nodejs/action.yml, .github/workflows/chromatic.yml, .github/workflows/create-release.yml, .github/workflows/on-pull.yml
=> chore(ci): update gh actions versions

yarn.lock
=> chore(ci): update yarn.lock

.github/actions/nodejs/action.yml, netlify.toml
update the yarn install command
=> chore(ci): update the yarn install command

.yarnrc.yml
=> test(ci): add verbose to yarn install

packages/styles/stories/AI/Patterns/ai-acknowledgment/ai-acknowledgment.example.html, packages/styles/stories/AI/Patterns/ai-acknowledgment/ai-acknowledgment.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
=> docs(styles): add AI Acknowledgment pattern [ci visual]

packages/styles/src/ai-writing-assistant-versioning.scss, packages/styles/src/ai-writing-assistant.scss, packages/styles/src/form-label.scss, packages/styles/src/fundamental-styles.scss, packages/styles/src/textarea.scss, packages/styles/src/toolbar.scss, packages/styles/stories/AI/Patterns/ai-writing-assistant-toolbar/ai-writing-assistant-toolbar.example.html, packages/styles/stories/AI/Patterns/ai-writing-assistant-toolbar/ai-writing-assistant-toolbar.stories.js, packages/styles/stories/AI/Patterns/ai-writing-assistant/ai-writing-assistant-inputs.example.html, packages/styles/stories/AI/Patterns/ai-writing-assistant/ai-writing-assistant.example.html, packages/styles/stories/AI/Patterns/ai-writing-assistant/ai-writing-assistant.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes none
- new AI Writing Assistant Pattern (includes SCSS code)
- new AI Writing Assistant Versioning Pattern (includes SCSS code)
- Form Label: new `.fd-form-label--stand-alone` class
- Toolbar: new `.fd-toolbar--ai` class
=> feat(styles): introduce AI Writing Assistant

.github/actions/nodejs/action.yml, .yarnrc.yml, netlify.toml, package.json, yarn.lock
=> chore(ci): yarn 4.4.1 migration

packages/styles/src/_avatar-variables.scss, packages/styles/stories/Components/avatar-group/group-type-vertical.example.html, packages/styles/stories/Components/avatar-group/group-type.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/5593
Overlap for XS Avatar Group changed from -0.75rem to -0.5rem.
=> fix(styles): update the spacing for XS Avatar Group [ci visual]

package.json, yarn.lock
=> chore(deps): update cssnano v.7 [ci visual]

packages/styles/src/popover.scss, packages/styles/src/theming/sap_fiori_3.scss, packages/styles/src/theming/sap_fiori_3_dark.scss, packages/styles/src/theming/sap_fiori_3_hcb.scss, packages/styles/src/theming/sap_fiori_3_hcw.scss, packages/styles/src/theming/sap_fiori_3_light_dark.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcw.scss
added background-color for popover when closeOnOutsideClick is false
=> feat(styles): added background styling for closeOnOutsideClick [ci visual]

packages/styles/src/illustrated-message.scss, packages/styles/stories/Components/illustrated-message/dialog.example.html, packages/styles/stories/Components/illustrated-message/dot.example.html, packages/styles/stories/Components/illustrated-message/illustrated-message.stories.js, packages/styles/stories/Components/illustrated-message/spot.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
BREAKING CHANGE: added a container element around illustration and figcaption, added a responsive container
Closes none
- update the component to latest design
- code improvements
=> fix(styles): refactor Illustrated Messages to latest design [ci visual]

packages/styles/src/notification.scss
Closes none
add option to have Message strip in individual notifications, not just in groups
=> fix(styles): add container for Message Strip in Notifications 

packages/styles/stories/Components/notification/notification.stories.js
fix lint error notification story name
=> chore: fix lint error

package.json, packages/styles/src/icon-tab-bar.scss, packages/styles/src/mixins/button/_button-types.scss, packages/styles/src/theming/common/button/_sap_fiori.scss, packages/styles/src/theming/common/button/_sap_fiori_hc.scss, packages/styles/src/theming/common/button/_sap_horizon.scss, packages/styles/src/theming/common/button/_sap_horizon_hc.scss, packages/styles/src/theming/common/checkbox/_common.scss, packages/styles/src/theming/common/checkbox/_sap_fiori_hc.scss, packages/styles/src/theming/common/checkbox/_sap_foiri.scss, packages/styles/src/theming/common/checkbox/_sap_horizon.scss, packages/styles/src/theming/common/checkbox/_sap_horizon_hc.scss, packages/styles/src/theming/common/radio/_common.scss, packages/styles/src/theming/common/radio/_sap_fiori.scss, packages/styles/src/theming/common/radio/_sap_fiori_hc.scss, packages/styles/src/theming/common/radio/_sap_horizon.scss, packages/styles/src/theming/common/radio/_sap_horizon_hc.scss, yarn.lock
theming-base-content version 11.19.0
require adoption of new params as per the [link](https://github.com/SAP/theming-base-content/releases/tag/11.19.0)
=> chore(deps): theming-base-content version 11.19.0 [ci visual]

packages/styles/stories/BTP/tool-header/tool-header.stories.js
=> docs(styles): deprecate btp tool header

packages/styles/src/fundamental-styles.scss, packages/styles/src/panel.scss, packages/styles/stories/Components/panel/fixed-height-content.example.html, packages/styles/stories/Components/panel/fixed.example.html, packages/styles/stories/Components/panel/panel.stories.js, packages/styles/stories/Components/panel/sticky-header.example.html, packages/styles/stories/Components/panel/transparent.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
part of https://github.com/SAP/fundamental-styles/issues/5775
- update Panel to use CSS variables 
- add sticky header
=> fix(styles): update Panel and add sticky header [ci visual]

.github/actions/bump-version/action.yml, .github/actions/generate-conventional-release-notes/action.yml, .github/actions/get-version/action.yml, .github/actions/npm-publish/action.yml, .github/actions/release-tags/action.yml
fix bump-versio action - revert to node20
=> chore: fix bump-versio action

.stylelintrc.json, README.md, packages/styles/README.md, packages/styles/package-config.ts, packages/styles/src/theming/sap_fiori_3_set.scss, packages/styles/src/theming/sap_horizon_set.scss, packages/styles/theming/sap_fiori_3_set.scss, packages/styles/theming/sap_horizon_set.scss, projects.js
=> feat(styles): add theming sets

packages/styles/src/button.scss, packages/styles/src/theming/common/button/_sap_fiori.scss, packages/styles/src/theming/common/button/_sap_fiori_hc.scss, packages/styles/src/theming/common/button/_sap_horizon.scss, packages/styles/src/theming/common/button/_sap_horizon_hc.scss, packages/styles/stories/Components/button/badge-on-button.example.html, packages/styles/stories/Components/button/button.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes none
- added Attention Badge
- Updated the Button spacing on the right when there's a badge (should be 4px, was 8px)
- Updated CSS variables and removed local variables used for theming
=> fix(styles): update Button Badge [ci visual]

packages/styles/src/button.scss, packages/styles/src/mixins/button/_button-types.scss, packages/styles/src/segmented-button.scss, packages/styles/src/theming/common/button/_sap_fiori.scss, packages/styles/src/theming/common/button/_sap_fiori_hc.scss, packages/styles/src/theming/common/button/_sap_horizon.scss, packages/styles/src/theming/common/button/_sap_horizon_hc.scss, packages/styles/stories/Components/segmented-button/button.stories.js, packages/styles/stories/Components/segmented-button/segmented-button-vertical.example.html, packages/styles/stories/Components/segmented-button/segmented-button.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes none
- cleanup local CSS variables used for theming (now using the vars from the package)
- update Segmented Button examples to show multiple selections are possible
=> fix(styles): update Button and examples [ci visual]

package.json, yarn.lock
=> chore(deps): theming-base-content v11.25.0 [ci visual]

packages/styles/stories/Components/avatar/avatar.stories.js
=> chore: cleanup avatar story

package.json, yarn.lock
=> chore(deps): chromatic v. 11.20.2 [ci visual]

netlify.toml, package.json
=> chore(deps): yarn 4.5.1 [ci visual]

.github/actions/nodejs/action.yml, .github/workflows/create-release.yml, .github/workflows/on-pull.yml
=> chore(ci): bump action versions

packages/styles/src/navigation-list.scss, packages/styles/src/theming/common/navigation-list/_sap_fiori.scss, packages/styles/src/theming/common/navigation-list/_sap_fiori_hc.scss, packages/styles/src/theming/common/navigation-list/_sap_horizon.scss, packages/styles/src/theming/common/navigation-list/_sap_horizon_hc.scss, packages/styles/src/theming/sap_fiori_3.scss, packages/styles/src/theming/sap_fiori_3_dark.scss, packages/styles/src/theming/sap_fiori_3_hcb.scss, packages/styles/src/theming/sap_fiori_3_hcw.scss, packages/styles/src/theming/sap_fiori_3_light_dark.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcw.scss, packages/styles/src/user-menu.scss, packages/styles/stories/Components/user-menu/default.example.html, packages/styles/stories/Components/user-menu/mobile.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/5718
- updates User menu to latest specs
=> fix(styles): update User menu for VEGA

packages/styles/src/shellbar.scss, packages/styles/src/theming/common/shellbar/_sap_fiori.scss, packages/styles/src/theming/common/shellbar/_sap_fiori_hc.scss, packages/styles/src/theming/common/shellbar/_sap_horizon.scss, packages/styles/src/theming/common/shellbar/_sap_horizon_hc.scss, packages/styles/src/theming/sap_fiori_3_light_dark.scss, packages/styles/stories/Components/shellbar/optional-items.example.html, packages/styles/stories/Components/shellbar/overflow-toolbar.example.html, packages/styles/stories/Components/shellbar/primary.example.html, packages/styles/stories/Components/shellbar/responsive-paddings.example.html, packages/styles/stories/Components/shellbar/responsiveness.example.html, packages/styles/stories/Components/shellbar/shellbar.stories.js, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes https://github.com/SAP/fundamental-styles/issues/5729
This PR also brings the latest changes (from Dec 19, 2024) for ShellBar
=> fix(styles): restyle Shellbar search to match latest UXC design, ShellBar updates

.github/actions/nodejs/action.yml, netlify.toml, package.json, yarn.lock
=> chore(deps): yarn 4.6

packages/configuration/src/lib/previous-versions.ts
=> docs: add link to 0.38 docs

packages/styles/src/settings.scss, packages/styles/stories/Components/settings/md.example.html, packages/styles/stories/Components/settings/sm.example.html, packages/styles/stories/Components/settings/xl-default.example.html, packages/styles/stories/Components/settings/xl.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
=> fix(styles): settings updates after ngx implementation [ci visual]

.github/dependabot.yml
=> chore(ci): update dependabot.yml

vite.config.ts
=> docs: fix storybook [ci visual]

.github/actions/bump-version/index.js, .github/actions/generate-conventional-release-notes/index.js
=> chore: revert imports

.github/actions/bump-version/index.js, .github/actions/generate-conventional-release-notes/index.js
=> chore: try to fix require

.github/actions/bump-version/index.js, .github/actions/generate-conventional-release-notes/index.js
=> chore: try 4

.github/actions/bump-version/index.js, .github/actions/generate-conventional-release-notes/index.js
=> chore: try 5

.github/actions/bump-version/index.js
=> chore: try6

packages/styles/src/mixins/list/_list-subline.scss, packages/styles/src/panel.scss, packages/styles/src/user-menu.scss, packages/styles/stories/Components/user-menu/default.example.html, packages/styles/stories/Components/user-menu/mobile.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
Closes none
- truncation rules for User Menu
- CSS changes that came up during the ng implementation
- handles the case where list with 3 lines (List with Subline) has only 2 lines
=> fix(styles): updates related to User Menu implementation [ci visual]

packages/configuration/src/lib/previous-versions.ts
=> docs: bump docs

packages/cx/src/_nested-list.scss, packages/cx/src/side-nav.scss, packages/cx/stories/Components/cx-side-navigation/cosy-narrow.example.html, packages/cx/stories/Components/cx-side-navigation/wrapping-long-text.example.html
Closes none
no breaking changes adoption of the new Side Nav design for CX Side Nav
=> fix(styles): restyle CX side nav [ci visual]

packages/cx/src/side-nav.scss
Closes none
for some reason this change didn't go into the last PR
=> fix(styles): remove again the hover in Side Nav narrow state [ci visual]

packages/styles/src/facet.scss
Closes https://github.com/SAP/fundamental-styles/issues/6005
change the font family and size of Facet's title
=> fix(styles): style properly the title of facets [ci visual]

package.json, yarn.lock
=> chore(deps): theming-base-content 11.29.0 [ci visual]

packages/styles/src/bar.scss, packages/styles/stories/Components/bar/bar.stories.js, packages/styles/stories/Components/bar/default.example.html, packages/styles/stories/Components/bar/floating-footer.example.html, packages/styles/stories/Components/bar/footer.example.html, packages/styles/stories/Components/bar/header-with-subheader.example.html, packages/styles/stories/Components/bar/header.example.html, packages/styles/stories/Components/bar/responsive.example.html, packages/styles/stories/Components/bar/subheader.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
- a11y: role and aria-label for the parent element
- CSS: text options in the header and the footer
- documentation updates
=> fix(styles): design and a11y updates for Bar [ci visual]

packages/styles/src/resizable-card-layout.scss
Closes none
Bring here the CSS that was needed in fund-ngx to position properly the resize handle.
=> fix(styles): minor update for the resize handle in Card Layout

netlify.toml, package.json
=> chore(deps): update yarn v 4.9

packages/configuration/src/lib/previous-versions.ts
=> docs: add doc version 0.40

packages/styles/src/object-status.scss, packages/styles/stories/Components/object-status/clickable-object-status.example.html, packages/styles/stories/Components/object-status/generic-indication-colors.example.html, packages/styles/stories/Components/object-status/icon-and-text.example.html, packages/styles/stories/Components/object-status/icon.example.html, packages/styles/stories/Components/object-status/inverted-indication-secondary.example.html, packages/styles/stories/Components/object-status/inverted-indication.example.html, packages/styles/stories/Components/object-status/inverted-states.example.html, packages/styles/stories/Components/object-status/inverted.example.html, packages/styles/stories/Components/object-status/large-object-status.example.html, packages/styles/stories/Components/object-status/object-status.stories.js, packages/styles/stories/Components/object-status/primary.example.html, packages/styles/stories/Components/object-status/text.example.html, packages/styles/stories/Components/object-status/truncate-example.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
added 2 visually hidden span elements serving the role of `aria-roledescription` and `aria-describedby`.
The links now are div elements with `role="button"` and `aria-roledescription`. `aria-describedby` is acheived by a visually hidden span element.
Before:
```
<span class="fd-object-status fd-object-status--indication-1">
<span class="fd-object-status__text">Dark Red</span>
</span>
```
After:
```
<span class="fd-object-status fd-object-status--indication-1">
<span class="fd-object-status__text">Dark Red</span>
<span class="fd-object-status__sr-only">Object Status</span>
<span class="fd-object-status__sr-only">Indication Color 1</span>
</span>
```
Clickable elements
Before:
```
<span class="fd-object-status …
```
=> fix(styles): add a11y updates for Object Status [ci visual]

packages/styles/src/form-group.scss, packages/styles/src/form-header.scss, packages/styles/src/form-label.scss, packages/styles/src/theming/sap_horizon.scss, packages/styles/src/theming/sap_horizon_dark.scss, packages/styles/src/theming/sap_horizon_hcb.scss, packages/styles/src/theming/sap_horizon_hcw.scss, packages/styles/stories/Components/Forms/checkbox/checkbox.stories.js, packages/styles/stories/Components/Forms/form-fieldset/form-fieldset.stories.js, packages/styles/stories/Components/Forms/form-grid/form-grid.stories.js, packages/styles/stories/Components/Forms/form-group/form-group.stories.js, packages/styles/stories/Components/Forms/form-group/group-header-in-form-grid.example.html, packages/styles/stories/Components/Forms/form-group/group-header.example.html, packages/styles/stories/Components/Forms/form-header/form-header.stories.js, packages/styles/stories/Components/Forms/form-header/primary.example.html, packages/styles/stories/Components/Forms/form-item/form-item.stories.js, packages/styles/stories/Components/Forms/form-item/primary.example.html, packages/styles/stories/Components/Forms/form-item/required.example.html, packages/styles/stories/Components/Forms/form-label/colon.example.html, packages/styles/stories/Components/Forms/form-label/disabled.example.html, packages/styles/stories/Components/Forms/form-label/form-label.stories.js, packages/styles/stories/Components/Forms/form-label/primary.example.html, packages/styles/stories/Components/Forms/form-label/required.example.html, packages/styles/stories/Components/avatar-group/individual-type-vertical.example.html, packages/styles/stories/Components/quick-view/popover.example.html, packages/styles/tests/__snapshots__/styles.test.ts.snap
- covers the following components: Field Set, Form Grid, Form Group, Form Header, Form Item and Form Label 
- reviewed and improved documentation
- reviewed and  improved examples for a11y 
- adopted latest design for Form Header
- added disabled styling for form labels
=> fix(styles): add improvements for Field Set, Form Grid, Group, Header, Item and Label 

packages/styles/src/panel.scss, packages/styles/stories/Components/panel/panel.stories.js, packages/styles/stories/Components/panel/transparent.example.html
Closes https://github.com/SAP/fundamental-styles/issues/6132
=> fix(styles): update Panel spacings to accommodate Title focus 

packages/cx/src/_nested-list.scss, packages/cx/stories/Components/cx-side-navigation/cozy-wide-icons.example.html, packages/styles/stories/BTP/Navigation/vertical/navigation-legacy.example.html, packages/styles/stories/BTP/Navigation/vertical/navigation-popup.example.html, packages/styles/stories/BTP/Navigation/vertical/navigation-snapped.example.html, packages/styles/stories/BTP/Navigation/vertical/navigation.example.html, packages/styles/stories/BTP/Navigation/vertical/navigation.stories.js, packages/styles/stories/Components/side-navigation/collapsed.example.html, packages/styles/stories/Components/side-navigation/expanded-add.example.html, packages/styles/stories/Components/side-navigation/expanded.example.html, packages/styles/stories/Components/side-navigation/side-navigation.stories.js
Closes https://github.com/SAP/fundamental-styles/issues/6138
- update Side Nav examples with sample data for consistency
- add modifier class for Quick Action in CX Side Navigation
=> fix(styles): update Side Navigation examples [ci visual]

package.json, yarn.lock
=> chore(deps): theming-base-content 11.32.1 [ci visual]

packages/styles/src/mixins/_forms.scss, packages/styles/src/popover.scss, packages/styles/src/select.scss, packages/styles/src/shellbar.scss, packages/styles/src/theming/common/shellbar/_sap_horizon.scss, packages/styles/src/theming/common/shellbar/_sap_horizon_hc.scss, packages/styles/stories/Components/select/as-form-item.example.html, packages/styles/stories/Components/select/blank.example.html, packages/styles/stories/Components/select/cozy.example.html, packages/styles/stories/Components/select/disabled.example.html, packages/styles/stories/Components/select/item-grouping.example.html, packages/styles/stories/Components/select/larger-select.example.html, packages/styles/stories/Components/select/match-select-popover-body-size.example.html, packages/styles/stories/Components/select/mobile-mode.example.html, packages/styles/stories/Components/select/no-wrapping.example.html, packages/styles/stories/Components/select/readonly.example.html, packages/styles/stories/Components/select/select.stories.js, packages/styles/stories/Components/select/semantic-states.example.html, packages/styles/stories/Components/select/text-wrapping.example.html, packages/styles/stories/Components/select/two-column.example.html, packages/styles/stories/Components/select/two-columns-and-icons.example.html
Closes https://github.com/SAP/fundamental-styles/issues/6167
- cleanup and refactor for Select code
- updated all examples with proper aria roles and attributes for a11y
1. updated markup for grouping list items
2. new aria-roles and attributes for the select control and list
=> fix(styles): design and a11y updates for Select component [ci visual]
