package-lock.json
package.json

Need to bump standard version to 4.4.0 to be consistent with other fundamental-* repos and for the auto generated release notes to work. 
Also fixed a spacing inconsistency in browserlist.

chore: bump standard version for release notes compatibility

---

scss/components/date-picker.scss

Closes SAP/fundamental-styles#8
There is no example of this in the documentation, but padding was not applied to the popover body when using popper.js and a date picker. This PR fixes this. If there's any issues or concerns please let me know as this is my first non-fundamental-ngx contribution in quite some time 😅

fix: fixed datepicker popper styling

---

package-lock.json
package.json

In looking at the breaking changes for this pr: https://github.com/SAP/fundamental-styles/pull/22 and https://github.com/SAP/fundamental-styles/pull/24, I realized we are no longer using "del" package  or "yargs" anywhere and we can remove it from the dependency tree.

chore: remove del and yargs dependencies

---

scss/components/breadcrumb.scss

Closes SAP/fundamental-styles#12
set bottom margin to 0 in breadcrumb component to avoid overlapping of components.

fix: fixed negative bottom margin

---

components/label.scss
test/resources/theme-ugly.css

Closes #102 
This PR contains the self-contained styling for the label component. 
This PR is part of the larger task of making all components self-contained.

fix: self-contained styles for label component

---

components/image.scss

Closes SAP/fundamental-styles#124
This PR contains the self-contained styling for the image component.

fix: added self-contained styles for image component

---

components/token.scss
test/resources/theme-ugly.css
test/templates/token/index.njk

Closes #132 
This PR contains the self-contained styling for the token component.

fix: Added self-contained style for token component

---

components/link.scss
scss/components/link.scss
scss/mixins/_mixins.scss

Closes #101 
This PR contains the self-contained styling for the link component. 

fix: added self-contained style for link component

---

scss/components/alert.scss
scss/components/side-nav.scss
scss/components/status-label.scss
scss/mixins/_mixins.scss
test/resources/unnormalize.css

After checking pages with the "Un-normalize" playground toggle, it was found that a number of components were allowing styles to bleed in.  This adds padding, margin and border resets to the `fd-reset` mixin.
Once that was in place, there were a few components that were adjusted to prevent the bleed in of external styling.  They were:
* Alert
* Link (no additional changes were necessary after the `fd-reset` mixin was adjusted)
* Side Nav
* Status Label (changed the modifier classes to be sibling classes rather than standalone)

fix: Added padding, margin and border to fd-reset mixin

---

components/inline-help.scss

Closes SAP/fundamental-styles#146
This PR contains the self-contained styling for the inline-help component.

fix: added self contained style for inline-help component

---

docs/js/search.json

Remove `summary` parameter from search.json template. This is not needed and often breaks search functionality due to quotes in summary content. 
* http://127.0.0.1:4000/components/index.html
**Removed**
* removed summary parameter from search.json template

docs: update search.json to remove summary

---

components/product-tile.scss
scss/components/product-tile.scss

Closes SAP/fundamental-styles#160
This PR contains the self-contained styling for the product-tile component.

fix: added self-contained style for product-tile component 

---

components/tabs.scss
scss/components/tabs.scss

Closes SAP/fundamental-styles#166
This PR contains the self-contained styling for the Tabs component.

fix: added self-contained style for Tabs component

---

README.md

previous slack link required admin approval to join the workspace

fix: update slack readme link

---

test/resources/layout.css

when "RTL" is selected, the label is not staying next to the checkbox. See 
inline-block keeps them together. see

fix: playground: use inline block to keep checkbox with label in rtl mode

---

.github/mergeable.yml

edits mergeable title regex to accept `chore(` as well as `chore:`. Edit the `or` block so it doesn't require min 2 AND one of the listed required reviewers.

chore: edit mergeable regex for dependabot prs

---

docs/_includes/display-component.html
docs/_sass/_docs-display-component.scss
docs/css/customstyles.css

In https://github.com/SAP/fundamental-styles/pull/227 I changed the selector from `input` element to class `fd-toggle__input` and forgot to update the docs site where we are using them in our display containers.
Also removed some unnecessary css overrides.
Before:
After:

docs: toggle on docs site missing fd-toggle__input class

---

docs/_sass/_docs-display-component.scss
docs/pages/layouts/page-layout.md

fixes #283 
1. remove bleeding styles to page from documentation
2. replace `<article>` with `<main>` in the documentation

fix: Remove bleeding styles to page from documentation

---

scss/components/input-group.scss

Changed the class `fd-input-group__input` to be a descendant selector of `fd-input-group` so the specificity will be applied.
n/a

fix: Input sizing in input groups

---

.github/mergeable.yml

Removing the approvals check from Mergeable -- GitHub already does this.  And when Mergeable does this, it marks all open PRs with a ❌, which makes it look like the build failed or there are other issues with the branch.  It's nice to see green checks and yellow dots when branches are successfully built or being built.

chore: Remove approvals from mergeable

---

src/mixins/_vars.scss

Closes https://github.com/SAP/fundamental-styles/issues/348
I added statements to `var` mixins, because the empty commas were causing errors on angular's compiler.

fix: Not allow to put empty comma in vars

---

src/breadcrumb.scss

*Description*
After the adoption of self-contained styles in Fundamental-ngx the Breadcrumb links have border-bottom `1px solid #0a6ed1` due to the fact that the `border-style: none;` rule is not taken into account. Adding a more specific rule `border-bottom-style: none;` fixes the issue (the border disappears).

fix:breadcrumb link border bottom style none fix

---

docs/_config.yml
docs/_data/sidebars/left-navigation-sidebar.yml
docs/_includes/topnav.html
docs/index.html
docs/pages/getting-started.md
docs/pages/resources/fundamentals-libraries.md
docs/pages/resources/index.md

changes:
- remove SAP from the name of the library(per recommendation)
- add links to the implementation libraries on the landing documentation page

docs: remove SAP from the library name

---

docs/pages/components/product-switch.md
src/product-switch.scss

Closes SAP/fundamental-styles#381
In mobile mode, the RTL support for the Product Switch component shows the icon on the right but the text stays on the left. The margin between the icon and the text should go to the left.

fix: add rtl support for mobile mode

---

src/time.scss

fix: fix the width issue of time after refactoring forms

---

src/form-label.scss

none
Checkbox + Radio-Input labels had `cursor: text`. Now they have `cursor: pointer;`

fix: Fixed cursor of checkboxes/radio—buttons with label

---

docs/js/customscripts.js

Closes SAP/fundamental-styles#484
Closes SAP/fundamental-styles#479
ES6 specification is not supported in IE 11 and ended up in displaying error in console. After fix, aria-controls which are handled by jquery works fine

docs: removed functionality of es6 because it brokes IE and fixed 2 issues

---

src/menu.scss

Closes SAP/fundamental-styles#466
Bug occurred due to fixed span height.
Fixed white background of an icon has been changed to transparent.
Merge also includes a little cleanup in `fd-menu__addon-before`, `fd-menu__list` and `fd-menu__group`.
Alignment:
Hover:
Alignment:
Hover:

fix: Miss-aligned menu icons

---

src/shellbar.scss

Closes SAP/fundamental-styles#467
Line height changed to match a character which went out of boundaries 
It is fixed but I can't upload the screenshot (github returns error)

fix: line height changed to match the font

---

docs/_sass/_docs-display-component.scss
src/inline-help.scss
src/mixins/_mixins.scss

I did some smoke tests on firefox, there is list of things, that was wrong
*  Docs - Width of fd-tile__content was exceeded, when there was overflow
* Scss - Height of the icon inside inline-help was not middle aligned
* Scss - There as bug with `moz-focus-inner`, which provided double focus on button elements.
>

fix: latest firefox bugs

---

docs/_data/sidebars/left-navigation-sidebar.yml
docs/pages/components/busy-indicator.md
docs/pages/layouts/shell-layout.md

On smoke tests, I found some of components examples doesn't look good on Firefox. So:
* (All) I removed `multi-input` link from component group - it was redirecting to wrong url. Place for `multi-input` is in Patterns section.
* ShellLayout example with `Alert` wasn't up to date with latest changes.  
* Busy Indicator - Flex wasn't good idea there, `<br>` Didn't work inside `flex` on firefox
>

docs: Example fixes on firefox

---

docs/js/customscripts.js

Closes SAP/fundamental-styles#524
IE11 does not support `.remove()` method on `Element` object.
Using jQuery to remove element solves the problem.

fix: Cannot close example alert on IE11

---

src/input-group.scss

Closes SAP/fundamental-styles#538
Fixes the sizing in IE11 for input groups with time picker and date picker.
Currently no screeenshots, using netlify for IE testing
>

fix: input-group-pickers

---

docs/js/customscripts.js
docs/pages/components/input-group.md

Closes SAP/fundamental-styles#530
IE11 does not support `stepUp` and `stepDown` methods on input element.
Separate function for this case has been created.

fix: Number input increment/decrement not working on IE11

---

src/form-input-message-group.scss

Closes https://github.com/SAP/fundamental-styles/issues/528
So after some research, I came up to think, that `flex: 1` on IE11 cause problem with message-group container. It's changed to `display:flex`. Now also the example looks better, before the container was interpreted like it has `0px height`

fix: Remove flex property from input-message-group IE11

---

src/mixins/_forms.scss

Closes https://github.com/SAP/fundamental-styles/issues/527
Problem with IE11 and the rgba values are well known. On our case, IE11 doesn't like variables, so it's taken in callback and transformed to raw value. Unfortunately one of the variables has rgba() value. The solution is to add hardcoded value, in case the variable/callback are not supported by explorer.

fix: Add hardcoded RGBA calue for readonly on forms

---

src/form-select.scss

Closes https://github.com/SAP/fundamental-styles/issues/529
there is removed dropdown default icon

fix: Remove IE11 Dropdown default icon

---

src/input-group.scss

Closes https://github.com/SAP/fundamental-styles/issues/554
We had some bug on input-group component, which was caused by setting `auto` property for `flex-basis`. It was mostly because of IE11, which doesn't have any native `min-width` for `inputs` 
>
IE11:
All browsers:
IE11:
All browsers:

fix: (InputGroup) Add min-width property only for ie10+, fix addon truncation

---

src/product-switch.scss

Closes SAP/fundamental-styles#531
IE11 has problem with `flex-basis` value. For some reason IE11 doesn't respect elements `height` value if `flex-basis: 25%` is used.
Since in mobile mode products are aligned as a list, my solution is changing to `flex-basis: auto` on mobiles.
To be honest product-switch styles are a little bit messy. I'd recommend small refactor in the future.

fix: Broken product switch on mobile devices - IE11

---

docs/pages/components/table.md

Closes SAP/fundamental-styles#534
Table header with context menu used wrong context menu implementation.
Documentation example has been fixed.

fix: Misaligned check in table header context menu (documentation)

---

docs/pages/patterns/multi-input.md

There was wrong checkbox usage inside multi-input pattern.
>

docs: Change usage of checkbox in multi input example

---

src/input-group.scss

https://github.com/SAP/fundamental-ngx/issues/1811
The button now has got `border-radius: 0` 
The container of button got `1px` border-radius, now it doesn't have white spaces on top/bottom.
This fix was needed mostly for NGX, because after compilation `border-radius` had wrong values.
>

fix: (InputGroup) Change border-radius applying

---

docs/_includes/demo-page-components/alert-app-overlay.html
docs/pages/components/alert.md

Closes SAP/fundamental-styles#582
Link now points to correct page section.
Alert component used in alert demo has been updated to newest styles.
(reopened #606 because of Travis bug)

docs: correct alert navigation link in the documentation

---

docs/pages/components/table.md
src/textarea.scss

Closes SAP/fundamental-styles#597
This PR:
- updates `Table` component documentation switching to new implementation of `checkbox` component
- Changes `white-space` property of `textarea` component to `pre-wrap`, because of Firefox not supporting default white-space wrapping in textareas.
(reopened #607 because of Travis bug)

fix: Update table with checkbox docs example | Fix text-wrapping in textarea on Firefox

---

docs/pages/components/form.md

Closes SAP/fundamental-styles#616
Radio buttons from "RLT" section had the same id property values as radio buttons in "Interaction States" section, thereupon changes on radios from "RTL" were reflected in "Interaction States".
Changing id property values to unique ones solved the problem.

fix: replace non-unique radio button id property values

---

docs/pages/components/identifier.md
docs/pages/components/image.md
docs/pages/components/popover.md
docs/pages/components/shellbar.md
docs/pages/components/table.md
docs/pages/components/tile.md

The images in the documentation were loaded in two different ways. We agreed to use only one approach which is using `https://placeimg.com` online library. For this reason the "static" images were replaced by `https://placeimg.com/400/400/nature` dynamic images.

docs: apply unified approach for loading images in the documentation

---

src/tabs.scss

There is removed part of invalid code on tabs.
Following documentation, last item should not have different styling than other elements. Only first tab shouldn't have spacing.
It also caused some bugs on RTL mode, when latest element hadn't spacing
>

fix: Remove invalid code, correct RTL for tabs

---

netlify.toml

avoid building netlify for dependabot PRs

chore:do not build netlify for dependabot PRs

---

src/_product-menu.scss
src/mixins/_mixins.scss

N/A
A background-image from global styling can creep into the fundamental control:

fix: Specify background-image: none; for product-menu control

---

docs/pages/components/form.md
src/form-message.scss
src/popover.scss

I added a modifier class in Popover component to handle the case when we have input group with messages. 
- The `fd-popover__control` is no longer used at the same level as the `fd-input` in the documentation.
- The `fd-popover__body` is no longer used at the same level as the `fd-message` in the documentation.
Because `fd-popover` scss file was imported first in `src/fundamental-styles.scss` the problem wasn't noticeable. We shouldn't rely on the order of file import. 
Please take a look at the code and we will discuss it tomorrow

fix: refactor form-message inside popover

---

src/popover.scss

This PR removes the input:last-child rule from popover control. The margin-bottom of the input should be there for a11y purpose (to achieve the 44px touchable area).

fix: remove input:last-child rules from popover control

---

src/notification.scss

part of [660](https://github.com/SAP/fundamental-styles/issues/660)
The RTL support for Notification indicator was missing
Default:
RTL:

fix: add rtl support for Notification indicator

---

src/tabs.scss

Closes https://github.com/SAP/fundamental-styles/issues/668
There are changed some margins/paddings on RTL mode for tabs component. Mostly on `:first-child`
>

fix: (tab) Add fully RTL support for tabs

---

docs/_sass/_docs-component-list.scss

Closes SAP/fundamental-styles#671
Update the name of CSS class used to position Switch component image on component grid.

docs: Update CSS class used to position Switch image on component grid

---

src/bar.scss

This PR adds `max-width: 100%` properties to Bar component sections `__left` `__middle` `__right` and sections `__element`.
This modification is needed to detect when the growth of the Bar elements started overflowing its parent element and limit flex growth behavior.

fix: add max-width to bar elements

---

src/breadcrumb.scss

Closes SAP/fundamental-styles#656
Breadcrumb element had additional margins on RTL mode.

fix: Remove additional spacing on Breadcrumb element on RTL

---

src/bar.scss

I added overflow rules to handle the case when a Bar element contains text only. These rules apply in X and Y direction. 
>

fix: add overflow rules for bar-element

---

src/input-group.scss
src/input.scss

closes: https://github.com/SAP/fundamental-styles/issues/673
closes: https://github.com/SAP/fundamental-styles/issues/666
There was some troubles, on zoom in/out. Mostly because of rem units usage, for example
0.0625rem. Multiplying it by 90% for example, was changing size of particular elements.
IE11 also has that issues, but without even zooming.
Adding overflow: hidden, to containers elements, fixed it.
>
90%:
90%:

fix: (input/input-group) zooming in/out and IE11 issues

---

docs/pages/components/select.md

Closes https://github.com/SAP/fundamental-styles/issues/647
There is added mobile mode for select component. It's used with bar and dialog components.
>

fix: select mobile mode

---

docs/pages/patterns/combobox-input.md

Closes https://github.com/SAP/fundamental-styles/issues/649
There is added mobile mode for combobox example.
>

fix: (combobox) Add mobile mode for combobox

---

docs/pages/components/form.md
docs/pages/components/input-group.md
docs/pages/components/select.md
docs/pages/components/table.md
docs/pages/components/time.md
docs/pages/patterns/combobox-input.md
docs/pages/patterns/multi-input.md
src/checkbox.scss
src/mixins/_forms.scss
src/radio.scss
src/table.scss
test/templates/checkbox/index.njk
test/templates/input-group/index.njk
test/templates/input/index.njk
test/templates/radio/index.njk
test/templates/table/index.njk
test/templates/textarea/index.njk

Validation states need to be normalized. This is one option.. the other is to switch `success` to `valid` and `error` to `invalid`. Either way is fine with me, but we should be consistent. 
Breaking:
* `is-invalid` renamed to `is-error`
* `is-vaild` renamed to `is-success`
* `fd-table__row--valid` renamed to `fd-table__row--success`
No style changes

feat: normalize validation states

---

docs/pages/components/dialog.md

No major changes - cleanup the size examples to have the outer `fd-dialog` div + fix a typo about vertical padding.

docs: cleanup Dialog page

---

scripts/create-library-config.js

The script that copies fonts and icons for the documentation site accidentally has an incorrect path for icons - sending it to a fonts folder that doesn't exist.

docs: align icon copy script with other fonts

---

docs/_sass/_docs-display-component.scss
docs/pages/components/action-bar.md
src/action-bar.scss
test/templates/action-bar/component.njk

`<p class="fd-action-bar__description--with-backBtn">` 
changed to
`<p class="fd-action-bar__description fd-action-bar__description--back">`
We don't want to have 2 classes that were essentially the same thing, `fd-action-bar__description` and `fd-action-bar__description--with-backBtn`. With these changes, the majority of the css is in `fd-action-bar__description`, with the additional padding changes need when there is a back button are inside of `--back`.

feat: ActionBar: rework description class names

---

src/shellbar.scss
src/tokenizer.scss

Specificity of (0,0,0) is not allowing `fd-shellbar__button` to override `fd-button`, same with `fd-tokenizer__input` and `fd-input`. These `!important` allow these to override. This is not seen on the fundamental styles docs site due to the order in the fundamental-styles.css file.
In Fundamental-react:

fix: Tokenizer Input + Shellbar button improve specificity

---

docs/pages/components/tree.md

Closes SAP/fundamental-styles#739
Since fundamental-styles doesn't use popover JS, we need to use the popover--right modifiers so that it doesn't go off the page

docs: tree to make popover not go off of page

---

src/popover.scss

For a11y reasons the input field has margin-top and margin-bottom. When the input field is used as a popover control this causes the popover body to look "detached" from the control element. One example is the form-messages that are used for input validation. For this reason we added a modifier class to the popover `--input-message-group` that is removing the shadow (border) from the popover body and is bringing it 0.25rem top. In NGX we are using Popper.js and we need to apply the same rules as we did for the popover body in Fundamental-styles. We added the `--input-message-group` modifier class to the `__popper` but due to the fundamental-ngx Popover specific implementation we don't have the option to apply this class to the body. We are keeping the modifier class as it was since other …

fix: add input-message-group popover specific rules to popper elements

---

src/input-group.scss

Closes SAP/fundamental-styles#690
On IE11 when container uses `display: flex` `min-width` property is ignored. Basic width can be set using `flex-basis` property.
Before:
After:

fix: Minimal input width on IE11 

---

src/button.scss

[ngx #2110](https://github.com/SAP/fundamental-ngx/issues/2110)
Button text is now truncated (as described in fiori3) when button width is set

fix: added support for text truncation if button width is set

---

docs/pages/components/switch.md

remove semantic switch example - we will add this in NGX as a logic is required to replace the info label

docs: remove semantic switch example

---

docs/pages/components/loading-spinner.md

add deprecate label to loading spinner component page

docs: add deprecate label to loading spinner component page

---

docs/pages/components/switch.md

remove second semantic switch example

docs: remove second semantic switch example

---

src/shellbar.scss

Closes SAP/fundamental-styles# #802 
Use different arrow icon for menu

fix: use different icon for shellbar menu arrow

---

src/input-group.scss
src/mixins/_forms.scss

Closes https://github.com/SAP/fundamental-styles/issues/784
There is disabled parameter added, instead of hadcoded `0.4` value on forms

fix: Add theming parameter for disabled forms

---

src/input-group.scss
src/tokenizer.scss

There is removed `overflow: hidden` for readonly mode on input group and tokenizer__inner.
>

fix: Show readonly mode popover on multi input

---

docs/_includes/head_print.html
docs/_sass/_docs-component-list.scss
docs/_sass/_docs-general.scss
docs/_sass/_docs-main-content.scss
docs/_sass/_docs-side-nav.scss
docs/_sass/_docs-top-nav.scss
docs/_sass/_include-media.scss
docs/_sass/_landingPage.scss

Closes #732 and #409
This PR does the following for our docs page
1. Adds display to one of the breakpoint options, it is classified in Fiori but forgot to be added
2. Makes our grids responsive no matter the size of the page when the user wants to select a component or pattern. I made the grid go to 2 columns for sizing at a certain size. Also the images themselves shrink proportionately.
3. Makes the actual component responsive
4. Makes our navigation bar scrollable on ipad
5. Fix the hamburger menu size for all types

docs: responsive issue for both component pages and grid pages

---

docs/pages/components/dialog.md

Closes SAP/fundamental-styles#848
Add missing aria attributes to Dialog examples:
- `role="dialog"`
- `aria-modal`
- `aria-labelledby`

docs: Add aria attributes to Dialog examples

---

src/bar.scss

fixes: https://github.com/SAP/fundamental-styles/issues/755
There was some issue on popover using bar. The bar component didn't expand container.
>

fix: IE11 popover with bar component

---

docs/pages/components/form.md

fixes: https://github.com/SAP/fundamental-styles/issues/872
Due to limited native select styling, there is deprecation note for form select

docs: Add deprecated note for native select

---

docs/pages/components/action-bar.md
docs/pages/components/button.md
docs/pages/components/localization-editor.md
docs/pages/components/popover.md
docs/pages/components/shellbar.md
docs/pages/components/table.md
docs/pages/components/tile.md
docs/pages/components/tree.md
docs/pages/patterns/contextual-menu.md
docs/pages/patterns/multi-input.md
docs/pages/patterns/search-input.md

In the aftermath of: #855
New Menu implementation brings by default menu box-shadow. Examples using menu within popover need to be modified to prevent using double box shadows coming separately from Menu and Popover.

feat: Modify examples with doubled menu box shadow

---

CHANGELOG.md
ci-scripts/publish.sh

After upgrading standard-verison, only the changelog was updated in the first commit:
https://github.com/SAP/fundamental-styles/commit/6b4cc32fca9e7484205b3fff01defce8513a952b
This caused subsequent builds to fail. This is working fine in fundamental-react, so hopefully it was just a one off. 
It also works if you run the standard-version npm command with `--dry-run` enabled.

fix: debug standard version

---

ci-scripts/publish-rc.sh
package-lock.json
package.json

Rolling back to standard-version 4.2.0 didn't fix the problem (which is a good thing), adding a debug command to help figure out why only the changelog is being edited.

fix: debug standard version with debug command + bump back to 7

---

src/switch.scss

fixes: https://github.com/SAP/fundamental-styles/issues/869
It will prevent from cutting switch, if it doesn't fit on some browsers, or when it's squashed by content in flex container.

fix: Remove overflow:hidden from switch

---

docs/pages/components/list.md

Hiding the Selection List and List with Byline from documentation page in order to test the markup in NGX

docs: hide Selection List and List with Byline from documentation page

---

docs/_sass/_docs-general.scss
docs/pages/components/calendar.md

Closes SAP/fundamental-styles#952
Added responsive design for the documentation page of the Calendar

docs: add responsive design for Calendar doc page

---

.travis.yml

This run the test, lint and size commands in different containers:
They can run concurrently if builds are available.

chore: improve travis build time

---

docs/pages/patterns/date-picker.md

Pr removes empty th from datepicker

docs: removed empty th

---

src/action-bar.scss

Related to SAP/fundamental-styles#938
In IE 11 the actions section container was not expanding to fit the content.

fix: add fix for Action Bar actions not taking the whole width

---

src/popover.scss

Relates: https://github.com/SAP/fundamental-styles/issues/938
There is `-ms-grid` removed on dropdown, when fill mode is activated. We don't need to use this property, because width is 100%.
>

fix: Fix dropdown fill content no ie11

---

src/product-switch.scss

Relates https://github.com/SAP/fundamental-styles/issues/938
There is `flex` property changed on mobile mode, for columns
>

fix: Fix product switch mobile mode on ie11

---

src/list.scss

Relates: https://github.com/SAP/fundamental-styles/issues/938
There is added `flex-basis: auto` for alone titles. other percentage values for `flex-basis` are not well seen by IE11
>

fix: IE11 popover list overflow fix

---

src/bar.scss

fix: multi input second button fix

---

src/input.scss

https://github.com/SAP/fundamental-styles/issues/938
Removes the x for search inputs in IE on focus

fix: remove x for IE in input

---

src/shellbar.scss

Fix brings back popover for shellbar
**IMPORTANT**
Please double-check #968 because this PR revert one change made there.

fix: overflow removed in order to show popover

---

docs/_sass/_docs-general.scss
docs/pages/components/calendar.md
docs/pages/components/dialog.md
docs/pages/components/message-box.md
docs/pages/components/side-navigation.md

Removes styles which had an impact on list rtl mode

docs: removed styles which causes problem with rtl

---

src/dialog.scss

Moves the dialog resize to the left side in RTL mode

fix: dialog resize handle in RTL mode

---

docs/pages/components/select.md
test/templates/select/component.njk

Changes to Select component markup:
- The inner `<button>` causes an extra unnecessary tab stop. Arguably, the entire select component should be a singular clickable/tabbable button.
- Each individual `<li>` option is tabbable. They should instead be navigable via arrow keys (which would be coded in the implementation libraries) and use a roving tabindex.
- Change `li` to `div` for validation messages, as they should not be part of the list, as described in https://github.com/SAP/fundamental-styles/issues/712
No visual changes.
https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html
Opting to use a roving tabindex vs. aria-activedescendant: https://zellwk.com/blog/element-focus-vs-aria-activedescendant/

feat: Select component reference markup

---

src/shellbar.scss

Closes SAP/fundamental-styles#1026 
Shellbar button hovers styles should work with focus (for tabbing).  See https://github.com/SAP/fundamental-ngx/issues/2448

fix: add shellbar button hover styles to :focus as well

---

docs/pages/components/tile.md

A typo was causing some visual bugs in Slide Tile

docs: fix typo in Slide Tiles example

---

src/tile.scss

The last dot (page indicator) had a margin-right which is used as a separator for dots. Since it's the last item it does not need it.

fix: remove the spacing from the last page indicator

---

package.json

You cannot make commits with the precommit hook running storybook

fix: remove storybook from precommit

---

docs/_sass/_docs-top-nav.scss

Relates: https://github.com/SAP/fundamental-styles/issues/1060
Whenever there is `align-items: center` property, there should be `height` wiht `min-height`. To make flex work on IE11

docs: Fix header on IE11

---

docs/pages/patterns/multi-input.md

part of #1060 
Remove "show all" from most examples and add example showing use of filtering in input and "show all" text

docs: multi-input - add example showing use of "show all" text

---

docs/_data/tags.yml
docs/_layouts/page.html
docs/pages/components/button.md

Introduces tags on component doc pages

docs: introduce tags for component doc pages

---

docs/pages/components/list.md

The new List types were commented out in order to test the markup in NGX. Since we decided to add experimental tags to the new components we can not make them visible in the docs.

docs: make the new List types visible in the documentation

---

docs/pages/components/side-navigation.md
src/_nested-list.scss
src/side-nav.scss

- Updated SideNavigation to be a collection of `nav` sections for multiple groups
- Moved group header out of the list so it can be correctly associated as the title of each nav
- Added aria-hidden to icons except in compact mode, where aria-label was added to replace the text
- Added aria-label to utility menu as it does not have an option for a visible header
- Updated role of nested group header to `button` and removed `href` as it is not a link
- Added skip link to top of navigation list so users can skip to the next content if desired
No visual changes

feat: updates to SideNavigation for accessibility

---

.storybook/main.js
package-lock.json
package.json
stories/button/button.stories.js
stories/panel/panel.stories.js
stories/step-input/step-input.stories.js
stories/table/table.stories.js

Now story descriptions can be added like this:
```
/** Story description here **/
export const basic = () => (`<button>Test</button`);
```
instead of:
```
export const basic = () => (`<button>Test</button`);
basic.parameters = {
docs: {
storyDescription: 'Story description here'
}
};
```

chore: move to jsdocs for story descriptions

---

docs/pages/components/shellbar.md
src/shellbar.scss

part of #1060 
According to the shellbar designer, shellbar buttons should behave the same as transparent buttons, other than what is specifically mentioned in the shellbar specs.  This PR makes the button outline the same as transparent buttons
Worth noting that the outline was, by default, smaller than the user menu button circle, so I used outline-offset to slightly expand that.  Which is what they are doing in sapui5 for the same problem.  Maybe we can discuss alternative solutions

feat: shellbar button outlines should follow behavior of transparent buttons

---

src/button.scss
src/checkbox.scss
src/info-label.scss
src/mixins/_states.scss
src/object-status.scss
src/radio.scss

On Angular we had some issues, when used `&:empty` styling. Sometimes Angular under the hood puts some commented code, especially when there are `*ngIf` statements.
So there is a need to be able to put empty programatically, it can be done only, by passing additional class.

fix: Add fd-empty mixin, replace empty selectors

---

src/panel.scss

Panel expand button did not have RTL support

fix: add RTL for Panel expand button

---

docs/pages/components/table.md
src/table.scss

Our Pop in mode wasn't prepared for thead usage on it, There was a need to have some change on styles.
I also added headers to examples.
Selected border on last row is also fixed.
>

feat: Add Headers to popin mode, add fixes to selection borders

---

docs/pages/components/bar.md
docs/pages/components/calendar.md
docs/pages/components/dialog.md
docs/pages/components/generic-tile.md
docs/pages/components/menu.md
docs/pages/components/message-box.md
docs/pages/components/popover.md
docs/pages/components/switch.md
docs/pages/patterns/combobox-input.md
docs/pages/patterns/date-picker.md
docs/pages/patterns/multi-input.md
docs/pages/patterns/time-picker.md
src/bar.scss
stories/bar/__snapshots__/bar.stories.storyshot
stories/bar/bar.stories.js
stories/calendar/calendar.stories.js
stories/dialog/dialog.stories.js
stories/generictile/__snapshots__/generic-tile.stories.storyshot
stories/generictile/generic-tile.stories.mdx
stories/menu/__snapshots__/menu.stories.storyshot
stories/menu/menu.stories.js
stories/message-box/__snapshots__/message-box.stories.storyshot
stories/message-box/message-box.stories.js
stories/popover/popover.stories.js
stories/switch/switch.stories.js

fixes: #1114 
Renamed class `fd-bar--cosy` to `fd-bar--cozy`
Affected components:
- bar.md
- calendar.md
- dialog.md
- menu.md
- message-box.md
- popover.md
- switch.md
- combobox-input.md
- date-picker.md
- multi-input.md
- time-picker.md

feat: rename class fd-bar--cosy to fd-bar--cozy

---

docs/_sass/_landingPage.scss
docs/index.html

This PR removes the Newsletter from the doc page.
Also adds width 100% to the header and the main section for big screens

docs: remove Newsletter from the documentation page

---

stories/bar/bar.stories.js

Closes SAP/fundamental-styles#905
Add an example that shows how to add text to a bar. There are other examples using buttons alone, therefore it would be smart to have one with a text with a span

docs: add logo text example to bar

---

src/radio.scss

Closes SAP/fundamental-styles#1196
The inner circle (which is an icon) is not centered horizontally and vertically within the outer circle. This is due to the latest update of the icons. Paddings are added to the element to "force" the inner circle to go in the middle. 
>
Vertical alignment problem:
Horizontal alignment problem in compact mode:

fix: align horizontally and vertically the inner circle of Radio Button

---

src/shellbar.scss

Closes SAP/fundamental-styles#1223
The position of the counter notification in Shellbar was not correct (per Fiori3 specs) and in RTL the bell icon had a margin-left.

fix: set the correct position of the counter notification in Shellbar, RTL support

---

src/button-split.scss
stories/button/__snapshots__/button.stories.storyshot
stories/button/button.stories.js

Closes #1210
The PR brings fix for hover transparent split button
Check issue

fix: hover for transparent split button fixed

---

docs/pages/components/form.md
docs/pages/patterns/multi-input.md
src/checkbox.scss
stories/checkbox/__snapshots__/checkbox.stories.storyshot
stories/checkbox/checkbox.stories.js

Closes SAP/fundamental-styles#610
In previous implementation text inside `.fd-checkbox__label` was not able to properly overflow with ellipsis, because of `display: flex`;
This PR introduces new wrapper which should be used inside `.fd-checkbox__label` to provide proper overflow for the text values.

feat: Checkbox label ellipsis overflow

---

stories/time/time.stories.js

Closes #1152
PR brings fix for a11y issue.
markup changes:
* html semantic for `meridian` has been changed

feat: Time component html syntax changed to meet a11y criteria

---

src/table.scss

Closes SAP/fundamental-styles##1233
In RTL Pop-in Table had issues with the border of the last item. This PR fixes this issue
>

fix: add fix for Pop-in Table last item border in RTL

---

src/form-item.scss
src/form-label.scss
src/mixins/_forms.scss
stories/form-label/__snapshots__/form-label.stories.storyshot
stories/form-label/form-label.stories.js

closes: https://github.com/SAP/fundamental-styles/issues/870
There is added `--colon` modifier to every label.
Also spacing between asterix and label/colon is fixed
IE11 label is fixed
Also there is fixed required label on IE11

fix: label asterix and colon

---

src/button.scss

Closes SAP/fundamental-styles#1237
`[class*=sap-icon]` brings a reset which causes a problem in cases like `<button class="fd-button fd-button--menu sap-icon--cart"></button>` where the `sap-icon--cart` resets the styling specified in `fd-button fd-button--menu`. One of the solutions we came up is adding specificity achieved by `iconOverwrite` mixin in the case of Button component.

fix: add fix for Menu Button related to Icon reset

---

.storybook/preview-head.html

Part of: #1238
IE11 does not support ES6 features which were used to write checkbox documentation helpers.

chore: Rewrite checkbox documentation helpers to ES5

---

src/info-label.scss
src/mixins/_mixins.scss
stories/info-label/__snapshots__/info-label.stories.storyshot
stories/info-label/info-label.stories.js

Part of SAP/fundamental-styles#1238
This PR fixes one of the issues reported during [Defect Hunting](https://github.com/SAP/fundamental-styles/issues/1238) regarding Info Label with Icon missing border. 
- SCSS variables that were used only once in the code have been removed
- The `fd-info-label--only-icon` class has been removed. 

feat: refactor Info Label

---

src/checkbox.scss

Part of SAP/fundamental-styles#1263

fix: add fix for Checkbox tristate misalignment

---

src/mixins/_icons.scss
src/panel.scss

Part of: #1263
Alternative to #1268
Removes unnecessary styling causing icon misalignment.

fix: center Panel expand button icon

---

src/checkbox.scss
src/mixins/_forms.scss
src/radio.scss

Closes SAP/fundamental-styles#1197
No longer use `::after` selector for focus ring on Radio and Checkbox to avoid Chrome crashes.

fix: focus ring on radio and checkbox

---

.storybook/custom/custom.scss

Closes: #1291
Page headers had a `before` pseudo-element which was overflowing page content preventing user from interaction with covered page elements.
I'm not sure what was the purpose to introduce this styling, but I don't see a value, so my proposition is just to remove it.

chore: Remove page header overflow

---

.gitignore
package-lock.json
package.json

Related Issue
Closes #1204
Description
PR migrate std version to 8.0.2 and upgrades nodejs ver to 12.18.2 in order to fix std versions for styles.
PR brings a nodejs script as a workaround till official response and actions are taken by owner of standard-version liblary

chore: fix and bump standard version

---

src/button.scss
stories/button/__snapshots__/button.stories.storyshot
stories/button/button.stories.js

Closes SAP/fundamental-styles#756
- Add Styling
added `__instructions` with `screen-reader-only` styling to alert message for a `disabled` button with `allowFocusOnDisable` set to **true**. This text is used for screen readers to alert a user when a button is disabled or when it becomes enabled. 
This message should not be visible to a sighted user not using a screen reader. The button retains all styling previously in place. 
- Add aria-disabled
By using `aria-disabled="true"` without the `disabled` prop, a screen reader will be able to read the state of the button since the button will now be focusable and reachable by key navigation. The screen reader will read out the state of the button informing the user the button is disabled
Related to [Fix: focusable disabled button …

feat: add screen-reader-only styles to button

---

src/mixins/button/_emphasized.scss
stories/button/__snapshots__/button.stories.storyshot
stories/button/button.stories.js

Closes SAP/fundamental-styles#756
Related to https://github.com/SAP/fundamental-styles/pull/1293
Add more examples to Button States to include Focusable Disabled Buttons.
Fix focus ring for focusable disabled emphasized buttons. Previously no focus ring for this button, now focus ring follows the same style as other button states.

fix: additional styles and docs for focusable disabled button

---

src/input-group.scss

fix: remove extra border on Input Group button

---

package.json

Now tests are failling randomly depending on OS and it's a need to investigate what's wrong with them. This PR disables tests, just to unblock other PRs from begin merged.

chore: temporary remove storybook tests

---

.storybook/static/unnormalize.css

In this change, we update the unnormalized styles to
* add the `section` element 
* include pseudo-elements i.e. `::before` and `::after` 

chore: update unnormalized styles

---

stories/dialog/__snapshots__/dialog.stories.storyshot
stories/dialog/dialog.stories.js
stories/list/standard/standard-list.stories.js
stories/multi-input/multi-input.stories.js

Closes #1396 
In this change, we update the List's markup so that the List's footer is no longer a list item. The footer appears as a span after the unordered list.
No visual changes

fix: List footer as span

---

src/button.scss

There is added additional spacing for buttons. . So now clickable area is expanded with invisible indicators.
Pseudo elements are absolute positioned.

fix: Add additional spacing to buttons as a pseudo element

---

src/button.scss
src/mixins/button/_attention.scss
src/mixins/button/_button-helper.scss
src/mixins/button/_emphasized.scss
src/mixins/button/_ghost.scss
src/mixins/button/_negative.scss
src/mixins/button/_positive.scss
src/mixins/button/_standard.scss

There is moved button focus indicator. From outline to ::after pseudo element with proper offset.

fix: button move focus indicator

---

src/product-switch.scss
stories/product-switch/product-switch.stories.js

fixes #1336 
before (look at the "g"):
after:

fix: border cutting off bottom of product switch item subtitles

---

src/button.scss

fixes #1055 
Problem is that when clicking a <button> on firefox or safari, specifically running OSX, :focus selector is not applied, only :active.  Previous implementation didn't apply outline unless the button was both focused and active.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus

fix: button active outline for safari and ff

---

.storybook/custom/custom.scss

After update of the storybook to `6.0.5` our custom styling has started breaking storybook layout. Breaking styling has been removed.
>

chore: Fix storybook main content overlapping

---

src/carousel.scss
stories/carousel/carousel.stories.js

The Button markup has changes so the Navigation buttons of the Carousel have to be updated with the latest markup. Also, additional modifier classes are introduced for the left and right button to place the buttons inside the content according to the specs.
- update the markup of the buttons to use `<i class="sap-icon--slim-arrow-left"></i>` and `<i class="sap-icon--slim-arrow-right"></i>`
- introduce additional modifier classes - `fd-carousel__button--left` and `fd-carousel__button--right`

fix: update navigation buttons of Carousel

---

src/_listDefinitions.scss
src/_listNavigation.scss
src/_listSelection.scss

Closes https://github.com/SAP/fundamental-styles/issues/1544
There is increased padding for selection list, on compact mode.
>
Selection + Navigation:

fix: Add spacing for list selection

---

src/mixins/_mixins.scss

This PR introduces base SCSS mixins for creating component specific icons.

fix: Create base SCSS mixins for icons

---

src/table.scss
stories/table/__snapshots__/table.stories.storyshot
stories/table/table.stories.js

- Create basic Grid Table example inspired by https://openui5.hana.ondemand.com/entity/sap.ui.table.Table/sample/sap.ui.table.sample.Basic
- Create `fd-table__caption` element
This is an initial Grid Table example meant to show what the Table looks like with inputs inside of it. No huge changes to the component itself other than adding a `<caption>` for screen reader users.

feat: Basic Grid Table example, caption element

---

src/mixins/_forms.scss
src/radio.scss
stories/radio/__snapshots__/radio.stories.storyshot
stories/radio/radio.stories.js

Closes https://github.com/SAP/fundamental-styles/issues/1589
https://github.com/SAP/fundamental-ngx/issues/3086
Compact radio filling is not centre aligned. fixed padding for compact radio.
>

fix: padding fix for compact radio button

---

src/menu.scss
stories/menu/__snapshots__/menu.stories.storyshot
stories/menu/menu.stories.js

Part of: SAP/fundamental-styles#1603
This PR:
- Moves icons to separate HTML tags
- Updates aria labels/roles
```
<a class="fd-menu__link" href="#" role="menuitem">
<span class="fd-menu__addon-before sap-icon--wrench"></span>
...
<span class="fd-menu__addon-after sap-icon--wrench"></span>
</a>
```
```
<a class="fd-menu__link" href="#" role="menuitem">
<span class="fd-menu__addon-before"><i class="sap-icon--wrench" role="presentation"></i></span>
...
<span class="fd-menu__addon-after"><i class="sap-icon--wrench" role="presentation"></i></span>
</a>
```

fix: Menu - Refactor icons usage

---

src/checkbox.scss
src/mixins/_forms.scss
src/radio.scss

There was missed leftover after old focus indicator. So the focus ring appeared twice on empty checkboxes and radio buttons
Focus pseudo elements were removed in https://github.com/SAP/fundamental-styles/pull/1283 .
>

fix: Remove redundant focus on empty forms

---

src/tabs.scss
stories/tabs/__snapshots__/tabs.stories.storyshot
stories/tabs/tabs.stories.js

Related to #1603 
Breaking Changes in 2 places:
- overflow button
Before:
```
<button class="fd-button fd-button--transparent fd-button--compact fd-tabs__overflow" aria-label="See More"></button>
```    
After:
```
<button class="fd-button fd-button--transparent fd-button--compact fd-tabs__overflow" aria-label="See More">
<i class="sap-icon--slim-arrow-down" role="presentation"></i>
</button>
```
-icons
Before:
```
<span class="fd-tabs__icon sap-icon--cart">
<p class="fd-tabs__count">15</p>
</span>    
```
After:
```
<span class="fd-tabs__icon">
<i class="sap-icon--cart" role="presentation"></i>
<p class="fd-tabs__count">15</p>
</span>
```

fix: Apply icons changes to tabs

---

src/switch.scss
stories/switch/switch.stories.js

Related to https://github.com/SAP/fundamental-styles/issues/1603
Breaking Changes - Only A11Y in markup:
Before:
```
<span class="fd-switch__icon--off fd-switch__icon sap-icon--decline"></span>
```
After:
```
<i class="fd-switch__icon--off fd-switch__icon sap-icon--decline" role="presentation"></i>
```

fix: refactor icons in switch

---

src/object-marker.scss
stories/object-marker/__snapshots__/object-marker.stories.storyshot
stories/object-marker/object-marker.stories.js

Part of: #1603 
and #1639
There is added 1 new element:
`fd-object-status__text`
And added A11Y support in markup.
Breaking Change:
Before:
```
<span class="fd-object-marker">Locked</span>
```
After:
```
<div class="fd-object-marker">
<span class="fd-object-marker__text">Draft</span>
</div>
```

fix: Refactor icons and text in object marker

---

src/_nested-list.scss
stories/side-navigation/side-navigation.stories.js

Successor of: #1656
Part of: #1603, #1639
This PR:
- Styles icon element with icon mixins
- Adds aria attributes
```
<span aria-hidden="true" class="fd-nested-list__icon sap-icon--employee"></span>
```
```
<i role="presentation" class="fd-nested-list__icon sap-icon--employee"></i>
```

fix: Side Navigation - Refactor icons usage - #2

---

src/_listBase.scss
src/_listByline.scss
src/table.scss
stories/card/card.stories.js
stories/list/byline/__snapshots__/byline-list.stories.storyshot
stories/list/byline/byline-list.stories.js
stories/list/standard/standard-list.stories.js
stories/select/select.stories.js
stories/table/__snapshots__/table.stories.storyshot
stories/table/table.stories.js

Successor of: #1651
Part of: #1603
This PR:
- Moves byline list thumbnail icon into separate element
- Updates table icon styling with icon mixins and adds aria labels
- Updates list icon styling with icon mixins and adds aria labels
List:
```
<li role="listitem" tabindex="0" class="fd-list__item">
<span class="sap-icon--activate fd-list__thumbnail"></span>
</li>
```
```
<li role="listitem" tabindex="0" class="fd-list__item">
<span class="fd-list__thumbnail"><i class="sap-icon--activate" role="presentation"></i></span>
</li>
```
Table:
```
<td class="fd-table__cell fd-table__cell--fit-content fd-table__cell--no-padding">
<span class="fd-table__icon fd-table__icon--navigation sap-icon--navigation-right-arrow"></span>
</td>
```
```
<td class="fd-table__cell fd-table__cell--fit-content …
```

fix: Table, List - Refactor icons usage - #2

---

src/numeric-content.scss
stories/card/card.stories.js
stories/generictile/__snapshots__/generic-tile.stories.storyshot
stories/generictile/generic-tile.stories.mdx
stories/numeric-content/__snapshots__/numeric-content.stories.storyshot
stories/numeric-content/numeric-content.stories.js

Successor of: #1659
Part of: #1603
This PR:
- Updates Numeric Content styling with icon mixins
- Updates Numeric Content markup to use `<i>` element
- Adds aria attributes
```
<span class="fd-numeric-content__scale-arrow sap-icon--down"></span>
```
```
<div class="fd-numeric-content__scale">
<span class="fd-numeric-content__scale-arrow sap-icon--down"></span>
</div>
```
```
<i class="fd-numeric-content__scale-arrow sap-icon--down" aria-label="decrease"></i>
```
```
<div class="fd-numeric-content__scale">
<i class="fd-numeric-content__scale-arrow sap-icon--down" aria-label="decrease"></i>
</div>
```

fix: Numeric Content - Refactor icons usage #2

---

src/info-label.scss
stories/info-label/__snapshots__/info-label.stories.storyshot
stories/info-label/info-label.stories.js

Part of: SAP/fundamental-styles#1603
This PR:
- Introduces `fd-info-label__text` and `fd-info-label__icon` class
- Moves icon to separate HTML elements
- Adds aria label/role attributes
```
<span class="fd-info-label fd-info-label--accent-color-1 fd-info-label--icon sap-icon--future">Info Label</span>
```
```
<span class="fd-info-label fd-info-label--accent-color-1 fd-info-label--icon">
<i class="fd-info-label__icon sap-icon--future" aria-hidden="true"></i>
<span class="fd-info-label__text">Info Label</span>
</span>
```

fix: Info label - Refactor icons usage

---

src/tile.scss
stories/generictile/__snapshots__/generic-tile.stories.storyshot
stories/generictile/generic-tile.stories.mdx

Part of: SAP/fundamental-styles#1603
This PR:
- Updates icon element code with icon mixins
```
<div class="fd-tile__section">
<span class="sap-icon--refresh fd-tile__refresh"></span>
<span class="fd-tile__footer-text">Now</span>
</div>
```
```
<div class="fd-tile__section">
<i class="fd-tile__refresh sap-icon--refresh" aria-label="Refresh"></i>
<span class="fd-tile__footer-text">Now</span>
</div>
```

fix: Tile - Refactor icons usage

---

src/avatar.scss
stories/avatar/__snapshots__/avatar.stories.storyshot
stories/avatar/avatar.stories.js

Part of: SAP/fundamental-styles#1603
This PR:
- Introduces new class `fd-avatar__icon`
- Introduces avatar icon as separate HTML element
- Updates aria role and label attributes
Avatar with icon
```
<span class="fd-avatar fd-avatar--xl fd-avatar--circle sap-icon--money-bills" role="presentation"></span>
```
Avatar with icon and zoom icon
```
<span class="fd-avatar fd-avatar--l fd-avatar--circle fd-avatar--accent-color-4 sap-icon--money-bills" role="presentation">
<span class="fd-avatar__zoom-icon sap-icon--edit" role="presentation"></span>
</span>
```
Avatar with icon
```
<span class="fd-avatar fd-avatar--xs fd-avatar--circle" aria-label="Avatar">
<i class="fd-avatar__icon sap-icon--money-bills" role="presentation"></i>
</span>
```
Avatar with icon and zoom icon
```
<span class="fd-avatar …
```

fix: Avatar - refactor icons usage

---

config/bundlesize.json
src/button.scss
src/tree.scss
stories/tree/__snapshots__/tree.stories.storyshot
stories/tree/tree.stories.js

Related to https://github.com/SAP/fundamental-styles/issues/1603
Breaking Change:
- Now Tree expander requires navigation icon
Before:
```
<button tabindex="0" class="fd-tree__expander" aria-label="Expander"></button>
```
After:
```
<button tabindex="0" class="fd-tree__expander" aria-label="Expander">
<i class="fd-tree__icon sap-icon--navigation-right-arrow" role="presentation"></i>
</button> 
```
>

fix: Apply icons changes to tree

---

src/object-status.scss
stories/object-status/__snapshots__/object-status.stories.storyshot
stories/object-status/object-status.stories.js

related to https://github.com/SAP/fundamental-styles/issues/1603
and #1639
There are added 2 new elements:
`fd-object-status__icon` and `fd-object-status__text`
Breaking change:
Object status icon and text are extracted in separate `<i>` and `<span>`  elements and new classes have been introduced: `fd-object-status__icon` and `fd-object-status__text`
Before:
```
<span class="fd-object-status sap-icon--to-be-negative">Negative</span>
```
After:
```
<span class="fd-object-status fd-object-status--negative">
<i class="fd-object-status__icon sap-icon--status-negative" role="presentation"></i>
<span class="fd-object-status__text">Negative</span>
</span>
```

fix: Refactor object status icons and text

---

src/mixins/button/_button-helper.scss
src/tile.scss
stories/generictile/__snapshots__/generic-tile.stories.storyshot
stories/generictile/generic-tile.stories.mdx

Closes https://github.com/SAP/fundamental-styles/issues/1684
In this PR:
BREAKING CHANGE
- Icons inside `fd-tile__action-close` and `fd-tile__action-indicator` are moved to separated `<i>` elements with proper roles and `sap-icon--*` classes
- Focus in such buttons is fixed - now it follows button's strategy with pseudo element.
>
Focus:

fix: update icons in tile actions

---

src/_nested-list.scss
stories/side-navigation/side-navigation.stories.js

Part of: #1433
This PR:
- Moves expand icon to separate `<i>` tag.
- Cleans up styling
```
<button class="fd-button fd-nested-list__button"></button>
```
```
<button class="fd-button fd-nested-list__button">
<i class="sap-icon--navigation-right-arrow"></i>
</button>
```

fix: Remove double outline from side navigation expand button

---

src/rating-indicator.scss
stories/rating-indicator/rating-indicator.stories.js

fixes SAP/fundamental-styles#1687
Aligned the naming of the Rating Indicator modifier classes
From `fd-rating-indicator--s` to `fd-rating-indicator--sm`
From `fd-rating-indicator--l` to `fd-rating-indicator--lg`
Removed the `fd-rating-indicator--m` since it's the default one and no modifier class is needed.

fix: align the naming of the Rating Indicator modifier classes

---

src/wizard.scss
stories/wizard/wizard.stories.js

fixes SAP/fundamental-styles#1687
Aligned the naming of the Rating Indicator modifier classes
From `fd-wizard__progress-bar--s` to `fd-wizard__progress-bar--sm`
From `fd-wizard__progress-bar--m` to `fd-wizard__progress-bar--md`
From `fd-wizard__content--s` to `fd-wizard__content--sm`
From `fd-wizard__content--m` to `fd-wizard__content--md`
Added more specificity to `fd-wizard__icon` by including the `fd-icon-element-base` and `fd-icon-selector` as in the other components.

fix: align the naming of the Wizard modifier classes

---

src/rating-indicator.scss

In some cases `flex-end` doesn't work on IE11, if wrapper contains only 1 element, the reverse direction can be used instead.
>

fix: rating indicator halves IE11

---

src/button.scss

Previously there was no way to make truncation work correctly on menu buttons. With `__text` element, there is a way to fix it, adding flex/center property to button.
>
3. Testing

fix: Truncation on menu button

---

src/notification.scss
stories/notification/__snapshots__/notification.stories.storyshot
stories/notification/notification.stories.js

The last item of the footer (7 minutes ago) was wrapped with a span and `fd-notification__footer-content` class in all examples. The footer items were always the same size, changed the max-width to be 50%, positioning the second item close to the first one.
>
2. Documentation

fix: add fix for Notifications examples markup and for the max-width of the footer content

---

stories/datepicker/datepicker.stories.js
stories/multi-input/multi-input.stories.js
stories/object-marker/object-marker.stories.js
stories/object-number/object-number.stories.js
stories/object-status/object-status.stories.js

Docs fixes as part of https://github.com/SAP/fundamental-styles/pull/1752 followup.

docs: theming followup - missing style imports in docs pages

---

.storybook/static/windows-hcm-1.css
.storybook/static/windows-hcm-2.css
.storybook/static/windows-hcm-black.css
.storybook/static/windows-hcm-white.css

Closes SAP/fundamental-styles#1005
Radio button checked state icon does not have HCM styles applied due to a lack of specificity coming from the selectors. Additional style rules have been added to all HCM styles where needed.
3. Testing

docs: add additional selector for hcm radio color

---

src/_listBase.scss
src/button.scss
src/calendar.scss
src/input-group.scss
src/input.scss
src/menu.scss
src/popover.scss
src/product-switch.scss
src/select.scss
src/side-nav.scss
src/theming/sap_fiori_3.scss
src/theming/sap_fiori_3_dark.scss
src/theming/sap_fiori_3_hcb.scss
src/theming/sap_fiori_3_hcw.scss
src/theming/sap_fiori_3_light_dark.scss
src/time.scss
src/token.scss

Closes SAP/fundamental-styles#1020
Closes SAP/fundamental-styles#1019
Closes SAP/fundamental-styles#1016
Closes SAP/fundamental-styles#1015
Closes SAP/fundamental-styles#1014
Closes SAP/fundamental-styles#1010
Closes SAP/fundamental-styles#1009
Closes SAP/fundamental-styles#1006
Closes SAP/fundamental-styles#1004
Closes SAP/fundamental-styles#1003
Closes SAP/fundamental-styles#996
This PR is addressing WCAG AAA Color contrast issue above which mainly pertain to the text contrast of these components against their backgrounds in Fiori **High Contrast Black** mode. The two colors used throughout are `#FFFFFF` for text, `#0F5D94` and `#7A5100` for background. This is currently failing color contrast WCAG AAA minimums.
`#FFFFFF` text color against `#7A5100` background results in 6.98:1 …

fix: wcag aaa text color contrast

---

src/button.scss

Part of https://github.com/SAP/fundamental-ngx/issues/3641
Part of https://github.com/SAP/fundamental-styles/issues/1760
Focus outline is not needed on selected buttons, when button is not focused.

fix: Remove focus on pressed button

---

src/layout-grid.scss

Closes: #1801 
This PR:
- Add RTL support for offset in layout grid columns
- Moves responsive column code into a mixin
Grid in LTR mode:
Grid in RTL mode:
Grid in RTL mode:

fix: Add RTL support for layout grid column offset

---

.github/workflows/chromatic.yml
stories/button/button.stories.js

Only run Chromatic build for commits without [ci skip] in the message. This prevents Chromatic builds from triggering on release commits.
- [N.A.] All values are in `rem`
- [N.A.] Text elements follow the truncation rules
- [N.A.] hover state of the element follow design spec
- [N.A.] focus state of the element follow design spec
- [N.A.] active state of the element follow design spec
- [N.A.] selected state of the element follow design spec
- [N.A.] selected hover state of the element follow design spec
- [N.A.] pressed state of the element follow design spec
- [N.A.] Responsiveness rules - the component has modifier classes for all breakpoints
- [N.A.] Includes Compact/Cosy/Tablet design
- [N.A.] RTL support
2. The code follows fundamental-styles …

chore: skip Chromatic build on release

---

src/_dialog-placeholders.scss
src/dialog.scss

Closes: #1100 
This PR:
- Adds overflow hidden for the Dialog window
- Moves border radius from header and footer to Dialog window
- Removes border radius from the dialog window if the Dialog is used in mobile mode

fix: Dialog - no border radius in mobile mode

---

.storybook/custom/custom.scss
.storybook/static/preview-head.js
stories/dialog/__snapshots__/dialog.stories.storyshot
stories/dialog/dialog.stories.js
stories/table/__snapshots__/table.stories.storyshot
stories/table/table.stories.js

Part of: #1760 
This PR:
- Replaces and removes `toggleDialog` with `toggleClass`
- Updates selection list implementation in Selection Dialog example
- Adds `z-index` to `.fd-dialog` and `.fd-message-box` examples
3. Testing

fix: Improve Dialog documentation examples

---

src/checkbox.scss
src/radio.scss
src/theming/sap_fiori_3.scss
src/theming/sap_fiori_3_dark.scss
src/theming/sap_fiori_3_hcb.scss
src/theming/sap_fiori_3_hcw.scss
src/theming/sap_fiori_3_light_dark.scss

Add theming deltas for Radio and Checkbox
>
- N/A  All values are in `rem`
- N/A  Text elements follow the truncation rules
- N/A hover state of the element follow design spec
- N/A focus state of the element follow design spec
- N/A active state of the element follow design spec
- N/A selected state of the element follow design spec
- N/A selected hover state of the element follow design spec
- N/A  pressed state of the element follow …

fix: add delta theming for Radio and Checkbox

---

src/switch.scss

part of https://github.com/SAP/fundamental-styles/issues/1818
3. Testing

fix: Center vertically text in switch component

---

src/panel.scss

Closes https://github.com/SAP/fundamental-styles/issues/1779
Related https://github.com/SAP/fundamental-ngx/issues/3674 
- Rotate arrow icon

fix: RTL mode arrow button direction

---

src/message-strip.scss

There is stronger selector for message-strip close element.
No visual/usage changes predicted

fix: Make stronger selector for message strip

---

src/carousel.scss

https://github.com/SAP/fundamental-ngx/issues/3753
Fixed focus and pressed (active) states for carousel navigation buttons for Safari and Firebox browsers.
>
Focus
Active
3. Testing

fix: Core Carousel navigation buttons - focus/active state in Safari and Firefox browser

---

src/dialog.scss
src/product-switch.scss

fix: center buttons in Product Switch and Dialog

---

src/counter.scss
src/shellbar.scss

part of https://github.com/SAP/fundamental-styles/issues/1818
There is added new strategy of dealing with focus color in shellbar buttons
>
3. Testing

fix: Shellbar button focus color

---

src/badge.scss
src/button.scss
src/card.scss
src/carousel.scss
src/mixins/button/_emphasized.scss
src/theming/sap_fiori_3.scss
src/theming/sap_fiori_3_dark.scss
src/theming/sap_fiori_3_hcb.scss
src/theming/sap_fiori_3_hcw.scss
src/theming/sap_fiori_3_light_dark.scss

The delta theming parameters for Button, Card, Badge and Carousel have been updates. Also introduced minor styling changes that I noticed when I introduced the deltas, such as the missing border radius for Card Header.
**Button:**
**Card and Badge:**
**Carousel:**
**Button:**
**Card and Badge:**
**Carousel:**
- [x ] hover state of the element follow design spec
- [ NA] focus state of the element follow design spec
- [NA] Responsiveness rules - the component has modifier classes for all breakpoints
- [NA] RTL …

fix: update delta theming for Button, Card, Badge and Carousel

---

.storybook/custom/custom.scss
src/_dialog-placeholders.scss
src/tabs.scss
src/theming/sap_fiori_3.scss
src/theming/sap_fiori_3_dark.scss
src/theming/sap_fiori_3_hcb.scss
src/theming/sap_fiori_3_hcw.scss
src/theming/sap_fiori_3_light_dark.scss
src/tile.scss
src/toolbar.scss

Closes SAP/fundamental-styles#625
There is:
- Dialog component changed overlay - from fade usage to pseudo element with opacity.
- tabs variable corrected
- tile variable corrected
- toolbar variable corrected
>
3. Testing

fix: replace fade functions

---

src/button.scss

Part of https://github.com/SAP/fundamental-styles/issues/1907
Buttons need to be centered by default
3. Testing

fix: center the content of Button by default

---

src/button.scss

this PR adds `!important` to the rule that sets spacing between the elements inside a Button. Without this rule, the behaviour depends on the import of the components. In Fundamental-ngx, the icons styling was overwriting the margin-left specified in the Button and was causing the issue where the expand icon was rendered right next to the text.  …

fix: add fix for missing space between Menu Button text and expand arrow

---

src/message-strip.scss

Part of #1907
Add icons to rtl mode for message strip 
3. Testing

fix: add fix for missing icons in RTL mode for Message Strip

---

stories/datepicker/__snapshots__/datepicker.stories.storyshot
stories/datepicker/datepicker.stories.js

Part of #907 
Changes the two buttons two one split button for the DateTime picker
3. Testing

fix: date time picker segmented button

---

src/flexible-column-layout.scss

Part of https://github.com/SAP/fundamental-styles/issues/1907
Button inside flexible column layout got fixed width and doesn't need padding.
>
3. Testing

fix: remove padding from button in Flexible Column Layout

---

src/badge.scss
src/tile.scss

Part of SAP/fundamental-styles#1907
The Play/Pause button, as well as the close button in Action mode were not changing positions in RTL mode in IE11 due to IE11 not supporting `initial`. `initial` is not changed to `auto`. 
Also, I notices the badges in RTL were cut so I added a quick fix for this.
- [na] Responsiveness rules - the component …

fix: add fixes for buttons not changing position in RTL in IE11 and cut badges in RTL

---

src/carousel.scss

Part of https://github.com/SAP/fundamental-ngx/issues/3922
Add fix for the bug where clicking on the button changes it position.

fix: (Core) add fix for Carousel button position on click

---

src/card.scss
src/numeric-content.scss

Part of: #1907 
IE11 does not support `width: initial` property.
To ensure that the numeric content and units keep required width `flex-shrink` has been added.
(IE11)
(IE11)

fix: add fix for overflowing card numeric content

---

src/popover.scss
stories/table/__snapshots__/table.stories.storyshot
stories/table/table.stories.js

Part of: #1907
This PR adds `full-width` modifier to popover to easily extend popover width when the popover and its content needs to fill the container.
The vertical misalignment seems to be "caused" by `display: inline-block` on `fd-popover` level. I don't know if there is a way to fix it.

fix: form controls in Table

---

.storybook/custom/custom.scss
src/message-box.scss
stories/message-box/__snapshots__/message-box.stories.storyshot
stories/message-box/message-box.stories.js

Closes SAP/fundamental-styles#1896
1. Add semantic icons to the Message Box title
2. Remove `.fd-message-box--no-icon` modifier class as by default the Message Box title does not have an icon.
3. In some Message Box examples it was not possible to click on the buttons or highlight the text. This issue was fixed by changing the position from static to relative (documentation class change)
4. Correct the documentation where instead of `.fd-message-box__xxx`, `.fd-message__xxx` was used.
BREAKING CHANGE: 
`.fd-message-box--no-icon` modifier class is removed
Semantic icons are added separately: `<i class="sap-icon--message-error"></i>` 
- [na] focus …

fix: add missing icons to semantic Message Box

---

src/shellbar.scss

Closes: #1726
Previous styling was targeting focus outline on the `fd-button` element. With button refactor, focus indicator has been moved to `fd-button::after`. Shellbar button styling has been updated to target `::after` element

fix: Shellbar menu button focus outline

---

src/_listDropdown.scss

part of https://github.com/SAP/fundamental-styles/issues/1907
Before:
After:

fix: add fix for missing spacing in Multi Combobox secondary data in IE11 

---

src/rating-indicator.scss

Importing whole dist `fundamental-styles` or `rating-indicator` into NGX file causes parse error. It's because of invalid variables declaration.
3. Testing

fix: add fix for Rating indicator parse error

---

src/button.scss
src/mixins/button/_attention.scss
src/mixins/button/_button-helper.scss
src/mixins/button/_button-transparent.scss
src/mixins/button/_emphasized.scss
src/mixins/button/_ghost.scss
src/mixins/button/_negative.scss
src/mixins/button/_positive.scss
src/mixins/button/_standard.scss
stories/button/__snapshots__/button.stories.storyshot
stories/button/button.stories.js

Closes SAP/fundamental-styles#1943
this PR adds an enhancement to Buttons - Toggle button. A toggle button switches between two actions. One of the actions is always active, one is inactive. 
- [na] `fd-reset()` mixin is applied to all elements
- [na] Variables are used, if some value is used more than twice.
3. Testing
- [na] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of …

feat: add Toggle Button to Buttons

---

src/slider.scss

part of https://github.com/SAP/fundamental-styles/issues/1907

fix: add fix for Slider labels not being centered in  IE11

---

src/button.scss

In case of usage `fd-button__text` , the text should be emphasized as well
>
3. Testing

fix: inherit font weight on button text

---

src/card.scss

Closes SAP/fundamental-styles#1715
Make the avatar selector under the card header so that it can apply the right styling in react, angular and vue
3. Testing

fix: add avatar selector under the header

---

src/switch.scss
stories/switch/switch.stories.js

Closes: #1869
This PR:
- improves switch component class structure.
- removes unnecessary SCSS variables
- On `.fd-switch__label` level should be used `.fd-switch` class
- On `.fd-switch` level should be used `.fd-switch__control` class
- On `.fd-switch` level should be used `.fd-switch__control` class
- Instead of  class should be used `.fd-switch__slider`
- `.fd-switch__label` and `.fd-switch__wrapper` have been removed
```
.fd-switch__label
.fd-switch__text
.fd-switch
.fd-switch__input
.fd-switch__wrapper
.fd-switch__track
.fd-switch__icon
.fd-switch__handle
```
```
.fd-switch
.fd-switch__text
.fd-switch__control
.fd-switch__input
.fd-switch__slider
.fd-switch__track
.fd-switch__icon
.fd-switch__handle
``` …

fix: improve class structure for Switch component

---

README.md

Closes SAP/fundamental-styles#1758
Fixes our read me to contain the project configuration as we no longer have the old file.
Also include the font size in px so that they can render the proper rem values

chore: add font and icon instructions to README for project config

---

src/fundamental-styles.scss

Closes SAP/fundamental-styles#1857
The global styles didn't have fd-title inside of it and users need access to the class
3. Testing

fix: add fd-title to global styles

---

src/breadcrumb.scss

Closes SAP/fundamental-styles#1892
Make all states have the same color for both items
3. Testing

fix: outline color of breakcrumb icon overflow

---

src/link.scss
stories/link/__snapshots__/link.stories.storyshot
stories/link/link.stories.js

Closes SAP/fundamental-styles#1777
Fix the color and underline of the icon when user hovers over link 
3. Testing

fix: hover text decoration of icon with link

---

src/form-message.scss
src/mixins/_forms.scss
src/theming/sap_fiori_3.scss
src/theming/sap_fiori_3_dark.scss
src/theming/sap_fiori_3_hcb.scss
src/theming/sap_fiori_3_hcw.scss
src/theming/sap_fiori_3_light_dark.scss

Add theming deltas for Forms
- N/A  All values are in `rem`
- N/A  Text elements follow the truncation rules
- N/A hover state of the element follow design spec
- N/A focus state of the element follow design spec
- N/A active state of the element follow design spec
- N/A selected state of the element follow design spec
- N/A selected hover state of the element follow design spec
- N/A  pressed state of the element follow design spec
- N/A  Responsiveness rules - the component has modifier classes for all breakpoints
- N/A  Includes Compact/Cosy/Tablet design
- N/A  RTL support
- N/A  BEM naming convention is used
- N/A  Mixins are used for repeatable …

fix: add delta theming for Forms

---

src/_listBase.scss
stories/list/standard/__snapshots__/standard-list.stories.storyshot
stories/list/standard/standard-list.stories.js

BREAKING CHANGES: fd-list__item--unread modifier added
Closes SAP/fundamental-styles#1111
Add unread modifier to list item per new fiori 3 spec
3. Testing

feat: unread selection

---

src/object-status.scss
stories/object-status/__snapshots__/object-status.stories.storyshot
stories/object-status/object-status.stories.js

Closes https://github.com/SAP/fundamental-styles/issues/2009
Part of https://github.com/SAP/fundamental-ngx/issues/3414
Added focus for Object status as a link.
3. Testing

fix: object status link focus

---

src/product-switch.scss
src/theming/sap_fiori_3.scss
src/theming/sap_fiori_3_dark.scss
src/theming/sap_fiori_3_hcb.scss
src/theming/sap_fiori_3_hcw.scss
src/theming/sap_fiori_3_light_dark.scss

Part of https://github.com/SAP/fundamental-styles/issues/1357
In this PR I changed all `&:hover/active` states to ``fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus` mixins
>
3. Testing

fix: Add theming to product switch

---

src/input-group.scss
src/theming/sap_fiori_3.scss
src/theming/sap_fiori_3_dark.scss
src/theming/sap_fiori_3_hcb.scss
src/theming/sap_fiori_3_hcw.scss
src/theming/sap_fiori_3_light_dark.scss

Part of #1357
There is added border on side for button inside multi input/combobox, on hover/active state, for HCB/HCW
>
3. Testing

fix: add delta theming for Combobox and Multi Input

---

src/switch.scss
src/theming/sap_fiori_3.scss
src/theming/sap_fiori_3_dark.scss
src/theming/sap_fiori_3_hcb.scss
src/theming/sap_fiori_3_hcw.scss
src/theming/sap_fiori_3_light_dark.scss

part of #1357 
example (semantic hover):

fix: add delta theming for Switch

---

src/_dialog-placeholders.scss
src/flexible-column-layout.scss
src/message-strip.scss
src/theming/sap_fiori_3.scss
src/theming/sap_fiori_3_dark.scss
src/theming/sap_fiori_3_hcb.scss
src/theming/sap_fiori_3_hcw.scss
src/theming/sap_fiori_3_light_dark.scss

some fund-styles theme variables had different naming format. This PR made their naming consistent with the majority of the theme variables

fix: unify delta theming variables naming

---

src/message-box.scss
src/theming/sap_fiori_3.scss
src/theming/sap_fiori_3_dark.scss
src/theming/sap_fiori_3_hcb.scss
src/theming/sap_fiori_3_hcw.scss
src/theming/sap_fiori_3_light_dark.scss

add delta theming for Message Box
NA
NA
3. Testing
NA
NA

fix: add delta theming for Message Box

---

src/checkbox.scss
stories/checkbox/__snapshots__/checkbox.stories.storyshot
stories/checkbox/checkbox.stories.js

Closes SAP/fundamental-styles#883
Fixes the positioning of the required label
3. Testing

fix: checkbox label for required

---

src/select.scss
src/theming/sap_fiori_3.scss
src/theming/sap_fiori_3_dark.scss
src/theming/sap_fiori_3_hcb.scss
src/theming/sap_fiori_3_hcw.scss
src/theming/sap_fiori_3_light_dark.scss

part of https://github.com/SAP/fundamental-styles/issues/1357
Added border on sides on HCB/HCW with interactive states
3. Testing

fix: add delta theming for Select

---

package-lock.json
package.json

chore: bump bundlesize version

---

src/button-split.scss
stories/button/__snapshots__/button.stories.storyshot
stories/button/button.stories.js

Closes  https://github.com/SAP/fundamental-styles/issues/1721
Add text overflow to the text of split button
For regular cosy button 9.75rem is used because the other button takes 2.25rem and the max-width is always 12rem
For compact 10rem is used to keep this same 12rem max-width
3. Testing

fix: split button overflow

---

src/dynamic-page.scss

Closes SAP/fundamental-styles#2043
This PR fixes the incorrect scrollbar appearing in dynamic page content area. This scrollbar should not have appeared at all since content is fitting well within the page. It also fixes the issue where 2 scrollbars appear when content does not fit the page. Verified in IE.
>
3. Testing …

fix: fix Dynamic Page default scrollbar appearing in IE

---

.storybook/custom/custom.scss

Part of SAP/fundamental-styles#2045
In IE11 the top box-shadow was missing for Dialog. I changed the custom docs css rules responsible for rendering static dialogs
NA
NA
3. Testing
NA
NA

docs: add fix for missing box-shadow for Dialog in IE11

---

.storybook/static/preview-head.js
stories/side-navigation/__snapshots__/side-navigation.stories.storyshot
stories/side-navigation/side-navigation.stories.js

Part of SAP/fundamental-styles#2045
Add JS to the documentation for changing the icon of the button responsible for opening/hiding the second level of the Side navigation
NA
NA
3. Testing
- [na] tested Storybook examples with "CSS Resources" `normalize` option 
- [na] tested Storybook examples with "CSS Resources" `unnormalize` option 

docs: change the icon of the button showing/hiding the second level of Side Nav

---

src/shellbar.scss

fix: put back button background color

---

stories/multi-combo-box/__snapshots__/multi-combo-box.stories.storyshot
stories/multi-combo-box/multi-combo-box.stories.js
stories/multi-input/__snapshots__/multi-input.stories.storyshot
stories/multi-input/multi-input.stories.js

part of https://github.com/SAP/fundamental-styles/issues/2045
There is new multi input markup relied on selection list. Because it looks same, so there is no reason to have 2 different htmls
3. Testing

docs: multi input markup update

---

src/carousel.scss
src/input-group.scss
src/mixins/button/_button-helper.scss
src/mixins/button/_standard.scss
src/tile.scss

https://github.com/SAP/fundamental-ngx/issues/3458
Fix for input group component focus state. Required for https://github.com/SAP/fundamental-ngx/pull/4204
Small rework for button component and related components (combobox, carousel, input group, tile)
3. Testing

fix: reworked styles for button and related components

---

src/theming/sap_fiori_3.scss
src/theming/sap_fiori_3_dark.scss
src/theming/sap_fiori_3_hcb.scss
src/theming/sap_fiori_3_hcw.scss
src/theming/sap_fiori_3_light_dark.scss
src/tile.scss

The current PR adds the delta theming for Generic Tiles. Changed values: in Slide Tile - the container background and the opacity, the dot sizes and colors, as well as the spacing between them.
This PR can be merged after the designers confirm the colors as it looks like something is off:
Element A - Transparent background layer on tile image. Has `background-color: --sapBlockLayer_Background` which results in #000000 in Quartz Light. It has opacity 0.85
Element B - title and subtitle area. The title (text) has color `--sapTile_TitleTextColor` which results in #32363A. The subtitle has  `--sapTile_TextColor` which results in #6A6D70. The final result in Quartz Light is a dark grey text on black background with 0.85 opacity. 
Text-shadow for HCW looks …

fix: add delta theming for Generic Tiles

---

stories/object-list/__snapshots__/object-list.stories.storyshot
stories/object-list/object-list.stories.js
stories/object-status/__snapshots__/object-status.stories.storyshot
stories/object-status/object-status.stories.js

BREAKING CHANGE: 
update the semantic icons for Object Status and Object List and remove icon for neutral one
update the semantic icons for Object Status and Object List and remove icon for neutral one
1. Testing
2. Documentation

fix: update semantic icons in object status and object list

---

stories/bar/__snapshots__/bar.stories.storyshot
stories/bar/bar.stories.js

fixes: #2030
use compact buttons in compact bars
2. Testing
3. Documentation

docs: update buttons in compact bars

---

src/quick-view.scss
stories/quick-view/__snapshots__/quick-view.stories.storyshot
stories/quick-view/quick-view.stories.js

Related to https://github.com/SAP/fundamental-ngx/issues/4400
If you use `fd-bar__left` or `fd-bar__right` instead of `fd-bar__middle` inside `fd-bar--header` your popover header (quick view title as well) will have no gaps.
2. The code follows fundamental-styles code …

fix: Quick View title gaps

---

src/text.scss
stories/text/__snapshots__/text.stories.storyshot
stories/text/text.stories.js

After Core: Text [spec](https://app.gitbook.com/@fundamental-ngx/s/docs/core-text) review
it was decided to add expand option, "MORE" and "LESS" links to show more and less of the text.
The new example was based on similar functionality in [feed-list-items](https://sap.github.io/fundamental-ngx/#/core/feed-list-item#feed-list-item-simple)
3. Testing

feat: introduce expand example for the Text component

---

src/_listBase.scss
src/_listDefinitions.scss
stories/list/byline/__snapshots__/byline-list.stories.storyshot
stories/list/byline/byline-list.stories.js
stories/list/standard/__snapshots__/standard-list.stories.storyshot
stories/list/standard/standard-list.stories.js

part of https://github.com/SAP/fundamental-styles/issues/2063
There is added: 
- `fd-list__item--interractive` modifier for interractive (hover/active) states for list item
- `is-selected` is now supported by basic `fd-list__item`
3. Testing

feat: list interractive states

---

src/avatar-group.scss
stories/avatar-group/__snapshots__/avatar-group.stories.storyshot
stories/avatar-group/avatar-group.stories.js

Related to https://github.com/SAP/fundamental-styles/issues/2023
3. Testing 

fix: added color accents to Overflow Button in Avatar Group

---

src/_listDefinitions.scss
src/table.scss

Closes https://github.com/SAP/fundamental-styles/issues/2085
This PR removes text-shadow, when cell/row is activated.
And changes focus color to contrast, when row/cell is active
3. Testing

fix: add fix for Table text shadow and focus color

---

stories/list/byline/__snapshots__/byline-list.stories.storyshot
stories/list/byline/byline-list.stories.js

Part of SAP/fundamental-styles#2063
Attachment list shares the same specification as the Standard List with Byline. No css rules were added, just an example in the Byline list

docs: add Attachment list example to the documentation

---

src/shellbar.scss
stories/shellbar/__snapshots__/shellbar.stories.storyshot
stories/shellbar/shellbar.stories.js

part of #2089 
The shellbar notifications, when moved into the overflow menu on small screens, were not positioned correctly.  This was not known in the styles library because we had only seen it in ngx thus far.  This PR fixes the positioning and adds an example
Before:
After:

fix: positioning of overflowed shellbar notification counter

---

src/bar.scss

Fixes #2089 
Floating footer bar had no z-index so it could appear behind other elements that even had low (but present) z-indexes such as fd-inputs.

fix: add z-index to floating footer bar

---

src/mixins/_states.scss
src/step-input.scss

part of https://github.com/SAP/fundamental-styles/issues/2089
So there is workaround to make focus within work - even when something inside is on hover
3. Testing

fix: Step Input focus within

---

src/_listBase.scss
src/_listDefinitions.scss
stories/list/standard/__snapshots__/standard-list.stories.storyshot
stories/list/standard/standard-list.stories.js

Part of SAP/fundamental-styles#2063
List has a Growing List functionality which is implemented in Fundamental-styles with Action List item. For Busy State a Busy Indicator component is added to the title of the list item
3. Testing

feat: add busy state to the Action List

---

src/_listBase.scss
stories/combobox-input/__snapshots__/combobox-input.stories.storyshot
stories/combobox-input/combobox-input.stories.js
stories/list/byline/__snapshots__/byline-list.stories.storyshot
stories/list/byline/byline-list.stories.js
stories/list/standard/__snapshots__/standard-list.stories.storyshot
stories/list/standard/standard-list.stories.js
stories/multi-combo-box/__snapshots__/multi-combo-box.stories.storyshot
stories/multi-combo-box/multi-combo-box.stories.js
stories/multi-input/__snapshots__/multi-input.stories.storyshot
stories/multi-input/multi-input.stories.js
stories/select/__snapshots__/select.stories.storyshot
stories/select/select.stories.js

Part of SAP/fundamental-styles#2063
This PR adds truncation rules for the List component Group Header <li> element
change in the markup, now the text is wrapped in a span with `fd-list__title` class.
Affected components: combobox-input, standard list, multi combobox, multi input, select
Before:
```
<li role="listitem" class="fd-list__group-header">
Group header 1
</li>
```
Now:
```
<li role="listitem" class="fd-list__group-header">
<span class="fd-list__title">Group header 1</span>
</li>
```
- [na] selected hover state of …

fix: add truncation for List group header text

---

src/wizard.scss

fix: wizard - all stacked steps last:children should have padding-right

---

src/card.scss
stories/card/__snapshots__/card.stories.storyshot
stories/card/card.stories.js

Closes https://github.com/SAP/fundamental-styles/issues/2097
There is added new `fd-card__header--non-interactive` class modifier. And description of its usage.
>
3. Testing

feat: Add non-interactive state to card header

---

stories/form-grid/form-grid.stories.js

Part of SAP/fundamental-styles#2090
Select component in Grid List examples didn't have arrow. Added missing imports for Button and Icon.

docs: add missing imports for Form Grid

---

src/tile.scss

Part of SAP/fundamental-styles#2090
Related IE11 isses:
- Feed Tile - the text should truncate after 2 lines. Line-clamp is not supported in IE11, max-height was added as a fix
- Link Tile - misaligned action close button

fix: add fix for IE related issues in Tiles

---

src/_listDefinitions.scss

Byline list item in selected mode didn't apply the correct background on hover.

fix: add fix for hover state in selected mode

---

src/_listByline.scss

part of https://github.com/SAP/fundamental-styles/issues/2090
There are 2 bugs fixed for byline list:
- Counter is fully visible now on IE11
- title has proper min-height, same as line-height
3. Testing
- [\x] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

fix: Change height of title and solve counter issues on byline

---

src/list-grid.scss
stories/list-grid/__snapshots__/list-grid.stories.storyshot
stories/list-grid/list-grid.stories.js

Comments 2, 5 https://github.com/SAP/fundamental-ngx/pull/4610#issuecomment-776993841
Removed counter focus
Fixed focus on the status indicator
3. Testing

fix: fix Grid List styles

---

src/_listDropdown.scss
stories/combobox-input/__snapshots__/combobox-input.stories.storyshot
stories/combobox-input/combobox-input.stories.js
stories/multi-combo-box/__snapshots__/multi-combo-box.stories.storyshot
stories/multi-combo-box/multi-combo-box.stories.js
stories/multi-input/__snapshots__/multi-input.stories.storyshot
stories/multi-input/multi-input.stories.js
stories/select/__snapshots__/select.stories.storyshot
stories/select/select.stories.js

Part of SAP/fundamental-styles#2090
List component used as a dropdown or multi-input has a max-width of 37.5rem. In mobile mode the List is placed in a Dialog and should take the whole width. For this reason a modifier class is added and the width is changed from 37.5rem to 100%
>
- [na] …

feat: add modifier class for List being used in a dialog in mobile mode

---

README.md

fixes #2070 
add examples with font light and bold in `README.me`

docs: add examples with light and bold 72 fonts

---

stories/radio/__snapshots__/radio.stories.storyshot
stories/radio/radio.stories.js

part of #2090 
HTML radio buttons do not support "readonly" functionality like a text input would, so I'm removing these examples from the docs.

docs: remove radio readonly examples

---

src/side-nav.scss

closes https://github.com/SAP/fundamental-styles/issues/2146
The Side Nav should take the whole width of the container. Height 100% is added.

fix: Side Nav taking the whole height of the container

---

src/button-split.scss

Closes SAP/fundamental-styles#1981
The text inside Split button should be left-aligned, not centered. 
3. Testing

fix: add proper alignment for the text inside Split button

---

.storybook/custom/custom.scss
src/fundamental-styles.scss
src/margins.scss
src/paddings.scss
stories/margins/__snapshots__/margins.stories.storyshot
stories/margins/margins.stories.js
stories/paddings/__snapshots__/paddings.stories.storyshot
stories/paddings/paddings.stories.js

Closes SAP/fundamental-styles#2119
This PR introduces helper modifier classes that can be added to any element that needs some spacings through paddings or margins.
NA
Margins:
Paddings:
- [n/a] `fd-reset()` mixin is applied to all elements
3. Testing …

feat: introduce Margins and Paddings

---

src/table.scss
stories/table/__snapshots__/table.stories.storyshot
stories/table/table.stories.js

fixes #2042 
Update Table navigation examples; fix the color and background on mouse down
update responsive table navigation icon
>
3. Testing

fix: update table navigation icons and states

---

.storybook/custom/custom.scss
src/avatar-group.scss
stories/avatar-group/__snapshots__/avatar-group.stories.storyshot
stories/avatar-group/avatar-group.stories.js

Closes https://github.com/SAP/fundamental-styles/issues/2091
Part of https://github.com/SAP/fundamental-styles/issues/2153
Added overflow spacing and overflow button accent border. 
3. Testing 

feat: Avatar Group overflow spacing and overflow button border color

---

src/tabs.scss

part of https://github.com/SAP/fundamental-styles/issues/2161
There are added some selectors into tabs component, to make semantic mode work properly
Before:
After:
3. Testing

fix: Semantic tabs color

---

src/object-status.scss

fixes #2164 
specify font-family for large object status
3. Testing

fix: update object status large font-family [ci visual]

---

src/product-switch.scss
src/shellbar.scss
stories/shellbar/__snapshots__/shellbar.stories.storyshot
stories/shellbar/shellbar.stories.js

Part of  https://github.com/SAP/fundamental-ngx/issues/4822 (NGX)
- add example of Shellbar with Side Nav control button aka hamburger menu
- add proper alignment for the button (spacing)
- add fix for the focus color of the buttons used inside Shellbar, including Product Switch toggle
>
3. Testing

fix: add alignment and focus related fixes for Shellbar

---

src/table.scss
stories/table/__snapshots__/table.stories.storyshot
stories/table/table.stories.js

fixes #2182
fixes #2183
fixes #2184
fixes #2185
apply the right color on components in an active table cell
2. Testing

fix: components in active table rows

---

src/flexible-column-layout.scss

DXP related issue
Add z-index so the button is not cut on hover or active
>

fix: add fix for button cutting on hover for Flexible Column Layout

---

src/dynamic-page.scss

Portal related issue
The elements in the Title container of Dynamic Page were not aligned vertically due to padding top added to the title and items being aligned `baseline`.
>

fix: add fix for Dynamic Page title alignment issues

---

src/pagination.scss

Closes SAP/fundamental-styles/issues/1860
left and right arrows for the disabled state will be displayed in  **rgba(51,51,51,0.5)** 
dots between pages will be displayed in **rgb(6, 56, 6);**
For arrows I have applied fd-disabled after fd-link as fd-link is widely used in the framework 
>
ARROW
DOTS
ARROW Left
ARROW Right 
DOTS
- [na] selected state of the element …

fix: pagination colors

---

src/table.scss
stories/table/__snapshots__/table.stories.storyshot
stories/table/table.stories.js

part of https://github.com/SAP/fundamental-ngx/issues/4622
part of https://github.tools.sap/dxp/jukebox/issues/420
There are
- added no-data mode
- responsvie mode borders removed
- word break css included into cells
3. Testing

feat: Add no-data, remove borders from responsive mode

---

src/table.scss

There is some code, that is unnecesary, needs to be removed
- [NA] Responsiveness rules - the component has modifier classes for all breakpoints
- [NA] RTL support
- [NA] only one top level `fd-*` class is used in the file
- [NA] BEM naming …

fix: Remove unnecessary code form table.scss

---

src/pagination.scss

There is some code, that is unnecesary, needs to be removed
- [NA] Responsiveness rules - the component has modifier classes for all breakpoints
- [NA] RTL support
- [NA] only one top level `fd-*` class is used in the file
- [NA] BEM naming …

fix: Remove unnecessary code form pagination.scss 

---

src/toolbar.scss

Closes SAP/fundamental-styles#1155
Added margins for buttons in toolbar overflow 
>
- [na] …

fix: toolbar button not having any margin

---

src/status-indicator.scss
stories/status-indicator/__snapshots__/status-indicator.stories.storyshot
stories/status-indicator/status-indicator.stories.js

changing the BEM to the status indicator and adding link css
>
fd-status-indicator--lg__text and fd-status-indicator--critical__text. 
fd-status-indicator__text--lg  fd-status-indicator__text--critical
- …

fix: change the naming of status indicator classes to follow BEM

---

package-lock.json
package.json

upgrade to theming-base-content version 11.1.28

chore: upgrade to theming-base-content version 11.1.28

---

.storybook/custom/custom.scss
src/resizable-card-layout.scss

Closes #2213 
1. Margin between cards is handled inside component using script. hence to be removed from styles.
2. added z-index for resize handlers
3. added missing "xl" screen size layout padding
>
3. Testing
- na Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

fix: remove margin from Resizable-Card-Layout item

---

src/_listDefinitions.scss
src/_listDropdown.scss
src/popover.scss
stories/select/__snapshots__/select.stories.storyshot
stories/select/select.stories.js

part of https://github.com/SAP/fundamental-styles/issues/2207
There is applied hcange for max width of default dropdown body.
Due to fiori3 `37,5rem` -> `40rem`.
Also there is added larger dropdown - achieved by class `fd-list--large-dropdown`
>
- [Na] focus state of the element follow design spec
- [NA] …

feat: larger dropdown body

---

src/radio.scss

part of https://github.com/SAP/fundamental-styles/issues/2194
Outline is removed from radio button label
3. Testing

fix: Remove outline from radio button

---

src/icons/_settings.scss
stories/icon/__snapshots__/icon.stories.storyshot
stories/icon/data.json

The latest release of SAP-icons version 4.9 has 3 new icons which the current PR is introducing in Fundamental-styles
>
3. Testing
- [na] tested Storybook examples with "CSS Resources" `normalize` option 
- [na] tested Storybook examples with "CSS Resources" `unnormalize` option 

chore: add 3 new SAP icons

---

src/toolbar.scss

Closes SAP/fundamental-styles#1155
This is update for form-label margins
3. Testing

fix: bring back the vertical margin for Form Label in Toolbar

---

stories/icon/BusinessSuiteInAppSymbols/iconBusinessSuite.stories.js
stories/icon/SAPIcons/icon.stories.js
stories/icon/TNTIcons/iconTnt.stories.js

The links to the Project Configuration section that contains instructions on how to include the icons fonts in a project were not working.

docs: update links to project configurations in Icons documentation

---

src/card.scss
src/numeric-content.scss

closes #1729 
Currently fundamental-ngx card component has some styles present in fundamental-ngx, which can be moved to fundamental-styles.
Negative sign placed correctly
Table border removed
3. Testing
- na Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

fix: move card styles from ngx to styles

---

config/postcss-add-fallback.js
config/postcss-remove-fonts.js
package.json

Closes SAP/fundamental-styles#2122
- Moved PostCSS 8 to peerDependencies in package.json;
- Replaced `module.exports = postcss.plugin(name, creator)` with `module.exports = creator`;
- Returned an object with postcssPlugin property containing a plugin name and the Once method;
- Moved plugin code to the Once method;
- Added `module.exports.postcss = true` to the end of the file;
- Removed postcss imports

chore: migrate "add fallback plugin" and "remove font variables" to postCSS v.8

---

src/fundamental-styles.scss

fix: import object-number as part of the whole css file

---

src/file-uploader.scss
stories/file-uploader/__snapshots__/file-uploader.stories.storyshot
stories/file-uploader/file-uploader.stories.js

Part of https://github.com/SAP/fundamental-ngx/issues/5025
- removed `readonly` attribute from File Uploader input and added some css rules associated with this move (text shadow and focus)
- introduced examples in the documentation of File Uploader with error, success, information and warning states.
>
3. Testing
- [NA] Breaking Changes …

fix: remove readonly attribute from File Uploader input and add examples of  File Uploader input states

---

src/user-menu.scss

Fixed https://github.com/SAP/fundamental-styles/issues/2287
Added padding for user menu subheader
3. Testing

fix: add padding for user menu subheader

---

src/avatar-group.scss
stories/avatar-group/__snapshots__/avatar-group.stories.storyshot
stories/avatar-group/avatar-group.stories.js

BREAKING CHANGE: 
- added `.fd-avatar-group__popover-control` class to `.fd-popover__control`
- `role` changed to `img`, added `alt` and `title` instead of `aria-label` for Avatars
Closes: https://github.com/SAP/fundamental-styles/issues/2240
Fixed: 
- focus state of popover-control
- text and border color of "more button"
- [n/a] `fd-reset()` mixin is applied to all elements
3. Testing

fix: Avatar Group popover control focus & more button color

---

src/table.scss

Closes #1948 
Change fixed column border width.
Shift fixed columns down so that bottom border would be visible
>
3. Testing

fix: Align borders properly for fixed columns

---

src/input.scss
src/menu.scss
src/mixins/_states.scss
src/select.scss
src/tabs.scss
src/textarea.scss
src/tree.scss

Closes #1620
Add `@mixin fd-expanded` and update code accordingly
3. Testing

chore: introduce fd-expanded() mixin

---

src/avatar.scss

Closes #2111
Fixed:
* Position of the zoom icon for circle avatar
* Vertical centering for the icons and text inside avatar
>
3. Testing

fix: avatar zoom icon issues

---

src/token.scss

Closes #1731
Change close button padding to vertically center the icon inside.
>
3. Testing

fix: vertically align close button for compact token

---

src/checkbox.scss

Closes #2152 
Make square smaller for compact checkbox, that way browser could evenly center it vertically and horizontally.
>
3. Testing

fix: checkbox make square smaller in order for browser to evenly move it from the center

---

src/step-input.scss

Part of SAP/fundamental-ngx#5025
Changes contains to move move hard coded style from ngx to  style to fix the alignment issue between input box and description.
>
3. Testing

fix: fix the alignment issue between input box and description/unit value for the step input component.

---

src/notification.scss
stories/notification/__snapshots__/notification.stories.storyshot
stories/notification/notification.stories.js

NA
- removed unused and unnecessary classes
- deleted the rule that removes the border bottom from the last notification in the notification list/group
- added margin for every child inside actions, not only for buttons as we can have a popover 
- fixed the RTL rules for the actions
- removed classes: `fd-notification__actions--dismiss`, `fd-notification--tabs` and `fd-notification__actions--popover`
NA
3. Testing

fix: cleanup unused classes in Notifications and minor code refactoring

---

src/avatar-group.scss

Related to https://github.com/SAP/fundamental-ngx/pull/5074
- Additional class for Avatar which could be focusable 
- [n/a] only one top level `fd-*` class is used in the file
- [n/a] Mixins are used for repeatable code (`fd-rtl`, …

chore: added class for focusable avatar in Avatar Group

---

src/carousel.scss

Closes https://github.com/SAP/fundamental-styles/issues/1909
Added shadow for hover state for navigation buttons
>
3. Testing

fix: Carousel - add shadow for hover state for controls [ci visual]

---

src/popover.scss
stories/popover/__snapshots__/popover.stories.storyshot
stories/popover/popover.stories.js

Closes https://github.com/SAP/fundamental-styles/issues/2153
Add `overflow: hidden` for inner elements of `fd-popover__body` which will prevent inner component's shadow to overlay outer one.
>
3. Testing

fix: Avatar group - do not overlay outer shadow with inner component's shadow [ci visual]

---

src/dynamic-page.scss

Closes SAP/fundamental-styles#2362
`align-items` was applied for the `--md` modifier on breadcrumbs, which is no longer needed as all elements are centre-aligned. This PR removes this unnecessary code.
>
3. Testing
- [] Verified all styles in IE11
- [n/a] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Cha …

fix: remove unnecessary alignment for breadcrumbs in Dynamic Page

---

src/table.scss
stories/table/__snapshots__/table.stories.storyshot
stories/table/table.stories.js

Closes SAP/fundamental-styles#2360
A table can be displayed inside a card, and that time outer border of the table should not visible, otherwise it will reserve some space. This PR adds fd-tabel-no border class inside table-component which hides the outer border when applied.
Requirement coming from below comment:
https://github.com/SAP/fundamental-ngx/pull/5015#pullrequestreview-657228575
3. Testing
- na Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

fix: class added for no outer border for table

---

src/slider.scss

Closes https://github.com/sap/fundamental-ngx/issues/4604
Fixed slider ticks for windows
3. Testing

fix: Slider - fix ticks for windows [ci visual]

---

src/status-indicator.scss
stories/status-indicator/__snapshots__/status-indicator.stories.storyshot
stories/status-indicator/status-indicator.stories.js

Closes: https://github.com/SAP/fundamental-styles/issues/2331
Removal of extra margin on the labelled status indicator
- [N/A]  All values are in `rem`
- [N/A]  Text elements follow the truncation rules
- [N/A] pressed state of the element follow design spec
- [N/A] Responsiveness rules - the component has modifier classes for all breakpoints
- [N/A] Includes Compact/Cosy/Tablet design
- [N/A] RTL support
- …

fix: removal of extra margin on the labelled status indicator

---

src/quick-view.scss

Part of SAP/fundamental-ngx#4963
- Added `display: inherit`

fix: quick view inherit display for fit in parent block

---

config/bundlesize.json
src/icon.scss
src/icons/_settings.scss
src/mixins/_icons.scss
stories/icon/BusinessSuiteInAppSymbols/__snapshots__/iconBusinessSuite.stories.storyshot
stories/icon/BusinessSuiteInAppSymbols/iconBusinessSuite.stories.js
stories/icon/SAPIcons/__snapshots__/icon.stories.storyshot
stories/icon/SAPIcons/icon.stories.js
stories/icon/TNTIcons/__snapshots__/iconTnt.stories.storyshot
stories/icon/TNTIcons/iconTnt.stories.js

Closes https://github.com/SAP/fundamental-styles/issues/1894
Add status indicators for icons
>
3. Testing

feat: Icons - add status enumeration

---

src/table.scss
stories/table/__snapshots__/table.stories.storyshot
stories/table/table.stories.js

Part of https://github.com/SAP/fundamental-ngx/issues/4415
We have applied a special right border to the last fixed column by `.class:last-of-type` selector. That's working since we have only one fixed column. Basically, that selector should not be applied to the class as it's working with the type (of the element). The additional class created for that purpose. 
Nothing changed in the examples. It's more like improvements for the future (when we will provide the ability to use multiple fixed columns), for the NGX library (where we do provide multiple fixed columns but there is a special border not shown).
3. Testing

fix: table fixed (freeze) column border fix

---

src/form-label.scss
src/form-layout-grid.scss
stories/form-grid/__snapshots__/form-grid.stories.storyshot
stories/form-grid/form-grid.stories.js

Closes  #2262 
Added a new modifier class to fd-row to achieve even alignment of its elements:`fd-row--top` in a form. 
Form Grid aligns items vertically to the center when according to the guideline it should align to the top.
*When you have more than one column and the number of the fields is not equal for each column fields are aligned to the middle instead of to the top*:
*According to the guideline it should be aligned to the top*:
3. Testing

fix: form grid aligns items vertically to the top

---

src/avatar.scss
src/icon.scss
src/mixins/_states.scss
stories/avatar/__snapshots__/avatar.stories.storyshot
stories/avatar/avatar.stories.js
stories/icon/SAPIcons/__snapshots__/icon.stories.storyshot
stories/icon/SAPIcons/icon.stories.js

Closes SAP/fundamental-styles #2443 
Providing focus options for icon and avatar components when used with tabindex for accessibility purpose.
No Focus 
Displaying focus when tabindex="0"
3. Testing

fix: provide focus for avatar and icon components

---

config/bundlesize.json
src/_listNavigationItem.scss
src/fundamental-styles.scss
src/icon-tab-bar.scss
src/mixins/_mixins.scss
src/theming/sap_fiori_3.scss
src/theming/sap_fiori_3_dark.scss
src/theming/sap_fiori_3_hcb.scss
src/theming/sap_fiori_3_hcw.scss
src/theming/sap_fiori_3_light_dark.scss
src/vertical-nav.scss
stories/icon-tab-bar/__snapshots__/icon-tab-bar.stories.storyshot
stories/icon-tab-bar/icon-tab-bar.stories.js

Closes SAP/fundamental-styles#2073
Introduce new Icon Tab Bar which is similar to the existing Tabs component with the following extra features
- Single Click Area
- Two Click Areas
- Semantic tab bar (with icons and colors and theming)
- Shell Navigation color delta
- Dropdown menu with/without separators
- IconTabBar with badges
- Badge inside dropdown mene
3. Testing

feat: introduce new Icon Tab Bar component

---

.storybook/custom/custom.scss
src/carousel.scss
stories/carousel/__snapshots__/carousel.stories.storyshot
stories/carousel/carousel.stories.js

Related to Issue SAP/fundamental-ngx#5025
Moving css present for carousel component in Ngx to styles.
navigation button in content area will be visible on hover on carousel.
>
3. Testing

fix: show navigation button on hover in carousel content area, carousel component css moved from ngx

---

src/panel.scss

fixes #2482 
add panel content bottom border
- [na] only one top level `fd-*` class is used in the file
- [na] BEM naming convention is used
- [na] Mixins are used for …

fix: add bottom border to panel content

---

src/_listNavigationItem.scss

Closes SAP/fundamental-styles#2521
Update css selectors to compile correctly.
- n/a All values are in `rem`
- n/a Text elements follow the truncation rules
- n/a hover state of the element follow design spec
- n/a focus state of the element follow design spec
- n/a active state of the element follow design spec
- n/a selected state of the element follow design spec
- n/a selected hover state of the element follow design spec
- n/a pressed state of the element follow design spec
- n/a Responsiveness rules - the component has modifier classes for all breakpoints
- n/a Includes Compact/Cosy/Tablet design
- n/a RTL support
- n/a only one top level `fd-*` class is used in the file
- n/a BEM …

fix: update css selector for list item [ci visual]

---

src/list-grid.scss

Closes : https://github.com/SAP/fundamental-styles/issues/2523
rtl support for the grid list highlighter for status.
>
- [N/A]  All values are in `rem`
- [N/A]  Text elements follow the truncation rules
- [N/A] selected hover state of the element follow …

fix: rtl support for the grid list highlighter for status

---

src/tabs.scss

Part of [#5128](https://github.com/SAP/fundamental-ngx/pull/5735)
>
- [n/a] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
3. Testing
4. …

fix: change tabs styles for routerLink

---

src/bar.scss
stories/bar/__snapshots__/bar.stories.storyshot
stories/bar/bar.stories.js

Closes #2479 
Added modifier class `fd-bar__element--title` class to bar component when title is placed as first element to add 0.5rem padding to it as per visual core.
Before:
```
<span aria-label="text">TEXT</span>
```
After:
```
<span class="fd-bar__element fd-bar__element--title" aria-label="text">TEXT</span>
```
3. Testing

fix: provide padding if title is first element in bar

---

src/theming/sap_fiori_3.scss
src/theming/sap_fiori_3_dark.scss
src/theming/sap_fiori_3_hcb.scss
src/theming/sap_fiori_3_hcw.scss
src/theming/sap_fiori_3_light_dark.scss
src/toolbar.scss
stories/toolbar/__snapshots__/toolbar.stories.storyshot
stories/toolbar/toolbar.stories.js

fixes: #2082 
few fixes:
- delta theming for toolbar
- typo in 1 css variable
- update info toolbar height (cozy and compact have same height)
3. Testing

fix: update toolbar styling

---

src/slider.scss
stories/slider/slider.stories.js

Closes SAP/fundamental-styles#2503
Added wrapper for slider to prevent getting out of the strip edges of slider track. (look related issue)
Also fixed position of "before element" of handle for rtl.
>
3. Testing

fix: added wrapper for slider [ci visual]

---

src/alert.scss

Relates to https://github.com/SAP/fundamental-ngx/issues/5790
Changed position of the icons for alert component do render in the correct position.
3. Testing

fix: correct position for rtl icons for alert component

---

src/theming/sap_fiori_3.scss
src/theming/sap_fiori_3_dark.scss
src/theming/sap_fiori_3_hcb.scss
src/theming/sap_fiori_3_hcw.scss
src/theming/sap_fiori_3_light_dark.scss

Closes SAP/fundamental-styles#2509
Updated border width so it won't jump on hover or focus.
3. Testing

fix: update border width for combobox button

---

src/slider.scss

Closes SAP/fundamental-styles#2503
Added additional padding to prevent hiding  of outline of handle inside block with overflow: hidden.
>
3. Testing

fix: added additional panding for slider [ci visual]

---

src/wizard.scss

fixes #2546 
Reset was bringing `box-sizing: border-box` to wizard steps in the progress bar where `content-box` should have been used, to accommodate for padding.
Before:
After:

fix: box-sizing of wizard step in progress bar [ci visual]

---

stories/bar/__snapshots__/bar.stories.storyshot
stories/bar/bar.stories.js

Closes #2528 
Updated documention examples with title component as first element in bar.
Before:
```
<div class="fd-bar__element">  
<span class="fd-bar__element--title" aria-label="text">TEXT</span>
</div>
```
After:
```
<div class="fd-bar__element fd-bar__element--title">
<h6 class="fd-title fd-title--h6" aria-label="text">TEXT</h6>
</div>
```
3. Testing

fix: refactor bar documentation as suggested

---

src/popover.scss

Adds the popover outline when the control is tabbed to
before:
after:

fix: popover outline focus-visible

---

src/icon-tab-bar.scss
stories/icon-tab-bar/__snapshots__/icon-tab-bar.stories.storyshot
stories/icon-tab-bar/icon-tab-bar.stories.js

Part of SAP/fundamental-styles#2210
Shell Navigation Tabs are a type of Icon Tab Bar with some color modifications so it can be used with Tool Header and Shell Bar. Once this PR and https://github.com/SAP/fundamental-styles/pull/2550 are merged I will create documentation for the entire Horizontal Navigation topic. There won't be more css needed, just putting 2 components together (Tool Header+Shell Navigation Tabs) in a documentation page.
3. Testing

feat: introduce navigation for IconTabBar

---

src/_listBase.scss

Closes SAP/fundamental-styles#2554
The line height property was restricting the list item height thereby truncating the text visibility. This property is not specified in the visual specs for List(or User Menu) and hence this PR removes this property.
>
3. Testing …

fix: remove line height to avoid List item title from getting cut

---

src/feed-input.scss

part of: https://github.com/SAP/fundamental-ngx/issues/5025
adding placeholder color for text area and adding rtl to the button
>
3. Testing
- [NA] Storybook documentation has been created/updated

fix: adding placeholder color and adding rtl to the button

---

src/list-grid.scss
stories/list-grid/__snapshots__/list-grid.stories.storyshot
stories/list-grid/list-grid.stories.js

part of https://github.com/SAP/fundamental-ngx/issues/5025
Breaking Change:
Added a modifier class `fd-grid-list__btn-navigation` to the navigation button to support RTL.
wiki link [here](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes#grid-list-2525)
This fixes and moves the grid list styles present in fundamental-ngx.
1. fix action button in Rtl mode
2. fix color for decline button on active hover
3. toolbar paddings
3. Testing
- [NA] Storybook documentation has been created/updated

fix: fix action button in Rtl mode for grid list component. Move grid list styles from Ngx.

---

src/card.scss

Closes SAP/fundamental-styles#2514
The Card header focus outline didn't have the same offset on all sides. Replaced the outline with fake focus, a similar approach used in List and Tiles.  
- [na] only one top level `fd-*` class is used in the file
- [na] BEM naming convention is used
- [na] A11y support - keyboard support, …

fix: add fix for Card header focus offset

---

stories/calendar/__snapshots__/calendar.stories.storyshot
stories/calendar/calendar.stories.js

Part of SAP/fundamental-styles#2460
hardcode the size of the Calendar container so it shows the component in Portrait mode all the time in the documentation.

docs: add fixed container size for Calendar in portrait mode

---

src/toolbar.scss

part of SAP/fundamental-styles#2460
When the GridList Item requires multi-selection and/or any kind of actions they are placed inside a Toolbar at the top, before the content area. The problem was that Toolbar didn't have a min-height, just a height. This was resulting in Toolbar having the same height as its content (buttons). The fix was to add min-height same as the height in cozy and compact mode.

fix: add fix for correct height of Grid List actions

---

src/checkbox.scss

Part of SAP/fundamental-styles#2460
Center horizontally the "square" icon used for tristate chackbox
- [na] only one top level `fd-*` class is used in the file
- [na] BEM naming convention is used
- [na] Mixins are used for …

fix: center tristate icon horizontally

---

.storybook/static/preview-head.js
src/_listDefinitions.scss
src/object-list.scss
stories/object-list/__snapshots__/object-list.stories.storyshot
stories/object-list/object-list.stories.js

Closes #2520 
Active state of Object List should has value as per fiori specifications.
3. Testing

fix: add active state background color for object list as per spec

---

src/fixed-card-layout.scss

Closes https://github.com/SAP/fundamental-styles/issues/2592
removed not-required word-break style which is causing style leak.
It is not needed any more as original issue for which this was added, has been addressed in table component.
Now column text in table does not overflow, but wraps.
so word break is not needed, it can be safely removed.
3. Testing
- [NA] Storybook documentation has been created/updated

fix: remove word-break from fixed-card-layout, leaking outside to other components

---

config/bundlesize.json
src/button.scss

Part of SAP/fundamental-styles#2460
Focusable disabled should get a focus outline for a11y purposes. This is achieved by using `aria-disabled` and `is-disabled` class. The element is styled as disabled but it gets a focus and is read by the screenreader. If `disabled` is used, the button does not get focus.

fix: add focus to focusable disabled button

---

src/_listNavigation.scss

fix: add fix for RTL Object List Item With Row Selection And Navigation

---

src/toolbar.scss
stories/dynamic-page/__snapshots__/dynamic-page.stories.storyshot
stories/dynamic-page/dynamic-page.stories.js
stories/facets/__snapshots__/facets.stories.storyshot
stories/facets/facets.stories.js
stories/toolbar/__snapshots__/toolbar.stories.storyshot
stories/toolbar/toolbar.stories.js

Part of SAP/fundamental-ngx#5025
Refactoring toolbar styles as part of ngx style clean up task.
- Modified class name as per BEM naming convention `fd-toolbar__overflow`
- Added modifiers for overflow body elements `fd-toolbar__button`, `fd-toolbar__button--menu`
- Changed `fd-toolbar__overflow__label` class name to `fd-toolbar__overflow-label` 
- Changed `fd-toolbar__overflow__form__label` class name to `fd-toolbar__overflow-form-label` with modifier class  `fd-toolbar__overflow-form-label--text`
3. Testing
- [NA] Verified all styles in IE11
- [NA] Updated tests

fix: refactor toolbar styles as part of ngx style clean up task

---

src/rating-indicator.scss
stories/rating-indicator/__snapshots__/rating-indicator.stories.storyshot
stories/rating-indicator/rating-indicator.stories.js

Closes #2008.
Non-interactive mode for the Rating Indicator component, styles refactoring.
3. Testing

feat: rating indicator non-interactive mode

---

src/toolbar.scss

Closes SAP/fundamental-styles#2622
Fixed active state for info toolbar
3. Testing

fix(core): fixed wrong styles for toolbar active state [ci visual]

---

src/_nested-list.scss
stories/side-navigation/__snapshots__/side-navigation.stories.storyshot
stories/side-navigation/side-navigation.stories.js

Closes https://github.com/SAP/fundamental-styles/issues/2618
Breaking Change:
Added a new modifier class .fd-nested-list--popover to display nested list inside a popover.
Nested list popover has some styles issue in fundamental-ngx.
It is because `fd-popover` component in `fundamental-ngx` is using class `fd-popover__popper` and not using class `fd-popover__body`.
To fix the issue, some modifier class needs to be created here.
3. Testing

fix: introduce modifier class to fix nested-list-popover

---

src/form-layout-grid.scss

Related to SAP/fundamental-ngx[#6062](https://github.com/SAP/fundamental-ngx/pull/6062)
Added fd-col-compact class into form-layout-grit to have possibility change padding using attribute [compact]="true" or "Content Density"  on home page when user selects Compact
This issue is related to [#4906](https://github.com/SAP/fundamental-ngx/issues/4906)
3. Testing …

fix: add compact class

---

src/input-group.scss

targets [#5938](https://github.com/SAP/fundamental-ngx/issues/5938)
Deleted not needed styles for input-group in order to avoid values changing position(padding) inside the field
3. Testing

fix: correct style in input-group 

---

src/mixins/_mixins.scss
stories/link/__snapshots__/link.stories.storyshot
stories/link/link.stories.js

fix: focus indication provided for Inverted Link [ci visual]
Closes: https://github.com/SAP/fundamental-styles/issues/2697
In high contrast white theme, focus indication provided for Inverted Link does not satisfy the minimum contrast ratio of 7:1
3. Testing

fix: focus indication provided for Inverted Link.

---

src/fundamental-styles.scss
src/horizontal-navigation.scss
src/icon-tab-bar.scss
stories/horizontal-navigation/__snapshots__/horizontal-navigation.stories.storyshot
stories/horizontal-navigation/horizontal-navigation.stories.js
stories/icon-tab-bar/__snapshots__/icon-tab-bar.stories.storyshot
stories/icon-tab-bar/icon-tab-bar.stories.js

Closes SAP/fundamental-styles#2668
In the current PR:
- introduced Flat Navigation (Part of ShellNavigation)
- refactored Horizontal Navigation to match the correct deltas from IconTabBar
- introduced a wrapper class (.fd-horizontal-navigation) for IcontTabBar and ToolHeader that applies box-shadow around the two elements.
- introduced a wrapper element with class ".fd-horizontal-navigation" for Tool Header and Navigation IconTabBar
- introduced an additional modifier class ".fd-icon-tab-bar--navigation-horizontal" to IconTabBar when used in Horizontal Navigation
3. Testing
- [na] tested Storybook examples with "CSS …

fix: introduce Flat Navigation, refactor Horizontal Navigation

---

src/form-layout-grid.scss

Closes https://github.com/sap/fundamental-ngx/issues/6389
Removed `form layout grid` unnecessary styles
- [n/a] only one top level `fd-*` class …

fix: form layout grid, remove unnecessary styles

---

src/layout-grid.scss
stories/layout-grid/__snapshots__/layout-grid.stories.storyshot
stories/layout-grid/layout-grid.stories.js

Closes #2612.
Negative margins were applied to the inappropriate elements that make rows wider than container and cause appearing the scrollbars. 
Gutter between rows was set by padding for the column not by a margin for the row.
3. Testing

fix: layout grid bug fixes, improvements, refactoring

---

src/object-marker.scss
stories/object-marker/__snapshots__/object-marker.stories.storyshot
stories/object-marker/object-marker.stories.js

Closes SAP/fundamental-styles https://github.com/SAP/fundamental-styles/issues/2729
This PR change contains adding focus to clickable object marker.
>
3. Testing

fix: add focus style on clickable object marker

---

src/object-status.scss

Closes SAP/fundamental-ngx/#6544
When focused, object status had undesired outline. It should be removed. The problem was reproducible in fundamental-ngx repo
>
3. Testing
- [n/a] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been …

fix(core): remove object status outline

---

src/table.scss

Closes SAP/fundamental-styles#2746
Fixed checkbox column in the table in condensed mode.
>
Don't look at the padding before the name, it's fixed in the scope of [NGX #6716](https://github.com/SAP/fundamental-ngx/pull/6716)
3. Testing

fix: table condensed checkbox

---

src/object-status.scss

Closes SAP/fundamental-ngx/#6544
When focused, object status had undesired outline. It should be removed. The problem was reproducible in fundamental-ngx repo
>
3. Testing
- [n/a] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been …

fix(core): remove object status outline [ci visual]

---

src/dialog.scss

Closes SAP/fundamental-ngx#6332
Fixed alignment of the resize handle 
3. Testing

fix: dialog resize handle alignment [ci visual]

---

src/styles/icon-tab-bar.scss
src/styles/mixins/_mixins.scss
stories/icon-tab-bar/__snapshots__/icon-tab-bar.stories.storyshot
stories/icon-tab-bar/icon-tab-bar.stories.js

is done as part of https://github.com/SAP/fundamental-ngx/issues/4093
Styles for tab reordering currently is not per spec. 
Should have proper icon for "insert after" state and border for "insert into" (see screenshots below)
Additionally:
- removed `fd-icon-tab-bar__item--dnd-separator-vertical` class. It's not needed, because vertical state is now determined automatically. It's not a breaking change, because `fd-icon-tab-bar__item--dnd-separator` was required to be specified with `-vertical` one;
- added fd-icon-tab-bar__item--dnd-separator-end` class. It allows to position the separator after the last element, which wasn't possible before
- created section in documentation describing drag&drop styles
> **NOTE:** If you've made any style changes, please provide appropriate screenshots …

fix(styles): icon tab bar drag&drop styles [ci visual]

---

src/styles/fundamental-styles.scss
src/styles/variables.scss

Closes #2837
remove `variables.css`, `variables-sap_fiori_3*.css` files from `dist` folder 
our bundled CSS files(e.g. `fundamental-sap_fiori_3_dark.css`) for all the themes were having wrongly built with fiori 3 light colors.
3. Testing

fix(styles): dark, hcb, hcw bundled CSS to contain the right colors 

---

src/styles/list-grid.scss

Closes #2853 
Added word break for list grid item body.
3. Testing
- n/a Storybook documentation has been created/updated
- n/a Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

fix(styles): add word break [ci visual]

---

src/styles/list-grid.scss

Closes #2852 
Added correct outline color when focusing on active element
3. Testing
- n/a Storybook documentation has been created/updated
- n/a Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

fix(styles): add correct outline color in Grid List

---

src/styles/icon-tab-bar.scss

Covering case when all items are hidden.
3. Testing

fix(styles): empty icon tab bar

---

src/styles/dialog.scss
src/styles/flexible-column-layout.scss
src/styles/mixins/_mixins.scss
stories/dialog/dialog.stories.js

Is being done as part of the fix for https://github.com/SAP/fundamental-ngx/issues/5286
Added styles for dialog without backdrop
>
3. Testing

fix: static dialog nobackdrop position fix [ci-visual]

---

src/styles/table.scss

related to SAP/fundamental-ngx#7013
Currently a focus appears on cell click. Removing it
>
3. Testing

fix: table - remove cell outline [ci visual]

---

src/styles/code.scss

fix(styles): add padding for inline code [ci visual]

---

src/styles/checkbox.scss

as part of https://github.com/SAP/fundamental-ngx/issues/5791
set `border-style: initial` to prevent broken outine when it selects checkbox via VoiceOver
>
3. Testing
- [n/a] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated …

fix(styles): checkbox broken outline voiceover [ci visual]

---

src/styles/checkbox.scss
src/styles/mixins/_forms.scss
stories/checkbox/__snapshots__/checkbox.stories.storyshot
stories/checkbox/checkbox.stories.js

none
Checkbox was using icon for the square that represents the tri-state. This was causing a lot of alignment issues and the new set of icons changed the look of this icon so we can no longer rely on it for the tri-state.
- **Checkbox:** introduced a new element with a class `.fd-checkbox__label-container` that is necessary for the fake focus and the new way of implementing the tri-state.
Before:
```
<label class="fd-checkbox__label">
<span class="fd-checkbox__text">Apple</span>
</label>
```
Now:
```
<label class="fd-checkbox__label">
<div class="fd-checkbox__label-container">
<span class="fd-checkbox__text">Apple</span>
</div>
</label>
```
- **Checkbox:** introduced a new modifier class for the label `.fd-checkbox__label--required` for when the Checkbox is a required …

fix(styles): refactor checkbox to use a square not an icon for tristate

---

src/fn/fn-input.scss

On some operating systems supporting sub-pixel rendering the browser may
inconsistently approximate the height/widths of boxes across zoom level. The
issue becomes apparent when multiple controls are placed together (e.g.,
table rows, tags, input boxes) as the user zooms in/out.
Specifying the border-width property is a solution that does not involve
using future CSS specs or GPU-based calculations.
Zoom level 80% - but the same issue occurs across multiple zoom levels.
3. Testing
- [na] tested Storybook examples with "CSS Resources" `normalize` option 
- [na] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [na] Verified all styles in …

fix(fn): inconsistent text field borders across zoom levels [ci visual]

---

src/fn/fn-tag.scss

On some operating systems supporting sub-pixel rendering the browser may inconsistently approximate the height/widths of boxes across zoom level. The issue becomes apparent when multiple controls are placed together (e.g., table rows, tags, input boxes) as the user zooms in/out.
Specifying the border-width property is a solution that does not involve
using future CSS specs or GPU-based calculations.
This issue occurs across different zoom levels.
3. Testing
- [na] tested Storybook examples with "CSS Resources" `normalize` option 
- [na] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [na] Updated tests
- [na] …

fix(fn): consistent highlights of tags across zoom levels [ci visual]

---

src/fn/fn-select.scss

On some operating systems supporting sub-pixel rendering the browser may
inconsistently approximate the height/widths of boxes across zoom level. The
issue becomes apparent when multiple controls are placed together (e.g.,
table rows, tags, input boxes) as the user zooms in/out.
Specifying the border-width property is a solution that does not involve
using future CSS specs or GPU-based calculations.
-  All values are in `rem`
- Text elements follow the truncation rules
- hover state of the element follow design spec
- focus state of the element follow design spec
- active state of the element follow design spec
-  pressed state of the element follow design spec
- Responsiveness rules - the component has modifier classes for all breakpoints
- Includes …

fix(fn): inconsistent selected item border in Select across zoom levels

---

src/fn/_fn-variables.scss
src/fn/fn-input.scss
src/fn/fn-select.scss
src/fn/fn-tabs.scss
src/fn/fn-tag.scss

Select, Input, Tabs and Tags components use the same value for border-width (0.125rem) and border-style (solid) so I created variables in `_fn-variables.scss` file for easier maintenance.

fix(fn): move border style and width to variables [ci visual]

---

src/styles/mixins/_mixins.scss
src/styles/pagination.scss
stories/pagination/__snapshots__/pagination.stories.storyshot
stories/pagination/pagination.stories.js
stories/table/__snapshots__/table.stories.storyshot
stories/table/table.stories.js

Part of https://github.com/SAP/fundamental-ngx/issues/7172
Pagination components styles update due to changed specifications.
Please check the pagination component examples. There are too many changes to place here.
https://deploy-preview-2912--fundamental-styles.netlify.app/?path=/docs/components-pagination--first-page
https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes#pagination-2912

fix(styles): pagination styles update

---

src/styles/menu.scss

Corrected selection for menu component
It needs for fundamental-ngx in the case when we use fdp-menu-item component instead of li tag
2. The code follows fundamental-styles code standards …

fix: fix selection in menu styles

---

src/styles/select.scss

* Select text label's `min-width` fix accordingly to the Fiori 3 specifications. 
Since the select inherits input's styles appropriate styles were applied
* Cozy `2.75rem`
* Compact\condensed `2rem`
* Code refacoring.

fix: select min-width

---

src/fn/_fn-new-variables.scss
src/fn/_fn-settings.scss

Added a new file containing variables for colors, box-shadows and borders. It's not modifying the existing `_fn-variables.scss` file as we now have more color variations and different way of naming the colors.
Before: `$fn-color-grey-1` ... `$fn-color-grey-9` (9 variations)
Now: `$fn-color-grey-50` ... `$fn-color-grey-900` (11 variations)
For shadows:
Before: `$fn-shadow-grey-xs`, `$fn-shadow-grey-small`, `$fn-shadow-grey-medium`, `$fn-shadow-grey-large`
`$fn-shadow-grey-xl`
Now: `$fn-shadow-grey-level-0` and `$fn-shadow-grey-level-1`
We will continue adding variables to this file and at some point, when all components are updated with the new design we will get rid of `_fn-variables.scss` file.

fix(fn): add new color variables

---

src/styles/form-layout-grid.scss

Closes #2918 
Added text alignment for form label.
3. Testing
- [ x] Updated tests

fix: fix correct label text placement [ci visual]

---

src/fn/_fn-new-variables.scss
src/fn/_fn-variables.scss
src/fn/fn-button.scss
src/fn/fn-checkbox.scss
src/fn/fn-input.scss
src/fn/fn-radio.scss
src/fn/fn-search.scss
src/fn/fn-segmented-button.scss
src/fn/fn-select.scss
src/fn/fn-switch.scss
src/fn/fn-tabs.scss
src/fn/fn-tag.scss
src/fn/fundamental-next.scss
stories/fn-button/__snapshots__/fn-button.stories.storyshot
stories/fn-button/fn-button.stories.js

Updated the design and types of the buttons per latest design. 
Added segmented button.
updated modifier classes to follow the naming in the design 
**Before:**
secondary | fn-button--secondary
flat | fn-button--flat
outline | fn-button--outline
naked | fn-button--naked
link | fn-button--link
**After:**
emphasized (primary) | fn-button--emphasized
ghost (secondary) | fn-button--ghost
neutral (secondary) | fn-button--neutral
transparent (layout) | fn-button--transparent
accept (semantic) | fn-button--accept
success (semantic) | fn-button--success
attention (semantic) | fn-button--attention
critical (semantic) | fn-button--critical
reject (semantic) | fn-button--reject
negative (semantic) | fn-button--negative
toggled (semantic) | fn-button--toggled

fix(fn): update Button component to latest Fiori Next design

---

stories/fn-button/__snapshots__/fn-button.stories.storyshot
stories/fn-button/fn-button.stories.js

Per discussion with the designers I changed the way we show the button types in the documentation

docs(fn): update the documentation examples for FN Buttons

---

src/fn/fn-button.scss

Designers confirmed that the spacing between button text and icon is 4px (0.25rem) so now we are updating Fiori Next Button with the correct value.

fix(fn): update the spacing between text and icon in FN Button 

---

src/fn/_fn-mixins.scss
src/fn/_fn-new-variables.scss
src/fn/fn-button.scss
src/fn/fn-checkbox.scss
src/fn/fn-fieldset.scss
src/fn/fn-radio.scss
src/fn/fundamental-next.scss
stories/fn-toggles/__snapshots__/fn-toggles.stories.storyshot
stories/fn-toggles/fn-toggles.stories.js

- update Radio buttons and Checkbox to latest Fiori Next design
- introduce `read-only` and `display` states
- introduce a new class `.fn-fieldset`  for the `<fieldset>` wrapper to form Radio group and Checkbox group. 
`.fn-checkbox--group` modifier class is no longer used for checkbox and radio button groups.
New markup for checkbox and radio button groups.
Before:
```
<div style="width: 10rem">
<label class="fn-checkbox fn-checkbox--group" tabindex="0">
<input class="fn-checkbox__input" type="checkbox" checked="checked" tabindex="-1">
<span class="fn-checkbox__checkmark"></span>
<span class="fn-checkbox__label">First</span>
</label>
<label class="fn-checkbox fn-checkbox--group" tabindex="0">
<input class="fn-checkbox__input" type="checkbox" tabindex="-1">
<span …
```

fix(fn): update Radio and Checkbox to latest FN design [ci visual]

---

src/fn/_fn-mixins.scss
src/fn/_fn-new-variables.scss
src/fn/fn-generic-tag.scss
stories/fn-generic-tag/__snapshots__/fn-generic-tag.stories.storyshot
stories/fn-generic-tag/fn-generic-tag.stories.js

part of https://github.com/SAP/fundamental-styles/issues/2928
Introduce new Fiori Next Generic Tag component with positive, critical, negative and info states.

feat(fn): introduce Generic Tag component

---

src/styles/carousel.scss

part of [#5765](https://github.com/SAP/fundamental-ngx/issues/5765) 
>
- [n/a] `fd-reset()` mixin is applied to all elements
3. Testing
- [n/a] Storybook documentation has …

fix(styles): horizontal scroll remove in carousel [ci visual]

---

src/styles/progress-indicator.scss
stories/progress-indicator/progress-indicator.stories.js

Small fixes that enable correct overflow behavior for the progress indicator text, mostly on small screens.
Before:
After:

fix(styles): fix issues with progress indicator overflow text wrapping [ci visual]

---

src/styles/rating-indicator.scss
stories/rating-indicator/__snapshots__/rating-indicator.stories.storyshot
stories/rating-indicator/rating-indicator.stories.js

Fixed rating-indicator styles for `Half values` state
>
2. …

fix: rating-indicator styles [ci visual]

---

src/fn/_fn-new-variables.scss
src/fn/fn-progress-bar.scss
src/fn/fn-slider.scss
src/fn/fundamental-next.scss
stories/fn-progress-bar/__snapshots__/fn-progress-bar.stories.storyshot
stories/fn-progress-bar/fn-progress-bar.stories.js
stories/fn-slider/__snapshots__/fn-slider.stories.storyshot
stories/fn-slider/fn-slider.stories.js

part of https://github.com/SAP/fundamental-styles/issues/2928
1. Refactored Slider component per latest design
2. Introduced Range Slider
3. Introduced Progress Bar
- removed `.fn-slider--vertical` modifier class
- removed `.fn-slider__dot` and `.fn-slider__dot--active`. Now using ::before and ::after 
- removed `.fn-slider__handle-wrapper`
Before:
```
<div class="fn-slider">
<div class="fn-slider__dot fn-slider__dot--active"></div>
<div class="fn-slider__track">
<div class="fn-slider__handle-wrapper">
<div class="fn-slider__handle">
<span class="sap-icon sap-icon--megamenu"></span>
<span class="sap-icon sap-icon--megamenu"></span>
</div>
</div>
<div class="fn-slider__track-range" ></div>
</div>
<div class="fn-slider__dot"></div>
</div>
```
Now:
```
<div …
```

feat(fn): refactor Slider and introduce Range Slider and  Progress Bar

---

src/fn/_fn-new-variables.scss
src/fn/fn-link.scss
stories/fn-link/__snapshots__/fn-link.stories.storyshot
stories/fn-link/fn-link.stories.js
stories/fn-title/__snapshots__/title.stories.storyshot
stories/fn-title/title.stories.js

none
Code improvements:
- Link: remove the focus outline on tab when the link is disabled, corrected the states and removed the default outline as it was resulting in the wrong color on focus
- Link: moved border-radius value to a variable and used mixin for horizontal padding
Docs improvements:
- added role to the link when it's used with aria-disabled. For more info you can read here: https://www.scottohara.me/blog/2021/05/28/disabled-links.html
- for Title changed a bit the text so it's more clear for the user which heading is used.

fix(fn): add fix for Link states and docs improvements for Title

---

src/styles/pagination.scss
stories/pagination/__snapshots__/pagination.stories.storyshot
stories/pagination/pagination.stories.js

Pagination component styles update due to the new design.
Too many changes, please see the doc page.
- If > 9 pages then 9 elements should be shown - including page links, more, current page input. Otherwise, all pages should be shown, use the link instead of input with `.is-active` class or `aria-selected="true"` attribute for the current page. Input should still be present to be shown in the mobile mode, but it's hidden in desktop mode if < 9 pages.
- Add an additional label with class `.fd-pagination__label` after the input in the mobile mode with the number of pages available.
See on wiki page [breaking changes](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes#pagination-2973).

fix(styles): pagination component update due to new designs

---

src/styles/pagination.scss

Remove from displaying active page link if pagination component in long (> 9 pages) mode. This needed to avoid any extra code logic on ngx side when showing pagination component.

fix: remove active page link when in long mode

---

src/styles/carousel.scss
src/styles/mixins/button/_button-helper.scss
src/styles/popover.scss
src/styles/slider.scss
src/styles/tree.scss

fixes: #2926 
replace focus style hardcoded value with the right theming variable in carousel, button, popover, slider, and tree

fix(styles): use the theming variable for focus style

---

src/fn/_fn-mixins.scss
src/fn/fn-nested-button.scss
src/fn/fn-tabs.scss
stories/fn-tabs/__snapshots__/fn-tabs.stories.storyshot
stories/fn-tabs/fn-tabs.stories.js

Refactor Tabs component to match latest design
- removed classes: `.fn-tabs--individual`, `.fn-tabs--line`
- added new classes: `.fn-tabs--positive`, `.fn-tabs--critical`, `.fn-tabs--negative`, `.fn-tabs--multi-instance`, `.fn-tabs__icon`, `.fn-tabs__text`, `.fn-tabs__button`
Before:
```
<ul class="fn-tabs" role="tablist">
<li role="tab" tabindex="0" class="fn-tabs__item fn-tabs__item--selected">One</li>
<li role="tab" tabindex="0" class="fn-tabs__item">Two</li>
</ul>
```
After:
```
<ul class="fn-tabs" role="tablist">
<li role="tab" tabindex="0" class="fn-tabs__item fn-tabs__item--selected">
<div class="fn-tabs__icon">
<span class="sap-icon sap-icon--calendar"></span>
</div>
<div class="fn-tabs__text">Tab …
```

fix(fn): refactor Tabs component

---

scripts/build-accessibility-tests.js
stories/fn-tabs/__snapshots__/fn-tabs.stories.storyshot

exclude fn-tabs from a11y tests
remove `fn-tabs` from `build-accessibility-tests.js` - line 35
and run:
```
npm run test:accessibility
```

test(fn): exclude fn-tabs from a11y tests

---

src/styles/mixins/_mixins.scss

part of defect hunting spring 77 https://github.com/SAP/fundamental-ngx/issues/7362
issue has been raised in comment https://github.com/SAP/fundamental-ngx/issues/7362#issuecomment-993861090
6th issue
fixed the over height of the img
- [n/a] Includes …

fix: link, fix img align [ci visual]

---

src/styles/pagination.scss
stories/pagination/__snapshots__/pagination.stories.storyshot
stories/pagination/pagination.stories.js

replaces #3067 
None
Pagination component:
* More element cozy & compact modes support implemented.
* Active link fixes.
Now `fd-pagination__more--compact` class should be applied to More element in compact mode.

fix(styles): pagination more element size, improvements

---

src/fn/fn-progress-bar.scss

Updated Progress Bar to latest design by adding status icons

fix(fn): update Fiori Next Progress Bar to latest design [ci visual]

---

.storybook/environment.js

PRODUCTION variable was set by the webpack DefinePlugin. Now by default it will be true

chore(deps): fixed unresolved variable on test update

---

src/styles/tabs.scss

Part of SAP/fundamental-ngx#7587
Focus outline was not visible on tab headers in case of icon tabs. This was because offset was negative exactly same as width of outline. I removed negativity and now it is visible

feat(styles): focus outline is visible now [ci visual]

---

src/styles/menu.scss
src/styles/vertical-nav.scss
stories/menu/__snapshots__/menu.stories.storyshot
stories/menu/menu.stories.js
stories/vertical-navigation/__snapshots__/vertical-navigation.stories.storyshot
stories/vertical-navigation/vertical-navigation.stories.js

- added modifier class to Menu component to allow vertical scroll - `fd-menu--overflow`
- fixed the width of Menu item to be `fit-content` and not the max-width as it was before
- added modifier class to Vertical Navigation component to allow vertical scroll  - `.fd-vertical-nav--overflow`

fix(styles): add overflow modifier classes for Menu and VertNav

---

src/fn/fn-dropdown.scss
stories/fn-dropdown/__snapshots__/fn-dropdown.stories.storyshot
stories/fn-dropdown/fn-dropdown.stories.js

- added code changes to dropdown after discussion with designers
- added 2 extra modifier classes to control the width and height of the dropdown
- added extra example

fix(fn): add additional modifier classes to Dropdown

---

src/fn/fn-slider.scss
stories/fn-slider/__snapshots__/fn-slider.stories.storyshot
stories/fn-slider/fn-slider.stories.js

none
Previously, slider handle was "tweaked" based on aria-valuenow property, which can be different in real-case scenario. Added wrapper which compensates handle offset so at the edge positions of the slider, handle would fit into the size of the slider itself.
- n/a Includes Compact/Cosy/Tablet design
3. Testing

fix(fn): adjust slider handle position [ci visual]

---

src/styles/nested-list.scss

none
- changed the hardcoded value for border radius to a variable 
- moved the custom css in fund-ngx to fund-styles

fix(styles): fix nested list button bgd issue and popover radius 

---

src/styles/card.scss

None.
Outline removed from the card header if it has non-interactive class.

fix: card header non-interactive outline

---

src/fn/_fn-mixins.scss
src/fn/fn-card.scss
stories/fn-card/__snapshots__/fn-card.stories.storyshot
stories/fn-card/fn-card.stories.js

part of https://github.com/SAP/fundamental-styles/issues/3166
- updated the Card implementation to include Card content
- added modifier classes for content padding, truncate
- update focus
*Before:*
```
<div class="fn-card">
<div class="fn-card__title-icon-button-container">
<div class="fn-avatar fn-avatar--xs fn-avatar--circle fn-card__title-icon">...</div>
<div class="fn-card__title-container">
<h1 class="fn-card__title">...</h1>
<span class="fn-card__subtitle">...</span>
</div>
<button class="fn-button fn-button--secondary fn-card__title-button">...</button>
</div>
</div>
```
*After:*
```
<div class="fn-card">
<div class="fn-card__header">
<span class="fn-icon fn-icon--sys-help-2">...</span>
<div class="fn-card__title-container">
<h1 class="fn-card__title">...</h1>
<p …
```

fix(fn): update Card with some extra features [ci visual]

---

src/fn/fn-message-strip.scss
stories/fn-message-strip/__snapshots__/fn-message-strip.stories.storyshot
stories/fn-message-strip/fn-message-strip.stories.js

- added a new modifier class `.fn-message-strip--dismissible` for when the message strip is dismissible (has a close button)
- use Nested instead of Layout for the close button of the Message strip
**Before:**
```
<div class="fn-message-strip">
<span class="fn-message-strip__text">Information (default) Message Strip Text</span>
<button class="fn-button fn-button--layout fn-button--icon-only fn-message-strip__close-button" aria-label="Close">
<span class="sap-icon sap-icon--decline"></span>
</button>
</div>
```
**After:**
```
<div class="fn-message-strip fn-message-strip--dismissible">
<span class="fn-message-strip__text">Information (default) Message Strip Text</span>
<button class="fn-nested-button …
```

fix(fn): update Message strip to latest design [ci visual]

---

src/styles/mixins/_forms.scss
src/styles/select.scss

Closes https://github.com/SAP/fundamental-ngx/issues/7246
In the textarea, we could have several lines. If the component is disabled, then it is not more possible to scroll through the lines. 
This PR removes "pointer-events: none" from form controls at all. Preserving it on "select" component, as the button handle should not be clickable
>
3. Testing …

fix: remove "pointer-events: none" from disabled form controls 

---

src/fn/fn-progress-bar.scss

update the colors for the Progress bar

fix(fn): update Progress Bar colors [ci visual]

---

src/fn/fn-input-message.scss

updates the width of the input messages to take into account the focus outline width

fix(fn): update the width of the input messages [ci visual]

---

src/styles/layout-grid.scss

Part of https://github.com/SAP/fundamental-ngx/issues/7815
Closes https://github.com/SAP/fundamental-styles/issues/3226
Layout grid overlap fix. See issue for more details.
**Note:** After this change container will have vertical paddings. See screenshots.

fix(styles): layout grid gutters

---

src/fn/fn-message-strip.scss
stories/fn-message-strip/fn-message-strip.stories.js

none, reported bug by Alex
- use position `absolute` to ensure that the icon and the close button always stay aligned with the first line of the text.

fix(fn): update the position of the icon on multi line for Message Strip

---

src/styles/popover.scss

Closes none.
Relates to https://github.com/SAP/fundamental-styles/pull/3215#pullrequestreview-907449272
Properly popover's arrow position in the compact mode.

fix: popover arrow in compact mode

---

src/fn/fn-checkbox.scss
src/fn/fn-radio.scss
src/styles/button.scss
stories/fn-toggles/fn-toggles.stories.js

none, issue reported directly by designers
Checkbox and Radio Button labels were not handling long text properly. Updated the implementation so now long texts wrap on a new line and the checkmark stays always aligned with the first line. 
Also added possibility if users want to truncate the text and have a single line by adding a modifier class.

fix(fn): update checkbox and radio labels for long text [ci visual]

---

stories/message-box/message-box.stories.js

- updated the icons used for semantic Message Box to match the ones specified in the Fiori specs
- for the theming part: no update was necessary
- changed the names of the icons used in semantic Message Box.
- Before: sap-icon--question-mark, sap-icon--message-error, sap-icon--message-success, sap-icon--message-warning, sap-icon--message-information
- Now: sap-icon--sys-help-2, sap-icon--error, sap-icon--sys-enter-2, sap-icon--alert, sap-icon--information

fix(styles): update Message Box icons per Fiori specs [ci visual]

---

src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss
src/styles/toolbar.scss
stories/toolbar/__snapshots__/toolbar.stories.storyshot
stories/toolbar/toolbar.stories.js

- add delta horizon theming for Toolbar 
- updated Toolbar title
- updated the markup for the title element in the Toolbar with Title 
- added a new class for Title used in Toolbar: fd-toolbar__title
**Before:**
```
<h4>Producs (104)</h4>
```
**After:**
```
<h4 class="fd-title fd-title--h4 fd-toolbar__title">Products (104)</h4>
```

feat(styles): add delta horizon theming for Toolbar [ci visual]

---

src/styles/switch.scss
src/styles/theming/common/switch/_sap_fiori.scss
src/styles/theming/common/switch/_sap_horizon.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss
stories/switch/switch.stories.js

Relates #3213
Updated switch theme to reflect horizon theming.
>
3. Testing

feat(styles): horizon theming for Switch component

---

src/styles/bar.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss
stories/bar/__snapshots__/bar.stories.storyshot
stories/bar/bar.stories.js

- add delta theming for Bar
- removed unused class `fd-bar__element--title`
removed unused class `fd-bar__element--title`
Before:
```
<div class="fd-bar__element fd-bar__element--title">
<h6 class="fd-title fd-title--h6" aria-label="text">TEXT</h6>
</div>
```
After:
```
<div class="fd-bar__element">
<h6 class="fd-title fd-title--h6" aria-label="text">TEXT</h6>
</div>
```

feat(styles): add delta theming for Bar [ci visual]

---

src/styles/popover.scss
src/styles/select.scss
stories/pagination/pagination.stories.js

Relates to https://github.com/SAP/fundamental-ngx/issues/7929
Select component:
* Min-width fix,
* Selected item overflow.

fix: select min-width fix, overflow fix

---

src/styles/table.scss
stories/table/table.stories.js

Relates to https://github.com/SAP/fundamental-ngx/issues/7930
Text shadow moved from the table to the table text element. 
Previously it was added to the cells in pr https://github.com/SAP/fundamental-styles/pull/1571 but in that way it breaks other components styles, see the mentioned issue. 
* Now you should wrap text in element with `fd-table__text` class to apply text shadow to it.

fix: table text shadow removal

---

src/styles/icon-tab-bar.scss
src/styles/mixins/_mixins.scss
src/styles/theming/common/icon-tab-bar/_sap_fiori.scss
src/styles/theming/common/icon-tab-bar/_sap_fiori_hc.scss
src/styles/theming/common/icon-tab-bar/_sap_horizon.scss
src/styles/theming/common/icon-tab-bar/_sap_horizon_hc.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss
stories/icon-tab-bar/icon-tab-bar.stories.js

part of #3213
Icon tabs bar update
* Overflow button instead of positioning itself using `position: absolute`, now positions using `margin-left: auto`. It now is always in the end of container

feat(styles): icon tabs header horizon delta theming

---

src/styles/menu.scss
stories/menu/menu.stories.js

Closes https://github.com/SAP/fundamental-ngx/issues/7986
The submenu width now is only as wide as the parent menu item. It should expand to the whole width of it's text instead
>
3. Testing
- [n/a] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of …

fix: menu sub-items should expand the menu width

---

src/styles/object-list.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss

Part of #3213.
Object list styles refactoring, horizon support implementation.
_Note: In Horizon specs colors of the Object Statuses in active state are remain the same and in Horizon they're made be one color. Unfortunately, we cannot make them one color in Fiori and don't change in Horizon, there are no any options to conditionally apply the styling._
Current:
Specs:

feat(styles): add delta horizon theming for Object List

---

src/styles/menu.scss
src/styles/theming/common/button/_sap_fiori.scss
src/styles/theming/common/button/_sap_horizon.scss

part of #3213 
fixes a minor issue with menu border radius
**before**
**after**

fix(styles): horizon menu border radius bug [ci-visual]

---

src/styles/input.scss
src/styles/mixins/_mixins.scss

Part of https://github.com/SAP/fundamental-ngx/issues/7908
Removes clear button from input of type search that automatically applied in webkit browsers.

fix(styles): remove search button in inputs in webkit browsers

---

src/styles/shellbar.scss

It was removed previously when horizon deltas were done, but these display properties should exists, otherwise width and height of replaced logo will not have effect and in ngx will cause issues

fix(styles): shellbar logo, product and subtitle display

---

.storybook/custom/styleChangers/utils/generateUseFn.js
.storybook/custom/styleChangers/utils/getLazyLoader.js

Closes none
Previously, componentStylesManager loaded styles for every example. This created an overhead of loaded identical style files, which could cause hang of the developer tools of the browser. This behaviour was changed that only unique hrefs will be loaded now.
>

fix(styles): load styles once

---

src/styles/checkbox.scss
src/styles/radio.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss

Checkbox, Radio border style fix in Horizon themes.

fix: checkbox, radio borders in horizon

---

src/styles/calendar.scss
stories/calendar/calendar.stories.js

Closes none.
Follow-up https://github.com/SAP/fundamental-styles/pull/3273.
Year & Month buttons markup refactoring inside the Calendar component.
Shouldn't be any changes.
* markup changed for the year/month items in the calendar. 
_Breaking change described in section https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes#calendar-3273_

fix(styles): calendar year/month buttons

---

src/styles/popover.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss
stories/action-bar/action-bar.stories.js
stories/action-sheet/action-sheet.stories.js
stories/feed-list/feed-list.stories.js
stories/popover/popover.stories.js

Closes none.
Popover's arrow placement fix.

feat(styles): popover body compact, arrow position fix

---

src/styles/card.scss
src/styles/theming/common/card/_sap_fiori.scss
src/styles/theming/common/card/_sap_fiori_hc.scss
src/styles/theming/common/card/_sap_horizon.scss
src/styles/theming/common/card/_sap_horizon_hc.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss
stories/card/card.stories.js

part of #3213
Card footer was missing from the styles. Some of the functionalities should be done with javascript. When action items overflow footer, there should be overflow button which will(probably, not clear from specs) open up dropdown for additional actions

feat(styles): card footer implementation

---

src/styles/button-split.scss

Closes none.
Split button separator fix in Horizon themes.

fix: split button separator in horizon

---

src/styles/card.scss
stories/card/card.stories.js

Added border radius to last and first card containers and added hidden overflow to them. This way, by default content will not overflow cards in corners

fix(styles): added card container border radius and overflow

---

src/styles/fundamental-styles.scss
src/styles/splitter.scss
src/styles/theming/common/splitter/_sap_fiori.scss
src/styles/theming/common/splitter/_sap_fiori_hc.scss
src/styles/theming/common/splitter/_sap_horizon.scss
src/styles/theming/common/splitter/_sap_horizon_hc.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss
stories/splitter/__snapshots__/splitter.stories.storyshot
stories/splitter/splitter.stories.js

Part of #3354
Splitter styles moved to this lib, hcw/hcb themes support implemented, horizon themes support implemented.
_Icon might look wrong but it just comes from the iconfont, nothing is done on the component level._
HC
Horizon
HC
Horizon

feat(styles): add delta horizon theming for Splitter

---

src/styles/nested-list.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_horizon.scss

Closes none
Minor border corner radius fix for nested list horizon
before
after

fix(styles): minor nested list border bug [ci-visual]

---

src/styles/theming/common/wizard/_sap_fiori.scss
src/styles/theming/common/wizard/_sap_fiori_hc.scss
src/styles/theming/common/wizard/_sap_horizon.scss
src/styles/theming/common/wizard/_sap_horizon_hc.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss
src/styles/wizard.scss
stories/wizard/__snapshots__/wizard.stories.storyshot
stories/wizard/wizard.stories.js

part of #3354 
Introduces a breaking change, a new class `fd-wizard__step-content-container`, which is needed because the Horizon wizard has another styled div within each step with a white background and rounded borders as pictured below.

feat(styles): wizard horizon updates [ci-visual]

---

src/styles/slider.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss

none
Fixes previously incorrect merge. Removes outdated css variables. Moves slider dots from root element to the track to keep vertical centering if vertical padding is not equal.

fix: remove outdated slider variables [ci visual]

---

src/styles/theming/common/card/_sap_fiori_hc.scss
src/styles/theming/common/card/_sap_horizon_hc.scss

Part of https://github.com/SAP/fundamental-styles/issues/3327#issuecomment-1108540654
Card had missing borders in high contrast themes

fix(styles): fixed card HC theme borders

---

src/styles/grid-list.scss
stories/list-grid/grid-list.stories.js

Part of #3213.
Grid List Item
* Auto height feature for the item
* Partial items (no image, no title & subtitle, no body)
* Selection radio label position fix
Selection
No title, subtitle
No image
No title, subtitle, image
Selection
No title, subtitle
No image
No title, subtitle, image

feat: grid list partial items, auto-height, selection labels position fix

---

src/styles/carousel.scss
src/styles/message-page.scss
src/styles/theming/common/carousel/_sap_fiori.scss
src/styles/theming/common/carousel/_sap_fiori_hc.scss
src/styles/theming/common/carousel/_sap_horizon.scss
src/styles/theming/common/carousel/_sap_horizon_hc.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss
stories/carousel/carousel.stories.js

Part of #3354.
Horizon support implemented for the Carousel component.

feat(styles): add delta horizon theming for Carousel

---

src/styles/switch.scss
src/styles/theming/common/switch/_sap_fiori.scss
src/styles/theming/common/switch/_sap_horizon.scss

Relates [SAP/fundamental-styles#](https://github.com/SAP/fundamental-styles/issues/3327)
Changed horizon switch outline to border in order for it to work in Safari browser.

fix(styles): safari switch outline visibility

---

src/styles/dynamic-page.scss

Closes https://github.com/SAP/fundamental-styles/issues/3327
Dynamic page subtitle color

fix(styles): dynamic page subtitle color

---

stories/user-menu/__snapshots__/user-menu.stories.storyshot
stories/user-menu/user-menu.stories.js

add compact modifier class to button in compact input group that is use ass search field in User Menu.
The button from compact input group needs a compact modifier class.
BEFORE:
```
<div class="fd-input-group">
<input class="fd-input fd-input--compact fd-input-group__input" type="text" id="aqwsde118" name="" aria-label="Search" placeholder="Search">
<span class="fd-input-group__addon fd-input-group__addon--button fd-input-group__addon--compact">
<button class="fd-input-group__button fd-button fd-button--icon fd-button--transparent" aria-label="Search">
<i class="sap-icon--search"></i>
</button>
</span>
</div>
```
NOW:
```
<div class="fd-input-group">
<input class="fd-input fd-input--compact …
```

fix(styles): add fix for User Menu search field

---

src/styles/popover.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss

fix(styles): popover arrow styles

---

src/styles/shellbar.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss
stories/shellbar/shellbar.stories.js

* Horizon, shellbar action active state
* Fiori, shellbar action outline color
* Fiori, Fiori HC, Horizon HC, shellbar search field look
Fiori
Horizon
Fiori
Horizon
* shellbar actions should have `fd-button--transparent` class from now

fix(styles): shellbar various issues

---

src/styles/checkbox.scss

Part of https://github.com/SAP/fundamental-styles/issues/3327#issuecomment-1100225638
Checkboxes had margin despite empty labels

fix(styles): fixed checkbox spacing when label is empty

---

src/styles/micro-process-flow.scss

Part of #3327
Fixed micro process flow icon overlay

fix(styles): micro process flow icon overlay

---

src/styles/product-switch.scss

part of https://github.com/SAP/fundamental-styles/issues/3327
change the focus outline color on active state

fix(styles): add fix for focus in active state

---

src/styles/menu.scss
src/styles/theming/common/menu/_sap_fiori.scss
src/styles/theming/common/menu/_sap_horizon.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss

fix the focus color of menu item on active state  for Horizon

fix(styles): add fix for focus color on active state for Horizon

---

src/styles/time.scss

part of https://github.com/SAP/fundamental-ngx/issues/4669
removing width limitation from the label of time column in order to be able to use longer text in labels
>
3. Testing

fix(styles): remove the width limitation from the label of time column

---

src/styles/input-group.scss

part of https://github.com/SAP/fundamental-ngx/issues/4663
`fd-disabled` mixin is applied to both input-group and inputs/buttons inside of it. Because of this opacity: 0.4 is applied multiple times
>
3. Testing …

fix(styles): remove additional dimming of controls inside input-group

---

src/fn/fn-input.scss

none
fixing the missing box-shadow for Inputs in MacOS Safari and Chrome
**BEFORE:**
**NOW:**

fix(fn): fix missing box-shadow for macOS inputs [ci visual]

---

src/styles/menu.scss

Part of https://github.com/SAP/fundamental-styles/issues/3327#issuecomment-1108540654.
Overflow menu radius.

fix(styles): overflow menu radius

---

src/styles/dialog.scss

part of https://github.com/SAP/fundamental-ngx/issues/7984
Fixes an issue that became apparent with Horizon when a dialog would have the `--mobile` modifier class which removes border radius but the dialog body's top corners would still have a border radius.
before:
after:

fix(styles): dialog body corner radius in mobile mode

---

src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss

Part of https://github.com/SAP/fundamental-styles/issues/3327#issuecomment-1128598823
Micro Process Flow icon colors in Horizon HC themes.

fix(styles): micro process flow horizon hc

---

src/styles/quick-view.scss

part of https://github.com/SAP/fundamental-ngx/issues/7984
Adds a background-color style to quick view so it works in standalone mode for all themes: https://sap.github.io/fundamental-ngx/#/core/quick-view#basic

fix(styles): quick view background [ci visual]

---

src/styles/carousel.scss
stories/carousel/carousel.stories.js

Part of https://github.com/SAP/fundamental-ngx/pull/8104#pullrequestreview-975799058
Carousel classes refactoring, styles improvements, examples update.
**As updated/changed classes in scope of this pr weren't mentioned in the docs there is no breaking changes.**
* Carousel content markup change, from now element with class fd-carousel__slides for carousel items.
[WIKI](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes#carousel-3439)

feat(styles): carousel full-size image, classes & styles improvements

---

src/styles/link.scss
src/styles/mixins/_mixins.scss
src/styles/theming/common/link/_sap_fiori.scss
src/styles/theming/common/link/_sap_fiori_hc.scss
src/styles/theming/common/link/_sap_horizon.scss
src/styles/theming/common/link/_sap_horizon_hc.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss

Part of https://github.com/SAP/fundamental-styles/issues/3327#issuecomment-1108540654
Closes #3437
Fixed underlines for horizon HC themes, fixed emphasized underlines

fix(styles): fixed link underline in HCB

---

src/styles/layout-grid.scss

Nested rows horizontal gutter fix.

fix(styles): layout grid nested rows

---

src/styles/table.scss

part of https://github.com/SAP/fundamental-ngx/issues/7984
removes an unnecessary border on pop-in table cells

fix(styles): remove pop-in border right [ci visual]

---

src/styles/mixins/vertical-nav/_vertical-nav-navigation.scss
src/styles/theming/common/vertical-nav/_sap_fiori.scss
src/styles/theming/common/vertical-nav/_sap_horizon.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss

part of #3327 
fixes incorrect focus outlines for vertical navigation items. I didn't see anything in the specs about this so I am basing this off of Menu styles
before:
after:

fix(styles): vertical navigation focus outlines for horizon [ci visual]

---

src/styles/mixins/_forms.scss
src/styles/select.scss
src/styles/theming/common/select/_sap_fiori.scss
src/styles/theming/common/select/_sap_horizon.scss
src/styles/theming/common/select/_sap_horizon_hc.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss

Closes SAP/fundamental-styles#](https://github.com/SAP/fundamental-styles/issues/3434)
This PR fixes the button in Select control when it's in expanded state. The fix automatically solves the issue in Pagination as it uses Select. 
>

fix(styles): fix the button states in expanded Select [ci visual]

---

src/styles/grid-list.scss
src/styles/theming/common/grid-list/_sap_fiori.scss
src/styles/theming/common/grid-list/_sap_horizon.scss
src/styles/theming/common/grid-list/_sap_horizon_hc.scss
src/styles/theming/sap_fiori_3.scss
src/styles/theming/sap_fiori_3_dark.scss
src/styles/theming/sap_fiori_3_hcb.scss
src/styles/theming/sap_fiori_3_hcw.scss
src/styles/theming/sap_fiori_3_light_dark.scss
src/styles/theming/sap_horizon.scss
src/styles/theming/sap_horizon_dark.scss
src/styles/theming/sap_horizon_hcb.scss
src/styles/theming/sap_horizon_hcw.scss
src/styles/toolbar.scss
stories/list-grid/grid-list.stories.js

Part of https://github.com/SAP/fundamental-styles/issues/3327#issuecomment-1122190654
Toolbar Infobar mode styling change.
Grid List Toolbar Infobar usage adoption.
* Grid list info bar markup change

fix(styles): toolbar info mode styling, grid list toolbar

---

src/styles/menu.scss

Part of https://github.com/SAP/fundamental-styles/issues/3327#issuecomment-1133854430
Menu component link outline fix.

fix(styles): menu focus outline [ci visual]

---

src/styles/mixins/_forms.scss
src/styles/theming/common/input/_sap_fiori.scss
src/styles/theming/common/input/_sap_horizon.scss

part of #3327
Readonly fields became unfocusable and unactionable with cursor and placeholder colors became visible in Horizon

fix(styles): input field readonly state fixes and adaptations

---

src/styles/product-switch.scss
stories/product-switch/product-switch.stories.js
stories/shellbar/shellbar.stories.js

Part of https://github.com/SAP/fundamental-ngx/issues/7984
**Breaking change** removes an old class that is no longer required because the styles are covered by `fd-button--transparent` class.

fix(styles): remove product switch control class [ci visual]

---

src/styles/menu.scss

https://github.com/SAP/fundamental-styles/issues/3495#issuecomment-1144101035
Fixed border radius in dialog context and removed disabled state focus outline

fix(styles): menu border radius in dialog and disabled outline

---

src/styles/dialog.scss
src/styles/popover.scss
stories/menu/menu.stories.js

part of #3495 
FIxes an issue with the focus outline on list items in a popover. This does unfortunately break our self-contained style rule, but as discussed we will address in a later refactor
before:
after:

fix(styles): focus border radius on list items in popovers [ci visual]

---

src/styles/tree.scss

part of #3495 
Fixes an outline issue on the tree expander buttons. Previously a `:focus-visible` outline was set by the browser when the buttons were accessed via tab key. This removes that by adding the button reset and adds the correct focus outline

fix(styles): tree expander button focus outline

---

src/styles/icon-tab-bar.scss

Part of https://github.com/SAP/fundamental-styles/issues/3495
fixes the issue with the double focus for Universal Icon Tab Bar Single Click Area and the wrong position of the badge on focus

fix(styles): add fix for double focus in single click area for IconTabBar

---

src/styles/carousel.scss

Part of https://github.com/SAP/fundamental-ngx/issues/7984#issuecomment-1145286641
Carousel outline fix.

fix(styles): carousel outline

---

src/styles/time.scss

part of #3495 
The distance between the time text and the top/bottom borders looked slightly off to me and I think this better centers them. Here they are zoomed in 500%, Measure the distance from the top of the digit to the top of the digit to the border and bottom of the digit to the border.

fix(styles): new time line height [ci visual]

---

src/styles/card.scss

fix(styles): list in card focus outline

---

src/styles/dialog.scss

Part of https://github.com/SAP/fundamental-ngx/issues/7984#issuecomment-1146817687
Added border radius for header and footer elements of the dialog component.

fix(styles): safari border radius

---

src/styles/tabs.scss

Part of https://github.com/SAP/fundamental-ngx/issues/7984#issuecomment-1146819031.
Tabs paddings fix.

fix(styles): tabs padding

---

src/styles/tool-header.scss

part of #3495 
Unsure why these elements have overflow: hidden, we don't have the same for shellbar and removing it doesn't seem to cause any problems. Alternatively we could add some padding but that will affect the whole toolbar. 
before:
after:

fix(styles): remove overflow: hidden from tool header elements [ci visual]

---

src/styles/dialog.scss
src/styles/product-switch.scss
stories/calendar/calendar.stories.js
stories/combobox-input/combobox-input.stories.js
stories/multi-combo-box/multi-combo-box.stories.js
stories/multi-input/multi-input.stories.js
stories/select/select.stories.js
stories/table/table.stories.js

part of #3495 
- Dialog mobile list modifiers were in the wrong place
- Product switch mobile should have 0 border radius
- Also fixes up some docs that should have been using `fd-dialog__content--mobile` modifier
- Issue with checkboxes i found in a dialog on the table docs

fix(styles): dialog mobile lists should be in --dialog class [ci visual]

---

src/styles/rating-indicator.scss

Part of https://github.com/SAP/fundamental-ngx/issues/7984#issuecomment-1150392147
Fixed correct display of the stars in horizon theme for disabled half-star example.

fix(styles): rating indicator for horizon fixes

---

src/styles/object-marker.scss

Part of https://github.com/SAP/fundamental-styles/issues/3495#issuecomment-1153915782
Link focus state applied to the Object Marker component. Styles refactored.

fix(styles): object marker focus state & styles refactoring

---

stories/side-navigation/side-navigation.stories.js
stories/tabs/tabs.stories.js

Closes none.
Move deprecated components in the separate list in the sidebar.

feat(docs): move deprecated components to the separate list

---

src/styles/mixins/_forms.scss
src/styles/mixins/_mixins.scss

Closes SAP/fundamental-styles#3688
Created mixin that set both height and min-height for an element and used it in `fd-input-field-base`

fix(styles): add min-height for input fields

---

src/styles/mixins/list/_list-dropdown.scss

dxp.
Min width of the select and other components that could have dropdown with list is 5rem accordingly to the wiki.

fix(styles): list dropdown min-width

---

src/styles/token.scss

Kafka
read-only token means we don't have "x" icon on it.
selected token means we have it with the different styling applied.
here is the fix when both of them applied together.

fix(styles): selected & readonly token

---

src/styles/input-group.scss
src/styles/mixins/_forms.scss
src/styles/select.scss
src/styles/step-input.scss

Closes https://github.com/SAP/fundamental-styles/issues/3723
Added correct element size for compact state for:
* Select
* Step Input
* input Group
>
3. Testing

fix(styles): compact state for form controls

---

src/styles/alert.scss

part of https://github.com/SAP/fundamental-ngx/issues/8342
before:
after:

fix(styles): fix vertical alignment of icon in alert

---

src/styles/shellbar.scss

part of https://github.com/SAP/fundamental-ngx/issues/8342
fixes shellbar logo focus

fix(styles): add shellbar logo focus

---

src/styles/input-group.scss
src/styles/mixins/_forms.scss
stories/input-group/input-group.stories.js

fixes #3742 
Italicized, right-aligned text is cut off by neighboring elements so this adds a small indent to the placeholder text in RTL mode.  This PR also corrects a minor RTL padding bug for input group
before:
after:

fix(styles): padding issues and RTL placeholder issues

---

src/styles/object-status.scss

Closes SAP/fundamental-styles#3724 
Closes SAP/fundamental-ngx#8431
For object status large size, `fd-only-child` should be used instead `fd-empty`.

fix(styles): fd-emty was used instead fd-only-child

---

src/styles/mixins/list/_list-byline.scss

Refers to dxp/backlog/643
Displaying SVG in byline list thumbnail fixed (Safari).

fix(styles): byline list thumbnail issue in safari

---

src/styles/notification.scss

Refers to https://github.com/SAP/fundamental-ngx/pull/8525
Notification mobile mode fixes.

fix(styles): notification mobile

---

stories/icon/SAPIcons/icon.stories.js

Broken link in icon.stories.js :Update to https://sap.github.io/fundamental-styles/?path=/docs/introduction--overview#icons
Updated the broken link in stories

docs(styles): fix icon broken link

---

src/styles/form-group.scss
src/styles/form-item.scss
src/styles/form-layout-grid.scss
stories/checkbox/__snapshots__/checkbox.stories.storyshot
stories/checkbox/checkbox.stories.js
stories/dialog/__snapshots__/dialog.stories.storyshot
stories/dialog/dialog.stories.js
stories/form-fieldset/__snapshots__/form-fieldset.stories.storyshot
stories/form-fieldset/form-fieldset.stories.js
stories/form-grid/__snapshots__/form-grid.stories.storyshot
stories/form-grid/form-grid.stories.js
stories/form-group/__snapshots__/form-group.stories.storyshot
stories/form-group/form-group.stories.js
stories/input-group/__snapshots__/input-group.stories.storyshot
stories/radio/__snapshots__/radio.stories.storyshot
stories/radio/radio.stories.js

Closes https://github.com/SAP/fundamental-styles/issues/3574
Refers to https://github.com/SAP/fundamental-ngx/issues/7854
Form container margins fixed.
_Form Grid_
_Note: Redundant gaps in horizontal mode._
_Note: No margins between groups._

fix(styles): form grid margins & paddings issues

---

src/styles/feed-list.scss
src/styles/theming/common/feed-list-item/_sap_fiori.scss
src/styles/theming/common/feed-list-item/_sap_horizon.scss
stories/feed-list/__snapshots__/feed-list.stories.storyshot
stories/feed-list/feed-list.stories.js

Closes https://github.com/SAP/fundamental-styles/issues/3803
* feed-list-item fixes & enhancements
* `fd-feed-list__action` class removed, use `fd-feed-list__actions` class instead.

fix(styles): feed-list-item horizon & fixes

---

src/styles/card.scss
src/styles/theming/common/card/_sap_fiori.scss
src/styles/theming/common/card/_sap_horizon.scss

Closes https://github.com/SAP/fundamental-styles/issues/3800
* card title font-size fix

fix(styles): card title, subtitle font-size

---

src/styles/mixins/list/_list-dropdown.scss

Closes https://github.com/SAP/fundamental-styles/issues/3802
Combobox row height fix.

fix(styles): combobox row height

---

src/fonts/sap_fonts.scss
src/styles/button.scss
src/styles/theming/common/button/_sap_fiori.scss
src/styles/theming/common/button/_sap_horizon.scss
src/styles/theming/common/button/_sap_horizon_hc.scss

Closes https://github.com/SAP/fundamental-styles/issues/3798 
Closes https://github.com/SAP/fundamental-styles/issues/3797
* fix button fonts
* `72-SemiboldDuplex` added to shared fonts.

fix(styles): button fonts

---

src/styles/shellbar.scss

Part of SAP/fundamental-ngx#7966
SAP/fundamental-ngx#8347
Changed shellbar-select style to fix mouse hover effect.

fix(styles): full height to shellbar select

---

src/styles/mixins/list/_list-base.scss
src/styles/mixins/list/_list-definitions.scss

fixes none. improvement upon this PR: https://github.com/SAP/fundamental-ngx/pull/8628
before:
after:

fix(styles): there should be no compact object list

---

.storybook/custom/DocsPage.scss

Closes none.
Although there is no difference on the large screen, the docs page container is too narrow on mobile.

fix(docs): docs container width

---

src/styles/popover.scss

Follows up https://github.com/SAP/fundamental-styles/pull/3858
Popover's styles specificity.

fix(styles): form message in popover

---

.storybook/custom/custom.scss

Closes none.
Components are meant to look well on screens >320px, not less. Examples container has 40px of horizontal padding, so there is only 280px left for components what's definitely not okay.

fix(docs): examples container width

---

src/styles/input-group.scss

Part of SAP/fundamental-ngx#8557
Solves one of [these](https://github.com/SAP/fundamental-ngx/issues/8557#issuecomment-1215609973): 
Added mixin  `fd-input-field-nested-reset` for input hover in input-group. 
**Hover over it** :
**Hover over it** :

fix(styles): reset input-field hover style in input-group

---

src/styles/tokenizer.scss

fixes #3897 
The tokens themselves are showing as compact but the tokenizer as a whole is not.
Before:
After:

fix(styles): tokenizer not rendering as compact

---

src/styles/quick-view.scss

Part of ngx defect hunting here: https://github.com/SAP/fundamental-ngx/issues/8557#issuecomment-1215401360
Before: 
After:

fix(styles): link in quick view width bug

---

src/styles/nested-list.scss

part of SAP/fundamental-ngx#8557
Solve one of [these](https://github.com/SAP/fundamental-ngx/issues/8557#issuecomment-1215609973) : Removed zero left padding of nested list in RTL

fix(styles): fix padding of nested list in rtl

---

.storybook/custom/components/Header.js
.storybook/custom/constants/availableThemes.js
.storybook/custom/decorators/themeProvider.js
.storybook/preview.js
README.md
config/constants.js
scripts/build-visual-stories.js
stories/BTP Experimental Design/fn-icons/IconsDocsPage.js
theming-preview/testsuite.json
theming-preview/theme-manager.js

align Theme's Names with the other technologies
- Replace `Fiori 3` with `Quartz`
- Add `Quarts` to `fiori 3` HC Themes
- Add `Horizon` to horizon themes

docs(styles): align theme names with the other technologies

---

src/styles/tokenizer.scss

fixes none
Multi-input, combobox etc. set paddings/margins so standalone tokenizer should not have these
before:
after:

fix(styles): more tokenizer fixes

---

src/styles/dynamic-page.scss
stories/dynamic-page/dynamic-page.stories.js

Refers to DXP.
Wrapping mode for Dynamic Page's Title & Subtitle elements.

feat(styles): dynamic page title & subtitle wrapping

---

src/styles/grid-list.scss

Part of SAP/fundamental-ngx#8557
Solves [this](https://github.com/SAP/fundamental-ngx/issues/8557#issuecomment-1215393590): Added full width to grid-list-item content.

fix(styles): add full width to grid-list-item content

---

src/styles/scrollbar.scss

Support for SAP/fundamental-ngx#8780
Added focus mixin with outline none.
**`Note:` This can only be reproducible on the PR branch of NGX.**

feat(styles): add focus styles to scrollbar

---

src/styles/dialog.scss
stories/dialog/dialog.stories.js

Closes none.
Dialog no x paddings feature and mobile mode issues fixes.
Red background added to highlight the defects.

fix(styles): dialog no horizontal paddings, mobile mode issues

---

package.json

removed verbose flag from build all. It is polluting CI run outputs

chore: removed verbose flag

---

packages/styles/src/mixins/list/_list-base.scss

Support for SAP/fundamental-ngx#8805
Added class `fd-list__title-text` with flex-center

fix(styles): add flex-center to list-title-text

---

packages/styles/src/card.scss
packages/styles/src/theming/common/card/_sap_fiori.scss
packages/styles/src/theming/common/card/_sap_horizon.scss
packages/styles/stories/Components/card/card.stories.js

Closes [SAP/fundamental-styles#](https://github.com/SAP/fundamental-styles/issues/3960)
- adds border-top to the Card Footer in Quartz theme (uses the same values as the header)
- changes the border-bottom for Card header to transparent instead of none to keep the Card dimensions
- adds an example of how to build a Card footer using Bar component

feat(styles): add border to the Card Footer in Quartz [ci visual]

---

packages/styles/src/menu.scss
packages/styles/src/mixins/_mixins.scss
packages/styles/src/panel.scss
packages/styles/src/popover.scss
packages/styles/src/product-switch.scss
packages/styles/src/scrollbar.scss
packages/styles/src/table.scss
packages/styles/src/textarea.scss
packages/styles/src/theming/common/scrollbar/_sap_fiori.scss
packages/styles/src/theming/common/scrollbar/_sap_horizon.scss

Closes [SAP/fundamental-styles#](https://github.com/SAP/fundamental-styles/issues/3959)
- moved the code for Scrollbar into a mixin so it can be reused in components with overflow area
- added a modifier class `fd-scrollbar--container` to `fd-scrollbar` for when the scrollbar is used inside a container with border radius.
- added scrollbar css (mixin reuse) to the components that have scrollable area: Popover, Menu, Textarea, Feed Input, Panel, Product Switch, Table

feat(styles): adopt Fiori Scrollbar for all components with scrollable area

---

packages/workspace-plugins/src/executors/build/executor.ts

Postcss output paths were incorrect in the build. This would result in flattened directory output and postCSS had no effect in subdirectories of dist

fix: incorrect output path of build

---

package.json
packages/workspace-plugins/src/executors/shared/postcss.plugins.ts
yarn.lock

postcss-custom-properties is not needed anymore, since we do not support IE11 and even if we did, that configuration did not have any meaningful effect on output files, because it was missing the source of the variables

chore(deps-dev): removed postcss-custom-properties

---

packages/styles/src/menu.scss

Part of https://github.com/SAP/fundamental-ngx/pull/8930
Fix for the last item border radius.

fix(styles): last item in menu list border radius issue

---

packages/styles/src/mixins/list/_list-base.scss
packages/styles/src/upload-collection.scss
packages/styles/stories/Components/upload-collection/upload-collection.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes SAP/fundamental-styles#3895
The only thing, that was different from the specs was the interactive item's thumbnail color, everything else aligns with the specs. In wiki UploadCollection and UploadSet are the same, so no need to move "collection" into the deprecation just to replace it with exact same contents with a different names.
>

feat(styles): added interactive upload collection item

---

packages/styles/src/shellbar.scss

Part of https://github.com/SAP/fundamental-ngx/pull/8347#pullrequestreview-1168875862
fix: input-group focus outline and select hover issues.
`:hover`

fix(styles): fix shellbar styles for input-group and addon

---

packages/cx/src/_nested-list.scss
packages/cx/src/side-nav.scss
packages/cx/stories/Components/cx-side-navigation/cx-side-navigation.stories.js

none
- fixed the arrow alignment
- changed `box-shadow: var(--sapContent_Shadow1);` to `box-shadow: var(--sapContent_Shadow0);`
- added functionality and examples for the case where a list item can have a link (text and icon) and expand/collapse functionality (button)
- added example to the popover with the case where the first level item with button is a link

fix(cx): add fixes after design review [ci visual]

---

packages/styles/src/dynamic-page.scss
packages/styles/src/theming/common/dynamic-page-layout/_sap_fiori.scss
packages/styles/src/theming/common/dynamic-page-layout/_sap_horizon.scss

Refers to `dxp/backlog/issues/812`
Dynamic Page button color fix.

fix(styles): dynamic page buttons styling

---

packages/styles/src/dynamic-page.scss

Refers to `dxp/organization/issues/87`
Tabs & dynamic page horizontal paddings issue fix.

fix(styles): tabs & dynamic page horizontal paddings

---

packages/styles/src/popover.scss

Closes none
Popover's visibility for vertical nav issue fix

fix(styles): popover's visibility for vertical nav

---

packages/styles/src/object-status.scss
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes https://github.com/SAP/fundamental-styles/issues/4027
adds text-shadow to Inverted Object Status, the font-size was recently fixed in another PR

fix(styles): add text shadow to inverted Object Status [ci visual]

---

packages/styles/stories/Components/shellbar/shellbar.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes https://github.com/SAP/fundamental-styles/issues/3780
the Menu button in Shellbar is a `<div>` with role=button but was missing tabindex, which is now added and the element gets a focus.

docs(styles): add tabindex to menu button in shellbar [ci visual]

---

packages/styles/src/shellbar.scss
packages/styles/stories/Components/shellbar/shellbar.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes https://github.com/SAP/fundamental-styles/issues/3779
The ShellBar logo should be used as an image and as a clickable element.
- updated the documentation to show an example with clickable logo
- added css for the focus outline

fix(styles): provide option for ShellBar logo to be used as a link 

---

packages/styles/src/table.scss

Closes https://github.com/SAP/fundamental-styles/issues/4029
the modifier classes for removing horizontal and vertical borders were flipped. `--no-horizontal-borders` were removing the vertical borders and vice-versa. The current issue provides a fix for this.

fix(styles): add fix for no horizontal and vertical borders in Table

---

packages/styles/src/select.scss
packages/styles/stories/Components/select/select.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes https://github.com/SAP/fundamental-styles/issues/3589
The inputs (by design) have margins top and bottom of 0.25rem. When the inputs are controls, aka open/close a menu, which is the case of Select component, the bottom margin should disappear. In recent fix the margin-bottom of the Select control was set to 0, which makes the control not vertically aligned when positioned with other controls. 
The current fix sets the margin-bottom to 0 only when the input has aria-expanded set to true or the class `is-expanded` is added to the element

fix(styles): add fix for margin-bottom of Select [ci visual]

---

packages/styles/src/toolbar.scss
packages/styles/stories/Components/toolbar/toolbar.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes https://github.com/SAP/fundamental-styles/issues/4087
- update the font-size of the title in Toolbar
- update the background color of the Toolbar
- `fd-toolbar--solid` modifier class is no longer needed when `fd-toolbar--title` is applied
**Before**
```
<div class="fd-toolbar fd-toolbar--solid fd-toolbar--title fd-toolbar-active">...</div>
```
**After**
```
<div class="fd-toolbar fd-toolbar--title fd-toolbar-active">...</div>
```

fix(styles): update values for Toolbar with Title [ci visual]

---

packages/styles/src/quick-view.scss
packages/styles/stories/Components/quick-view/quick-view.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Relates to https://github.com/SAP/fundamental-styles/issues/3955#issuecomment-1355378065
Quick view styles & docs issues fixes.

fix(styles): quick view styles & examples

---

packages/styles/src/mixins/_mixins.scss
packages/styles/stories/Components/breadcrumb/breadcrumb.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Relates to https://github.com/SAP/fundamental-styles/issues/3955#issuecomment-1355348853
Added `0.0625rem`(`1px`) horizontal padding in link to better align with design specs.
Overflow icon used in breadcrumb overflow item to better align with the specs.

fix(styles): link styles & breadcrumbs overflow item

---

packages/styles/src/vertical-nav.scss

Relates to https://github.com/SAP/fundamental-styles/issues/3955#issuecomment-1355402445
Custom scrollbar applied to Vertical Nav component.

fix(styles): apply custom scrollbar to vertical nav

---

packages/styles/src/textarea.scss

Relates to https://github.com/SAP/fundamental-styles/issues/3955#issuecomment-1355341272
Fixes for the textarea focus styles & scrollbar styles.
*Note: Not rounded*
*Note: way too rounded on hover*
*Note: ideally rounded*

fix(styles): textarea focus & scrollbar styles

---

packages/styles/src/popover.scss

Refers to https://github.com/SAP/fundamental-ngx/issues/8897#issuecomment-1361911872.
popover wrapper with `overflow: visible` to don't hide submenus.

feat(styles): popover wrapper with overflow visible

---

packages/styles/src/pagination.scss

Refers to https://github.com/SAP/fundamental-ngx/issues/8897#issuecomment-1366587987
Pagination active item button focus styles issue fix.

fix(styles): pagination button focus styles

---

packages/styles/src/mixins/_forms.scss
packages/styles/src/theming/common/input-group/_sap_horizon_hc.scss
packages/styles/src/theming/sap_fiori_3.scss
packages/styles/src/theming/sap_fiori_3_dark.scss
packages/styles/src/theming/sap_fiori_3_hcb.scss
packages/styles/src/theming/sap_fiori_3_hcw.scss
packages/styles/src/theming/sap_fiori_3_light_dark.scss
packages/styles/src/theming/sap_horizon.scss
packages/styles/src/theming/sap_horizon_dark.scss
packages/styles/src/theming/sap_horizon_hcb.scss
packages/styles/src/theming/sap_horizon_hcw.scss

Refers to https://github.com/SAP/fundamental-ngx/issues/8897#issuecomment-1366555025
Input group button styling in HC themes.
Hover State
Active state
Hover State
Active State
*Note: I suppose that blue background on button in active state is the mistake in the wiki because it's said*
> __The Input Button inherit all styles__ from [Button (Horizon)](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698912599) with the following deltas:
> 
> border-radius: --sapField_BorderCornerRadius;
> border-color: --sapButton_Hover_BorderColor;
> 
> The Field's underline must appear on top of the Button in all states.
> __The Down state of the input button preserves the hover visual.__
And button in active state has orange background in HC themes.

fix(styles): input group btn in HC themes

---

packages/styles/src/mixins/_forms.scss

Refers to https://github.com/SAP/fundamental-ngx/issues/7246
Inputs read-only state issue when it's unable to scroll.

fix(styles): input readonly state

---

packages/styles/src/layout-panel.scss

Relates to [#9173](https://github.com/SAP/fundamental-ngx/issues/9173)

fix(styles): layout panel scrollbar

---

packages/styles/src/dynamic-page.scss

fix(styles): outline-offset of dynamic page header not visible when page is fullscreen

---

packages/styles/stories/Components/table/table.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes https://github.com/SAP/fundamental-styles/issues/4088
Update the Toolbar used in tables to Title Toolbar and the <h4> with the appropriate classes.
- `fd-toolbar--solid` class is removed
- the h4 element in the Toolbar has classes `fd-title fd-title--h4 fd-toolbar__title`
Before:
```
<div class="fd-toolbar fd-toolbar--solid fd-toolbar--title fd-toolbar-active">
<h4>Default Table</h4>
<span class="fd-toolbar__spacer fd-toolbar__spacer--auto"></span>
</div>
```
Now:
```
<div class="fd-toolbar fd-toolbar--title fd-toolbar-active">
<h4 class="fd-title fd-title--h4 fd-toolbar__title">Default Table</h4>
<span class="fd-toolbar__spacer fd-toolbar__spacer--auto"></span>
</div>```

docs(styles): update Table to use Toolbar Title [ci visual]

---

packages/styles/src/mixins/_forms.scss
packages/styles/src/select.scss

Closes https://github.com/SAP/fundamental-styles/issues/4197
Fixes Select's and StepInput's button border styles in HC themes.

fix(styles): select's, step-input's button border styles in hc [ci visual]

---

packages/styles/src/object-status.scss
packages/styles/stories/Components/object-status/object-status.stories.js

Fixes https://github.com/SAP/fundamental-ngx/issues/9228
- Refactored Object status to rely on local css variables;
- Fixed issue with large inverted Object Status scenario;
>
3. Testing

fix(styles): refactor object status component [ci visual]

---

packages/styles/src/input-group.scss
packages/styles/src/select.scss
packages/styles/stories/Components/Forms/input-group/input-group.stories.js
packages/styles/stories/Components/select/select.stories.js
packages/styles/stories/Patterns/combobox-input/combobox-input.stories.js
packages/styles/stories/Patterns/datepicker/datepicker.stories.js
packages/styles/stories/Patterns/multi-combo-box/multi-combo-box.stories.js
packages/styles/stories/Patterns/multi-input/multi-input.stories.js

Fixes https://github.com/SAP/fundamental-ngx/issues/9228
- Fixed input-group (and it's descendants) examples to reflect correct compact state;
- Fixed select margin bottom issue @InnaAtanasova style specs does not reflect on removing bottom margin. Popover should be adjusted accordingly to the element margin instead;
Compact input group should have `.fd-input-group--compact` class to apply new margins.
3. Testing

fix(styles): form input correct margins [ci visual]

---

packages/workspace-plugins/src/executors/build/executor.ts

Closes SAP/fundamental-styles#4274
The exported map was missing an important list of the CSS files as well. This update both shortens the package.json and fixes the issue

fix: fixed package.json exports

---

packages/workspace-plugins/src/executors/build/executor.ts

Relates to SAP/fundamental-styles#4274
Fixing error `Module not found: Error: Default condition should be last one`

fix: fixed package.json exports default condition order

---

packages/styles/src/popover.scss

Closes SAP/fundamental-ngx#9228
Popover wrapper had a reset styles, which were overriding styles that were assigned to the popover body if the user used custom classes

fix: popover wrapper styles overriding custom body class styles

---

packages/styles/src/mixins/table/_table-fixed.scss

fixes this issue with the header which was only noticeable after importing in NGX - i think because storybook has some `overflow: hidden` hiding somewhere, breaking `position: sticky`. Problem was sticky logic was being applied to every cell - logic needed to be in `--fixed` block

fix(styles): fixed table styles should only exist under --fixed [ci visual]

---

packages/styles/src/button-split.scss
packages/styles/src/button.scss
packages/styles/src/mixins/button/_button-helper.scss
packages/styles/src/mixins/button/_button-types.scss
packages/styles/src/theming/common/button/_sap_fiori.scss
packages/styles/src/theming/common/button/_sap_fiori_hc.scss
packages/styles/src/theming/common/button/_sap_horizon.scss
packages/styles/src/theming/common/button/_sap_horizon_hc.scss

Closes https://github.com/SAP/fundamental-styles/issues/4252
Button focus outline in Safari is not rendered properly. It's a known issue of Safari https://medium.com/@jeandesravines/use-border-radius-and-outline-simultaneously-on-safari-14ce92889e1f
To fix the issue we abandon the normal way of applying outline and use a normal border which is added with `::after` to the element. This solution requires some refactoring for the Split button as the second button (with the arrow) uses\ `::after` to apply the separator and `::before` is also taken. 
No breaking changes are introduced.

fix(styles): add fix for button outline in Safari [ci visual]

---

packages/styles/src/icon-tab-bar.scss
packages/styles/stories/Components/icon-tab-bar/icon-tab-bar.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes https://github.com/SAP/fundamental-styles/issues/4336
When the Icon Tab Bar had more than 1 tab with multi click option and one is selected, the other multi click tabs had visual issues. This was due to paddings not being applied properly.

fix(styles): add fix for multi click Icon Tab Bar [ci visual]

---

packages/styles/src/illustrated-message.scss

none
after discussion with the designers, the max height for the title and text is removed as well as the truncation rules, so now the containers will grow with the text.

fix(styles): remove max height and truncation from texts in Illustrated Messages

---

packages/styles/src/btp/avatar.scss
packages/styles/src/fundamental-styles.scss
packages/styles/stories/BTP/avatar/avatar.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes https://github.com/SAP/fundamental-styles/issues/4322
- add 2 additional sized to Avatar component that are specific for BTP, the scss file is in a separate folder called `btp`
- the documentation part is in the BTP section

feat(styles): add BTP avatar extension [ci visual]

---

packages/styles/src/avatar.scss
packages/styles/src/checkbox.scss
packages/styles/src/mixins/_forms.scss
packages/styles/src/mixins/_mixins.scss
packages/styles/src/pagination.scss
packages/styles/src/radio.scss

- Removed ::placeholder related stuff from checkbox and ratio button styling;
- Simplified cycled markup for avatar;
- combined multiple selectors for avatar size into one with same styling properties;
3. Testing

fix(styles): simplify avatar, checkbox and radio built markup

---

packages/styles/src/_avatar-variables.scss
packages/styles/src/message-strip.scss
packages/styles/stories/Components/message-strip/message-strip.stories.js
packages/styles/stories/Components/notification/notification.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap
packages/theming-preview/src/semantic-colors.html

Closes https://github.com/SAP/fundamental-styles/issues/4383
- added custom icon
- added custom colors (accent colors)
- text with Link option
- a11y improvements: aria-role is changed, added aria-live, aria-labelledby, etc.
**Markup change:** - the ability to add custom icon required change in the markup. The status icon is no longer added by the modifier class, but is wrapped in a container.
```
<div class="fd-message-strip fd-message-strip--information fd-message-strip--dismissible" role="alert">
<p class="fd-message-strip__text">...</p>
</div>
```
```
<div class="fd-message-strip fd-message-strip--information fd-message-strip--dismissible" role="note" aria-live="assertive" id="message-strip-2" aria-labelledby="message-strip-2">
<div …
```

feat(styles): update Message Strip to latest Horizon design [ci visual]

---

packages/styles/src/shellbar.scss
packages/styles/stories/Components/shellbar/shellbar.stories.js

none
Added shrink/grow modifiers to shellbar
3. Testing

fix(styles): allow shellbar group shrinking [ci visual]

---

packages/styles/src/mixins/tree/_mixins.scss

Closes none
Fixed outline bottom offset for active tree item when focused
>

fix(styles): tree item active outline

---

packages/styles/src/checkbox.scss
packages/styles/src/radio.scss
packages/styles/stories/Components/Forms/checkbox/checkbox.stories.js
packages/styles/stories/Components/Forms/form-fieldset/form-fieldset.stories.js
packages/styles/stories/Components/Forms/radio/radio.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes none
By default, long checkbox and radio button labels should truncate with ellipsis. Currently this behaviour is not working (a bug). For checkbox the fix was easy, achieved only with css. 
For radio button the fix required breaking changes as the label is a flex container and in order for the ellipsis to work on the text, the text should be wrapped in an element. 
For more information regarding this flex issue please check: https://stackoverflow.com/questions/51351137/css-text-overflow-ellipsis-not-working-in-grid-flex
- added modifier class to the label to allow text wrap on a new line to chow the whole text: `fd-checkbox__label--wrap` and `fd-radio__label--wrap`
Radio Button: added a child element for the label.
**Before:**
```
<div class="fd-form-item">
<input …
```

fix(styles): add option to wrap long label for checkbox and radio button

---

packages/styles/src/mixins/list/_list-base.scss
packages/styles/src/mixins/list/_list-definitions.scss
packages/styles/src/mixins/list/_list-navigation-indication.scss
packages/styles/src/mixins/list/_list-selection.scss
packages/styles/src/theming/sap_fiori_3.scss
packages/styles/src/theming/sap_fiori_3_dark.scss
packages/styles/src/theming/sap_fiori_3_hcb.scss
packages/styles/src/theming/sap_fiori_3_hcw.scss
packages/styles/src/theming/sap_fiori_3_light_dark.scss
packages/styles/src/theming/sap_horizon.scss
packages/styles/src/theming/sap_horizon_dark.scss
packages/styles/src/theming/sap_horizon_hcb.scss
packages/styles/src/theming/sap_horizon_hcw.scss
packages/styles/src/tree.scss
packages/styles/stories/Components/List/list/byline/interractive.example.html
packages/styles/stories/Components/List/list/standard/action-list.example.html
packages/styles/stories/Components/List/list/standard/icons.example.html
packages/styles/stories/Components/List/list/standard/interactive.example.html
packages/styles/stories/Components/List/list/standard/navigation-indicator.example.html
packages/styles/stories/Components/List/list/standard/secondary-data.example.html
packages/styles/stories/Components/List/list/standard/standard-list.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes https://github.com/SAP/fundamental-styles/issues/4380
- updates List to latest Horizon
- added modifier classes for status text: `fd-list__secondary fd-list__secondary--positive`, `fd-list__secondary fd-list__secondary--critical`, `fd-list__secondary fd-list__secondary--negative`, `fd-list__secondary fd-list__secondary--informative`
- code refactor to use css variables in order to avoid CSS rules repetition 
- added modifier classes for status text (fd-list__secondary): `fd-list__secondary fd-list__secondary--positive`, `fd-list__secondary fd-list__secondary--critical`, `fd-list__secondary fd-list__secondary--negative`, `fd-list__secondary fd-list__secondary--informative`

fix(styles): update List component to latest Horizon [ci visual]

---

packages/styles/src/menu.scss
packages/styles/src/theming/common/menu/_sap_fiori.scss
packages/styles/src/theming/common/menu/_sap_horizon.scss
packages/styles/stories/Components/menu/buttons.example.html
packages/styles/stories/Components/menu/desktop-and-tablet-overflow.example.html
packages/styles/stories/Components/menu/desktop-and-tablet.example.html
packages/styles/stories/Components/menu/different-states.example.html
packages/styles/stories/Components/menu/input.example.html
packages/styles/stories/Components/menu/menu-icon.example.html
packages/styles/stories/Components/menu/menu.stories.js
packages/styles/stories/Components/menu/mobile-cozy-mode.example.html
packages/styles/stories/Components/menu/segmented-button.example.html
packages/styles/stories/Components/menu/seperated-items.example.html
packages/styles/stories/Components/menu/toggle-button.example.html
packages/styles/stories/Components/menu/with-submenu.example.html
packages/styles/stories/Patterns/context-menu/with-icon-and-button.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes https://github.com/SAP/fundamental-styles/issues/4381
- updates Menu per latest Horizon 2023 updates
- adds extended Menu Item features: 
-  Active Dot (Segmented Button)
- Checkmark (Toggle Button)
- Buttons as Menu Items
- Input in a Menu Item
- code refactor to use CSS variables
- remove the separator as it's not accessible
- added a modifier class for when a menu items have icons
- new elements with classes `fd-menu__active-dot`, `fd-menu__checkmark`, `fd-menu__input`
- span element with class `fd-menu__separator` is removed as we can't have elements between `li` items
**Before:**
```
<span class="fd-menu__separator"></span>
```
**After:**
The `li` item with class `fd-menu__item` has additional class `has-separator`. This will add a separator under the item …

feat(styles): update Menu to Horizon 2023 [ci visual]

---

packages/styles/src/panel.scss

Closes https://github.com/SAP/fundamental-styles/issues/4542
- checked the latest design changes: no updates needed. We have addressed the changes (paddings of the expanded content) in the previous Panel refactoring. 
- noticed a small bug with the elements overlapping, resulting in Panel border bottom being cut and fixed it.

fix(styles): fix the issue with border bottom of Panel header 

---

packages/styles/src/popover.scss
packages/styles/stories/Components/popover/placement.example.html
packages/styles/stories/Components/popover/popover.stories.js
packages/styles/stories/Components/popover/resizable.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

Part of SAP/fundamental-ngx#9747
The name should be `bottom` not the `end` in case of the vertical placement. Deprecated previous modifier. No visual changes

fix(styles): fixed semantics of the popover vertical arrow positioning

---

packages/styles/src/message-strip.scss
packages/styles/stories/Components/message-strip/message-strip-with-accent-colors.example.html
packages/styles/stories/Components/message-strip/message-strip.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes https://github.com/SAP/fundamental-styles/issues/4556
The custom Message strip now uses 2 sets of indication colors. 
Added new modifier classes:
`fd-message-strip--indication-color-1` ... `fd-message-strip--indication-color-10`
`fd-message-strip--indication-color-1b` ... `fd-message-strip--indication-color-10b`
- removed classes `fd-message-strip--accent-color-1`... `fd-message-strip--accent-color-10`
- introduced new classes:
`fd-message-strip--indication-color-1` ... `fd-message-strip--indication-color-10`
`fd-message-strip--indication-color-1b` ... `fd-message-strip--indication-color-10b`

feat(styles): bring indication colors set to Message Strip [ci visual]

---

.storybook/static/preview-head.js
packages/styles/src/checkbox.scss
packages/styles/src/message-popover.scss
packages/styles/src/mixins/_forms.scss
packages/styles/src/radio.scss
packages/styles/src/slider.scss
packages/styles/src/textarea.scss
packages/styles/src/theming/common/slider/_sap_fiori.scss
packages/styles/src/theming/common/slider/_sap_horizon.scss
packages/styles/src/theming/sap_horizon/_css_variables.scss
packages/styles/stories/Components/Forms/checkbox/checkbox.stories.js
packages/styles/stories/Components/Forms/input/primary.example.html
packages/styles/stories/Components/Forms/radio/interaction-states.example.html
packages/styles/stories/Components/Forms/radio/radio.stories.js
packages/styles/stories/Components/Forms/radio/text-truncation.example.html
packages/styles/stories/Components/Forms/textarea/disabled-and-read-only.example.html
packages/styles/stories/Components/slider/range.example.html
packages/styles/stories/Components/slider/standard.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes NONE
This PR includes multiple fixes reported by the designers regarding components already migrated to latest Horizon 2023 design specs.
1. Missing Read only tristate square in all 4 Horizon themes.
**Before:**
**After:**
2. Readonly state for Radio and Checkbox shouldn't have hover
3. For HCB and HCW – the hover colour is wrong
**Before:**
**After:**
4. Wrapping of long label for Checkbox and Radio. Now we have top-aligned wrapping:
5. Slider missing focus state
**Before:**
**After:**
6. Textarea, the scrollbar overlaps the border and box shadow
**Before:**
**After:**
7. Textarea in Read-only state should have dashed border around all sides and the focus should be inside (with an offset)
**Before:**
**After:**
8. Input field in read-only state should have shadow
**Before:** …

fix(styles): address design review comments regarding Horizon 2023 

---

packages/styles/src/carousel.scss
packages/styles/src/mixins/_mixins.scss
packages/styles/src/theming/common/carousel/_sap_fiori.scss
packages/styles/src/theming/common/carousel/_sap_horizon.scss
packages/styles/stories/Components/carousel/carousel-backgrounds.example.html
packages/styles/stories/Components/carousel/carousel.stories.js

Closes https://github.com/SAP/fundamental-styles/issues/4371
- Horizon 2023 updates
- Code refactor
- Vertical mode: new modifier classes for the buttons `fd-carousel__button--up` and `fd-carousel__button--down`
- Backgrounds: new modifier classes for the Content background and Page Indicator Container.
**Content background:**  `fd-carousel__content--transparent`, `fd-carousel__content--solid`
**Page Indicator Container:** `fd-carousel__page-indicator-container--transparent`, `fd-carousel__page-indicator-container--translucent` , `fd-carousel__page-indicator-container--no-border`

fix(styles): add Horizon 2023 updates for Carousel [ci visual]

---

packages/styles/src/menu.scss

Menu item should not have width limitation, it should come from entire menu list, items should follow what is coming from parent. If some different width is needed for list item, user cal always override that

fix(styles): menu full width

---

packages/styles/src/fundamental-styles.scss
packages/styles/src/skeleton.scss
packages/styles/stories/Components/skeleton/circle.example.html
packages/styles/stories/Components/skeleton/complex.example.html
packages/styles/stories/Components/skeleton/lines.example.html
packages/styles/stories/Components/skeleton/skeleton.example.html
packages/styles/stories/Components/skeleton/skeleton.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes none
add skeleton examples and styling

feat(styles): add skeleton examples and styling [ci visual]

---

config/bundlesize.json
packages/styles/src/mixins/_states.scss
packages/styles/src/object-status.scss
packages/styles/src/theming/common/object-status/_sap_fiori.scss
packages/styles/src/theming/common/object-status/_sap_fiori_hc.scss
packages/styles/src/theming/common/object-status/_sap_horizon.scss
packages/styles/src/theming/common/object-status/_sap_horizon_hc.scss
packages/styles/src/theming/common/rating-indicator/_sap_horizon_hc.scss
packages/styles/src/theming/sap_fiori_3.scss
packages/styles/src/theming/sap_fiori_3_dark.scss
packages/styles/src/theming/sap_fiori_3_hcb.scss
packages/styles/src/theming/sap_fiori_3_hcw.scss
packages/styles/src/theming/sap_fiori_3_light_dark.scss
packages/styles/src/theming/sap_horizon.scss
packages/styles/src/theming/sap_horizon_dark.scss
packages/styles/src/theming/sap_horizon_hcb.scss
packages/styles/src/theming/sap_horizon_hcw.scss
packages/styles/stories/Components/object-status/clickable-object-status.example.html
packages/styles/stories/Components/object-status/inverted-indication.example.html
packages/styles/stories/Components/object-status/inverted-states.example.html
packages/styles/stories/Components/object-status/inverted.example.html
packages/styles/stories/Components/object-status/object-status.stories.js

Closes https://github.com/SAP/fundamental-styles/issues/4630
- update to latest design changes
- introduces new modifier class for icon only: `fd-object-status--icon-only`
Icon only Object status now needs a modifier class `fd-object-status--icon-only`
**Before:**
```
<span class="fd-object-status fd-object-status--inverted fd-object-status--negative fd-object-status--large">
<i class="fd-object-status__icon sap-icon--message-error" role="presentation"></i>
</span>
```
**After:**
```
<span class="fd-object-status fd-object-status--inverted fd-object-status--negative fd-object-status--large fd-object-status--icon-only">
<i class="fd-object-status__icon sap-icon--message-error" role="presentation"></i>
</span>
```

fix(styles): update Object Status to latest Horizon 2023 [ci visual]

---

packages/styles/stories/Components/quick-view/no-header.example.html
packages/styles/stories/Components/quick-view/popover.example.html

Relates to  https://github.com/SAP/fundamental-styles/issues/3955#issuecomment-1355378065
Added bottom margin to improve clarity for quick view 
**Before**
**After**

docs(styles): quick view styles & examples [ci visual]

---

packages/styles/src/card.scss
packages/styles/src/theming/common/card/_sap_fiori.scss
packages/styles/src/theming/common/card/_sap_horizon.scss

Closes https://github.com/SAP/fundamental-styles/issues/4482
- apply the correct box-shadow in Quart theme on hover state

fix(styles): add the proper box-shadow for Card in Quartz Theme

---

packages/styles/src/icon-tab-bar.scss
packages/styles/stories/Components/icon-tab-bar/icon-tab-bar.stories.js
packages/styles/stories/Components/icon-tab-bar/single-click.example.html
packages/styles/stories/Components/icon-tab-bar/text-only-closable.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes none
address the bugs reported by the designers after design review

fix(styles): design review fixes for Icon Tab Bar [ci visual]

---

packages/styles/stories/Components/avatar/avatar.stories.js

Relates to  https://github.com/SAP/fundamental-styles/issues/3955
increased bottom margin between interactive elements
**Before**
**After**

docs(styles): increased bottom margin between interactive elements [ci visual]

---

packages/styles/stories/Patterns/horizontal-navigation/horizontal-navigation.stories.js

Relates to  https://github.com/SAP/fundamental-styles/issues/3955
Fixed typo in horizontal navigation

docs(styles): fixed typo in horizontal navigation [ci visual]

---

packages/styles/stories/Components/avatar-group/group-type-vertical.example.html
packages/styles/stories/Components/avatar-group/individual-type-vertical.example.html

Relates to  https://github.com/SAP/fundamental-styles/issues/3955
Added interactivity to vertical components 
**Before**
individual:
group:
**After**
individual:
group:

docs(styles): added interactivity to vertical components [ci visual]

---

packages/styles/src/mixins/list/_list-base.scss
packages/styles/src/mixins/list/_list-byline.scss
packages/styles/src/mixins/list/_list-definitions.scss
packages/styles/src/mixins/list/_list-navigation.scss
packages/styles/stories/Components/List/list/byline/long-text.example.html
packages/styles/stories/Components/List/list/byline/unread-notification.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes none
- Spacing between Title and Byline is now 0,5rem, not 0.75rem
- Icon size is now 2rem, not 2.5rem
- Byline height for compact and cozy is 80px  (5rem)
- Wrapping behaviour issues:
- The Avatar is top aligned
- The left and right sections are not in 2 columns
- unread notifications have bold title
Before:
After:
- Unread `fd-list__item` requires  `fd-list__item--unread` modifier class to make the title bold
- `<div class="fd-list__byline fd-list__byline--2-col">` is now` <div class="fd-list__byline fd-list__byline--wrap">`

fix(styles): update Byline List after design review [ci visual]

---

packages/cx/src/side-nav.scss

Relates to [4708](https://github.com/SAP/fundamental-styles/pull/4708)
Scrollbar was improperly displayed for cx nav-bar.

fix(styles): proper scrollbar display

---

packages/styles/src/toolbar.scss

closes none;
Small fix for ngx side when popover is rendered outside fd-toolbar scope.

fix(styles): toolbar ejected popover scope [ci visual]

---

.github/workflows/create-release.yml

Previously I removed fn and fn-icons from repo and forgot to remove fn-icons from list of publish libraries

fix: removed fn-icons from publish

---

packages/styles/src/link.scss

fix(styles): link with icon needs inline-flex

---

packages/styles/src/icon-tab-bar.scss
packages/styles/stories/Components/icon-tab-bar/text-only-closable.example.html

closes none;
Fixes the issue with the padding of nested list items with closable items.
Before:
After:

fix(styles): icon tab bar nested paddings fix

---

package.json

Old version of the common-css was published
Disabling cached builds for prod in CI

chore: skipping nx cache in prod builds

---

packages/styles/src/btp/avatar.scss
packages/styles/src/navigation.scss
packages/styles/src/user-menu.scss
packages/styles/stories/BTP/user-menu/user-menu-phone.example.html
packages/styles/stories/BTP/user-menu/user-menu-tablet.example.html
packages/styles/stories/BTP/user-menu/user-menu.example.html
packages/styles/stories/BTP/user-menu/user-menu.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes https://github.com/SAP/fundamental-styles/issues/4313
- introduces the BTP variation of User Menu.
- the examples are placed under the BTP section
- adds new modifier class in the Navigation component for Menu Item `fd-navigation__item--menu`
- adds new element to Title Item for Back navigation `fd-navigation__back-indicator`

feat(styles): add BTP variant for User Menu [ci visual]

---

packages/styles/src/shellbar.scss

Fixed shellbar category dropdown outline

fix: shellbar category dropdown box-shadow invisibility

---

packages/styles/src/rating-indicator.scss
packages/styles/stories/Components/rating-indicator/disabled.example.html

Part of DH
- Unifies half-star design for disabled, display non-interactive modes
- Added half-star display for disabled example

fix(styles): half star unification and doc update [ci visual]

---

packages/common-css/README.md
packages/common-css/package.json

chore(common-css): update the Common CSS doc

---

packages/doc-ui/src/components/DocsPage/custom.scss
packages/styles/src/icon-tab-bar.scss

Closes SAP/fundamental-styles#4813
- Removed `overflow-x: hidden`;
- Added case when overflow dropdown is available. In this case add `overflow: visible` for popovers that are bound inside icon tab bar would still be visible.
>
3. Testing

fix(styles): visible overflow when more dropdown is available

---

config/bundlesize.json
packages/styles/src/mixins/_forms.scss
packages/styles/src/select.scss
packages/styles/stories/Components/Forms/input/primary.example.html
packages/styles/stories/Components/select/cozy.example.html

relates https://github.com/SAP/fundamental-styles/issues/4912
- Visual core states that placeholder should not be visible for any input when it's state is `readonly` or `disabled`. Same logic should be applied to a select component;
- Updated doc examples to resemble such visual states
>

fix(styles): input and select disabled placeholder

---

packages/styles/src/button.scss
packages/styles/stories/BTP/button/button.stories.js
packages/styles/stories/BTP/button/nested-square.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes none
BTP added a new type of Nested Button - square nested button

feat(styles): add square Nested Button to BTP [ci visual]

---

packages/styles/src/mixins/list/_list-message-view.scss
packages/styles/src/mixins/list/_list-navigation-indication.scss

relates #4912
- Adjusted message popover parameters for arrow icon font size;
- List item paddings;
- List item title font metrics

fix(styles): message popover adjustments

---

packages/styles/src/title-bar.scss
packages/styles/stories/BTP/title-bar/desktop.example.html
packages/styles/stories/BTP/title-bar/mobile.example.html
packages/styles/stories/BTP/title-bar/tablet.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

- adopts the latest design changes
- uses Nested button instead of transparent
- uses Nested button instead of transparent, wrapped in a container with a new classname `fd-title-bar__container`
Before:
```
<div class="fd-title-bar__container">
<button class="fd-button fd-button--compact fd-button--transparent" aria-label="Back">
<i class="sap-icon--navigation-left-arrow" role="presentation"></i>
</button>
</div>
```
After:
```
<div class="fd-title-bar__button-container">
<button class="fd-button fd-button--compact fd-button--nested" aria-label="Back">
<i class="sap-icon--navigation-left-arrow" role="presentation"></i>
</button>
</div>
```

fix(styles): update Title Bar to latest design [ci visual]

---

packages/styles/src/fonts/sap_horizon_fonts.scss

Previous font path did not exist in theming base content

fix: fixed font path to the sap-theming [ci visual]

---

packages/styles/src/toolbar.scss

Closes none
The height of Tool Bar when used with Title Bar should be auto in compact state.

fix(styles): add fix for correct height for Title Bar ToolBar in compact state

---

packages/doc-ui/src/components/Community.tsx

remove old links (twitter and react/vue link) in the doc site

chore: remove old links

---

packages/styles/src/title.scss
packages/styles/src/variant-management.scss
packages/styles/stories/Components/variant-management/dirty-label.example.html
packages/styles/stories/Components/variant-management/sizes.example.html
packages/styles/stories/Components/variant-management/variant-management.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes  https://github.com/SAP/fundamental-styles/issues/5000
- updated the Variant Management 
- code refactoring for Title to use CSS variables
- added new modifier classes: `.fd-variant-management__title--object-header`, `.fd-variant-management__title--snapped-object-header` and `.fd-variant-management__title--title` to the `.fd-variant-management__title` base class.

fix(styles): update Variant Management [ci visual]

---

packages/styles/src/layout-panel.scss

Closes none, reported by CCP
When the border-bottom is applied to the body of the Layout Panel it appears when the footer is omitted. By moving the border to the footer it would allow to make the footer optional.

fix(styles): change body border to allow optional footer [ci visual]

---

.stylelintrc.json
packages/common-css/src/_common-mixins.scss
packages/common-css/src/sap-container-type.scss
packages/common-css/src/sap-padding.scss
packages/common-css/stories/container-queries/container-queries.stories.js
packages/common-css/stories/container-queries/container-queries.story.description.html
packages/common-css/stories/content-paddings/content-paddings.stories.js
packages/common-css/stories/media-queries/meta-queries.story.description.html
packages/common-css/stories/padding/padding.stories.js

part of https://github.com/SAP/fundamental-styles/issues/5045

feat(common-css): add CSS container quesries to common-css [ci visual]

---

packages/styles/src/navigation.scss

Closes none
Fixes the issue with list item with external expander button when navigation in snapped state
>

fix(styles): btp nav expander spanned state [ci visual]

---

packages/styles/src/theming/common/switch/_sap_fiori.scss

Closes https://github.com/SAP/fundamental-ngx/issues/11147
The issue appears with Compact switch and fiori 3 theme only.
>
3. Testing

fix(styles): compact switch fiori

---

packages/styles/src/grid-list.scss

Closes https://github.com/SAP/fundamental-styles/issues/5102
adds box-shadow --sapContent_Shadow2 on hover
Per design specs, on hover state the grid list item gets an all around border 0.0625rem solid var(--sapTile_Interactive_BorderColor) and box shadow --sapContent_Shadow2. 
Since the other states don't have border we implemented the border with box-shadow to not affect the size of the element. The box-shadow on hover is added as second in the chain.

fix(styles): add a fix for hover state in Grid List [ci visual]

---

packages/styles/src/step-input.scss
packages/styles/stories/Components/step-input/full-width.example.html
packages/styles/stories/Components/step-input/step-input.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes none
Requested by CX app
The Step Input doesn't take the whole width of the container as it has by default `width: auto`. Added a new modifier class `fd-step-input--full-width` that would allow it to take the entire width of the container element.

feat(styles): add full width modifier to Step Input [ci visual]

---

packages/styles/src/_avatar-variables.scss
packages/styles/src/avatar.scss
packages/styles/stories/Components/avatar/accent-colors-shell-header-context.example.html
packages/styles/stories/Components/avatar/accent-colors.example.html
packages/styles/stories/Components/avatar/avatar.stories.js
packages/styles/stories/Components/avatar/background-image.example.html
packages/styles/stories/Components/avatar/borders.example.html
packages/styles/stories/Components/avatar/circle.example.html
packages/styles/stories/Components/avatar/icon.example.html
packages/styles/stories/Components/avatar/initials.example.html
packages/styles/stories/Components/avatar/placeholder-background.example.html
packages/styles/stories/Components/avatar/tile-icon-background.example.html
packages/styles/stories/Components/avatar/transparent.example.html
packages/styles/stories/Components/avatar/value-states.example.html
packages/styles/stories/Components/avatar/zoom-icon.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

v1.0.0 
- added new modifier classes for the Avatar sizes to unify the naming with the other components. The old ones are kept to avoid breaking changes in existing apps.
`fd-avatar--sm`, `fd-avatar--md` and `fd-avatar--lg`
- the examples were updated to use these classes so future users use them instead of the old ones
- updated the examples to use the proper icons representing user and product
- Value states badges were updated to use the correct state icons
- For interactive Avatars the active/toggled states were updated with the latest design
- improvements in the documentation were added

fix(styles): Avatar component v1.0.0 updates

---

packages/styles/src/micro-process-flow.scss

Closes https://github.com/SAP/fundamental-styles/issues/5182
Updated the params for the step with state `information`.
It's not the best code solution but otherwise we need to introduce state values for all other states. Since only information is different, I applied the colors for hover and active only for it.

fix(styles): add fix for information state hover and active [ci visual]

---

packages/styles/src/text.scss
packages/styles/stories/Components/text/text.stories.js

Truncation in Text component
**BEFORE:** 
**AFTER:**

fix(styles): less and more words capitalize not uppercase [ci visual]

---

packages/styles/src/message-strip.scss

Closes https://github.com/SAP/fundamental-styles/issues/5232
added a css rule to break very long words
Before:
After:

fix(styles): add word break for text in Message Strip component

---

packages/styles/src/product-switch.scss
packages/styles/src/theming/sap_fiori_3.scss
packages/styles/src/theming/sap_fiori_3_dark.scss
packages/styles/src/theming/sap_fiori_3_hcb.scss
packages/styles/src/theming/sap_fiori_3_hcw.scss
packages/styles/src/theming/sap_fiori_3_light_dark.scss
packages/styles/src/theming/sap_horizon.scss
packages/styles/src/theming/sap_horizon_dark.scss
packages/styles/src/theming/sap_horizon_hcb.scss
packages/styles/src/theming/sap_horizon_hcw.scss

related to an issue in Fundamental-ngx https://github.com/SAP/fundamental-ngx/issues/11494
Added a transparent border to the Product switch item so that when the item is selected and a border is applied the content does not "jump" due to different height of the available container.

fix(styles): add fix for Product Switch items jumping on selection

---

packages/styles/src/tokenizer.scss

Closes https://github.com/SAP/fundamental-styles/issues/5248
the focus of the tokens is being cut vertically

fix(styles): add fix for the Tokens focus being cut in Tokenizer

---

packages/styles/src/card.scss
packages/styles/stories/Components/card/analytical-card.example.html
packages/styles/stories/Components/card/card-anatomy.example.html
packages/styles/stories/Components/card/extended-header.example.html
packages/styles/stories/Components/card/object-card.example.html
packages/styles/stories/Components/card/table-card.example.html
packages/styles/stories/Layouts/fixed-card-layout/fixed-card-layout.example.html
packages/styles/stories/Layouts/resizable-card-layout/resize-card-layout.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes none
after discussion with Nikolay today I did some changes regarding clickable zones in main card header. The clickable areas are 2 with role button. The focus of the first area is applied on the entire main header.

fix(styles): add focus and a11y changes for Card header [ci visual]

---

packages/styles/src/dynamic-page.scss
packages/styles/src/mixins/_mixins.scss
packages/styles/stories/Layouts/dynamic-page/collapsed-header.example.html
packages/styles/stories/Layouts/dynamic-page/desktop.example.html
packages/styles/stories/Layouts/dynamic-page/expandable.example.html
packages/styles/stories/Layouts/dynamic-page/mobile-collapsed.example.html
packages/styles/stories/Layouts/dynamic-page/mobile.example.html
packages/styles/stories/Layouts/dynamic-page/only-collapse.example.html
packages/styles/stories/Layouts/dynamic-page/summary-line.example.html
packages/styles/stories/Layouts/dynamic-page/tablet.example.html
packages/styles/stories/Layouts/dynamic-page/with-facets-mobile.example.html
packages/styles/stories/Layouts/dynamic-page/with-facets.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes none
Related to https://github.com/SAP/fundamental-ngx/issues/11253
The problem: in the current implementation of Dynamic Page, the header has tabindex="0" and is focusable. Inside it we have a heading and other focusable elements, which is not allowed. 
The solution: created a visually hidden button as a sibling to the focusable area of the header and it will get the real focus. Once the button is focussed its sibling (header -> title area) will get a visual focus (outline)
- dynamic page container is now `article` not `section` with `aria-roledescription`
- the `fd-dynamic-page__title-area` element has a new sibling, a `button` that receives the focus and once it's focussed applies a visual outline to the container
- dynamic page title is not an `<h1>` element, …

fix(styles): add a11y improvements for Dynamic Page header [ci visual]

---

packages/cx/src/_nested-list.scss

part of https://github.com/SAP/fundamental-styles/issues/5308
change the icon size from 14px to 16px as requested from the designers

fix(styles): change the font-size of Side Nav icon [ci visual]

---

packages/styles/src/menu.scss
packages/styles/stories/Components/menu/input.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes https://github.com/SAP/fundamental-styles/issues/5283
from all the requirement listed in the JIRA ticket we only missed the one where we can have as a menu item a combination of an icon, a text and in input. I added an example and CSS to change the text width to fit-content when the next sibling is an input.
After:

fix(styles): add an option to have an icon, text and input on same level in Menu item

---

packages/styles/src/card.scss
packages/styles/stories/Components/card/card-anatomy.example.html
packages/styles/stories/Components/card/card-non-interactive-header.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes none
- when the Card itself is interactive and has role listitem, the header should not get focus. 
- when the Card has a badge the header border radius was wrong

fix(styles): add focus improvements to Card [ci visual]

---

packages/styles/src/table.scss
packages/styles/stories/Components/table/primary.example.html
packages/styles/stories/Components/table/table.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes https://github.com/SAP/fundamental-styles/issues/5392
adds a modifier class to the header to remove the hover and active states

fix(styles): add option to make header cells non interactive [ci visual]

---

packages/styles/src/mixins/_forms.scss
packages/styles/src/tokenizer.scss

Closes https://github.com/SAP/fundamental-styles/issues/5406
the min-width of input field and input in Tokenizer was not working because of wrong variable values

fix(styles): fix the wrong min-width variable values for Input and Tokenizer

---

packages/styles/src/card.scss
packages/styles/stories/Components/card/analytical-card.example.html
packages/styles/stories/Components/card/card-anatomy.example.html
packages/styles/stories/Components/card/card-non-interactive-header.example.html
packages/styles/stories/Components/card/card.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

- added an option to have 2 badges on Card as defined in the latest design specs
- changed the font-family of the description text for Media Cards
BREAKING CHANAGE:
- badges are wrapped in an element with class `fd-card__badge-container`
Before:
```
<span class="fd-object-status fd-object-status--inverted fd-object-status--indication-5b fd-card__badge">
<i class="fd-object-status__icon sap-icon--example" role="presentation"></i>
<span class="fd-object-status__text">badge</span>
</span>
```
After:
```
<div class="fd-card__badge-container">
<span class="fd-object-status fd-object-status--inverted fd-object-status--indication-5b fd-card__badge">
<i class="fd-object-status__icon sap-icon--example" role="presentation"></i>
<span class="fd-object-status__text">badge</span>
</span>
</div>
```

fix(styles): add option for a second badge on Cards [ci visual]

---

packages/styles/src/message-box.scss

Closes none, related to an issue in FNGX
Although not recommended, the user can add a dismiss button in the Message Box header. The dismiss button receives some CSS that is intended only for the status icon, like margin-right and color.
The solution for this issue is to target all icons that are not children of a button.
After the solution:
NOTE: the screenshots can't be found in the documentation as this is not something we would like users to do. I added the buttons in the header just to test the solution and removed them after.

fix(styles): add status color only to the status icon of Message Box 

---

packages/common-css/src/_common-mixins.scss
packages/common-css/stories/text/hyphenation.example.html
packages/common-css/stories/text/max-lines.example.html
packages/common-css/stories/text/text.stories.js
packages/common-css/stories/text/whitespace.example.html

Closes none, improvements suggested by @trilodge 
add data attr as alternative to modifier classes to handle hyphens, wrap, line-clamp in Text (common CSS)

feat(common-css): add data attribute to common css Text [ci visual]

---

packages/styles/src/input-group.scss

Closes none
related to a bug reported in fngx Search input (a fix is also provided there https://github.com/SAP/fundamental-ngx/pull/12234). The control is built on top of Input Group therefore the fix is there.

fix(styles): remove the default background for autofill input

---

packages/styles/src/notification.scss

Closes none
these icons are not aligned with the text

fix(styles): align the notification indicator icon [ci visual]

---

packages/styles/src/calendar.scss

Closes none, a bug in FNGX
the reset function sets `padding-inline` and `padding-block` to 0. Setting `padding: var(--fdCalendar_Padding);` in fund-styles correctly overwrites the reset, but in FNGX the `padding-inline` and `padding-block` and rendered after `padding: var(--fdCalendar_Padding);` and the Calendar loses its padding. Trying now to see if using explicitly `padding-inline` and `padding-block` will fix this problem

fix(styles): an attempt to fix the padding issue in FNGX [ci visual]

---

packages/styles/stories/Components/table/checkbox.example.html
packages/styles/stories/Components/table/condensed-checkbox.example.html
packages/styles/stories/Components/table/grid-table.example.html
packages/styles/stories/Components/table/nav-indicators.example.html
packages/styles/stories/Components/table/responsive-table.example.html
packages/styles/stories/Components/table/semantic-rows.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes none, reported by a user
The checkboxes in Table documentation were missing because the Checkbox component has not been updated with the Breaking changes in the markup. Before it was relying on `::before` pseudo element to render the square, now it's a span element. 
Before:
```
<label class="fd-checkbox__label fd-table__checkbox-label" for="Ai4ez611"></label>
```
After:
```
<label class="fd-checkbox__label fd-table__checkbox-label" for="Ai4ez611">
<span class="fd-checkbox__checkmark" aria-hidden="true"></span>
</label>
```

docs(styles): add the missing checkboxes in Table examples [ci visual]

---

packages/doc-ui/src/components/DocsPage/custom.scss

hide old versions links to small resolutions

docs: hide old versions links to small resolutions

---

packages/styles/src/popover.scss
packages/styles/src/slider.scss

Closes none
This PR brings the CSS code from fund-ngx. Contains updates for the Tooltip latest design.

fix(styles): bring Slider tooltip styling from FNGX [ci visual]

---

packages/styles/src/form-label.scss

fix(styles): add more spacing between text and colon [ci visual]

---

packages/styles/src/form-group.scss
packages/styles/src/form-item.scss
packages/styles/stories/AI/Patterns/ai-guided-prompt/ai-guided-prompt.example.html
packages/styles/stories/Components/Forms/form-group/group-header-in-form-grid.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes https://github.com/SAP/fundamental-styles/issues/5660
The extra gap between Radio buttons and the misalignment in inline radio button group was added because form items in a form should have 0.625rem spacing. 
Added a new modifier class `fd-form-group--with-spacing` that adds spacing between the form-items only when explicitly applied. 
Removed the margin-block-start from the form-item.
**_Without spacing:_**
**_With spacing:_**

fix(styles): remove redundant spacing between form items [ci visual]

---

packages/styles/src/table.scss
packages/styles/stories/Components/table/primary.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes none
related to https://github.com/SAP/fundamental-ngx/issues/11919
adds `fd-table__cell--non-interactive` modifier class to `fd-table__cell` so that individual header cells can be non-interactive

fix(styles): add option to make individual Table cells non-interactive

---

packages/styles/src/form-label.scss
packages/styles/src/mixins/_forms.scss

fixes #5692 
fixes https://github.com/SAP/fundamental-ngx/issues/11284

fix(styles): make screenreader not announce asterisk on required fields [ci visual]

---

packages/styles/src/shellbar.scss
packages/styles/src/theming/common/shellbar/_sap_horizon.scss
packages/styles/stories/Components/shellbar/shellbar.stories.js

Closes none
- adds `fd-shellbar--xxl` modifier
- adds styling for the Shellbar overlay
- change the color of the product name to `--sapShell_SubBrand_TextColor`

fix(styles): minor CSS fixes for Shellbar [ci visual]

---

packages/styles/src/checkbox.scss

fix(styles): checkbox link in  label  is not clickable [ci visual]
closes [#12577](https://github.com/SAP/fundamental-ngx/issues/12577)
Updated the checkbox component to ensure that links within custom labels are clickable and function as intended.

fix(styles): checkbox link in  label  is not clickable [ci visual]

---

packages/styles/src/shellbar.scss
packages/styles/stories/Components/shellbar/optional-items.example.html
packages/styles/stories/Components/shellbar/overflow-toolbar.example.html
packages/styles/stories/Components/shellbar/shellbar.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes none
Context area is a separate ShellBar group
- removed class `fd-shellbar__context-area`
- added a modifier class for `fd-shellbar__group` to represent context area `fd-shellbar__group--context-area`
- updated the examples markup
Before:
```
<div class="fd-shellbar__context-area" role="group" aria-label="Additional info">...</div>
```
After:
```
<div class="fd-shellbar__group fd-shellbar__group--context-area" role="group" aria-label="Additional info">...</div>
```

fix(styles): updates for context area in ShellBar [ci visual]

---

packages/styles/src/message-toast.scss
packages/styles/src/theming/sap_fiori_3.scss
packages/styles/src/theming/sap_fiori_3_dark.scss
packages/styles/src/theming/sap_fiori_3_hcb.scss
packages/styles/src/theming/sap_fiori_3_hcw.scss
packages/styles/src/theming/sap_fiori_3_light_dark.scss
packages/styles/src/theming/sap_horizon.scss
packages/styles/src/theming/sap_horizon_dark.scss
packages/styles/src/theming/sap_horizon_hcb.scss
packages/styles/src/theming/sap_horizon_hcw.scss
packages/styles/stories/Components/message-toast/default-toast.example.html

part of https://github.com/SAP/fundamental-styles/issues/5727
- CSS update
- a11y: apply role alert
- the CSS variable `--sapContent_Lite_Shadow` is not added to sap-theming package yet, therefore I added the values to the local theming files

fix(styles): update Message toast to latest design UXC [ci visual]

---

packages/styles/src/theming/sap_fiori_3.scss
packages/styles/src/theming/sap_fiori_3_dark.scss
packages/styles/src/theming/sap_fiori_3_hcb.scss
packages/styles/src/theming/sap_fiori_3_hcw.scss
packages/styles/src/theming/sap_fiori_3_light_dark.scss
packages/styles/src/theming/sap_horizon.scss
packages/styles/src/theming/sap_horizon_dark.scss
packages/styles/src/theming/sap_horizon_hcb.scss
packages/styles/src/theming/sap_horizon_hcw.scss

Closes none
with the release of version 11.22.0 theming-base-content, the `--sapContent_Lite_Shadow` variable now fund-styles consumes it directly

fix(styles): remove local theming var for Message Toast [ci visual]

---

packages/styles/src/calendar.scss
packages/styles/stories/Components/calendar/calendar.stories.js
packages/styles/stories/Components/calendar/days.example.html
packages/styles/stories/Components/calendar/legend.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

The styling needed for the calendar legend: https://github.com/SAP/fundamental-ngx/issues/12403
Example:

feat(styles): added an optional Calendar legend section [ci visual]

---

packages/styles/src/breadcrumb.scss
packages/styles/src/link.scss
packages/styles/stories/Components/breadcrumb/breadcrumb.stories.js
packages/styles/stories/Components/breadcrumb/current-item.example.html
packages/styles/stories/Components/breadcrumb/overflow.example.html
packages/styles/stories/Components/breadcrumb/standard.example.html
packages/styles/stories/Components/breadcrumb/styles.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes none
- add separator styles
- two options for current page appearance
- updated examples
- updated height of the link for a11y requirements

feat(styles): add separator styles and a11y updates for Breadcrumb

---

packages/styles/src/settings.scss

Closes none
adding more specificity to the modifier classes of Settings as once deployed the order of the import of the classes cause some variables to be overwritten. We should not rely on the order of the file imports.

fix(styles): add specificity for Settings overwrite classes [ci visual]

---

packages/styles/src/list.scss
packages/styles/src/menu.scss
packages/styles/src/mixins/list/_list-subline.scss
packages/styles/src/user-menu.scss
packages/styles/stories/Components/List/list/subline/standard.example.html
packages/styles/stories/Components/List/list/subline/subline-list.stories.js
packages/styles/stories/Components/user-menu/default.example.html
packages/styles/stories/Components/user-menu/mobile.example.html
packages/styles/stories/Components/user-menu/user-menu.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes none
- added new type of List called "subline" that is used in User Menu panel to display account information
- User menu is refactored to use Menu and not Navigation List (this is a Breaking change)
- Menu component sublist needed some small fixes for the paddings when is used in Menu with icons
- New modifier classes for the User Menu: `.fd-user-menu__menu` and `.fd-user-menu__menu-list` for style overwrite of Menu elements.
- User Menu is now using Menu, not Navigation List
- User Menu is wrapped in `.fd-popover__wrapper` element
- New classes: `.fd-user-menu__menu` and `.fd-user-menu__menu-list`

feat(styles): latest updates for User Menu [ci visual]

---

packages/styles/stories/Components/shellbar/shellbar.stories.js
packages/theming-preview/src/shell-tile-card.html

fix: remove shellbar subtitle from examples

---

packages/styles/src/input-group.scss
packages/styles/src/mixins/_forms.scss

Closes https://github.com/SAP/fundamental-styles/issues/5951
Input Group is a composite component consisting of an input and a button. The current CSS allows us to detect focus on either element and apply a focus outline to the parent. Previously, this was possible in Fundamental-ngx but required JavaScript in Fundamental-styles.

fix(styles): show outline on focus for input group [ci visual]

---

packages/styles/src/mixins/list/_list-base.scss
packages/styles/src/mixins/list/_list-byline.scss
packages/styles/stories/Components/List/list/byline/byline-list.stories.js
packages/styles/stories/Components/List/list/byline/group-header.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

related to https://github.com/SAP/fundamental-ngx/issues/13107
- brings CSS from fund-ngx 
- ensures the height of the li element with group header stays consistent in byline
- updates the example to catch problems with visual tests

fix(styles): bring CSS for byline list from fund-ngx

---

packages/styles/src/tile.scss

related to https://github.com/SAP/fundamental-ngx/issues/11490
Design changes to the generic line tiles according to the specs
[
](url)

fix(styles): redesign line/link Tiles in both static and edit mode

---

packages/styles/src/mixins/_forms.scss

Closes  none
The issue is reported by a CX designer for an example in fund-ngx.

fix(styles): remove z-index from readonly input [ci visual]

---

packages/styles/src/breadcrumb.scss
packages/styles/stories/Components/breadcrumb/current-item.example.html
packages/styles/stories/Components/breadcrumb/overflow.example.html
packages/styles/stories/Components/breadcrumb/standard.example.html
packages/styles/stories/Components/breadcrumb/styles.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

- design updates: spacings and color for the separators
- a11y: aria-label, aria-current for the links
The last item (current), the text should be wrapped in a span with the necessary aria attributes.
Before:
```
<li aria-current="page" class="fd-breadcrumb__item">Laptop</li>
```
After:
```
<li class="fd-breadcrumb__item">
<span role="link" aria-current="page" aria-label="Current page 7 of 7">Laptop</span>
</li>
```

fix(styles): add design and a11y updates for Breadcrumb [ci visual]

---

packages/styles/src/action-sheet.scss
packages/styles/src/theming/sap_horizon.scss
packages/styles/src/theming/sap_horizon_dark.scss
packages/styles/stories/Components/action-sheet/action-sheet-mobile.example.html
packages/styles/stories/Components/action-sheet/action-sheet.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

- design updates for Action Sheet
- no a11y updates needed
Action Sheet Title is now in a Bar component.
Before:
```
<div class="fd-action-sheet__wrapper fd-action-sheet__wrapper--active" id="actionSheetPhone">
<h6 class="fd-action-sheet__title">Press cancel to hide action sheet</h6>
<ul class="fd-action-sheet fd-action-sheet--mobile">...</ul>
</div>
```
After:
```
<div class="fd-action-sheet__wrapper fd-action-sheet__wrapper--active" id="actionSheetPhone">
<div class="fd-bar fd-action-sheet__bar" role="toolbar" aria-label="Bar">
<div class="fd-bar__left">
<div class="fd-bar__element">
<h6 class="fd-action-sheet__title">Control Title</h6>
</div>
</div>
</div>
<ul class="fd-action-sheet …
```

fix(styles): update Action Sheet [ci visual]

---

packages/styles/src/busy-indicator.scss
packages/styles/stories/Components/busy-indicator/busy-dialog.example.html
packages/styles/stories/Components/busy-indicator/contrast-mode.example.html
packages/styles/stories/Components/busy-indicator/extended-busy-indicator-inside-message-toast.example.html
packages/styles/stories/Components/busy-indicator/extended-busy-indicator.example.html
packages/styles/stories/Components/busy-indicator/standard.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

- design update: spacing between the dots, margin-bottom
- a11y: role and aria attributes (breaking change)
new a11y role and aria attributes
Before:
```
<div class="fd-busy-indicator fd-busy-indicator--l" aria-hidden="false" aria-label="Loading">...</div>
```
After:
```
<div class="fd-busy-indicator fd-busy-indicator--l" aria-hidden="false" tabindex="0" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuetext="Busy" title="Please wait">...</div>
```

fix(styles): deaign and a11y updates for Busy Indicator [ci visual]

---

packages/styles/src/button.scss
packages/styles/src/mixins/button/_button-types.scss
packages/styles/stories/Components/button-split/split-menu-button.example.html
packages/styles/stories/Components/button/badge-on-button.example.html
packages/styles/stories/Components/button/button-states.example.html
packages/styles/stories/Components/button/button.stories.js
packages/styles/stories/Components/button/focusable-disabled.example.html
packages/styles/stories/Components/button/icon-and-text.example.html
packages/styles/stories/Components/button/menu-button.example.html
packages/styles/stories/Components/button/styles.example.html
packages/styles/stories/Components/button/toggle.example.html
packages/styles/stories/Components/segmented-button/segmented-button-vertical.example.html
packages/styles/stories/Components/segmented-button/segmented-button.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

- design changes: for Menu Button with fixed width
- a11y: roles, aria attributes, etc. Breaking changes for Segmented button
Segmented button has different role and attributes

fix(styles): add design and a11y updates for Button controls [ci visual]

---

packages/styles/src/carousel.scss
packages/styles/src/message-page.scss
packages/styles/stories/Components/carousel/carousel-backgrounds.example.html
packages/styles/stories/Components/carousel/carousel-bottom.example.html
packages/styles/stories/Components/carousel/carousel-no-navigation.example.html
packages/styles/stories/Components/carousel/carousel-top.example.html
packages/styles/stories/Components/carousel/carousel.stories.js
packages/styles/stories/Components/carousel/error.example.html
packages/styles/stories/Components/carousel/horizontal-carousel.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

- design changes: spacings and box-shadow for buttons over content
- a11y: roles, aria attributes, markup for the page indicator (breaking changes)
updated markup with proper roles and aria-attributes, page indicator is no longer an ordered list
Before:
```
<div class="fd-carousel is-focus" data-ride="carousel">
<div class="fd-carousel__content">
<div class="fd-carousel__slides">
<div class="fd-carousel__item fd-carousel__item--active">
</div>
</div>
</div>
<div class="fd-carousel__page-indicator-container">
<button
class="fd-button fd-carousel__button fd-carousel__button--left"
data-slide="prev"
aria-label="Go to previous item"
>
<i class="sap-icon--slim-arrow-left"></i>
</button>
<ol …
```

fix(styles): a11y and design updates for Carousel [ci visual]

---

packages/styles/stories/Components/message-box/message-box.stories.js
packages/styles/stories/Components/message-box/responsive.example.html
packages/styles/stories/Components/message-box/structure.example.html
packages/styles/stories/Components/message-box/types.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

- a11y update: markup and aria-describedby
markup and aria-describedby 
Before:
```
<div 
class="fd-message-box-docs-static fd-message-box fd-message-box--active" 
role="alertdialog" 
aria-modal="true" 
aria-labelledby="fd-message-box-title-1 fd-message-box-text-1">
<section class="fd-message-box__content">
<header class="fd-bar fd-bar--header fd-message-box__header">
... 
<h1 class="fd-title fd-title--h5" id="fd-message-box-title-1">Title</h1>
</header>
<div class="fd-message-box__body" id="fd-message-box-text-1">...</div>
<footer class="fd-bar fd-bar--footer fd-message-box__footer">
...
</footer>
</section>
</div>
```
After:
```
<div 
class="fd-message-box-docs-static fd-message-box fd-message-box--active" …
```

fix(styles): a11y update for Message box [ci visual]

---

packages/styles/src/_dialog-placeholders.scss
packages/styles/src/dialog.scss
packages/styles/src/theming/sap_fiori_3.scss
packages/styles/src/theming/sap_fiori_3_dark.scss
packages/styles/src/theming/sap_fiori_3_hcb.scss
packages/styles/src/theming/sap_fiori_3_hcw.scss
packages/styles/src/theming/sap_fiori_3_light_dark.scss
packages/styles/src/theming/sap_horizon.scss
packages/styles/src/theming/sap_horizon_dark.scss
packages/styles/src/theming/sap_horizon_hcb.scss
packages/styles/src/theming/sap_horizon_hcw.scss
packages/styles/stories/Components/dialog/default-dialog.example.html
packages/styles/stories/Components/dialog/device-specifications.example.html
packages/styles/stories/Components/dialog/draggable.example.html
packages/styles/stories/Components/dialog/horizontal-form-in-dialog.example.html
packages/styles/stories/Components/dialog/loading.example.html
packages/styles/stories/Components/dialog/resizable.example.html
packages/styles/stories/Components/dialog/selectable.example.html
packages/styles/stories/Components/dialog/sizes.example.html
packages/styles/stories/Components/dialog/vertical-form-in-dialog.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

- design update: opacity of the backdrop, cleanup
- bug fix: missing resize handle
- a11y: markup update
updated markup and aria
Before:
```
<section class="fd-dialog">
<div class="fd-dialog__content" role="dialog" aria-modal="true" aria-labelledby="dialog-title-1">
<header class="fd-dialog__header fd-bar fd-bar--header">
...
<h2 class="fd-title fd-title--h5" id="dialog-title-1">...</h2>
...
</header>
<div class="fd-dialog__body">
....
</div>
<footer class="fd-dialog__footer fd-bar fd-bar--footer">
...
</footer>
</div>
</section>
```
After:
```
<div class="fd-dialog">
<div class="fd-dialog__content" role="dialog" aria-modal="true" aria-labelledby="dialog-title-2" aria-describedby="dialog-title-2">
<header …
```

fix(styles): dialog design and a11y updates [ci visual]

---

packages/styles/src/button.scss
packages/styles/src/feed-input.scss
packages/styles/src/theming/common/button/_sap_fiori.scss
packages/styles/src/theming/common/button/_sap_fiori_hc.scss
packages/styles/src/theming/common/button/_sap_horizon.scss
packages/styles/src/theming/common/button/_sap_horizon_hc.scss
packages/styles/stories/Components/feed-input/disabled.example.html
packages/styles/stories/Components/feed-input/input-growth.example.html
packages/styles/stories/Components/feed-input/not-empty.example.html
packages/styles/stories/Components/feed-input/over-max-height.example.html
packages/styles/stories/Components/feed-input/placeholder-image.example.html
packages/styles/stories/Components/feed-input/standard.example.html
packages/styles/stories/Components/feed-input/without-user-image.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

- design updates: paddings, dimensions, the Submit button should have the same size in cozy and compact modes, an additional div element with class `fd-feed-input__container` is added to handle to component responsiveness (breaking change). The vertical margin and the thumbnail should be hidden when the element reaches max 20rem. It has to use container query, not media query.
- a11y updates: the parent should have role `group`, thumbnail doesn't need title, textarea does't need aria-label, etc.
an additional div element with class `fd-feed-input__container` is added, aria attributes and roles are updated.

fix(styles): update Feed Input component [ci visual]

---

packages/styles/src/generic-tag.scss
packages/styles/stories/Components/generic-tag/primary.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

This PR enhances the accessibility of the fd-generic-tag component:
- Introduced a new utility class to visually hide elements while keeping them accessible to screen readers.
- Added aria-disabled, aria-labelledby, and aria-describedby attributes to the component container for improved screen reader support.
- Injected two visually hidden <span> elements to convey semantic meaning and usage instructions to assistive technologies.
- Assigned unique id values to key elements to support ARIA attributes.
Markup changes: two new visually hidden <span> elements are now required for screen reader support.
Before: 
```
<div 
class="fd-generic-tag" 
role="button" 
tabindex="0" 
aria-roledescription="Object Tag">
<span …
```

fix(styles): a11y updates for Generic Tag [ci visual]

---

packages/styles/src/mixins/table/_table-pop-in.scss
packages/styles/stories/Components/table/responsive-table-pop-in-mode.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

fixes none
Previously, checkboxes were not rendering in the pop-in examples. Also pop-in was missing headers. Lastly, fixes a bug with the padding of text in cells after the checkbox cells, though this was more noticeable in fd-ngx.
before:
after:

fix(styles): missing checkboxes in table pop-in example, pop-in headers, text padding fix

---

packages/styles/src/message-strip.scss
packages/styles/src/theming/sap_fiori_3.scss
packages/styles/src/theming/sap_fiori_3_dark.scss
packages/styles/src/theming/sap_fiori_3_hcb.scss
packages/styles/src/theming/sap_fiori_3_hcw.scss
packages/styles/src/theming/sap_fiori_3_light_dark.scss
packages/styles/src/theming/sap_horizon.scss
packages/styles/src/theming/sap_horizon_dark.scss
packages/styles/src/theming/sap_horizon_hcb.scss
packages/styles/src/theming/sap_horizon_hcw.scss
packages/styles/stories/Components/message-strip/default-strip.example.html
packages/styles/stories/Components/message-strip/error.example.html
packages/styles/stories/Components/message-strip/information.example.html
packages/styles/stories/Components/message-strip/message-strip-with-accent-colors.example.html
packages/styles/stories/Components/message-strip/message-strip-with-custom-icon.example.html
packages/styles/stories/Components/message-strip/message-strip-with-link.example.html
packages/styles/stories/Components/message-strip/message-strip.stories.js
packages/styles/stories/Components/message-strip/no-icons-not-dismissible.example.html
packages/styles/stories/Components/message-strip/no-icons.example.html
packages/styles/stories/Components/message-strip/success.example.html
packages/styles/stories/Components/message-strip/warning.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

IMPORTANT:
We received this from the designer:
- code cleanup
- added option for multiple links in the text element
- added a sr only span to describe the message strip
- markup update, roles, aria attributes, etc.
added a visually hidden span to add description to the message strip
Before:
```
<div class="fd-message-strip fd-message-strip--no-icon" role="note" aria-live="assertive" id="message-strip-1" aria-labelledby="message-strip-1">
<p class="fd-message-strip__text">
Vivamus sagittis diam in vehicula lobortis sapien arcu mattis erat vel aliquet sem urna et.
</p>
</div>
```
After:
```
<div 
class="fd-message-strip fd-message-strip--no-icon" 
role="note"
aria-labelledby="message-strip-hidden-text-1 …
```

fix(styles): a11y update for Message Strip [ci visual]

---

packages/styles/src/avatar-group.scss
packages/styles/stories/Components/avatar-group/avatar-group.stories.js
packages/styles/stories/Components/avatar-group/group-type-interaction-states.example.html
packages/styles/stories/Components/avatar-group/group-type-vertical.example.html
packages/styles/stories/Components/avatar-group/group-type.example.html
packages/styles/stories/Components/avatar-group/individual-type-vertical.example.html
packages/styles/stories/Components/avatar-group/individual-type.example.html
packages/styles/stories/Components/avatar-group/overflow.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

- focus for Avatar group (Group type) when alone and with Popover
- Avatar with `role="img"` doesn't need title property. `aria-label` is enough in this case.
- updated the doc examples

fix(styles): a11y and focus improvements for Avatar Group [ci visual]

---

packages/styles/stories/Components/avatar/accent-colors-shell-header-context.example.html
packages/styles/stories/Components/avatar/accent-colors.example.html
packages/styles/stories/Components/avatar/avatar.stories.js
packages/styles/stories/Components/avatar/background-image.example.html
packages/styles/stories/Components/avatar/borders.example.html
packages/styles/stories/Components/avatar/circle.example.html
packages/styles/stories/Components/avatar/initials.example.html
packages/styles/stories/Components/avatar/interactive.example.html
packages/styles/stories/Components/avatar/placeholder-background.example.html
packages/styles/stories/Components/avatar/tile-icon-background.example.html
packages/styles/stories/Components/avatar/transparent.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

- use `role` instead of `aria-role`
- in `aria-label` where missing added the word `Avatar`
- checked for design updates: all up to date

docs(styles): update Avatar examples with correct a11y roles [ci visual]

---

packages/styles/src/input-group.scss

related to https://github.com/SAP/fundamental-ngx/issues/13350
apply focus only when the input is focussed, show the btn outline if the btn is focussed

fix(styles): add fix for missing btn focus in input group [ci visual]

---

packages/styles/stories/Components/Forms/radio/inline.example.html
packages/styles/stories/Components/Forms/radio/interaction-states.example.html
packages/styles/stories/Components/Forms/radio/primary.example.html
packages/styles/stories/Components/Forms/radio/radio.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

Closes https://github.com/SAP/fundamental-styles/issues/6096
- check for design changes (no changes)
- adopt the design changes (if any) (none)
- check for ACC improvements (yes)
- adopt WCAG 2.2 requirements (no specific requirements for this component)
- documentation improvements and updates (yes)
1. `disabled` attributed should be accompanied by `aria-disabled="true"`
2. `readonly` attribute is not relevant to non-textual input elements, such as radio btn. Needs additional way to communicate to the used the checkbox is readonly: added aria-description
Before:
```
<input type="radio" class="fd-radio is-readonly"  readonly>
```
After:
```
<input type="radio" class="fd-radio is-readonly" aria-readonly="true" aria-description="This radio button is read-only and cannot be changed." …
```

docs(styles): improve Radio button examples for a11y [ci visual]

---

packages/styles/src/input.scss
packages/styles/stories/Components/Forms/input/input.stories.js
packages/styles/stories/Components/Forms/input/primary.example.html
packages/styles/stories/Components/Forms/input/states.example.html
packages/styles/tests/__snapshots__/styles.test.ts.snap

par of https://github.com/SAP/fundamental-styles/issues/5763
- updated the examples
- added necessary aria attributes
- added a new visually hidden element to describe input states
added a new visually hidden element to describe input states with class `fd-input__sr-only`

fix(styles): add a11y improvements for Input control [ci visual]

---

packages/styles/src/textarea.scss
packages/styles/stories/Components/Forms/textarea/counter.example.html
packages/styles/stories/Components/Forms/textarea/disabled-and-read-only.example.html
packages/styles/stories/Components/Forms/textarea/primary.example.html
packages/styles/stories/Components/Forms/textarea/states.example.html
packages/styles/stories/Components/Forms/textarea/textarea.stories.js
packages/styles/tests/__snapshots__/styles.test.ts.snap

- no design updates
- added a new visually hidden element with class `fd-textarea__sr-only` to provide additional info about the state of the textarea.
- updated the examples with necessary attributes for a11y
added a new visually hidden element with class `fd-textarea__sr-only` to provide additional info about the state of the textarea.

fix(styles): add a11y updates for textarea [ci visual]

---

packages/common-css/src/sap-flex.scss
packages/common-css/stories/flex/flex.stories.js

part of https://github.com/SAP/fundamental-styles/issues/6116
- documentation improvements (some of the tables in the example descriptions were broken)
- flex order, grow and shrink now take values from 1 to 10, not from 1 to 20, which will minimize the size of the CSS file

fix(common-css): optimizations for common-css flex [ci visual]

---

packages/common-css/src/_common-mixins.scss
packages/common-css/stories/border-radius/border-radius.example.html
packages/common-css/stories/busy-indicator/busy-indicator.stories.js
packages/common-css/stories/colors/all-colors/all-background-color.example.html
packages/common-css/stories/colors/all-colors/all-colors.stories.js
packages/common-css/stories/colors/main-colors/main-background-color.example.html
packages/common-css/stories/colors/main-colors/main-colors.stories.js
packages/common-css/stories/display/display.stories.js
packages/common-css/stories/focus/focus.stories.js
packages/common-css/stories/margin/margin.stories.js
packages/common-css/stories/padding/padding.stories.js
packages/common-css/stories/page-title/title.stories.js
packages/common-css/stories/position/position-classes.example.html
packages/common-css/stories/position/position-mixins.example.html
packages/common-css/stories/text/text.stories.js
packages/common-css/stories/typography/common-cases.example.html
packages/common-css/stories/typography/typography.stories.js

part of https://github.com/SAP/fundamental-styles/issues/6116
- Code related:  border-left, border-right, border-top, border-bottom, etc. are replaced by 
border-block-start, border-block-end, ... which doesn't require RTL handling
- Documentation related: Some doc examples and descriptions were broken due to formatting. This was fixed. Simplified some examples

fix(common-css): doc examples fixes[ci visual]

---

packages/common-css/src/_common-mixins.scss
packages/common-css/src/_common-variables.scss
packages/common-css/src/common-css.scss
packages/common-css/src/sap-border.scss
packages/common-css/stories/border/border-mixin.example.html
packages/common-css/stories/border/border.example.html
packages/common-css/stories/border/border.stories.js

part of https://github.com/SAP/fundamental-styles/issues/6145
- Added CSS utility classes for the most commonly used border parameters (style, width, and color).
- Updated documentation and examples to reflect new border utilities and usage patterns.
- Enhanced SCSS mixin to support directional border properties, including block, inline, block-start, block-end, inline-start, and inline-end.

feat(common-css): add additional features to Border [ci visual]

---

packages/styles/src/theming/common/link/_sap_fiori.scss
packages/styles/src/theming/common/link/_sap_fiori_hc.scss
packages/styles/src/theming/common/link/_sap_horizon_hc.scss

Closes https://github.com/SAP/fundamental-styles/issues/6162
Added bigger offset for focus outline so it gives a bit more space around the text, esp in high contrast themes.
Before:
After:

fix(styles): add bigger outline offset for Link focus [ci visual]
